### ISSUE TITLE
Error create new app with experimental env

### ISSUE THREAD

**Issue by iboldurev** [vuejs/vue-cli#1000]
### Version
3.0.0-beta.6

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
VUE_CLI_EXPERIMENTAL=true vue create vue-typescript-example

Vue CLI v3.0.0-beta.6
? Please pick a preset: Manually select features
? Check the features needed for your project: TS, Linter
? Use class-style component syntax? No
? Compile TS with babel? (experimental) Yes
? Pick a linter / formatter config: Standard
? Pick additional lint features: Lint on save, Lint and fix on commit
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In package.json
? Save this as a preset for future projects? No

### What is expected?
Create new app

### What is actually happening?
yarn install v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 32.85s.

🚀  Invoking generators...
📦  Installing additional dependencies...

yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 14.83s.

``` ERROR  Error: Command failed: git commit -m init
 > running pre-commit hook: lint-staged
Running tasks for *.js [started]
Running tasks for *.vue [started]
vue-cli-service lint [started]
vue-cli-service lint [started]
vue-cli-service lint [failed]
→ ✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed
Running tasks for *.js [failed]
→ ✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed
vue-cli-service lint [failed]
→ ✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed
Running tasks for *.vue [failed]
→ ✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed
✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed
✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed

pre-commit hook failed (add --no-verify to bypass)


Error: Command failed: git commit -m init
 > running pre-commit hook: lint-staged
Running tasks for *.js [started]
Running tasks for *.vue [started]
vue-cli-service lint [started]
vue-cli-service lint [started]
vue-cli-service lint [failed]
→ ✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed
Running tasks for *.js [failed]
→ ✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed
vue-cli-service lint [failed]
→ ✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed
Running tasks for *.vue [failed]
→ ✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed
✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed
✖ vue-cli-service lint found some errors. Please fix them and try committing again.

 ERROR  Invalid options in vue.config.js: "experimentalCompileTsWithBabel" is not allowed

pre-commit hook failed (add --no-verify to bypass)


    at Promise.all.then.arr (/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by yyx990803** [comment]
It's experimental for a reason...
