### ISSUE TITLE
vue create fails on OS X 10.12.6

### ISSUE THREAD

**Issue by pwrstudio** [vuejs/vue-cli#1035]
### Version
3.0.0-beta.6

### Steps to reproduce
Install vue-cli globally with yarn:
`yarn global add @vue/cli`

Create new project with default settings:
`vue create vue3test`

### What is expected?
New project is set up in.

### What is actually happening?
Command fails with:
` ERROR  command failed: yarn `

This is output to yarn-error.log:
```
Arguments: 
  /Users/rasmussvensson/.nvm/versions/node/v8.5.0/bin/node /usr/local/bin/yarn

PATH: 
  /Users/rasmussvensson/Documents/localdev/htdocs/vue3test/node_modules/.bin:/Users/rasmussvensson/Documents/localdev/htdocs/node_modules/.bin:/Users/rasmussvensson/Documents/localdev/node_modules/.bin:/Users/rasmussvensson/Documents/node_modules/.bin:/Users/rasmussvensson/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/rasmussvensson/.nvm/versions/node/v8.5.0/bin:/Users/rasmussvensson/.nvm/versions/node/v8.5.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/rasmussvensson/.local/bin:/usr/local/opt/opencv3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/MAMP/bin/php/php7.1.0:bin

Yarn version: 
  0.16.1

Node version: 
  8.5.0

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "vue3test",
    "version": "0.1.0",
    "private": true,
    "devDependencies": {
      "@vue/cli-plugin-babel": "^3.0.0-beta.6",
      "@vue/cli-plugin-eslint": "^3.0.0-beta.6",
      "@vue/cli-service": "^3.0.0-beta.6"
    }
  }

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  TypeError: Expected `count` to be a positive finite number
      at module.exports (/usr/local/lib/node_modules/yarn/node_modules/repeating/index.js:10:9)
      at ProgressBar.render (/usr/local/lib/node_modules/yarn/lib/reporters/console/progress-bar.js:58:22)
      at ConsoleReporter.progress (/usr/local/lib/node_modules/yarn/lib/reporters/console/console-reporter.js:413:9)
      at /usr/local/lib/node_modules/yarn/lib/package-fetcher.js:122:36
      at Generator.next (<anonymous>)
      at step (/usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at Promise (<anonymous>)
      at F (/usr/local/lib/node_modules/yarn/node_modules/core-js/library/modules/_export.js:35:28)
      at /usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
```

**Comment by pwrstudio** [comment]
Due to running very outdated version of yarn: 0.16.1
