### ISSUE TITLE
build with development mode set & dest folder fails

### ISSUE THREAD

**Issue by capsur** [vuejs/vue-cli#1073]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/capsur/cc-setup](https://github.com/capsur/cc-setup)

### Steps to reproduce
`yarn build -- --mode=development --dest=test`

### What is expected?
Project is built in development mode and output goes into test folder

### What is actually happening?
```shell
vue-cli-service build --mode=development --dest=test

-  Building for development...\node_modules\@vue\cli-service\lib\commands\build\index.js:69
            args[0][0].to = dest
                   ^

TypeError: Cannot read property '0' of undefined
    at config.plugin.tap.args (\node_modules\@vue\cli-service\lib\commands\build\index.js:69:20)
    at Object.tap (\node_modules\webpack-chain\src\Plugin.js:19:22)
    at api.chainWebpack.config (\node_modules\@vue\cli-service\lib\commands\build\index.js:68:33)
    at webpackChainFns.forEach.fn (\node_modules\@vue\cli-service\lib\Service.js:135:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (\node_modules\@vue\cli-service\lib\Service.js:135:26)
    at Service.resolveWebpackConfig (\node_modules\@vue\cli-service\lib\Service.js:139:48)
    at PluginAPI.resolveWebpackConfig (\node_modules\@vue\cli-service\lib\PluginAPI.js:117:25)
    at api.registerCommand.args (\node_modules\@vue\cli-service\lib\commands\build\index.js:86:27)
    at Service.run (\node_modules\@vue\cli-service\lib\Service.js:129:28)
error An unexpected error occurred: "Command failed.
Exit code: 1
```

---
For comparison: `vue-cli-service build --mode production --dest` test works without any issues

**Comment by capsur** [comment]
Quickly checked, seems to be related to the fact that the copy-webpack-plugin is not configured for `development` builds => https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/app.js#L147

**Comment by bigteejay** [comment]
I too am experiencing the same issue.

package.json
```
//snip
 "scripts": {
    "dev": "vue-cli-service build --mode development --dest builds/dev",
//snip
```

`npm run dev ` yields the same error as you reported.

I (however) have no luck when trying just `vue-cli-service build --mode development --dest builds/dev` (or just "... `--dest dev`" in case it was the path separator that was causing problems.)

Either reports the same error.
