### ISSUE TITLE
Can not emit declaration files for TypeScript

### ISSUE THREAD

**Issue by duduluu** [vuejs/vue-cli#1081]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/HuijiFE/void-ui/tree/0.1](https://github.com/HuijiFE/void-ui/tree/0.1)

### Steps to reproduce
```
git clone git@github.com:HuijiFE/void-ui.git
cd void-ui
git checkout 0.1
yarn
yarn build:void
```

### What is expected?
Output declaration files after building.

### What is actually happening?
There is not any declaration files after building.

---
I have set `"declaration": true,` in tsconfig.json, but it doesn't output the typescript declaration files.

And then I use `tsc --emitDeclarationOnly`, although it output the declaration files but without vue single file component.

**Comment by yyx990803** [comment]
This doesn't seem to be a Vue issue... At least doesn't qualify as a bug report.

**Comment by duduluu** [comment]
But I actually emit the declaration files all along, using legacy webpack template in branch master of my project.

**Comment by dhensche** [comment]
I am unable to get the `build:void` script to run in your example repository without modifying the package.json (it references `src/void.ts` but the only similarly named file I can see is `src/VoidUI.ts`). Modifying the script to point to this file gets the build going (not seeing typing files though). Just running `yarn tsc --emitDeclarationOnly` results in an error in the console. Are you running a globally installed version of `tsc`? if so, can you specify which version to make sure that is not causing us problems

**Comment by dhensche** [comment]
after simplifying the `ts` file so that typescript stopped complaining on build, I found this issue https://github.com/TypeStrong/ts-loader/issues/711 . Turns out that using the `happyPackMode` (used when building for production and the parallel flag is set) or setting `transpileOnlye: true` (always the case in the current typescript plugin) in the ts-loader config options will disable the output of declaration files. I'm pretty sure these settings are for build performance reasons so I don't know how the team would like to handle this

**Comment by yyx990803** [comment]
@dhensche thanks for looking into this!

**Comment by duduluu** [comment]
@dhensche 
Thx, you could checkout https://github.com/HuijiFE/void-ui/tree/alpha-1.0
So... it's a issue for ts-loader.

**Comment by dhensche** [comment]
yes, `ts-loader` related issue. I'm wondering if we need to change the `build` task for projects with the typescript plugin to change the related options so that we still see the performance gains during development (`serve`), but build the definitions file during a full build. You could modify your webpack config in your `vue.config.js` to fix the issue locally by adding 
```javascript
config.module
  .rule('ts')
    .use('ts-loader')
      .loader('ts-loader')
        .tap(opts => {
          opts.transpileOnly = false;
          opts.happyPackMode = false;
          return opts;
        });
```

to disable the `transpileOnly` and `happyPackMode` options.

**Comment by elevatebart** [comment]
Declaration files are only relevant when generating a library consumable by a package manager. 
The build time overhead would only happen in this case.
We could disable HappyPack in this case only.

I will cook up a quick PR.

**Comment by azampagl** [comment]
@dhensche I've tried your suggestion with vu-cli 3.0. When opts.happyPackMode = false I get the following error during build:

 error  in ./src/index.ts

```

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot read property 'options' of undefined

    at Object.makeServicesHost (C:\...\node_modules\ts-loader\dist\servicesHost.js:18:66)
    at successfulTypeScriptInstance (C:\...\node_modules\ts-loader\dist\instances.js:164:45)
    at Object.getTypeScriptInstance (C:\...\node_modules\ts-loader\dist\instances.js:51:12)
    at Object.loader (C:\...\node_modules\ts-loader\dist\index.js:16:41)

 @ ./node_modules/@vue/cli-service/lib/commands/build/entry-lib.js 2:0-24 3:15-18 4:0-22 4:0-22

|  Building for production as library (commonjs + umd)...
```

(Oddly enough, if I comment out opts.happyPackMode = false; everything is fine).

**Comment by mumrich** [comment]
exacly the same issue here...

**Comment by mumrich** [comment]
after some further investigation, it seems that (at least in my case), the issue is related with the 'thread-loader' package that the 'cli-plugin-typescript' is using...
if I set `parallel: false` in the vue.config.js, the typings are correctly emitted!

**Comment by grofit** [comment]
This is effecting me at the moment too would be great if there could be specific bit in the documentation detailing what should be done by the dev to enable outputting of declaration files when building as a lib, I appreciate if you are outputting an application you will not care about d.ts files.

**Comment by grofit** [comment]
For some reason the workaround (stopping parallel, removing the happy stuff, add declaration config to tsconfig) behaviour has changed slightly in the new versions. It still outputs the d.ts files but where I used to have to use:

```
"declarationDir": "." // change from "." to "dist"
```

This will then go back to putting the d.ts files in the dist folder, for some reason it used to always work relative to the dist folder so `"."` would indicate to bung the files there, but now it seems to work relative to the root directory for the declaration files.

Not a clue as to why and I dont have the time to go and investigate further but incase anyone has the same issue just change the declaration directory in your tsconfig. I would still ideally want a proper solution to this problem as some of my projects are taking 30 seconds+ to build the library with the workaround in place :(

**Comment by khuguet-tfg** [comment]
I dealing with this issue as well, and when applying the suggested workaround the type definition files are properly generated, but only on the initial build, any additional builds will clear out the dist folder and after it is rebuilt the type files are not regenerated.

**Comment by luotaoyeah** [comment]
@khuguet-tfg you need to delete `cache-loader`:
```javascript
chainWebpack: config => {
    config.module.rule("ts").uses.delete("cache-loader");
    config.module.rule("tsx").uses.delete("cache-loader");
}
```

**Comment by kjleitz** [comment]
Any update on this?

**Comment by wizardnet972** [comment]
Same here for library :(
`npx vue-cli-service build --target lib --dest lib ./src/index.ts`

I have set "declaration": true, in tsconfig.json, but it doesn't output the **typescript declaration files**.

**Comment by eakarpov** [comment]
Have there been any updates through almost a year?

**Comment by grofit** [comment]
I just ended up removing vue-cli and using webpack directly :( it was becoming too much of a time sink and faff to build TS related libraries with vue-cli.

**Comment by HamedFathi** [comment]
It does not work for me too :(

**Comment by HamedFathi** [comment]
> yes, `ts-loader` related issue. I'm wondering if we need to change the `build` task for projects with the typescript plugin to change the related options so that we still see the performance gains during development (`serve`), but build the definitions file during a full build. You could modify your webpack config in your `vue.config.js` to fix the issue locally by adding
> 
> ```js
> config.module
>   .rule('ts')
>     .use('ts-loader')
>       .loader('ts-loader')
>         .tap(opts => {
>           opts.transpileOnly = false;
>           opts.happyPackMode = false;
>           return opts;
>         });
> ```
> 
> to disable the `transpileOnly` and `happyPackMode` options.

@dhensche I want to use your solution but I got an error

I created a `vue.config.js` file and copied your code but compile failed

```
 ERROR  Error loading vue.config.js:
 ERROR  ReferenceError: config is not defined
ReferenceError: config is not defined
```

How to fix it and create `.d.ts` files?

**Comment by Gramatiik** [comment]
Hello @HamedFathi,

You need to place this code under the `chainWebpack` property of the exported module.

```javascript
// vue.config.js

module.exports = {
  chainWebpack: config => {
    // here you can access and tweak the webpack config
  }
}
```

This is described in the docs [**here**](https://cli.vuejs.org/guide/webpack.html#chaining-advanced).

have a nice day :)

**Comment by eakarpov** [comment]
Hello @Gramatiik!

I've already tried to use this config property for modifying webpack configuration.

```javascript
chainWebpack: config => {
        config.module
            .rule('ts')
            .use('ts-loader')
            .loader('ts-loader')
            .tap(opts => {
                opts.transpileOnly = false;
                opts.happyPackMode = false;
                return opts;
            });
    },
```

Though, I receive such an error: "Cannot read property 'hooks' of undefined". Do you know, what the cause could be?

**Comment by Gramatiik** [comment]
@eakarpov This seems to be related to [thread-loader](https://github.com/webpack-contrib/thread-loader),

The workaround proposed in [this issue](https://github.com/vuejs/vue-cli/issues/2171) is to disable simply disable **thread-loader**.

Because this will slow down the build, you can disable it only for **production builds** when you want to emit the declaration files.

**Comment by eakarpov** [comment]
@Gramatiik it seems like the proposal in thread-loader issue does not fix the problem. There are yet no declarations after build.

**Comment by Gramatiik** [comment]
@eakarpov Hello, here's my current configuration file with which I get the precious `.d.ts` files !

```javascript
// vue.config.js

module.exports = {
  configureWebpack: config => {
    if(process.env.NODE_ENV === 'production') {
      config.module.rules.forEach(rule => {
        if (rule.use) {
          let idx = rule.use.findIndex(w => w.loader === 'thread-loader')
          if (idx !== -1) rule.use.splice(idx, 1)
        }
      })
    }
  },
  chainWebpack: config => {
    if(process.env.NODE_ENV === 'production') {
      // disable cache (not sure if this actually useful...)
      config.module.rule("ts").uses.delete("cache-loader");

      config.module
        .rule('ts')
        .use('ts-loader')
        .loader('ts-loader')
        .tap(opts => {
          opts.transpileOnly = false;
          opts.happyPackMode = false;
          return opts;
        });
    }
  }
}
```

The only small problem is that it emits empty declarations files for the tests (`*.spec.ts`, if someone has an idea how to ignore them I am interested) but everything else works well :)

**Comment by LinusBorg** [comment]
@Gramatiik Presumably, this ts-loader option would help:

https://github.com/TypeStrong/ts-loader#onlycompilebundledfiles-boolean-defaultfalse

**Comment by Gramatiik** [comment]
Very interesting, thank you @LinusBorg :)

**Comment by eakarpov** [comment]
@Gramatiik 
I copied your config and do not receive .d.ts files after production build :(

**Comment by jianwu** [comment]
> ```js
> configureWebpack: config => {
>     if(process.env.NODE_ENV === 'production') {
>       config.module.rules.forEach(rule => {
>         if (rule.use) {
>           let idx = rule.use.findIndex(w => w.loader === 'thread-loader')
>           if (idx !== -1) rule.use.splice(idx, 1)
>         }
>       })
>     }
>   },
>   chainWebpack: config => {
>     if(process.env.NODE_ENV === 'production') {
>       // disable cache (not sure if this is actually useful...)
>       config.module.rule("ts").uses.delete("cache-loader");
> 
>       config.module
>         .rule('ts')
>         .use('ts-loader')
>         .loader('ts-loader')
>         .tap(opts => {
>           opts.transpileOnly = false;
>           opts.happyPackMode = false;
>           return opts;
>         });
>     }
>   }
> ```

I tried that, but seems it doesn't work. My Vue version is: 2.6.10, Vue-cli version:3.11.0

**Comment by Joehunk** [comment]
I just hit this issue myself. The solution for me was substantially similar to some of the previous ones claimed to work, but with some key differences. This is my `vue.config.js`:
```
module.exports = {
  chainWebpack: config => {
    // These are some necessary steps changing the default webpack config of the Vue CLI
    // that need to be changed in order for Typescript based components to generate their
    // declaration (.d.ts) files.
    //
    // Discussed here https://github.com/vuejs/vue-cli/issues/1081
    if(process.env.NODE_ENV === 'production') {
      config.module.rule("ts").uses.delete("cache-loader");

      config.module
        .rule('ts')
        .use('ts-loader')
        .loader('ts-loader')
        .tap(opts => {
          opts.transpileOnly = false;
          opts.happyPackMode = false;
          return opts;
        });
    }
  },
  parallel: false,
}
```
In particular, the section in previous examples that disabled `thread-loader` had no effect. I had to add `parallel: false` to avoid the error `Cannot read property 'options' of undefined`.

Additionally (this is obvious but bears mentioning), you must specify `"declaration": true` in your `tsconfig.json` to have declaration files emitted. This is with the latest (4.1.x) Vue CLI.

**Comment by MikeMitterer** [comment]
All these things did not work for me. I switched to rollup. I someone is interested here is my TS+vuetify+rollup SFC starter template: https://github.com/MikeMitterer/vue-ts-sfc-starter

**Comment by lukasfrana** [comment]
Any progress on this?

**Comment by axer0910** [comment]
I tried set happyPackMode to false in chainWebpack config item, and also set parallel to false, but when I try building the vue app I get stuck, after 10 minutes, I get error JavaScript heap out of memory.

My Node version: 12.16.3, vue cli version 4.3.1

**Comment by axer0910** [comment]
> I tried set happyPackMode to false in chainWebpack config item, and also set parallel to false, but when I try building the vue app I get stuck, after 10 minutes, I get error JavaScript heap out of memory.
> 
> My Node version: 12.16.3, vue cli version 4.3.1

I found that my hang issue is caused by composition api library, issue link is [https://github.com/vuejs/composition-api/issues/330](url), use command `tsc -d` to compile ts code can directly generate d.ts file.

**Comment by XavierChevalier** [comment]
@Joehunk's answer works for me. I've added it in an object so I can remove it more easily when this issue is solved.
```js
/**
 * These are some necessary steps changing the default webpack config of the Vue CLI
 * that need to be changed in order for TypeScript based components to generate their
 * declaration (.d.ts) files.
 * Discussed here https://github.com/vuejs/vue-cli/issues/1081
 */
const fixEmitDeclarationFilesForTypeScript = {
  chainWebpack: (config) => {
    if (process.env.NODE_ENV === 'production') {
      config.module.rule('ts').uses.delete('cache-loader');
      config.module
        .rule('ts')
        .use('ts-loader')
        .loader('ts-loader')
        .tap((options) => ({
          ...options,
          transpileOnly: false,
          happyPackMode: false,
        }));
    }
  },
  parallel: false,
};

module.exports = {
  ...fixEmitDeclarationFilesForTypeScript,
  // some other configuration
};
```

However, it is indeed possible to generate the declaration files after the build of your application. All you have to do is run the `tsc --emitDeclarationOnly` command after the build. That's probably the fastest way.
```json
{
  "scripts": {
    "build": "vue-cli-service build --target lib --name library src/index.ts && tsc --emitDeclarationOnly"
  }
}

**Comment by ethanvaughan** [comment]
> EDIT NOTE: this way do not generate declaraction files for .vue files.

That's kind of the point though haha

**Comment by jianwu** [comment]
Still struggle with the problem, with all the suggested solutions. non of them works for me.

**Comment by yaquawa** [comment]
Oh my.. It's been 2 years past, the year of Vue3, the year of TypeScript. 
now, I can't believe this bug still there 😱

**Comment by m-thomson** [comment]
Same problem here. Does anyone know if this same problem exists in Vue 3?

**Comment by yaquawa** [comment]
@m-thomson No, I finally turn to using rollup from scratch..

**Comment by ProTip** [comment]
For production mode I had to specify declarations via the ts-loader compiler options:

```
config.module.rules.forEach( r => {
      if (r.use)
        r.use.forEach( u => {
          if (u.loader.match(/ts-loader/)) {
            u.options.transpileOnly = false
            u.options.configFile = 'tsconfig.webpack.json'
            u.options.logLevel = 'info'
            u.options.compilerOptions = {
              "declaration": true
            }
          }
        })
    })
```

Might have something to do with the NODE_ENV getting set to `production` and some ts-loader internal config.. Unsure, but it resolved for me.

**Comment by nelisbijl** [comment]
Ok, the transpileOnly: false and happyPackMode: false does indeed give me *.vue.d.ts files but they do not seem very useful. If I obtain a reference (ref="myComp") to a published component in an application using the library, I do not get code completion nor does it satisfy eslint; regardless of whether I am referencing props, methods or setup() results. Even using such a reference inside another component in the same library does not work. What  am I missing?
PS: components are in .vue files (Vue 2.x.x) and defined with the @vue/composition-api using defineComponent(...

**Comment by Robula** [comment]
@yaquawa Since it looks like this bug is never going to get resolved, would you mind sharing your rollup configuration, please?

**Comment by yaquawa** [comment]
@Robula Here you go https://github.com/yaquawa/muku-ui/blob/master/rollup.config.js

**Comment by nelisbijl** [comment]
@william-will-angi No I ended up adding and exporting additional interfaces alongside the components. Component is exported as <ComponentName>Vue and interface as <ComponentName>. Very unsatisfying.

** EDITED **
I no longer export additional interfaces as stated above
After the vue build, I perform a tsc --emitDeclarationOnly build
This generates type definitions for the defineComponent results (these are actually instances not types)
Recently I found that the component's type can be extracted from that using: InstanceType<typeof [defineComponentResult]>

```
import { TestComponent } from 'mylib';

export default defineComponent({
  setup() {
    const testComp = ref<InstanceType<typeof TestComponent> | null>(null);
    ...
```

This seems to work quite well. Still wondering why this is so poorly documented (if at all).

**Comment by johnnyshankman** [comment]
This should be automatically built into `vue-cli build` command when you pass in ts files and have `declaration: true` in the `tsonfig.json` of your project.

Why would I ever want to export a library build of vue component without types? It guarantees compiler warnings on the client side who uses the library.

**Comment by Tofandel** [comment]
With the fix suggested here I get ts errors on intermediate files `.vue.ts`

```
[tsl] ERROR in ./resources/js/InertiaModal.vue.ts(138,41)
      TS2345: Argument of type '{ new (): { $props: VNodeProps & TeleportProps; }; __isTeleport: true; }' is not assignable to parameter of type 'VNodeTypes | ClassComponent'.

(and a bunch more)
```

Any idea how to solve this?

**Comment by Belphemur** [comment]
With VueJS 3 you can use `vue-tsc --declaration --emitDeclarationOnly` when you add the package `vue-tsc`

https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc

This will generate the declaration file where you have set your `outDir` in `tsconfig.json`

**Comment by seamory** [comment]
In 2024, this problem is still alive. Too terrible.

**Comment by bodograumann** [comment]
I thought vue-cli was deprecated anyway, so it should come as no suprise that no more development is going on.

**Comment by johnnyshankman** [comment]
Yeah you're better off swapping to vite @seamory @bodograumann, vue cli is dead.
