### ISSUE TITLE
htmlWebpackPlugin not defined when invoking custom plugin with prompts

### ISSUE THREAD

**Issue by andreasvirkus** [vuejs/vue-cli#1087]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/andreasvirkus/vue-cli-plugin-component-library-repl](https://github.com/andreasvirkus/vue-cli-plugin-component-library-repl)

### Steps to reproduce
Install the custom plugin from this github and invoke it
```
npm i -D andreasvirkus/vue-cli-plugin-component-library-repl
vue invoke component-library-repl
```

### What is expected?
That the plugin's generator modifies package.json and swaps out the necessary files:
```
$ vue invoke component-library-repl

🚀  Invoking generator for vue-cli-plugin-component-library-repl...
⚓  Running completion hooks...

   Successfully invoked generator for plugin: vue-cli-plugin-component-library-repl
   The following files have been updated / added:

     package-lock.json
     package.json
     public/favicon.ico
     public/img/icons/android-chrome-192x192.png
     public/img/icons/android-chrome-512x512.png
     public/img/icons/apple-touch-icon-120x120.png
     public/img/icons/apple-touch-icon-152x152.png
     public/img/icons/apple-touch-icon-180x180.png
     public/img/icons/apple-touch-icon-60x60.png
     public/img/icons/apple-touch-icon-76x76.png
     public/img/icons/apple-touch-icon.png
     public/img/icons/favicon-16x16.png
     public/img/icons/favicon-32x32.png
     public/img/icons/msapplication-icon-144x144.png
     public/img/icons/mstile-150x150.png
     src/assets/logo.png
     src/main.js

   You should review these changes with git diff and commit them.
```

### What is actually happening?
I'm met with the following error stack trace:
```
$ vue invoke component-library-repl
? Allow Interface Components to replace App.vue and Hello.vue? Yes

⠋  Invoking generator for vue-cli-plugin-bb-interface... ERROR  ReferenceError: ejs:5
    3|     <msapplication>
    4|         <tile>
 >> 5|             <square150x150logo src="<%= htmlWebpackPlugin.files.publicPath %>static/img/icons/mstile-150x150.png"/>
    6|             <TileColor>#2d89ef</TileColor>
    7|         </tile>
    8|     </msapplication>

htmlWebpackPlugin is not defined
ReferenceError: ejs:5
    3|     <msapplication>
    4|         <tile>
 >> 5|             <square150x150logo src="<%= htmlWebpackPlugin.files.publicPath %>static/img/icons/mstile-150x150.png"/>
    6|             <TileColor>#2d89ef</TileColor>
    7|         </tile>
    8|     </msapplication>

htmlWebpackPlugin is not defined
    at eval (eval at compile (/Users/andreas.virkus/.npm-global/lib/node_modules/@vue/cli/node_modules/ejs/lib/ejs.js:584:12), <anonymous>:11:26)
    at returnedFn (/Users/andreas.virkus/.npm-global/lib/node_modules/@vue/cli/node_modules/ejs/lib/ejs.js:615:17)
    at Object.exports.render (/Users/andreas.virkus/.npm-global/lib/node_modules/@vue/cli/node_modules/ejs/lib/ejs.js:414:37)
    at renderFile (/Users/andreas.virkus/.npm-global/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:246:14)
    at _injectFileMiddleware (/Users/andreas.virkus/.npm-global/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:142:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

---
**NB!** The issue is only present when I add `prompts.js` to the repo

**Comment by andreasvirkus** [comment]
Another note is that the same line works just fine when I try installing any other plugin making use of `api.render()` like
https://github.com/vuetifyjs/vue-cli-plugin-vuetify
or
https://github.com/Akryum/vue-cli-plugin-apollo

But I can't see a drastic difference between the generators 🤔

**Comment by andreasvirkus** [comment]
...Found the culprit

https://github.com/andreasvirkus/vue-cli-plugin-component-library-repl/blob/8d428259fa8533d2f34e9e5f6e614e30f7bf86df/generator/templates/default/public/img/icons/browserconfig.xml#L5

**Comment by PascalAOMS** [comment]
So ehm...what did you do exactly to fix this issue?
Simply remove the line?
