### ISSUE TITLE
vue create [project] fails with v3.0.0-beta.6 on linux (Ubuntu)

### ISSUE THREAD

**Issue by jim-cooper** [vuejs/vue-cli#1103]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/vuejs/vue-cli/releases/tag/v3.0.0-beta.6](https://github.com/vuejs/vue-cli/releases/tag/v3.0.0-beta.6)

### Steps to reproduce
* `npm install -g @vue/cli`
* `vue create vue-test-cli3`
* Select default preset

After the line "Invoking generators..." I get the specified error.

### What is expected?
Expected cli to create project

### What is actually happening?
Receiving the error:
ERROR  Error: Cannot find module '@vue/cli-service/generator' from '/home/jim/dev/vue-test-cli3'
Error: Cannot find module '@vue/cli-service/generator' from '/home/jim/dev/vue-test-cli3'
    at Function.module.exports [as sync] (/home/jim/.nvm/versions/node/v8.9.4/lib/node_modules/@vue/cli/node_modules/resolve/lib/sync.js:42:15)
    at Object.keys.map.id (/home/jim/.nvm/versions/node/v8.9.4/lib/node_modules/@vue/cli/lib/Creator.js:265:30)
    at Array.map (<anonymous>)
    at Creator.resolvePlugins (/home/jim/.nvm/versions/node/v8.9.4/lib/node_modules/@vue/cli/lib/Creator.js:264:36)
    at Creator.create (/home/jim/.nvm/versions/node/v8.9.4/lib/node_modules/@vue/cli/lib/Creator.js:137:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

---
Running Ubuntu 16.04, node 8.9.4, and npm v5.6.0.

**Comment by jim-cooper** [comment]
FYI, I tried this on beta.5 and beta.1 and got the same results.

**Comment by jim-cooper** [comment]
After rebooting my system this issue disappeared. Must have been an environment issue.  FYI, I use nvm to install node.
