### ISSUE TITLE
.vue使用jade语法出现错误时，热加载失败

### ISSUE THREAD

**Issue by daimon99** [vuejs/vue-cli#111]
使用vue init webpack生成的项目模板，在.vue文件中使用jade
```
<template lang='jade'>
</template>
```

在template中，这时如果jade模板出现语法错误，比如
`input(type='text') 这是一个异常`
这时expresss server 后台报错，然后即使修复jade错误，webpack也不在自动编译，前端页面也不再自动刷新。
webpack报错如下：

```
webpack: bundle is now INVALID.
webpack building...
Unhandled rejection Error: /Users/daimon/Git/arisb/src/components/ar_footer.vue:24
    22|         li
    23|           a(href="http://www.w3school.com.cn/js/" target="_blank") Javascript手册12
  > 24|           input(type='text') p
    25| 
    26| 
    27| 

input is self closing and should not have content.
    at Object.Compiler.visitTag (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:471:32)
    at Object.Compiler.visitNode (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitBlock (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:295:12)
    at Object.Compiler.visitNode (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitTag (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:480:12)
    at Object.Compiler.visitNode (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitBlock (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:295:12)
    at Object.Compiler.visitNode (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitTag (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:480:12)
    at Object.Compiler.visitNode (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitBlock (/Users/daimon/Git/arisb/node_modules/jade/lib/compiler.js:295:12)
```
这个时候只能退出npm run dev的进程，重新启动。

**Comment by Eden-Sun** [comment]
+1

**Comment by Eden-Sun** [comment]
vue-loader issue , I can make a PR for it later.
