### ISSUE TITLE
Error creating project with eslint

### ISSUE THREAD

**Issue by leonardovilarinho** [vuejs/vue-cli#1206]
### Version
3.0.0-beta.6

### Steps to reproduce
Run `vue create myproject` and select eslint   standard

### What is expected?
Project created

### What is actually happening?
```
Vue CLI v3.0.0-beta.7
✨  Creating project in /home/leonardo/projects/vue/testpwa.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.3: The platform "linux" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 59.48s.

🚀  Invoking generators...
 ERROR  TypeError: api.genJSConfig is not a function
TypeError: api.genJSConfig is not a function
    at api.render.files (/home/leonardo/projects/vue/testpwa/node_modules/@vue/cli-plugin-eslint/generator.js:88:46)
    at Generator.resolveFiles (/home/leonardo/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:129:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by yyx990803** [comment]
Upgrade please.

**Comment by hojas** [comment]
@yyx990803 手动创建项目时还是会出现这个问题，版本 v3.0.0-beta.9
