### ISSUE TITLE
Possible bug when authoring a 3rd party plugin within a monorepo

### ISSUE THREAD

**Issue by LukasBombach** [vuejs/vue-cli#1232]
### Version
3.0.0-beta.9

### Reproduction link
[https://github.com/LukasBombach/emc-vue](https://github.com/LukasBombach/emc-vue)

### Steps to reproduce
```
git clone https://github.com/LukasBombach/emc-vue
cd emc-vue/packages/app
yarn install
vue invoke vue-cli-plugin-elmc
```

### What is expected?
It should invoke the 3rd party plugin `vue-cli-plugin-elmc`, call its generator which will log "elmc generator" to the console

### What is actually happening?
VUE cli says the plugin does not have a generator:

```
Error: Plugin vue-cli-plugin-elmc does not have a generator.
    at invoke (/Users/luke/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:74:11)
    at module.exports.args (/Users/luke/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js:162:10)
    at Command.program.command.allowUnknownOption.description.action (/Users/luke/.config/yarn/global/node_modules/@vue/cli/bin/vue.js:65:29)
    at Command.listener (/Users/luke/.config/yarn/global/node_modules/@vue/cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:180:13)
    at Command.parseArgs (/Users/luke/.config/yarn/global/node_modules/@vue/cli/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/luke/.config/yarn/global/node_modules/@vue/cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/luke/.config/yarn/global/node_modules/@vue/cli/bin/vue.js:148:9)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
```

---
I tried adding a generator as `generator.js` in the root folder as well as creating a dummy generator in `generator/index.js`, both resulting in this error message. I am not sure if the issue is that I am using yarn workspaces here (monorepo) because everything else seems no different to the typescript plugin (for instance). I can say though, that the vue cli _finds_ the 3rd party plugin package, because otherwise it would have said it does not find a package.json.

**Comment by dhensche** [comment]
After fixing the babel-core dev dependency in app (`7.0.0-0` does not appear to be a valid version), I was able to invoke your plugin without issue

**Comment by yyx990803** [comment]
You need to run `yarn` in the root of your monorepo, otherwise the workspace packages will not be properly linked.

**Comment by LukasBombach** [comment]
Sorry, yes it does work.
