### ISSUE TITLE
Vue Create Fails with 504 Error

### ISSUE THREAD

**Issue by codyseibert** [vuejs/vue-cli#1307]
### Version
3.0.0-beta.10

### Reproduction link
[https://jsbin.com/hirinefuye/1/edit?js,output](https://jsbin.com/hirinefuye/1/edit?js,output)

### Steps to reproduce
run "vue create myapp".

### What is expected?
(note, I downgraded to beta.9 to be able to show the "expected") options for selecting configuration should appear that looks like this:

```
cseibert@Codys-MacBook-Pro:/Users/cseibert/Workspace/vue-adonis-todo$ vue create client

Vue CLI v3.0.0-beta.9
┌───────────────────────────────────┐
│  Update available: 3.0.0-beta.10  │
└───────────────────────────────────┘
? Please pick a preset:
  yum (vue-router, vuex, babel, eslint)
  default (babel, eslint)
❯ Manually select features
```
### What is actually happening?
(note: this is with -beta.10) I get this error:

```
 ERROR  StatusCodeError: 504 - "<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n\n"
StatusCodeError: 504 - "<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n\n"
    at new StatusCodeError (/usr/local/lib/node_modules/@vue/cli/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/@vue/cli/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/@vue/cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/@vue/cli/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/request/request.js:1079:12)
```

---
I downgraded to 3.0.0-beta.9 and it works fine

**Comment by yyx990803** [comment]
Is this still happening? Cannot reproduce and this looks like a temporary downtime for the npm registry...

If it's still happening with beta.10 please provide more information (OS, Node version, your `~/.vuerc` config)
