### ISSUE TITLE
library build without html plugin result build error: Cannot read property 'tapAsync' of undefined TypeError

### ISSUE THREAD

**Issue by crazyxhz** [vuejs/vue-cli#1331]
### Version
3.0.0-beta.10

### Reproduction link
[https://github.com/arthurbergmz/webpack-pwa-manifest/issues/53](https://github.com/arthurbergmz/webpack-pwa-manifest/issues/53)

### Steps to reproduce
```javascript
config.plugins
        .delete('html');
config
        .entry('warm')
        .add('./src/components')
        .end()
        .output.path(path.resolve('libs'))
        .filename('[name].js')
        .libraryTarget('commonjs2');
```
### What is expected?
I want to build a commonjs2 library without html output. But delete the html plugin cause the build error

### What is actually happening?
```
Building for production... ERROR  TypeError: Cannot read property 'tapAsync' of undefined
TypeError: Cannot read property 'tapAsync' of undefined
    at node_modules/preload-webpack-plugin/build/index.js:163:67
    at SyncHook.eval [as call] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:15:1)
    at SyncHook.lazyCompileHook [as _call] (node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation (node_modules/webpack/lib/Compiler.js:438:26)
    at hooks.beforeCompile.callAsync.err (node_modules/webpack/lib/Compiler.js:474:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (node_modules/webpack/lib/Compiler.js:469:28)
    at readRecords.err (node_modules/webpack/lib/Compiler.js:220:11)
    at Compiler.readRecords (node_modules/webpack/lib/Compiler.js:342:11)
    at hooks.run.callAsync.err (node_modules/webpack/lib/Compiler.js:217:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (node_modules/tapable/lib/Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (node_modules/webpack/lib/Compiler.js:214:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (node_modules/tapable/lib/Hook.js:35:21)
```

**Comment by yyx990803** [comment]
Use build --target lib.
