### ISSUE TITLE
项目从vue-cli2.x迁移，导致崩溃

### ISSUE THREAD

**Issue by gaarashura** [vuejs/vue-cli#1351]
### Version
3.0.0-beta.11

### Reproduction link
[https://github.com/jantimon/html-webpack-plugin/issues/870](https://github.com/jantimon/html-webpack-plugin/issues/870)

### Steps to reproduce
与上面的html-webpack-plugin中的issue可能是同样的问题

### What is expected?
 92% after chunk asset optimization SourceMapDevToolPlugin 40.js attach SourceMap
 94% after seal
 95% emitting HtmlWebpackPluginD:\WorkSpace\devweb\node_modules\toposort\index.js:35
      throw new Error('Cyclic dependency'   nodeRep)
      ^

Error: Cyclic dependency
    at visit (D:\WorkSpace\devweb\node_modules\toposort\index.js:35:13)
    at visit (D:\WorkSpace\devweb\node_modules\toposort\index.js:53:9)
    at visit (D:\WorkSpace\devweb\node_modules\toposort\index.js:53:9)
    at Function.toposort [as array] (D:\WorkSpace\devweb\node_modules\toposort\index.js:22:22)
    at Object.module.exports.dependency (D:\WorkSpace\devweb\node_modules\html-webpack-plugin\lib\chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (D:\WorkSpace\devweb\node_modules\html-webpack-plugin\index.js:364:35)
    at D:\WorkSpace\devweb\node_modules\html-webpack-plugin\index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\WorkSpace\devweb\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\WorkSpace\devweb\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.emitAssets (D:\WorkSpace\devweb\node_modules\webpack\lib\Compiler.js:307:19)
    at onCompiled (D:\WorkSpace\devweb\node_modules\webpack\lib\Watching.js:50:19)
    at hooks.afterCompile.callAsync.err (D:\WorkSpace\devweb\node_modules\webpack\lib\Compiler.js:487:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\WorkSpace\devweb\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\WorkSpace\devweb\node_modules\tapable\lib\Hook.js:35:21)
    at compilation.seal.err (D:\WorkSpace\devweb\node_modules\webpack\lib\Compiler.js:484:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\WorkSpace\devweb\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:9:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

进程完成，退出码 1

### What is actually happening?
程序无法运行

---
在vue.config.js中修改html-webpack-plugin的chunksSortMode参数为‘none’后程序正常运行

**Comment by ckken** [comment]
same issue how can i fixed it

**Comment by GodStream** [comment]
求助 vue.config.js 里 html-webpack-plugin 配置是怎样修改的？
@gaarashura

**Comment by transtone** [comment]
@GodStream 
https://github.com/vuejs/vue-cli/blob/dev/docs/guide/webpack.md
```js
// vue.config.js
module.exports = {
  chainWebpack: config => {
    config
      .plugin('html')
      .tap(args => {
        return [{ chunksSortMode: "none" }]
      })
  }


```

**Comment by GodStream** [comment]
@transtone 
当天已经找到配置方式了，不过还是感谢回复

**Comment by ysfscream** [comment]
运行 `yarn test:unit` 出现了相同的问题，相同配置了`chainwebpack`后还是没能解决，求助一下！
