### ISSUE TITLE
Corporate Proxy Issue

### ISSUE THREAD

**Issue by tpck** [vuejs/vue-cli#1364]
### Version
3.0.0-beta.11

### Reproduction link
[https://github.com](https://github.com)

### Steps to reproduce
`vue create <project_name>`

### What is expected?
A project to be created.

### What is actually happening?
It hangs for awhile then times out with the following error: ERROR  RequestError: Error: connect ETIMEDOUT

---
Any documentation/steps I can take to fix the issue? I have CNTLM configured for NPM to work behind the proxy, but not sure what I should do to get vue-cli to work as normal.

Edit: as a workaround, can I use vue-loader manually to get around the proxy issue? Looking at the documentation it looks like it wants you to use vue-cli though. Is there a guide on installing vue-loader?

**Comment by marco-carvalho** [comment]
i'm having the same problem

```
ERROR  RequestError: Error: connect ETIMEDOUT 104.18.94.96:443
RequestError: Error: connect ETIMEDOUT 104.18.94.96:443
    at new RequestError (C:\Users\mlj\AppData\Roaming\npm\node_modules\@vue\cli\nodese-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\mlj\AppData\Roaming\npm\node_modules\@vueest-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\mlj\AppData\Roaming\npm\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\mlj\AppData\Roaming\npm\node_modules\@vue\cli\node_mojs:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (C:\Users\mlj\AppData\Roaming\npm\node_modules\@vue\cl\request.js:877:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:375:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
```

**Comment by yyx990803** [comment]
Closing as we don't really have the network environment to reproduce or debug the scenario. Here's some general info which hopefully can help to some extent:

- Vue CLI respects `http_proxy` or `https_proxy` env variables
- You can also explicitly specify the proxy to use with the `--proxy` flag when running `vue create`.

**Comment by wcheek** [comment]
This is an npm issue I think. If we config the proxy for npm it should solve the issue. Try this:
```bash
# Set Proxy
npm config set proxy http://<username>:<password>@<proxy-server-url>:<port> 
npm config set https-proxy http://<username>:<password>@<proxy-server-url>:<port> 

# Unset proxy
npm config rm proxy 
npm config rm https-proxy
```
Don't forget the `http://`!
