### ISSUE TITLE
Cannot set property 'filename' of undefined

### ISSUE THREAD

**Issue by Patcher56** [vuejs/vue-cli#1378]
### Version
3.0.0-beta.11

### Reproduction link
[https://github.com/Patcher56/vue-flowy/blob/master/package.json](https://github.com/Patcher56/vue-flowy/blob/master/package.json)

### Steps to reproduce
1. yarn install
2. Type in yarn dev into terminal for building in development mode for target library and watch it for changes

### What is expected?
Building my library in development mode and watch it for changes

### What is actually happening?
An error (seems unhandled) appears:
```
⠋  Building for development as library (commonjs   umd)... ERROR  TypeError: Cannot set property 'filename' of undefined
TypeError: Cannot set property 'filename' of undefined
    at config.plugin.tap.args (/home/patrick/dev/vue-flowy/node_modules/@vue/cli-service/lib/commands/build/resolveLibConfig.js:38:30)
    at Object.tap (/home/patrick/dev/vue-flowy/node_modules/webpack-chain/src/Plugin.js:19:24)
    at genConfig (/home/patrick/dev/vue-flowy/node_modules/@vue/cli-service/lib/commands/build/resolveLibConfig.js:37:12)
    at module.exports (/home/patrick/dev/vue-flowy/node_modules/@vue/cli-service/lib/commands/build/resolveLibConfig.js:99:5)
    at build (/home/patrick/dev/vue-flowy/node_modules/@vue/cli-service/lib/commands/build/index.js:74:52)
    at Service.run (/home/patrick/dev/vue-flowy/node_modules/@vue/cli-service/lib/Service.js:167:12)
    at Object.<anonymous> (/home/patrick/dev/vue-flowy/node_modules/@vue/cli-service/bin/vue-cli-service.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

---
I am no pro with vue-cli-service or webpack. Can be possible that I misconfigured something.
Anyway it would be cool if there appears a better error description with the information what I did wrong.
Node version stable 10.0.0

**Comment by LinusBorg** [comment]
When building with `--target lib` you also have to define a `--name` for the generated UMD lib to use.
