### ISSUE TITLE
TypeError: api.injectImports is not a function

### ISSUE THREAD

**Issue by zyw5791557** [vuejs/vue-cli#1400]
### Version
3.0.0-beta.13

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
npm i -g @vue/cli or yarn add global @vue/cli.
Then run vue create <project-name> and select default settings.

### What is expected?
Command to scaffold project and install dependencies.

### What is actually happening?
```
 Invoking generators...
 ERROR  TypeError: api.injectImports is not a function
TypeError: api.injectImports is not a function
    at module.exports (E:\web\练手\hehe\node_modules\@vue\cli-service\generator\router\index.j
s:2:7)
    at module.exports (E:\web\练手\hehe\node_modules\@vue\cli-service\generator\index.js:28:24
)
    at Generator.plugins.forEach (C:\Program Files\nodejs\node_modules\@vue\cli\lib\Generator.js:46:7)
    at Array.forEach (<anonymous>)
    at new Generator (C:\Program Files\nodejs\node_modules\@vue\cli\lib\Generator.js:44:13)
    at Creator.create (C:\Program Files\nodejs\node_modules\@vue\cli\lib\Creator.js:136:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by Nandiin** [comment]
8b32f4a60f4c1dff4d7f995643fffa90a82be35b addes this feautre

@vue/cli always uses `npm install` to install current version of @vue/cli-service when creating new project thus when a new version is released it causes a version-mismatch
