### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by zyw5791557** [vuejs/vue-cli#1401]
### Version
3.0.0-beta.13

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
npm i -g or yarn add global .
Then run vue create and select default settings.

### What is expected?
build success

### What is actually happening?
```
λ npm run build

> lala@0.1.0 build E:\web\练手\lala
> vue-cli-service build


-  Building for production... ERROR  TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at config.plugin.tap (E:\web\练手\lala\vue.config.js:38:32)
    at Object.tap (E:\web\练手\lala\node_modules\webpack-chain\src\Plugin.js:19:24)
    at chainWebpack (E:\web\练手\lala\vue.config.js:37:14)
    at webpackChainFns.forEach.fn (E:\web\练手\lala\node_modules\@vue\cli-service\lib\Service.
js:173:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (E:\web\练手\lala\node_modules\@vue\cli-service\l
ib\Service.js:173:26)
    at Service.resolveWebpackConfig (E:\web\练手\lala\node_modules\@vue\cli-service\lib\Servic
e.js:177:48)
    at PluginAPI.resolveWebpackConfig (E:\web\练手\lala\node_modules\@vue\cli-service\lib\Plug
inAPI.js:103:25)
    at build (E:\web\练手\lala\node_modules\@vue\cli-service\lib\commands\build\index.js:81:27
)
    at Service.run (E:\web\练手\lala\node_modules\@vue\cli-service\lib\Service.js:167:12)
    at Object.<anonymous> (E:\web\练手\lala\node_modules\@vue\cli-service\bin\vue-cli-service.
js:22:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lala@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lala@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator.SKY-20170515ZBK\AppData\Roaming\npm-cache\_logs\2018-05-30T03_03_45_177Z-debug.log
```

**Comment by Akryum** [comment]
Thanks for submitting this issue! Due to our limited time, we ask you to include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository) so we can find what is causing the issue. Thank you for your understanding!

**Comment by zyw5791557** [comment]
@Akryum thanks， i have solved this issue.
