### ISSUE TITLE
test:unit with jest can't find babel in freshly created project

### ISSUE THREAD

**Issue by davestaab** [vuejs/vue-cli#1424]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/davestaab/vue-cli-jest-broken.git](https://github.com/davestaab/vue-cli-jest-broken.git)

### Steps to reproduce
1. install the new 3.0.0-beta.15 cli
2. create a new app with `vue create test-app`
3. select `pwa, eslint, unit-jest e2e-cypress` as the features
4. run unit tests with `npm run test:unit`

Unit tests fail with error:

Test suite failed to run
```
Cannot find module '@babel/core'
    at Object.<anonymous> (node_modules/babel-core/index.js:2:18)
```

### What is expected?
The basic unit test is expected to run and pass

### What is actually happening?
The unit tests can't run and fails.
Error message is:

Test suite failed to run
```
Cannot find module '@babel/core'
    at Object.<anonymous> (node_modules/babel-core/index.js:2:18)
```

---
It seems to be related to the e2e-cypress plugin. 
If I don't choose cypress I can get it to run the jest tests

**Comment by davestaab** [comment]
# More Info
I found the problem. I managed to make a vue cli preset without babel but with jest.

Here's my preset:
```json
 "res-standard": {
      "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-pwa": {},
        "@vue/cli-plugin-eslint": {
          "config": "prettier",
          "lintOn": ["save", "commit"]
        },
        "@vue/cli-plugin-unit-jest": {},
        "@vue/cli-plugin-e2e-cypress": {}
      }
    }
```

Notice no mention of `@vue/cli-plugin-babel`. 
----

So the question is how can we prevent someone else from making this mistake?

Is it true that jest is dependant on babel? If so should jest not be an option if you don't choose babel?
