### ISSUE TITLE
RequestError: Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by Christilut** [vuejs/vue-cli#1427]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
vue create my-app

### What is expected?
Vue CLI asking the usual questions

### What is actually happening?
RequestError: Error: unable to verify the first certificate
    at new RequestError (/home/alpha/.npm-global/lib/node_modules/@vue/cli/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/alpha/.npm-global/lib/node_modules/@vue/cli/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/alpha/.npm-global/lib/node_modules/@vue/cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/alpha/.npm-global/lib/node_modules/@vue/cli/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/alpha/.npm-global/lib/node_modules/@vue/cli/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)

---
I installed vue-cli with the global flag but without sudo.
I use [this](https://raw.githubusercontent.com/glenpike/npm-g_nosudo/master/npm-g-nosudo.sh) script to install global packages in my user folder.

Running Kubuntu 18.04

**Comment by Christilut** [comment]
Beta 10 does work as expected. I tried all beta versions up to 15 and they all have the above error.

**Comment by Christilut** [comment]
``npm_config_strict_ssl=false vue create webpack my-project` doesn't help either

**Comment by yyx990803** [comment]
This is probably related to a ping to alternative npm registries. You can try to locally apply the changes in  be5526e to see if that fixes your issue.
