### ISSUE TITLE
TypeError: api.genCacheConfig is not a function

### ISSUE THREAD

**Issue by eaf-josephportello** [vuejs/vue-cli#1437]
### Version
3.0.0-beta.15

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
1) Loaded up working project.
2) Added typescript.
3) Run npm run serve
4) Receive error.

### What is expected?
NPM run serve will begin or begin stating TypeErrors in my actual code.

### What is actually happening?
```
npm run serve

> my-project-beta@0.5.0 serve /Users/user/Documents/Projects/my-project
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  TypeError: api.genCacheConfig is not a function
TypeError: api.genCacheConfig is not a function
    at api.chainWebpack.config (/Users/user/Documents/Projects/my-project/node_modules/@vue/cli-plugin-typescript/index.js:25:20)
    at webpackChainFns.forEach.fn (/Users/user/Documents/Projects/my-project/node_modules/@vue/cli-service/lib/Service.js:173:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/user/Documents/Projects/my-project/node_modules/@vue/cli-service/lib/Service.js:173:26)
    at Service.resolveWebpackConfig (/Users/user/Documents/Projects/my-project/node_modules/@vue/cli-service/lib/Service.js:177:48)
    at PluginAPI.resolveWebpackConfig (/Users/user/Documents/Projects/my-project/node_modules/@vue/cli-service/lib/PluginAPI.js:102:25)
    at serve (/Users/user/Documents/Projects/my-project/node_modules/@vue/cli-service/lib/commands/serve.js:43:31)
    at Service.run (/Users/user/Documents/Projects/my-project/node_modules/@vue/cli-service/lib/Service.js:167:12)
    at Object.<anonymous> (/Users/user/Documents/Projects/my-project/node_modules/@vue/cli-service/bin/vue-cli-service.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project-beta@0.5.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project-beta@0.5.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

---
It works pre installing Typescript to the existing project.

Regards

**Comment by Akryum** [comment]
Make sure the cli is at beta.15 and the plugins inside your project too.

**Comment by yyx990803** [comment]
Your core `@vue/cli-service` is not at the same version of the typescript plugin (which is late installed into the project).

**Comment by eaf-josephportello** [comment]
@yyx990803 and @Akryum 

Evan, thanks. That is it. As always, appreciate your insight. Thanks!
