### ISSUE TITLE
TypeError: api.injectImports is not a function

### ISSUE THREAD

**Issue by Zhennan-Ren** [vuejs/vue-cli#1442]
# Version
3.0.0-beta.6
# Operation sequence
1. npm install vue@cli -g
2. vue create myapp
1)Router
2)Vuex
3)CSS Pre-processors
4)Linter / Formatter
5)Unit Testing
# error
Invoking generators...
 ERROR  TypeError: api.injectImports is not a function
TypeError: api.injectImports is not a function
    at module.exports (E:\vue-cli\knowledgeCombing\node_modules\@vue\cli-service\generator\router\index.js:2:7)
    at module.exports (E:\vue-cli\knowledgeCombing\node_modules\@vue\cli-service\generator\index.js:28:24)
    at Generator.plugins.forEach (D:\nodejs\nodejs\node_cache\node_modules\@vue\cli\lib\Generator.js:46:7)
    at Array.forEach (anonymous)
    at new Generator (D:\nodejs\nodejs\node_cache\node_modules\@vue\cli\lib\Generator.js:44:13)
    at Creator.create (D:\nodejs\nodejs\node_cache\node_modules\@vue\cli\lib\Creator.js:137:23)
    at anonymous
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by shamrt** [comment]
Per @darraghenright's [comment](https://github.com/vuejs/vue-cli/issues/1439#issuecomment-396565423):

> For others stumbling across this issue, just upgrade/reinstall vue cli.

> `yarn global add @vue/cli`

> or

> `npm install -g @vue/cli`

> I was running 3.0.0-beta.1 when this error started happening to me - running beta.16 now and all is well again

**Comment by sleroy** [comment]
Thank you the solution has worked.
