### ISSUE TITLE
Installation fails on windows 8.1

### ISSUE THREAD

**Issue by gj1118** [vuejs/vue-cli#146]
I am running Gtit Bash as an Admin on a Windows 8.1 64 Bit OS.  

**Node Version = 4.4.5
NPM version  = 3.9.3**

I am experiencing an issue where 
```
npm install vue-cli -g
```
always fails. This is a fresh installation. 
Following is the error stack 

```
$ npm install -g vue-cli
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "vue-cli"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.3
npm ERR! path C:\Users\USERNAME\AppData\Roaming\npm\node_modules\vue-cli
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\vue-cli' -> 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\.vue-cli.DELETE'
npm ERR!     at moveAway (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\vue-cli' -> 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\.vue-cli.DELETE'
npm ERR!     at Error (native)
npm ERR!  [Error: EPERM: operation not permitted, rename 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\vue-cli' -> 'C:\Users\USERNAME\AppData\Roaming\npm\node_modules\.vue-cli.DELETE']
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\USERNAME\npm-debug.log

```

I can confirm that there is NO vue-cli folder in my appdata\..\node_modules folder.
I created one manually with the hopes that it will work , but that does not work either. 

Can you please help me out with this ? 

Thanks

**Comment by LinusBorg** [comment]
Not a windows expert, but it seems like the npm executable does not have the rights to write to this folder.

**Comment by zigomir** [comment]
@gj1118 still a problem? Googling the issue and saw `npm cache clean` might help you... Can you confirm?

**Comment by zigomir** [comment]
Closing due to inactivity, please open new issue if there's more information available.
