### ISSUE TITLE
Error: Failed to resolve plugin: @vue/cli-service

### ISSUE THREAD

**Issue by macwac** [vuejs/vue-cli#1486]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
vue create my-project
defualt config or custom

### What is expected?
Command to scaffold project and install dependencies.

### What is actually happening?
Command creates package.json, package-lock.json files and installs some (or all?) dependencies into node_modules dir, but doesn't scaffold any other files.

---
$ npm -v
6.1.0
$node -v
v9.2.1

🚀  Invoking generators...
 ERROR  Error: Failed to resolve plugin: @vue/cli-service
Error: Failed to resolve plugin: @vue/cli-service
    at Creator.resolvePlugins (/usr/local/lib/node_modules/@vue/cli/lib/Creator.js:303:15)
    at Creator.create (/usr/local/lib/node_modules/@vue/cli/lib/Creator.js:146:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by macwac** [comment]
similar problem https://github.com/vuejs/vue-cli/issues/1396 but in beta.14 and node v8
