### ISSUE TITLE
Error when setting up a new vue project with latest vue cli 

### ISSUE THREAD

**Issue by lauragift21** [vuejs/vue-cli#1492]
### Version
3.0.0-beta.15

### Steps to reproduce
I tried using the vue create project-name and i keep getting this error.
```
module.js:544
    throw err;
    ^

Error: Cannot find module './ui/bottom-bar'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/egwuenu/.config/yarn/global/node_modules/@vue/cli/node_modules/inquirer/lib/inquirer.js:18:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

### What is expected?
Create a new vue project with vue create command

### What is actually happening?
Throwing `Error: Cannot find module './ui/bottom-bar'`  After running the command.

**Comment by yyx990803** [comment]
Looks like you have a corrupted installation of the `inquirer` module. This is not related to Vue CLI itself.
