### ISSUE TITLE
Callback was already called

### ISSUE THREAD

**Issue by shaunc869** [vuejs/vue-cli#1513]
### Version
3.0.0-beta.15

### Reproduction link
[https://codesandbox.io/s/nkx106k5yl](https://codesandbox.io/s/nkx106k5yl)

### Steps to reproduce
Run yarn pmd

### What is expected?
The app builds and launches.

### What is actually happening?
I get the error:

$ vue-cli-service serve --open --mode pmd
 INFO  Starting development server...
(node:18771) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
 68% building modules 928/946 modules 18 active …/UserAvatar.vue?vue&type=script&lang=ts/Users/hackintosh/PycharmProjects/spm-ts/node_modules/neo-async/async.js:14
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/hackintosh/PycharmProjects/spm-ts/node_modules/neo-async/async.js:14:11)
    at /Users/hackintosh/PycharmProjects/spm-ts/node_modules/neo-async/async.js:2805:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.

---
This happened when I upgraded from vue-cli beta 6 to beta 15.

**Comment by shaunc869** [comment]
This was caused oddly by vuedraggable I have no idea why, but just in case someone else runs across this. I was able to comment it out as I am not currently using it in my code. Please close this issue, thanks!
