### ISSUE TITLE
TypeError: api.injectImports is not a function

### ISSUE THREAD

**Issue by vv13** [vuejs/vue-cli#1547]
### Version
3.0.0-beta.15

### Steps to reproduce
in /.vuerc:
```
{
  "packageManager": "yarn",
  "useTaobaoRegistry": false,
  "presets": {
    "test": {
      "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-eslint": {
          "config": "airbnb",
          "lintOn": [
            "save",
            "commit"
          ]
        }
      },
      "router": true,
      "vuex": true,
      "cssPreprocessor": "stylus"
    }
  }
}
```

then command: 
$ `vue create test -p test`

### What is expected?
🎉  Successfully created project test.
👉  Get started with the following commands:

 $ cd test
 $ yarn serve

### What is actually happening?
TypeError: api.injectImports is not a function
    at module.exports (/PROJECT_PATH/node_modules/@vue/cli-service/generator/router/index.js:2:7)
    at module.exports (/PROJECT_PATH/node_modules/@vue/cli-service/generator/index.js:28:24)
    at Generator.plugins.forEach (/HOME/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:28:7)
    at Array.forEach (<anonymous>)
    at new Generator (/HOME/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:26:13)
    at Creator.create (/HOME/.config/yarn/global/node_modules/@vue/cli/lib/Creator.js:135:23)
    at process._tickCallback (internal/process/next_tick.js:178:7)

---
macOS 10.13.4
yarn@1.7.0
node@10.0.0
npm@6.1.0

`vue create` can only be successful by default (babel, eslint) preset.

**Comment by yyx990803** [comment]
Please update to beta.16.

**Comment by vv13** [comment]
thank u. my local yarn and npm version of @vue/cli is different, i remove yarn package then it works.
