### ISSUE TITLE
[RC3] Cannot read property 'startOffset' of undefined while building

### ISSUE THREAD

**Issue by JCKodel** [vuejs/vue-cli#1612]
### Version
3.0.0-rc.3

### Reproduction link
[http://none.available](http://none.available)

### Steps to reproduce
Just build (or change some existing file)

### What is expected?
The build succeed without any issue.

### What is actually happening?
The build succeeds, but an error is displayed on console (no file related to my project):

```
 DONE  Compiled successfully in 294ms

Type checking in progress...

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.0.250:8080/

G:\XXX\XXX\XXX.Frontend\node_modules\vue-parser\lib\index.js:34
        var nodeContent = input.substring(node.__location.startTag.endOffset, node.__location.endTag.startOffset);
                                                                                                     ^

TypeError: Cannot read property 'startOffset' of undefined
    at padContent (G:\XXX\XXX\XXX.Frontend\node_modules\vue-parser\lib\index.js:34:102)
    at Object.parse (G:\XXX\XXX\XXX.Frontend\node_modules\vue-parser\lib\index.js:19:22)
    at Object.host.getSourceFile (G:\XXX\XXX\XXX.Frontend\node_modules\fork-ts-checker-webpack-plugin\lib\VueProgram.js:118:40)
    at findSourceFile (G:\XXX\XXX\XXX.Frontend\node_modules\typescript\lib\typescript.js:79645:29)
    at processImportedModules (G:\XXX\XXX\XXX.Frontend\node_modules\typescript\lib\typescript.js:79840:25)
    at findSourceFile (G:\XXX\XXX\XXX.Frontend\node_modules\typescript\lib\typescript.js:79696:17)
    at G:\XXX\XXX\XXX.Frontend\node_modules\typescript\lib\typescript.js:79567:85
    at getSourceFileFromReferenceWorker (G:\XXX\XXX\XXX.Frontend\node_modules\typescript\lib\typescript.js:79534:34)
    at processSourceFile (G:\XXX\XXX\XXX.Frontend\node_modules\typescript\lib\typescript.js:79567:13)
    at processRootFile (G:\XXX\XXX\XXX.Frontend\node_modules\typescript\lib\typescript.js:79414:13)

```

I've disabled all linters, checkers and tests while creating the new project. Using babel + typescript + less + sass.

---
The build completes successfully, regadless of this message.

**Comment by Akryum** [comment]
You need to provide a reproduction.

**Comment by ascott18** [comment]
This may have been caused by a self-closing `<script src="..." />` tag somewhere in your components. Self-closing script tags aren't valid. https://github.com/prograhammer/vue-parser/issues/4

**Comment by MeirionHughes** [comment]
Unclosed <script> also causes it
