### ISSUE TITLE
Feat: allow third party plugins to use @vue/cli-test-utils

### ISSUE THREAD

**Issue by nklayman** [vuejs/vue-cli#1693]
### What problem does this feature solve?
This makes it much easier for 3rd-party plugin developers (like myself) to write e2e tests for their plugins. The tools in @vue/cli-test-utils are extremely useful for testing vue-cli plugins and should be available to all plugin devs. There should also be documentation for it in the plugin development section of the docs.

### What does the proposed API look like?
Add documentation for @vue/cli-test-utils in a testing section of the plugin development guide. Also there are some modifications necessary for third party plugins to work properly. When I try and add my plugin to the defaultPreset object, i get `Error: Failed to resolve plugin: vue-cli-plugin-electron-builder`. I think that this is related to the @vue/cli-test-utils expecting all packages to be in packages/@vue/*.

**Comment by nklayman** [comment]
I can get past the failed to resolve plugin by modifying the Creator so that it will use the resolve field of the plugin's options in the inlinePreset argument to `require.resolve()` the package. However, it gets stuck later with the following error:
```
PS C:\Users\Noah\Documents\HTML\vue-cli-plugin-electron-builder> rm -r -fo .\__tests__\projects\build\ ; yarn test --env node
yarn run v1.6.0
(node:10776) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ jest --env node

 RUNS  __tests__/build.spec.js
@vue/cli-service/generator
C:\Users\Noah\Documents\HTML\vue-cli-plugin-electron-builder\node_modules\@vue\cli-service\generator\index.js
@vue/cli-plugin-babel/generator
C:\Users\Noah\Documents\HTML\vue-cli-plugin-electron-builder\node_modules\@vue\cli-plugin-babel\generator.js
@vue/cli-plugin-eslint/generator
C:\Users\Noah\Documents\HTML\vue-cli-plugin-electron-builder\node_modules\@vue\cli-plugin-eslint\generator.js
 FAIL  __tests__/build.spec.js
  × build:electron (1682ms)

  ● build:electron

    Error

      Error: Command failed: C:\Users\Noah\Documents\HTML\vue-cli\packages\@vue\cli-service\bin\vue-cli-service.js build:electron
      internal/modules/cjs/loader.js:596
          throw err;
          ^

      Error: Cannot find module 'vue-cli-plugin-electron-builder'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
      at Function.Module._load (internal/modules/cjs/loader.js:520:25)
      at Module.require (internal/modules/cjs/loader.js:650:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at idToPlugin (../vue-cli/packages/@vue/cli-service/lib/Service.js:128:14)
          at Array.map (<anonymous>)
      at Service.resolvePlugins (../vue-cli/packages/@vue/cli-service/lib/Service.js:152:10)
      at new Service (../vue-cli/packages/@vue/cli-service/lib/Service.js:30:25)
      at Object.<anonymous> (../vue-cli/packages/@vue/cli-service/bin/vue-cli-service.js:16:17)
      at Module._compile (internal/modules/cjs/loader.js:702:30)
      at makeError (../vue-cli/node_modules/execa/index.js:172:9)
      at Promise.all.then.arr (../vue-cli/node_modules/execa/index.js:277:16)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.872s, estimated 12s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nklayman** [comment]
So I found out all the module errors were specific to my computer, as it worked on a different one just fine with the exact same files. Still, documentation would be nice.
