### ISSUE TITLE
vue create not working: Cannot read property 'prev' of undefined

### ISSUE THREAD

**Issue by shunjinchan** [vuejs/vue-cli#1710]
### Version
3.0.0-rc.3

### Reproduction link
https://github.com/vuejs/vue-cli

### Steps to reproduce
```npm install -g @vue/cli```
```vue create <project-name>```

### What is expected?
Should create project and install dependencies

### What is actually happening?
Creates package.json and package-lock.json files but fails with error:
```
🚀  Invoking generators...
 ERROR  TypeError: Cannot read property 'prev' of undefined
TypeError: Cannot read property 'prev' of undefined
    at Compiler.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/nanomatch/lib/compilers.js:213:25)
    at Compiler.visit (/usr/local/lib/node_modules/@vue/cli/node_modules/snapdragon/lib/compiler.js:129:15)
    at Compiler.mapVisit (/usr/local/lib/node_modules/@vue/cli/node_modules/snapdragon/lib/compiler.js:143:12)
    at Compiler.compile (/usr/local/lib/node_modules/@vue/cli/node_modules/snapdragon/lib/compiler.js:168:10)
    at Snapdragon.compile (/usr/local/lib/node_modules/@vue/cli/node_modules/snapdragon/index.js:156:32)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/micromatch/index.js:786:23
    at memoize (/usr/local/lib/node_modules/@vue/cli/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.compile (/usr/local/lib/node_modules/@vue/cli/node_modules/micromatch/index.js:783:10)
    at create (/usr/local/lib/node_modules/@vue/cli/node_modules/micromatch/index.js:686:25)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/micromatch/index.js:695:16
```

**Comment by Akryum** [comment]
What is your OS and node versions?

**Comment by shunjinchan** [comment]
@Akryum 
OS: macOS High Sierra 10.13.5
node: v8.9.4

**Comment by wa05** [comment]
Same problem here.. Windows 10 Node 8.11

`added 1420 packages from 739 contributors in 388.911s
[+] no known vulnerabilities found [11991 packages audited]


🚀  Invoking generators...
 ERROR  TypeError: Cannot read property 'prev' of undefined
TypeError: Cannot read property 'prev' of undefined
    at Compiler.<anonymous> (C:\Users\walte\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\nanomatch\lib\compilers.js:213:25)
    at Compiler.visit (C:\Users\walte\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\snapdragon\lib\compiler.js:129:15)
    at Compiler.mapVisit (C:\Users\walte\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\snapdragon\lib\compiler.js:143:12)
    at Compiler.compile (C:\Users\walte\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\snapdragon\lib\compiler.js:168:10)
    at Snapdragon.compile (C:\Users\walte\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\snapdragon\index.js:156:32)
    at C:\Users\walte\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\micromatch\index.js:786:23
    at memoize (C:\Users\walte\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\micromatch\index.js:859:13)
    at Function.micromatch.compile (C:\Users\walte\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\micromatch\index.js:783:10)
    at create (C:\Users\walte\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\micromatch\index.js:686:25)
    at C:\Users\walte\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\micromatch\index.js:695:16`

**Comment by wa05** [comment]
Solved uninstalling vuetify globally and installing it again ..

**Comment by LinusBorg** [comment]
> vuetify 

Do you mean vue-cli?

**Comment by yyx990803** [comment]
This was caused by an upstream dep and now fixed: https://github.com/micromatch/nanomatch/issues/15
