### ISSUE TITLE
Unknown option: .useBuiltIns. Check out http://babeljs.io/docs/usage/options/ for more information about options.

### ISSUE THREAD

**Issue by itxuye** [vuejs/vue-cli#1743]
I set the babel.config 
```
module.exports = {
  presets: [
    "@vue/app",
    {
      "useBuiltIns": "entry"
    }
  ]
};
```
But i got the error,
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: [BABEL] /src/main.ts: Unknown option: .useBuiltIns. Check out http://babeljs.io/docs/usage/options/ for more information about options.
    at buildUnknownError (/Users/itxuye/Desktop/TutorABC/bd-refactor-ims/node_modules/@babel/core/lib/config/validation/options.js:113:11)
    at Object.keys.forEach.key (/Users/itxuye/Desktop/TutorABC/bd-refactor-ims/node_modules/@babel/core/lib/config/validation/options.js:99:57)
    at Array.forEach (<anonymous>)
    at validate (/Users/itxuye/Desktop/TutorABC/bd-refactor-ims/node_modules/@babel/core/lib/config/validation/options.js:69:21)
    at instantiatePreset (/Users/itxuye/Desktop/TutorABC/bd-refactor-ims/node_modules/@babel/core/lib/config/full.js:242:36)
    at cachedFunction (/Users/itxuye/Desktop/TutorABC/bd-refactor-ims/node_modules/@babel/core/lib/config/caching.js:42:19)
    at loadPresetDescriptor (/Users/itxuye/Desktop/TutorABC/bd-refactor-ims/node_modules/@babel/core/lib/config/full.js:233:45)
    at config.presets.map.descriptor (/Users/itxuye/Desktop/TutorABC/bd-refactor-ims/node_modules/@babel/core/lib/config/full.js:68:19)
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/itxuye/Desktop/TutorABC/bd-refactor-ims/node_modules/@babel/core/lib/config/full.js:66:38)
    at loadFullConfig (/Users/itxuye/Desktop/TutorABC/bd-refactor-ims/node_modules/@babel/core/lib/config/full.js:106:6)
    at process.nextTick (/Users/itxuye/Desktop/TutorABC/bd-refactor-ims/node_modules/@babel/core/lib/transform.js:28:33)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

 @ multi (webpack)-dev-server/client?http://192.168.237.177:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

**Comment by latel** [comment]
same here #2594
