### ISSUE TITLE
npm run build: SyntaxError: Unexpected token: operator (>)

### ISSUE THREAD

**Issue by selfup** [vuejs/vue-cli#175]
First of all, thank you for such a great tool!

***
Started the project with: `vue init browserify project-name`
Everything works fine with `npm run watchify` as well as `npm run dev`
Here is the Repo: https://github.com/selfup/vue-reegux-example-repo

Which uses: https://github.com/selfup/vue-reegux (a state manager I made. So it could potentially be the install method I expose)

***

`vue -V` => 2.3.1 
node v6.6.0
npm  v3.10.8

***

Once I `npm run build`

```bash
> vue-reegux-example-repo@ build /Users/RJPB2/VUE/vue-reegux-example-repo
> cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o dist/build.css ] -e src/main.js | uglifyjs -c warnings=false -m > dist/build.js

Parse error at -:185,40
SyntaxError: Unexpected token: operator (>)
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/RJPB2/VUE/vue-reegux-example-repo/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Users/RJPB2/VUE/vue-reegux-example-repo/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/Users/RJPB2/VUE/vue-reegux-example-repo/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)
    at token_error (eval at <anonymous> (/Users/RJPB2/VUE/vue-reegux-example-repo/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)
    at unexpected (eval at <anonymous> (/Users/RJPB2/VUE/vue-reegux-example-repo/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2106:9)
    at expr_atom (eval at <anonymous> (/Users/RJPB2/VUE/vue-reegux-example-repo/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2633:9)
    at maybe_unary (eval at <anonymous> (/Users/RJPB2/VUE/vue-reegux-example-repo/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2795:19)
    at expr_ops (eval at <anonymous> (/Users/RJPB2/VUE/vue-reegux-example-repo/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2830:24)
    at maybe_conditional (eval at <anonymous> (/Users/RJPB2/VUE/vue-reegux-example-repo/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2835:20)
    at maybe_assign (eval at <anonymous> (/Users/RJPB2/VUE/vue-reegux-example-repo/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2859:20)
```

**Comment by egoist** [comment]
Compile the down to ES5 first?

**Comment by egoist** [comment]
The main entry of your `vue-reegux` is written in ES6, use a compiled version instead. Browserify does not seem to transform modules in `node_modules/*` by default, but here's some alternative https://github.com/babel/babelify/issues/53

**Comment by selfup** [comment]
@egoist Thank you so much. That makes complete sense!
