### ISSUE TITLE
Build fails when HtmlWebpackPlugin is removed from webpack config

### ISSUE THREAD

**Issue by joshiste** [vuejs/vue-cli#1785]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/joshiste/issues/tree/vue-issue-build-wo-html](https://github.com/joshiste/issues/tree/vue-issue-build-wo-html)

### Steps to reproduce
npm run build

### What is expected?
build completes whithout emitting index.html

### What is actually happening?
build fails:
```
TypeError: Cannot read property 'tapAsync' of undefined
    at compiler.hooks.compilation.tap.compilation (/Users/jedmeier/projects/issues/node_modules/@vue/preload-webpack-plugin/src/index.js:128:67)
    at SyncHook.eval [as call] (eval at create (/Users/jedmeier/projects/issues/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:15:1)
    at SyncHook.lazyCompileHook [as _call] (/Users/jedmeier/projects/issues/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation (/Users/jedmeier/projects/issues/node_modules/webpack/lib/Compiler.js:504:26)
    at hooks.beforeCompile.callAsync.err (/Users/jedmeier/projects/issues/node_modules/webpack/lib/Compiler.js:540:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jedmeier/projects/issues/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/jedmeier/projects/issues/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (/Users/jedmeier/projects/issues/node_modules/webpack/lib/Compiler.js:535:28)
    at readRecords.err (/Users/jedmeier/projects/issues/node_modules/webpack/lib/Compiler.js:274:11)
    at Compiler.readRecords (/Users/jedmeier/projects/issues/node_modules/webpack/lib/Compiler.js:402:11)
    at hooks.run.callAsync.err (/Users/jedmeier/projects/issues/node_modules/webpack/lib/Compiler.js:271:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jedmeier/projects/issues/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/jedmeier/projects/issues/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (/Users/jedmeier/projects/issues/node_modules/webpack/lib/Compiler.js:268:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jedmeier/projects/issues/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/jedmeier/projects/issues/node_modules/tapable/lib/Hook.js:35:21)
```

**Comment by LinusBorg** [comment]
You also have to remove the preload and prefetch plugins. Run `vue inspect` so see how to reach them via `chainWebpack`
