### ISSUE TITLE
create project need python, but doc never mention it.

### ISSUE THREAD

**Issue by pecliu** [vuejs/vue-cli#1873]
### Version
3.0.0-rc.5

### Reproduction link
[https://codepen.io/pecliu/pen/NBNzdb](https://codepen.io/pecliu/pen/NBNzdb)

### Steps to reproduce
vue create template

Vue CLI v3.0.0-rc.5
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, Router, Vuex, CSS Pre-processors, Linter
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): SCSS/SASS
? Pick a linter / formatter config: Standard
? Pick additional lint features: Lint on save
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
? Pick the package manager to use when installing dependencies: NPM

### What is expected?
create the project with no error
or vue-cli's docs mention that this application need python 2.7

### What is actually happening?
the process aborted.
console shows:

```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\code\local\vue-cli-3-template\template\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\code\local\vue-cli-3-template\template\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\code\local\vue-cli-3-template\template\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\code\local\vue-cli-3-template\template\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\code\local\vue-cli-3-template\template\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\code\local\vue-cli-3-template\template\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
```

```
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\code\local\vue-cli-3-template\template\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\code\local\vue-cli-3-template\template\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at D:\code\local\vue-cli-3-template\template\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\code\\local\\vue-cli-3-template\\template\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\code\local\vue-cli-3-template\template\node_modules\node-sass
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

---
think about add "need python" into vue-cli's doc ?

**Comment by LinusBorg** [comment]
This is an error from the node-sass package, which only is installed if you choose SASS - and this only happens if node-sass has to be built on your system as npm can't find a pre built binary for your system. 

What system and node version are you on? 

I don't think that we will document edge cases of The nstall process of specific dependencies though.

**Comment by pecliu** [comment]
> What system and node version are you on?

Windows 7 & node v8.10.0   : )

**Comment by feichangtutu** [comment]
same sisue;
 macOS10.13.4 ; node: v8.9.4
