### ISSUE TITLE
Error: Cannot find module 'typescript/package.json'

### ISSUE THREAD

**Issue by CXY037** [vuejs/vue-cli#1985]
### Version
3.0.0-rc.9

### Node and OS info
yarn

### Steps to reproduce
upgrade from rc5 to rc9. Got an error. 
Error: Cannot find module 'typescript/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at api.chainWebpack.config (/home/wwwroot/vuecli/matchmobile/node_modules/@vue/cli-plugin-typescript/index.js:27:23)
    at webpackChainFns.forEach.fn (/home/wwwroot/vuecli/matchmobile/node_modules/@vue/cli-service/lib/Service.js:209:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/home/wwwroot/vuecli/matchmobile/node_modules/@vue/cli-service/lib/Service.js:209:26)
    at Service.resolveWebpackConfig (/home/wwwroot/vuecli/matchmobile/node_modules/@vue/cli-service/lib/Service.js:213:48)
    at PluginAPI.resolveWebpackConfig (/home/wwwroot/vuecli/matchmobile/node_modules/@vue/cli-service/lib/PluginAPI.js:115:25)
    at serve (/home/wwwroot/vuecli/matchmobile/node_modules/@vue/cli-service/lib/commands/serve.js:49:31)
    at Service.run (/home/wwwroot/vuecli/matchmobile/node_modules/@vue/cli-service/lib/Service.js:203:12)
    at Object.<anonymous> (/home/wwwroot/vuecli/matchmobile/node_modules/@vue/cli-service/bin/vue-cli-service.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### What is expected?
work well

### What is actually happening?
Got an error

**Comment by CXY037** [comment]
[3/4] Linking dependencies...
warning "@vue/cli-plugin-babel > babel-loader@8.0.0-beta.4" has unmet peer dependency "webpack@>=2".
warning " > @vue/cli-plugin-typescript@3.0.0-rc.9" has unmet peer dependency "typescript@>=2".
warning "@vue/cli-plugin-typescript > fork-ts-checker-webpack-plugin@0.4.3" has unmet peer dependency "typescript@^2.1.0".
warning "@vue/cli-plugin-typescript > fork-ts-checker-webpack-plugin@0.4.3" has unmet peer dependency "webpack@^2.3.0 || ^3.0.0 || ^4.0.0".
warning "@vue/cli-plugin-typescript > tslint@5.11.0" has unmet peer dependency "typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev".
warning "@vue/cli-plugin-typescript > tslint > tsutils@2.29.0" has unmet peer dependency "typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >= 3.0.0-dev || >= 3.1.0-dev".
warning " > less-loader@4.1.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".

**Comment by CXY037** [comment]
I solve the problem
I add "typescript": "^2.9.0" to the package.json

**Comment by CXY037** [comment]
please close the issue Thx

**Comment by yyx990803** [comment]
You can close it yourself.....

**Comment by CXY037** [comment]
@yyx990803 sorry , I will do next time
