### ISSUE TITLE
Debugging tests failed

### ISSUE THREAD

**Issue by fourteenmeister** [vuejs/vue-cli#2005]
### Version
3.0.0-rc.10

### Node and OS info
yarn 1.6.0 / Windows 7

### Steps to reproduce
to reproduce this error you create empty project (like this vue create hello-world).

### What is expected?
debugging tests

### What is actually happening?
you receive the following error:

```
$ node --inspect-brk ./node_modules/.bin/vue-cli-service test:unit
Debugger listening on ws://127.0.0.1:9229/170adada-3120-4d04-97e9-2881670ea58e
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
D:\Projects\test2\node_modules\.bin\vue-cli-service:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
Waiting for the debugger to disconnect...
```

**Comment by Akryum** [comment]
What options did you chose while creating the project?

**Comment by yyx990803** [comment]
For windows the command should be:

``` sh
node --inspect-brk ./node_modules/@vue/cli-service/bin/vue-cli-service.js test:unit
```

I'll update the docs.
