### ISSUE TITLE
Cannot find module '@vue/cli-plugin-eslint'

### ISSUE THREAD

**Issue by H1D** [vuejs/vue-cli#2111]
### Version
3.0.0-rc.11

### Node and OS info
node v10.8.0, npm 6.2.0, macOS High Sierra

### Steps to reproduce
`vue create test -p default && cd test && vue-cli-service build`

### What is expected?
build

### What is actually happening?
```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@vue/cli-plugin-eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at idToPlugin (/usr/local/lib/node_modules/@vue/cli-service/lib/Service.js:136:14)
    at Array.map (<anonymous>)
    at Service.resolvePlugins (/usr/local/lib/node_modules/@vue/cli-service/lib/Service.js:162:10)
    at new Service (/usr/local/lib/node_modules/@vue/cli-service/lib/Service.js:33:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli-service/bin/vue-cli-service.js:16:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

**Comment by sodatea** [comment]
Since rc.11 we make `vue-template-compiler` a peer dependency of `@vue/cli-service`, so installing `@vue/cli-service-global` won't automatically install `vue-template-compiler`.

A temporary workaround is to manually run `npm i -g vue-template-compiler`

**Comment by sodatea** [comment]
`vue-cli-service` should not be called directly.
You need to call it by `npm run serve` or with a path prefix `./node_modules/.bin/vue-cli-service build`.

**Comment by tdrach** [comment]
I'm getting this same problem with `npm run build`:

**Version:** 3.0.0-beta.9
**Node:** 10.0.0
**macOS:** 10.13.5

```
$ npm run build
> vue-cli-service build

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '@vue/cli-plugin-eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at idToPlugin (/Users/thomasdrach/Documents/code/p/node_modules/@vue/cli-service/lib/Service.js:136:14)
    at Array.map (<anonymous>)
    at Service.resolvePlugins (/Users/thomasdrach/Documents/code/p/node_modules/@vue/cli-service/lib/Service.js:162:10)
    at new Service (/Users/thomasdrach/Documents/code/p/node_modules/@vue/cli-service/lib/Service.js:33:25)
    at Object.<anonymous> (/Users/thomasdrach/Documents/code/p/node_modules/@vue/cli-service/bin/vue-cli-service.js:16:17)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
```

**Comment by Modnadeer** [comment]
เมื่อ 8 ส.ค. 2018 19:14 "Haoqun Jiang" <notifications@github.com> เขียนว่า:
>
> Since rc.11 we make vue-template-compiler a peer dependency of
@vue/cli-service, so installing @vue/cli-service-global won't automatically
install vue-template-compiler.

**Comment by Akryum** [comment]
Still seeing this error in yarn workspaces.

**Comment by Akryum** [comment]
Moving to #4911
