### ISSUE TITLE
dev 分支的源码，运行 lerna bootstrap 失败

### ISSUE THREAD

**Issue by zongkelong** [vuejs/vue-cli#2143]
### Version
3.0.0-rc.12

### Node and OS info
yarn macOS

### Steps to reproduce
1. 下载官方vuecli  dev 分支源码
2. 在根目录下运行 lerna bootstrap
3. 一直报找不到某个包，错误信息如下：
error Couldn't find package "external-dep@1.0.0" required by "babel-transpile-deps@0.1.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find any versions for "@vue/cli-plugin-typescript" that matches "*"
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:51264:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:92:30)
    at /usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find any versions for "@vue/cli-plugin-eslint" that matches "*"
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:51264:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:92:30)
    at /usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find any versions for "@vue/cli-plugin-eslint" that matches "*"
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:51264:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:92:30)
    at /usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find any versions for "@vue/cli-plugin-eslint" that matches "*"
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:51264:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:92:30)
    at /usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find any versions for "@vue/cli-plugin-eslint" that matches "*"
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:243:66)
    at new MessageError (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:272:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:51264:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:92:30)
    at /usr/local/Cellar/yarn/1.9.4/libexec/lib/cli.js:103:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'vue-cli'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'vue-cli'

### What is expected?
期望能把项目跑起来

### What is actually happening?
。。

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-cli/blob/dev/.github/CONTRIBUTING.md

直接运行 `yarn` 就行了，不需要 `lerna bootstrap`

**Comment by zongkelong** [comment]
貌似直接运行 yarn 也不是太行，在 iterm 里面显示如下：
? Please choose a version of "@vue/cli-plugin-eslint" from this list: (Use arrow keys)
❯ 3.0.0-rc.12
  3.0.0-rc.11
  3.0.0-rc.10
  3.0.0-rc.9
  3.0.0-rc.8
  3.0.0-rc.7
  3.0.0-rc.6
  3.0.0-rc.5
  3.0.0-rc.4
  3.0.0-rc.3
  3.0.0-rc.2
  3.0.0-rc.1
  3.0.0-beta.16
  3.0.0-beta.15
  3.0.0-beta.14
  3.0.0-beta.13
  3.0.0-beta.12
  3.0.0-beta.11
  3.0.0-beta.10
  3.0.0-beta.9
  3.0.0-beta.8
  3.0.0-beta.7
  3.0.0-beta.6
  3.0.0-beta.5
  3.0.0-beta.4
  3.0.0-beta.3
  3.0.0-beta.2
  3.0.0-beta.1
  3.0.0-alpha.13
  3.0.0-alpha.12
  3.0.0-alpha.11
  3.0.0-alpha.10
  3.0.0-alpha.9
  3.0.0-alpha.8
  3.0.0-alpha.7
  3.0.0-alpha.6
  3.0.0-alpha.5
  3.0.0-alpha.4
  3.0.0-alpha.3
  3.0.0-alpha.2
Couldn't find any versions for "@vue/cli-plugin-eslint" that matches "*"
? Please choose a version of "@vue/cli-plugin-eslint" from this list: (Use arrow keys)
❯ 3.0.0-rc.12
  3.0.0-rc.11
  3.0.0-rc.10
  3.0.0-rc.9
  3.0.0-rc.8
  3.0.0-rc.7
  3.0.0-rc.6
  3.0.0-rc.5
  3.0.0-rc.4
  3.0.0-rc.3
  3.0.0-rc.2
  3.0.0-rc.1
  3.0.0-beta.16
  3.0.0-beta.15
  3.0.0-beta.14
  3.0.0-beta.13
  3.0.0-beta.12
  3.0.0-beta.11
  3.0.0-beta.10
  3.0.0-beta.9
  3.0.0-beta.8
  3.0.0-beta.7
  3.0.0-beta.6
  3.0.0-beta.5
  3.0.0-beta.4
  3.0.0-beta.3
  3.0.0-beta.2
  3.0.0-beta.1
  3.0.0-alpha.13
  3.0.0-alpha.12
  3.0.0-alpha.11
  3.0.0-alpha.10
  3.0.0-alpha.9
  3.0.0-alpha.8
  3.0.0-alpha.7
  3.0.0-alpha.6
  3.0.0-alpha.5
  3.0.0-alpha.4
  3.0.0-alpha.3
  3.0.0-alpha.2
Couldn't find any versions for "@vue/cli-plugin-typescript" that matches "*"
? Please choose a version of "@vue/cli-plugin-typescript" from this list: (Use arrow keys)
❯ 3.0.0-rc.12
  3.0.0-rc.11
  3.0.0-rc.10
  3.0.0-rc.9
  3.0.0-rc.8
  3.0.0-rc.7
  3.0.0-rc.6
  3.0.0-rc.5
  3.0.0-rc.4
  3.0.0-rc.3
  3.0.0-rc.2
  3.0.0-rc.1
  3.0.0-beta.16
  3.0.0-beta.15
  3.0.0-beta.14
  3.0.0-beta.13
  3.0.0-beta.12
  3.0.0-beta.11
  3.0.0-beta.10
  3.0.0-beta.9
  3.0.0-beta.8
  3.0.0-beta.7
  3.0.0-beta.6
  3.0.0-beta.5
  3.0.0-beta.4
  3.0.0-beta.3
  3.0.0-beta.2
  3.0.0-beta.1
  3.0.0-alpha.13
  3.0.0-alpha.12
  3.0.0-alpha.11
  3.0.0-alpha.10
  3.0.0-alpha.9
  3.0.0-alpha.8
  3.0.0-alpha.7
  3.0.0-alpha.6
  3.0.0-alpha.5
  3.0.0-alpha.4
  3.0.0-alpha.3
  3.0.0-alpha.2
warning Resolution field "babel-core@7.0.0-bridge.0" is incompatible with requested version "babel-core@^6.26.3"
error Couldn't find package "external-dep@1.0.0" required by "babel-transpile-deps@0.1.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by sodatea** [comment]
你用的哪个版本的 yarn？我试了一下 `lerna boostrap` 和 `yarn` 都没碰到你说的问题……

**Comment by githoniel** [comment]
I just ran into this problem,  remove `packages/test` will work
