### ISSUE TITLE
"Error: write EPIPE" in Travis

### ISSUE THREAD

**Issue by Kocal** [vuejs/vue-cli#2176]
### Version
3.0.0-rc.11

### Node and OS info
Node 8.11.3 / yarn 1.9.4 / [Travis Trusty without sudo](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system)

### Steps to reproduce
In a Travis environment:
- Run `yarn build` (which runs `vue-cli-service build --modern`)
- Or run `yarn test:unit` (which runs `vue-cli-service test:unit --runInBand`)

### What is expected?
It should not throw errors.

### What is actually happening?
This is `yarn build` output: 
```
Starting type checking service...
Using 1 worker with 2048MB memory limit
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
```

---
This problem just happens after migrating our code base from [PWA template](https://github.com/vuejs-templates/pwa) to vue-cli 3.

I don't know if it's related to `vue-cli-service` or `yarn` or Travis, because I have another command (`yarn lint` which runs `vue-cli-service lint`) and it's working properly.

Also, sometimes it works fine...  there is no errors... :thinking: 

By the way, I don't have this kind of problem when running those commands:
- on my laptop: Node 9.11.2, yarn 1.7.0, Debian 9.5
- on production server: Node 8.11.3, yarn 1.9.2, Debian 9.5

Thanks you!

**Comment by Kocal** [comment]
Hum, it will be difficult to give you a depo that reproduce this issue, because this problem happens on a private repo (from work). 😕 Anyway I will try to do something.

Oh by the way, I forgot to say that this problem just happens after migrating our code base from [PWA template](https://github.com/vuejs-templates/pwa) to vue-cli 3. 🤔

**Comment by Kocal** [comment]
Interesting, I don't know if it coincidence or not, but I stopped to build the app with `--modern` flag and I have no errors anymore. :thinking:

**Comment by Kocal** [comment]
Interesting, now `yarn lint` gives me this output:

```
Starting type checking service...
Using 1 worker with 2048MB memory limit
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:364:12)
    at PoolWorker.writeJson (/home/travis/build/Yproximite/XXX/node_modules/thread-loader/dist/WorkerPool.js:89:22)
    at PoolWorker.run (/home/travis/build/Yproximite/XXX/node_modules/thread-loader/dist/WorkerPool.js:69:12)
    at WorkerPool.distributeJob (/home/travis/build/Yproximite/XXX/node_modules/thread-loader/dist/WorkerPool.js:326:20)
    at /home/travis/build/Yproximite/XXX/node_modules/thread-loader/node_modules/async/queue.js:10:5
    at Object.process (/home/travis/build/Yproximite/XXX/node_modules/thread-loader/node_modules/async/internal/queue.js:175:17)
    at /home/travis/build/Yproximite/XXX/node_modules/thread-loader/node_modules/async/internal/queue.js:82:19
    at Immediate._onImmediate (/home/travis/build/Yproximite/XXX/node_modules/thread-loader/node_modules/async/internal/setImmediate.js:27:16)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
error Command failed with exit code 1.
```

I will take a look to thread-loader.

**Comment by jvanst** [comment]
I am running into the same problem right now building with TravisCI.

This project is for work but I will make one which I can share the source code of.

### Version
3.0.1

### Node and OS info
OS: [Ubuntu 14.04.5 LTS](https://docs.travis-ci.com/user/reference/trusty/)
Node: v8.12.0
NPM: 6.4.1
NVM: 0.33.11

### Steps to reproduce
Scaffold project with PWA support.

`npm run build` (Which runs `vue-cli-service build`)

### What is expected?

I expect vue-cli to build the appropriate bundles. 

### What is actually happening?

Error is being thrown.

```
> tournkey-client@0.1.0 build /home/travis/build/sport-travel/tournkey-client
> vue-cli-service build
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:376:12)
    at PoolWorker.writeJson (/home/travis/build/sport-travel/tournkey-client/node_modules/thread-loader/dist/WorkerPool.js:89:22)
    at PoolWorker.run (/home/travis/build/sport-travel/tournkey-client/node_modules/thread-loader/dist/WorkerPool.js:69:12)
    at WorkerPool.distributeJob (/home/travis/build/sport-travel/tournkey-client/node_modules/thread-loader/dist/WorkerPool.js:326:20)
    at /home/travis/build/sport-travel/tournkey-client/node_modules/async/queue.js:10:5
    at Object.process (/home/travis/build/sport-travel/tournkey-client/node_modules/async/internal/queue.js:164:17)
    at /home/travis/build/sport-travel/tournkey-client/node_modules/async/internal/queue.js:104:15
    at /home/travis/build/sport-travel/tournkey-client/node_modules/async/internal/onlyOnce.js:12:16
    at callback (/home/travis/build/sport-travel/tournkey-client/node_modules/thread-loader/dist/WorkerPool.js:163:21)
    at /home/travis/build/sport-travel/tournkey-client/node_modules/thread-loader/dist/WorkerPool.js:190:15
    at /home/travis/build/sport-travel/tournkey-client/node_modules/async/internal/map.js:32:9
    at /home/travis/build/sport-travel/tournkey-client/node_modules/async/internal/once.js:12:16
    at replenish (/home/travis/build/sport-travel/tournkey-client/node_modules/async/internal/eachOfLimit.js:59:25)
    at iterateeCallback (/home/travis/build/sport-travel/tournkey-client/node_modules/async/internal/eachOfLimit.js:49:17)
    at /home/travis/build/sport-travel/tournkey-client/node_modules/async/internal/onlyOnce.js:12:16
    at /home/travis/build/sport-travel/tournkey-client/node_modules/async/internal/map.js:29:13
    at Socket.onChunk (/home/travis/build/sport-travel/tournkey-client/node_modules/thread-loader/dist/readBuffer.js:32:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Socket.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tournkey-client@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tournkey-client@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-09-13T17_45_55_960Z-debug.log
The command "npm run build" exited with 1.
Done. Your build exited with 1.
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
{ Error: EPIPE: broken pipe, write errno: -32, code: 'EPIPE', syscall: 'write' }
```

**Comment by jvanst** [comment]
@Kocal Do you have any updates since you last commented?

**Comment by jvanst** [comment]
Update to this. 

I was able to solve this by changing the travis build environment from a container based to full virtualization. The thread-loader package does not play nicely with containers that don't use all the threads available. 

Read more here: https://docs.travis-ci.com/user/reference/overview/#virtualization-environments

To run in a full virtual machine add `sudo: required` to the top of your .travis.yaml

**Comment by Kocal** [comment]
How much boot-time do you lose when using a full VM?

**Comment by jvanst** [comment]
Boot-times are about 30s longer now, a trade off I'm willing to take for now.

**Comment by LinusBorg** [comment]
Would it help to set `parallel` to `false`, or is that even slower?

https://cli.vuejs.org/config/#parallel
