### ISSUE TITLE
Vue UI error at launch: Syntax Error: Unexpected [

### ISSUE THREAD

**Issue by hendrasan** [vuejs/vue-cli#2180]
### Version
3.0.0

### Node and OS info
Node 10.8.0 / Yarn 1.6.0 / npm 6.2.0 / Mac OS

### Steps to reproduce
```
yarn global add @vue/cli
vue ui
```

### What is expected?
Vue UI runs

### What is actually happening?
Error

```
🚀  Starting GUI...
 ERROR  Syntax Error: Unexpected [
               
GraphQL request (78:1)
          77: }
78: [object Object]
              ^
           79: 
               
GraphQLError: Syntax Error: Unexpected [
    at syntaxError (/Users/hendra/.config/yarn/global/node_modules/graphql/error/syntaxError.js:24:10)
    at unexpected (/Users/hendra/.config/yarn/global/node_modules/graphql/language/parser.js:1322:33)
    at parseDefinition (/Users/hendra/.config/yarn/global/node_modules/graphql/language/parser.js:152:9)
    at parseDocument (/Users/hendra/.config/yarn/global/node_modules/graphql/language/parser.js:110:22)
    at Object.parse (/Users/hendra/.config/yarn/global/node_modules/graphql/language/parser.js:38:10)
    at Object.buildSchemaFromTypeDefinitions (/Users/hendra/.config/yarn/global/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:20:33)
    at Object.makeExecutableSchema (/Users/hendra/.config/yarn/global/node_modules/graphql-tools/dist/makeExecutableSchema.js:27:29)
    at new ApolloServerBase (/Users/hendra/.config/yarn/global/node_modules/apollo-server-core/dist/ApolloServer.js:91:43)
    at new ApolloServer (/Users/hendra/.config/yarn/global/node_modules/apollo-server-express/dist/ApolloServer.js:41:1)
    at module.exports (/Users/hendra/.config/yarn/global/node_modules/vue-cli-plugin-apollo/graphql-server/index.js:127:18)```

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by hendrasan** [comment]
Any quick fix that I can do while waiting for the fix/update?

**Comment by hendrasan** [comment]
I tried it in another Mac with the same Node and NPM installed, and it works.
Not sure why it didn't work in the first Mac.

**Comment by joshua-s** [comment]
This happens for me too. Vue CLI 3.5.5 on Mac OS 10.14.4

**Comment by joshua-s** [comment]
It was fixed by removing the `node_modules` directory in my yarn global folder and reinstalling all packages.
