### ISSUE TITLE
Event.js unhandeled error event

### ISSUE THREAD

**Issue by cor** [vuejs/vue-cli#22]
I keep getting this error when running `npm run dev`, i'm using the browserify version
```
> woording-web@0.0.2 dev /Users/cor/Development/woording/woording-web
> watchify -vd -p browserify-hmr -e src/main.js -o dist/build.js & http-server -c 1 -a localhost

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)

npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.3
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! woording-web@0.0.2 dev: `watchify -vd -p browserify-hmr -e src/main.js -o dist/build.js & http-server -c 1 -a localhost`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the woording-web@0.0.2 dev script 'watchify -vd -p browserify-hmr -e src/main.js -o dist/build.js & http-server -c 1 -a localhost'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the woording-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     watchify -vd -p browserify-hmr -e src/main.js -o dist/build.js & http-server -c 1 -a localhost
npm ERR! You can get their info via:
npm ERR!     npm owner ls woording-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cor/Development/woording/woording-web/npm-debug.log
```

**Comment by LeonGr** [comment]
+1

**Comment by PhiliPdB** [comment]
+1

**Comment by yyx990803** [comment]
`EADDRINUSE` means your 8080 port is already in use.

**Comment by cor** [comment]
@yyx990803 That's really weird because port 8080 definitely isn't in use, I've tried it on multiple machines and I keep getting this error

**Comment by yyx990803** [comment]
@cor hmm try upgrading your Node version? The latest stable is at 5.x...

**Comment by cor** [comment]
It had something to do with our (@PhiliPdB, @LeonGr and I) school network, sorry for the inconvenience.
