### ISSUE TITLE
vue inspect --rules error

### ISSUE THREAD

**Issue by JFGHT** [vuejs/vue-cli#2206]
### Version
3.0.0

### Node and OS info
yarn 1.9.4 / Linux Mint 19

### Steps to reproduce
Just typing vue inspect --rule vue OR vue inspect --rules shows this error.

### What is expected?
A list of webpack rules.

### What is actually happening?
TypeError: Cannot read property '0' of undefined
    at config.module.rules.map.r (/home/jesus/apps/annexum-new-webpack/node_modules/@vue/cli-service/lib/commands/inspect.js:25:55)
    at Array.map (<anonymous>)
    at api.registerCommand.args (/home/jesus/apps/annexum-new-webpack/node_modules/@vue/cli-service/lib/commands/inspect.js:25:33)
    at Service.run (/home/jesus/apps/annexum-new-webpack/node_modules/@vue/cli-service/lib/Service.js:203:12)
    at Object.<anonymous> (/home/jesus/apps/annexum-new-webpack/node_modules/@vue/cli-service/bin/vue-cli-service.js:22:9)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

**Comment by JFGHT** [comment]
Here you are:

```
const StyleLintPlugin = require('stylelint-webpack-plugin');

module.exports = {
  devServer: {
    https: true,
  },
  // Fixing CircleCi Bug related to thread-loader
  parallel: !process.env.CIRCLECI,
  configureWebpack: {
    plugins: [
      new StyleLintPlugin({ emitErrors: false, syntax: 'scss' }),
    ],
  },
  chainWebpack: (config) => {
    const svgRule = config.module.rule('svg');

    svgRule.uses.clear();

    svgRule
      .oneOf('inline')
      .resourceQuery(/inline/)
      .use('vue-svg-loader')
      .loader('vue-svg-loader')
      .end()
      .end()
      .oneOf('external')
      .use('file-loader')
      .loader('file-loader')
      .options({ name: 'assets/[name].[hash:8].[ext]' });
  },
};

```

**Comment by sodatea** [comment]
As a workaround, always use `chainWebpack`.

The root cause here is that the merge strategy of `webpack-merge` (which calls `lodash.mergeWith`) strips off the private `__ruleName` property used by `webpack-chain` to stringify config contents.

https://github.com/mozilla-neutrino/webpack-chain/blob/255b4b5f21c70c4fe83844a3fc5ae1da57526b2b/src/Rule.js#L59-L61
