### ISSUE TITLE
Vue-UI missing dependency

### ISSUE THREAD

**Issue by chroriginal** [vuejs/vue-cli#2218]
### Version
3.0.0

### Node and OS info
Node v10.8.0, NPM v6.3.0, MacOS 10.13.6

### Steps to reproduce
vue ui

### What is expected?
The Vue-UI is expected.

### What is actually happening?
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es7.object.entries'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/<USERNAME>/.nvm/versions/node/v10.8.0/lib/node_modules/@vue/cli/node_modules/apollo-upload-server/lib/middleware.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

---
I got earlier an issue with "apollo-server-core":
https://github.com/apollographql/apollo-server/issues/1530

Although the issue has been solved, the "apollo-upload-server" package is referenced in the stack trace and could be related.

**Comment by chroriginal** [comment]
Issue already exists #2215
