### ISSUE TITLE
 404 Not Found: @akryum/winattr@^3.0.0

### ISSUE THREAD

**Issue by Draichi** [vuejs/vue-cli#2220]
### Version
3.0.0

### Node and OS info
node 8.11.3 / yarn 1.9.4 / ubuntu 16.04 / npm 5.6.0

### Steps to reproduce
Trying to install vue-cli 3 running:
```
npm i @vue/cli -g
```

can't find the winattr package:

```
npm ERR! code E404
npm ERR! 404 Not Found: @akryum/winattr@^3.0.0
```
trying with yarn:
```
yarn global add @vue/cli 
```
```
yarn global v1.9.4
[1/4] Resolving packages...
error Couldn't find package "@akryum/winattr@^3.0.0" required by "@vue/cli-ui@^3.0.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
Error: Couldn't find package "@apollographql/graphql-playground-html@^1.6.0" required by "apollo-server-express@^2.0.0-rc.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:243:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:272:123)
    at PackageRequest.<anonymous> (/usr/share/yarn/lib/cli.js:38988:17)
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:92:30)
    at /usr/share/yarn/lib/cli.js:105:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```
i tried to install winattr using 
```
npm i @akryum/winattr
```

same 404 error

### What is expected?
Install vue-cli 3 successfully

### What is actually happening?
Error 404 Not Found: "@akryum/winattr@^3.0.0" required by "@vue/cli-ui@^3.0.0"

---
i tried to uninstall and reinstall node, npm and vue-cli itself

**Comment by sodatea** [comment]
Have you ever modified your `~/.npmrc` file?

**Comment by Draichi** [comment]
Never. Should I?

Em 15 de ago de 2018 05:42, "Haoqun Jiang" <notifications@github.com>
escreveu:

Have you ever modified your ~/.npmrc file?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vuejs/vue-cli/issues/2220#issuecomment-413133068>, or mute
the thread

**Comment by Akryum** [comment]
I think it's an issue with your environment since the package exists: https://www.npmjs.com/package/@akryum/winattr

**Comment by yyx990803** [comment]
Likely outdated local resolution cache, or npm server issue.

**Comment by maweiyi** [comment]
I have the same problem.

**Comment by sodatea** [comment]
Try reset npm cache using
```
npm cache clean --force
```

**Comment by billy21** [comment]
> $ npm install -g @vue/cli  
 
```    
npm ERR! code E404
npm ERR! 404 Not Found: @akryum/winattr@^3.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jiangxin/nodejs/npm_cache/_logs/2018-08-17T14_34_14_944Z-debug.log
```
> $ yarn global add @vue/cli

```
yarn global v1.9.4
warning package.json: No license field
[1/4] 🔍  Resolving packages...
error Couldn't find package "@akryum/winattr@^3.0.0" required by "@vue/cli-ui@^3.0.1" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
Error: Couldn't find package "@apollographql/graphql-playground-html@^1.6.0" required by "apollo-server-express@^2.0.0-rc.5" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/jiangxin/.yarn/lib/cli.js:243:66)
    at new MessageError (/Users/jiangxin/.yarn/lib/cli.js:272:123)
    at PackageRequest.<anonymous> (/Users/jiangxin/.yarn/lib/cli.js:38988:17)
    at Generator.throw (<anonymous>)
    at step (/Users/jiangxin/.yarn/lib/cli.js:92:30)
    at /Users/jiangxin/.yarn/lib/cli.js:105:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by sohcalvin** [comment]
I encountered the same issue. 
This worked for me

npm install --registry=https://registry.npmjs.com/  -g @vue/cli

**Comment by johnnymetz** [comment]
Restarting my machine did the trick

**Comment by darthchudi** [comment]
> npm install --registry=https://registry.npmjs.com/ -g @vue/cli

This worked for me. Thanks

**Comment by ethaneisenhard** [comment]
yarn install v1.13.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this comman
d.
error Couldn't find package "@vue/babel-preset-jsx@^1.0.0-beta.2" required by "@vue/ba
bel-preset-app@^3.4.0" on the "npm" registry.
Error: Couldn't find package "@xtuc/long@4.2.1" required by "@webassemblyjs/leb128@1.7.11" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)
    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:35729:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:317:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@xtuc/long@4.2.1" required by "@webassemblyjs/wast-printer@1.7.11" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)
    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:35729:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:317:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@xtuc/long@4.2.1" required by "@webassemblyjs/wast-parser@1.7.11" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)
    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:35729:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:317:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Couldn't find package "@xtuc/ieee754@^1.2.0" required by "@webassemblyjs/ieee754@1.7.11" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:727:66)
    at new MessageError (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:756:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:35729:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js:317:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
 ERROR  command failed: yarn 
~/TestVue$ yarn -version
1.13.0
~/TestVue$ 

Anyone know how to fix this? I have tried un installing, deleting and then reinstalling. I have updated yarn and I have looked up everything I can on this and cant find the solution.

**Comment by renztoygwapo** [comment]
I got same issue, the yarn add command will not works well when installing the @vue/cli

**Comment by sodatea** [comment]
What about deleting `~/.npmrc` and then try again? In my experience, installation issues of scoped packages are likely to be caused by misconfigured npmrc.
