### ISSUE TITLE
使用Preset选项初始化项目报错 obs.pipe is not a function

### ISSUE THREAD

**Issue by TaroXin** [vuejs/vue-cli#2235]
### Version
3.0.0

### Node and OS info
Node v8.11.1 / Yarn 1.6.0 / Windows 10 / MacOS 10.13.5

### Steps to reproduce
- `vue create --preset ./preset my-project`

创建所使用的Preset仓库地址：`https://github.com/TaroXin/vue-cli-creator-preset.git`

### What is expected?
项目成功创建

### What is actually happening?
得到一个JS错误，错误代码如下
```
success Saved lockfile.
✨  Done in 84.41s.
🚀  Invoking generators...

Preset options:...
 ERROR  TypeError: obs.pipe is not a function
TypeError: obs.pipe is not a function
    at PromptUI.run (/usr/local/lib/node_modules/@vue/cli/node_modules/inquirer/lib/ui/prompt.js:33:24)
    at Object.promptModule [as prompt] (/usr/local/lib/node_modules/@vue/cli/node_modules/inquirer/lib/inquirer.js:28:22)
    at Creator.resolvePlugins (/usr/local/lib/node_modules/@vue/cli/lib/Creator.js:323:36)
    at Creator.create (/usr/local/lib/node_modules/@vue/cli/lib/Creator.js:154:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by sodatea** [comment]
你看错文档了，第三方 preset 的 prompt.js 应该返回一个数组，你复制的代码是内置插件用的

https://cli.vuejs.org/zh/dev-guide/plugin-dev.html#%E7%AC%AC%E4%B8%89%E6%96%B9%E6%8F%92%E4%BB%B6%E7%9A%84%E5%AF%B9%E8%AF%9D
