### ISSUE TITLE
npm run serve     Unclosed string    1870 | }   1871 | .icons-shopping-14:before { > 1872 |   content: "\e182";        |                  ^   1873 | }

### ISSUE THREAD

**Issue by Randy618** [vuejs/vue-cli#2249]
### Version
3.0.0

### Reproduction link
[https://github.com/Randy618/gulu.git](https://github.com/Randy618/gulu.git)### Node and OS info
npm

### Steps to reproduce
npm run serve

### What is expected?
成功启动

### What is actually happening?
报错

---
项目中添加了字体图片 运行 npm run serve 报错 
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                      17:15:40

 error  in ./src/assets/global/css/icons/line-icons/line-icons.css

Module build failed (from ./node_modules/postcss-loader/lib/index.js):
Syntax Error

(1872:18) Unclosed string

  1870 | }
  1871 | .icons-shopping-14:before {
> 1872 |   content: "\e182";
       |                  ^
  1873 | }
  1874 | 

 @ ./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/lib??ref--6-oneOf-3-2!./src/assets/global/css/style.css 10:10-190
 @ ./src/assets/global/css/style.css
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.73:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (F:\workspaces\gulu\node_modules\express\lib\router\layer.js:172:12)
    at Layer.match (F:\workspaces\gulu\node_modules\express\lib\router\layer.js:123:27)
    at matchLayer (F:\workspaces\gulu\node_modules\express\lib\router\index.js:574:18)
    at next (F:\workspaces\gulu\node_modules\express\lib\router\index.js:220:15)
    at expressInit (F:\workspaces\gulu\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (F:\workspaces\gulu\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (F:\workspaces\gulu\node_modules\express\lib\router\index.js:317:13)
    at F:\workspaces\gulu\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (F:\workspaces\gulu\node_modules\express\lib\router\index.js:335:12)
    at next (F:\workspaces\gulu\node_modules\express\lib\router\index.js:275:10)
    at query (F:\workspaces\gulu\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (F:\workspaces\gulu\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (F:\workspaces\gulu\node_modules\express\lib\router\index.js:317:13)
    at F:\workspaces\gulu\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (F:\workspaces\gulu\node_modules\express\lib\router\index.js:335:12)

**Comment by sodatea** [comment]
应该是因为你的 baseUrl 设置用了相对路径
参见这里 https://github.com/vuejs/vue-cli/issues/1451#issuecomment-394183752

如果不是这个原因的话请带上复现代码后重开一个 issue

**Comment by kiran8910** [comment]
This is an issue because of at some css rule within the file might consists of **content:"\";** backward slash will act as an escape sequence so string won't close. Hence, change to **content:"\\"**
