### ISSUE TITLE
vue-cil3.0打包失败

### ISSUE THREAD

**Issue by chenmingye** [vuejs/vue-cli#2316]
### Version
3.0.1

### Node and OS info
v10.9.0

### Steps to reproduce
就随便新建一个项目，然后选择打包就会重现

### What is expected?
尽快

### What is actually happening?
$ vue-cli-service build --mode production --dest dist --target app --dashboard

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at PoolWorker.writeJson (F:\hlhj\tm-back\tm-background\node_modules\thread-loader\dist\WorkerPool.js:89:22)
    at PoolWorker.run (F:\hlhj\tm-back\tm-background\node_modules\thread-loader\dist\WorkerPool.js:69:12)
    at WorkerPool.distributeJob (F:\hlhj\tm-back\tm-background\node_modules\thread-loader\dist\WorkerPool.js:330:17)
    at F:\hlhj\tm-back\tm-background\node_modules\thread-loader\node_modules\async\queue.js:10:5
    at Object.process (F:\hlhj\tm-back\tm-background\node_modules\thread-loader\node_modules\async\internal\queue.js:175:17)
    at F:\hlhj\tm-back\tm-background\node_modules\thread-loader\node_modules\async\internal\queue.js:82:19
    at Immediate.<anonymous> (F:\hlhj\tm-back\tm-background\node_modules\thread-loader\node_modules\async\internal\setImmediate.js:27:16)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:425:12)
    at onwrite (_stream_writable.js:456:5)
    at doWrite (_stream_writable.js:406:11)
    at writeOrBuffer (_stream_writable.js:394:5)
    [... lines matching original stack trace ...]
    at processImmediate (timers.js:646:5)

Error while running task F:\hlhj\tm-back\tm-background:build with message 'spawn vue-cli-service ENOENT'

**Comment by sodatea** [comment]
请提供可以复现的示例，凭目前的描述我们并不能知道你碰上了什么问题。

**Comment by chenmingye** [comment]
就是用vue-cil3.0新建一个项目，然后打包出来就会出现上面的错误，我电脑是今天重装的其他应该没问题呀

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-cli/issues/2096 
参见这里的讨论。
可以稍后重试，也可以在命令行打包。

**Comment by chenmingye** [comment]
我这个问题各种尝试都做过了，也已经重装过系统了，那边的讨论上午看过好像并没有什么好的解决办法

**Comment by lx28110846** [comment]
> 我这个问题各种尝试都做过了，也已经重装过系统了，那边的讨论上午看过好像并没有什么好的解决办法

重装系统就好了吗？？我也是刚装的win10也是同样的问题

**Comment by 768722060** [comment]
如何解决??
