### ISSUE TITLE
BaseURI decoding problem when running serve

### ISSUE THREAD

**Issue by joanlamrack** [vuejs/vue-cli#2342]
### Version
3.0.1

### Node and OS info
Node 10.6.0/Ubuntu 18.04 LTS

### Steps to reproduce
vue create <app name>
cd <app name>
npm run serve

### What is expected?
the initial vue -cli project should be loaded when accessing localhost:8080 and behaving normally

### What is actually happening?
when the localhost:8080 accessed, it seems that the vue app is not injected, resulting in blank html page.

in the terminal, it showed error::

URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:574:18)
    at next (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:317:13)
    at /home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:335:12)
    at next (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:275:10)
    at query (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:317:13)
    at /home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:335:12)
URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:574:18)
    at next (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:317:13)
    at /home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:335:12)
    at next (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:275:10)
    at query (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:317:13)
    at /home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/zephira/#JoanUbuntuData/Hacktiv8/Phase2/Week3/golb-blog-client/node_modules/express/lib/router/index.js:335:12)

---
weirdly enough, if you made the project in trash directory, it behaves normally.

already tried install and unistalling vue-cli few times as global

**Comment by sodatea** [comment]
Please provide a reproduction repo.
Also, check if this issues is relevant https://github.com/vuejs/vue-cli/issues/1451

**Comment by joanlamrack** [comment]
you were very right indeed, i removed the # and it works, didnt know it would caused complications
