### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by hanwong** [vuejs/vue-cli#2388]
### Version
3.0.0

### Node and OS info
node 9.8.0 / npm 5.6.0 / macOS 10.13.1

### Steps to reproduce
When install project like below settings.

? Please pick a preset: Manually select features
? Check the features needed for your project: TS, Router, Vuex, CSS Pre-processors
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript for auto-detected polyfills? Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): SCSS/SASS
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No

### What is expected?
Fix this errors

### What is actually happening?
Vue CLI v3.0.0-beta.9
✨  Creating project in /Users/hanwoongkim/workspace/vue-ts22.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

> fsevents@1.2.4 install /Users/hanwoongkim/workspace/vue-ts22/node_modules/fsevents
> node install

[fsevents] Success: "/Users/hanwoongkim/workspace/vue-ts22/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote

> yorkie@2.0.0 install /Users/hanwoongkim/workspace/vue-ts22/node_modules/yorkie
> node bin/install.js

setting up Git hooks
done

added 1342 packages in 20.388s

🚀  Invoking generators...
 ERROR  TypeError: api.injectImports is not a function
TypeError: api.injectImports is not a function
    at module.exports (/Users/hanwoongkim/workspace/vue-ts22/node_modules/@vue/cli-service/generator/router/index.js:2:7)
    at module.exports (/Users/hanwoongkim/workspace/vue-ts22/node_modules/@vue/cli-service/generator/index.js:28:24)
    at Generator.plugins.forEach (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:46:7)
    at Array.forEach (<anonymous>)
    at new Generator (/usr/local/lib/node_modules/@vue/cli/lib/Generator.js:44:13)
    at Creator.create (/usr/local/lib/node_modules/@vue/cli/lib/Creator.js:136:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

**Comment by sodatea** [comment]
You are using Vue CLI v3.0.0-beta.9. Please update to the latest v3.0.1
