### ISSUE TITLE
添加了element-ui的运行依赖后，运行依赖中看不到element-ui。

### ISSUE THREAD

**Issue by vimtt** [vuejs/vue-cli#2469]
### Version
3.0.0

### Node and OS info
node 8.9.4 npm 4.6.1

### Steps to reproduce
点击添加依赖，查找element-ui,勾选，安装，提示成功

### What is expected?
运行依赖中显示element-ui

### What is actually happening?
运行依赖中没有显示element-ui

**Comment by sodatea** [comment]
无法复现。
请问 `element-ui` 是否有成功写入项目的 package.json？

**Comment by vimtt** [comment]
安装vux后也是一样的问题，后面有异常信息

kiosk-cli@0.1.0 H:\workspace\application\vuejs\kiosk-cli
`-- vux@2.9.2
  +-- @antv/f2@3.2.2
  | +-- @antv/adjust@0.0.7
  | | `-- @antv/util@1.2.5
  | |   `-- @antv/gl-matrix@2.7.1
  | +-- @antv/attr@0.0.7
  | | `-- @antv/util@1.2.5
  | |   `-- @antv/gl-matrix@2.7.1  deduped
  | +-- @antv/scale@0.0.9
  | | +-- @antv/util@1.2.5
  | | | `-- @antv/gl-matrix@2.7.1  deduped
  | | `-- fecha@2.3.3
  | +-- @antv/util@1.0.12
  | `-- hammerjs@2.0.8
  +-- array-filter@1.0.0
  +-- array-find@1.0.0
  +-- array-shuffle@1.0.1
  +-- autosize@3.0.21
  +-- axios@0.15.3
  | `-- follow-redirects@1.0.0
  |   `-- debug@2.6.9
  +-- blueimp-md5@2.10.0
  +-- countup.js@1.9.3
  +-- fastclick@1.0.6
  +-- lodash.throttle@4.1.1
  +-- qr.js@0.0.0
  +-- shake.js@1.2.2
  +-- validator@9.4.1
  +-- vanilla-masker@1.2.0
  +-- vux-blazy@1.6.4
  +-- vux-xscroll@3.1.12
  `-- x-photoswipe@4.1.3-rc.1

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:499:7)
    at Object.readPackage (D:\root\nodejs\npm_global_modules\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\folders.js:103:24)
    at readPackage (D:\root\nodejs\npm_global_modules\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:84:20)
    at getLink (D:\root\nodejs\npm_global_modules\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:163:15)
    at Object.keys.filter.map.id (D:\root\nodejs\npm_global_modules\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:64:16)
    at Array.map (<anonymous>)
    at findDependencies (D:\root\nodejs\npm_global_modules\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:59:5)
    at list (D:\root\nodejs\npm_global_modules\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:45:5)
    at progress.wrap (D:\root\nodejs\npm_global_modules\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:188:5)

**Comment by LinusBorg** [comment]
@sodatea can we close this? No successful reproduction for 3 months. Anything left to do?
