### ISSUE TITLE
devServer does not start when proxy target is an object

### ISSUE THREAD

**Issue by hoa1942** [vuejs/vue-cli#2478]
### Version
3.0.1

### Reproduction link
[https://github.com/hoa1942/vue-cli-proxy-bug](https://github.com/hoa1942/vue-cli-proxy-bug)

### Node and OS info
node v8.11.2 / npm 5.6.0

### Steps to reproduce
execute 'npm run serve'

### What is expected?
App to start up with proxy working

### What is actually happening?
Getting exception:

```
 INFO  Starting development server...
 ERROR  TypeError: Parameter "url" must be a string, not object
TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at resolveLoopback (node_modules\@vue\cli-service\lib\util\prepareProxy.js:131:17)
    at createProxyEntry (node_modules\@vue\cli-service\lib\util\prepareProxy.js:55:16)
    at Object.keys.map.context (node_modules\@vue\cli-service\lib\util\prepareProxy.js:125:19)
    at Array.map (<anonymous>)
    at prepareProxy (node_modules\@vue\cli-service\lib\util\prepareProxy.js:114:29)
    at serve (node_modules\@vue\cli-service\lib\commands\serve.js:95:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

---

I need to proxy to a server that requires ssl and a client certificate.  

My config in vue.config.js looks like this:  

```
module.exports = {
	devServer : {
		https : true,
//		pfx : fs.readFileSync(process.env.proxyServerCert),
//		pfxPassphrase : process.env.proxyServerCertPassword,
//		ca : fs.readFileSync(process.env.proxyServerCA),
//		requestCert : false,		
		
		proxy : {
			'/test' : {
				target : {
					protocol : 'https:',
					host : 'localhost',
					port : 8443
					//pfx :  fs.readFileSync(process.env.proxyClientCert),
					//passphrase : process.env.proxyClientCertPassword,
					//ca : fs.readFileSync(process.env.proxyServerCA)					
				},
				changeOrigin : true,
				logLevel : 'debug',
			}
		}
	}
}
```

I have commented out the additional properties that I use but are not required to repro the problem.  The equivalent config works in vue-cli 2.x.

To get around the problem for now I've modified 'node_modules/@vue/cli-service/lib/util/prepareProxy.js' on line 54 to include a check for 'string' type before attempting to call resolveLoopback(target)

```
 53  function createProxyEntry (target, usersOnProxyReq, context) {
 54      if (typeof target === 'string' && process.platform === 'win32') {
 55         target = resolveLoopback(target)
 56      }
```

Obviously this is not really a viable work-around since every developer has to make the change not to mention issues with automated builds

**Comment by iagocavalcante** [comment]
Can I try to contribute  ?
