### ISSUE TITLE
build failure bug

### ISSUE THREAD

**Issue by Longx** [vuejs/vue-cli#2483]
![_20180911175121](https://user-images.githubusercontent.com/16624689/45354837-4ab63100-b5f1-11e8-94b9-40a3d329ba6f.png)
![_20180911175230](https://user-images.githubusercontent.com/16624689/45354838-4ab63100-b5f1-11e8-9706-8c20977fb4de.png)

### Version
3.0.1

### Node and OS info
windows7 / node 11.8.1 / yarn 1.9.2

### Steps to reproduce
$ yarn build
yarn run v1.9.2
$ vue-cli-service build

|  Building for production...

 ERROR  Failed to compile with 2 errors                                                      17:50:02

 error  in ./src/App.vue?vue&type=style&index=0&lang=scss&

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[NS] is not a function
    at childCompiler.runAsChild (D:\job\xinghan\cli3-test\node_modules\mini-css-extract-plugin\dist\l
oader.js:148:15)
    at compile (D:\Job\xinghan\cli3-test\node_modules\webpack\lib\Compiler.js:296:11)
    at hooks.afterCompile.callAsync.err (D:\Job\xinghan\cli3-test\node_modules\webpack\lib\Compiler.j
s:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Job\xinghan\cli3-test\node_modules\tap
able\lib\HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Job\xinghan\cli3-test\node_modules\tapable
\lib\Hook.js:35:21)
    at compilation.seal.err (D:\Job\xinghan\cli3-test\node_modules\webpack\lib\Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Job\xinghan\cli3-test\node_modules\tap
able\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Job\xinghan\cli3-test\node_modules\tapable
\lib\Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (D:\Job\xinghan\cli3-test\node_modules\webpack\lib\Compilat
ion.js:1294:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Job\xinghan\cli3-test\node_modules\tap
able\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Job\xinghan\cli3-test\node_modules\tapable
\lib\Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (D:\Job\xinghan\cli3-test\node_modules\webpack\lib\Com
pilation.js:1285:32)
    at _err0 (eval at create (D:\Job\xinghan\cli3-test\node_modules\tapable\lib\HookCodeFactory.js:24
:12), <anonymous>:11:1)
    at D:\Job\xinghan\cli3-test\node_modules\uglifyjs-webpack-plugin\dist\index.js:287:11
    at Runner.runTasks (D:\Job\xinghan\cli3-test\node_modules\uglifyjs-webpack-plugin\dist\uglify\Run
ner.js:67:9)
    at UglifyJsPlugin.optimizeFn (D:\Job\xinghan\cli3-test\node_modules\uglifyjs-webpack-plugin\dist\
index.js:198:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Job\xinghan\cli3-test\node_modules\tap
able\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Job\xinghan\cli3-test\node_modules\tapable
\lib\Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (D:\Job\xinghan\cli3-test\node_modules\webpack\lib\Compil
ation.js:1280:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Job\xinghan\cli3-test\node_modules\tap
able\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\Job\xinghan\cli3-test\node_modules\tapable
\lib\Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (D:\Job\xinghan\cli3-test\node_modules\webpack\lib\Compilatio
n.js:1276:32)

 @ ./src/App.vue?vue&type=style&index=0&lang=scss& 1:0-482 1:498-501 1:503-982 1:503-982
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

### What is expected?
yarn build failure

### What is actually happening?
 Running the yarn build with cmd under windows can package the file normally, but it will fail to package directly under git bash.

**Comment by sodatea** [comment]
Closed in favor of https://github.com/vuejs/vue-cli/issues/2223
