### ISSUE TITLE
crashed with nodejs 7.1.0 on windows10

### ISSUE THREAD

**Issue by luxp** [vuejs/vue-cli#254]
My vue-cli version is 2.5.1, and nodejs version is 7.1.0.
When I try to run `vue init webpack` throw errors below
```
D:\Project\lu>node -v
v7.1.0

D:\Project\lu>vue --version
2.5.1

D:\Project\lu>vue init webpack

D:\App\Node\node_modules\vue-cli\node_modules\rx-lite\rx.lite.js:75
    throw e;
    ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at MuteStream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at MuteStream.emit (events.js:188:7)
    at MuteStream.write (D:\App\Node\node_modules\vue-cli\node_modules\mute-stream\mute.js:116:8)
    at Object.exports.clearLine (D:\App\Node\node_modules\vue-cli\node_modules\inquirer\lib\utils\readline.js:50:13)
    at module.exports.ScreenManager.clean (D:\App\Node\node_modules\vue-cli\node_modules\inquirer\lib\utils\screen-manager.js:92:8)
    at module.exports.ScreenManager.render (D:\App\Node\node_modules\vue-cli\node_modules\inquirer\lib\utils\screen-manager.js:26:8)
    at Prompt.render (D:\App\Node\node_modules\vue-cli\node_modules\inquirer\lib\prompts\confirm.js:85:15)
    at Prompt._run (D:\App\Node\node_modules\vue-cli\node_modules\inquirer\lib\prompts\confirm.js:65:8)
```
When I changed my nodejs version to v6.9.1, it works well.

**Comment by aronpc** [comment]
Same issue here (Windows 10)

```
$ node --version
v7.1.0

$ npm --version
4.0.5

$ vue --version
2.5.1

$ vue init webpack

C:\Users\aronc\AppData\Roaming\npm\node_modules\vue-cli\node_modules\rx-lite\rx.lite.js:75
    throw e;
    ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at MuteStream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
    at MuteStream.emit (events.js:188:7)
    at MuteStream.write (C:\Users\aronc\AppData\Roaming\npm\node_modules\vue-cli\node_modules\mute-stream\mute.js:116:8)
    at Object.exports.clearLine (C:\Users\aronc\AppData\Roaming\npm\node_modules\vue-cli\node_modules\inquirer\lib\utils\readline.js:50:13)
    at module.exports.ScreenManager.clean (C:\Users\aronc\AppData\Roaming\npm\node_modules\vue-cli\node_modules\inquirer\lib\utils\screen-manager.js:92:8)
    at module.exports.ScreenManager.render (C:\Users\aronc\AppData\Roaming\npm\node_modules\vue-cli\node_modules\inquirer\lib\utils\screen-manager.js:26:8)
    at Prompt.render (C:\Users\aronc\AppData\Roaming\npm\node_modules\vue-cli\node_modules\inquirer\lib\prompts\confirm.js:85:15)
    at Prompt._run (C:\Users\aronc\AppData\Roaming\npm\node_modules\vue-cli\node_modules\inquirer\lib\prompts\confirm.js:65:8)
```

**Comment by Cheazer** [comment]
Same issue on windows10

**Comment by Cheazer** [comment]
solved w/ node 7.2.0

**Comment by posva** [comment]
Closing since this seems to be solved. Can you confirm, please, @luxp @aronpc

**Comment by luxp** [comment]
It works well with node v7.2.1 and v7.3.0 on windows 10. @posva

**Comment by readone7** [comment]
failing on node v7.10.0

**Comment by readone7** [comment]
Error: EINVAL: invalid argument, uv_interface_addresses
    at Object.lib.networkInterfaces (/mnt/c/Sites/JS_projects/second-vue/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/Sites/JS_projects/second-vue/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/Sites/JS_projects/second-vue/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/Sites/JS_projects/second-vue/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/Sites/JS_projects/second-vue/node_modules/cssnano/dist/index.js:21:30)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! second-vue@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the second-vue@1.0.0 build script 'node build/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the second-vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs second-vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls second-vue
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /home/codesmear/.npm/_logs/2017-06-15T15_25_54_803Z-debug.log.2321715871
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open '/home/codesmear/.npm/_logs/2017-06-15T15_25_54_803Z-debug.log.2321715871'
npm ERR!  { Error: EACCES: permission denied, open '/home/codesmear/.npm/_logs/2017-06-15T15_25_54_803Z-debug.log.2321715871'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
