### ISSUE TITLE
@vue/cli 3.x 创建项目失败

### ISSUE THREAD

**Issue by xuehebinglan** [vuejs/vue-cli#2566]
### Version
3.0.3

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-cli](https://new-issue.vuejs.org/?repo=vuejs/vue-cli)

### Node and OS info
node: v10.10.0 npm: 6.4.1 mac

### Steps to reproduce
1.使用npm install -g @vue/cli安装全局包

2.使用vue --version检测版本，确认安装成功 3.0.3

3.使用vue create demo 来创建项目

4.使用非默认的或者非默认来创建，报错

5. 无论我怎么升级了node、npm，重新安装了vue-cli也卸载了之前的2版本都失败了。。

错误如下：

Installing CLI plugins. This might take a while...

 ERROR  Error: Command failed: npm config get registry
internal/modules/cjs/loader.js:583
     throw err;              ^

Error: Cannot find module 'dezalgo'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581
:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/didi/node_modules/npm/lib/utils/correct-m
kdir.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10
)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

at makeError (/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:277:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
### What is expected?
能创建个项目

### What is actually happening?
不能创建，创建过程中报错

**Comment by xuehebinglan** [comment]
报错说 找不到dezalgo，我就在全局还有cli里面都去安装了dezalgo，还是不成功

**Comment by sodatea** [comment]
试试这个回复里说的方法：
https://github.com/vuejs/vue-cli/issues/889#issuecomment-397225829

**Comment by sodatea** [comment]
Closing due to inactivity for more than 1 week.
