### ISSUE TITLE
Unable to install vue-cli

### ISSUE THREAD

**Issue by ejlocop** [vuejs/vue-cli#2686]
### Version
3.0.4

### Node and OS info
Node v8.10.0 / npm v5.6.0 / Windows 10 x64

### Steps to reproduce
I just did,

```
npm install -g @vue/cli
```

### What is expected?
it should install the vue-cli

### What is actually happening?
Can't install vue-cli

```
npm ERR! code EINTEGRITY
npm ERR! sha512-NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E lHDAJzu7kLAkDeY08z2/A0hg== integrity checksum failed when using sha512: wanted sha512-NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E lHDAJzu7kLAkDeY08z2/A0hg== but got sha512-PdGaSveJTYagfLnzsPCoxqr0UxshVv577hWscOk vg6KTISBJeLdnsqQBSYM7FI9QY0vrtfyXfnoZiFzTiQGrw==. (45089 bytes)
npm WARN tar ENOENT: no such file or directory, open 'C:\Program Files\nodejs\node_modules\.staging\@vue\cli-ui-addon-webpack-2ca582ea\dist\img\webpack.b7bef091.svg'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\name\AppData\Roaming\npm-cache\_logs\2018-10-06T10_13_40_093Z-debug.log
```

---
Iv'e already tried
```
$npm cache clear --force 
$npm cache verify 
$npm install -g @vue/cli
```
but it still failed. any idea why? I'm thinking it's because of my npm. not sure.

My npm logs.
```
9137 silly pacote trying registry-url@https://registry.npmjs.org/registry-url/-/registry-url-3.1.0.tgz by hash: sha1-PU74cPc93h138M aOBQyRE4XSUI=
9138 silly pacote data for sha512-k55yxKHwaXnpYGsOzg4Vl8 tDrWylxDEpknGjhTiZB8dFRU5rTo9CAzeycivxV3s zlTKwrs6WxMxR95n26kwg== not present. Using manifest.
9139 silly pacote data for sha1-PU74cPc93h138M aOBQyRE4XSUI= not present. Using manifest.
9140 verbose unlock done using C:\Users\name\AppData\Roaming\npm-cache\_locks\staging-dfd8fbf9c1feea0f.lock for C:\Program Files\nodejs\node_modules\.staging
9141 verbose stack Error: sha512-NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E lHDAJzu7kLAkDeY08z2/A0hg== integrity checksum failed when using sha512: wanted sha512-NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E lHDAJzu7kLAkDeY08z2/A0hg== but got sha512-PdGaSveJTYagfLnzsPCoxqr0UxshVv577hWscOk vg6KTISBJeLdnsqQBSYM7FI9QY0vrtfyXfnoZiFzTiQGrw==. (45089 bytes)
9141 verbose stack     at Transform.on (C:\Users\name\AppData\Roaming\nvm\v8.10.0\node_modules\npm\node_modules\ssri\index.js:275:19)
9141 verbose stack     at emitNone (events.js:111:20)
9141 verbose stack     at Transform.emit (events.js:208:7)
9141 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
9141 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
9141 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
9142 verbose cwd D:\Projects\Taraveler
9143 verbose Windows_NT 10.0.14393
9144 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@vue/cli"
9145 verbose node v8.10.0
9146 verbose npm  v5.6.0
9147 error code EINTEGRITY
9148 error sha512-NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E lHDAJzu7kLAkDeY08z2/A0hg== integrity checksum failed when using sha512: wanted sha512-NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E lHDAJzu7kLAkDeY08z2/A0hg== but got sha512-PdGaSveJTYagfLnzsPCoxqr0UxshVv577hWscOk vg6KTISBJeLdnsqQBSYM7FI9QY0vrtfyXfnoZiFzTiQGrw==. (45089 bytes)
9149 verbose exit [ 1, true ]
```

**Comment by ejlocop** [comment]
got it working when I used the official version and not the node/npm installed by the nvm-windows.

**Comment by Kapeutini2018** [comment]
same issue, it works fine at home and I can get vue ui from npm but at work I'm becoming crazy, not able to install it ... And we have until this friday to decide which one: React, Angular, Vue, I like the simplicity and possibilities of Vue but I'm disappointed and lost with npm and would like to have vue ui and vue working in my sources.

**Comment by Kapeutini2018** [comment]
I used: npm config set stric-ssl false and I got Vue UI, nice tool

**Comment by ignatius22** [comment]
I'm having this same issue help anyone please

**Comment by evergreen2001** [comment]
any help guys , getting same error
