### ISSUE TITLE
VSCode profile for debugging Mocha tests

### ISSUE THREAD

**Issue by Stoom** [vuejs/vue-cli#2694]
### Version
3.0.1

### Reproduction link
[n/a](n/a)

### Node and OS info
Node 9.5.0 / yarn 1.3.2 / Windows 10

### Steps to reproduce
Use the following `launch.config` in vscode:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha All",
            "program": "${workspaceFolder}/node_modules/@vue/cli-service/bin/vue-cli-service.js",
            "args": [
                "test:unit",
                "-r ${workspaceFolder}\\tests\\setup.js"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        },
    ]
}
```

### What is expected?
All unit tests execute after `.vue` files are transpiled

### What is actually happening?
The following error is returned:
```shell
PS C:\Users\user\Projects\foobar> cd 'c:\Users\user\Projects\foobar'; & 'C:\Program Files\nodejs\node.exe' '--inspect-brk=18708' 'node_modules\@vue\cli-service\bin\vue-cli-service.js' 'test:unit' '-r C:\Users\user\Projects\foobar\tests\setup.js'

Debugger listening on ws://127.0.0.1:18708/9fd3beb8-b722-4d6e-ba63-83dff9a645b8
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
module.js:557
    throw err;
    ^

Error: Cannot find module ' C:\Users\user\Projects\foobar\tests\setup.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function._resolveFilename (C:\Users\user\Projects\foobar\node_modules\mocha-webpack\lib\util\registerRequireHook.js:44:34)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at C:\Users\user\Projects\foobar\node_modules\mocha-webpack\lib\cli\index.js:65:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\user\Projects\foobar\node_modules\mocha-webpack\lib\cli\index.js:64:17)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
 ERROR  mocha-webpack exited with code 1.
Waiting for the debugger to disconnect...
```

**Comment by LinusBorg** [comment]
Please provide a runnable reproduction.

The default setup doesn't come with a `setup.js` file and we are not gonna guess what you did wrong.

**Comment by LinusBorg** [comment]
Closing for inactivity.
