### ISSUE TITLE
The cli-plugin-eslint need upgrade babel-eslint to ^10 and eslint to ^5

### ISSUE THREAD

**Issue by luxueyan** [vuejs/vue-cli#2704]
### Version
3.0.5

### Node and OS info
node v8.10.0 / yarn 1.9.4 / macos 10.12.6

### Steps to reproduce
when using nullish-coalescing-operator in code, vue-cli-service lint throw error because of eslint
```javacript
this.empty2 ?? 'empty2'
```

### What is expected?
Expected eslint run ok

### What is actually happening?
Error: unreachable
    at CodePathState.popChoiceContext (/Users/luxueyan/bitmain/data-tag-frontend/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/code-path-analysis/code-path-state.js:444:23)
    at processCodePathToExit (/Users/luxueyan/bitmain/data-tag-frontend/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:434:19)

---
Upgrade eslint (babel-eslint) version is ok

**Comment by LinusBorg** [comment]
I'm not aware of this operator, can you link to some info? google didn't help.

**Comment by luxueyan** [comment]
https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator

**Comment by LinusBorg** [comment]
...and you have added that proposal to your babel config?

**Comment by luxueyan** [comment]
Yes! But it  throws error yet. When I update the eslint and babel-elint to latest in the cli-plugin-eslint package, it works!
