### ISSUE TITLE
Cannot change Nightwatch Selenium port

### ISSUE THREAD

**Issue by ijdickinson** [vuejs/vue-cli#2739]
### Version
3.0.5

### Reproduction link
[https://github.com/ijdickinson/nightwatch-issue](https://github.com/ijdickinson/nightwatch-issue)

### Node and OS info
node 8.12.0 / yarn 1.9.4 / Ubuntu 18.04

### Steps to reproduce
1. Run e2e tests normally:

    yarn test:e2e

2. Re-run the test with Selenium running on a different port:

    SELENIUM_PORT=4445 yarn test:e2e

### What is expected?
Both cases should run a single e2e test normally

### What is actually happening?
When I use the documented option in the Nightwatch config to run Selenium on a different port, the test seems to try to connect to Selenium running on the default port:

    DONE  Compiled successfully in 1314ms                                                                                                                         11:59:17
      App running at:
      - Local:   http://localhost:8080/ 
      - Network: http://192.168.1.120:8080/

      App is served in production mode.
      Note this is for preview or E2E testing only.

    Starting selenium server... started - PID:  23757

    [Test] Test Suite
    =====================

    Running:  default e2e tests

    Error retrieving a new session from the selenium server

    Connection refused! Is selenium server started?
    { Error: connect ECONNREFUSED 127.0.0.1:4444
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
      errno: 'ECONNREFUSED',
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 4444 }

     ERROR  Error: Command failed: /home/ian/workspace/sanoma/nightwatch-issue/node_modules/nightwatch/bin/nightwatch --config /home/ian/workspace/sanoma/nightwatch-issue/node_modules/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js --env chrome
    Error: Command failed: /home/ian/workspace/sanoma/nightwatch-issue/node_modules/nightwatch/bin/nightwatch --config /home/ian/workspace/sanoma/nightwatch-issue/node_modules/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js --env chrome
        at makeError (/home/ian/workspace/sanoma/nightwatch-issue/node_modules/execa/index.js:172:9)
        at Promise.all.then.arr (/home/ian/workspace/sanoma/nightwatch-issue/node_modules/execa/index.js:277:16)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

---
This was an ask from my ops team to be able to run multiple instances of the e2e tests in parallel sometimes. Running two sets of e2e tests at once means that the Selenium servers clash on port 4444, so I wanted to run one or more test instances on different Selenium ports.

I'm not sure whether this is a Nighwatch issue, or a Vue CLI issue. However, since Nightwatch documents the `selenium.port` config option, I assume it's likely that it works in vanilla Nightwatch. So my guess - and I admit that it is just a guess - is that the Vue wrapper is somehow pinning the Selenium port.

**Comment by ijdickinson** [comment]
Looks like I missed the matching `selenium_port` setting in my Nightwatch config. So the solution was:

    const selenium_port = process.env.SELENIUM_PORT || 4444

    module.exports = {
      'test_settings': {
        'default': {
          selenium_port
        }
      },
      'selenium': {
        'port': selenium_port
      }
    }
