### ISSUE TITLE
Unable to use Import statement when running e2e tests with nightwatch

### ISSUE THREAD

**Issue by liron-navon** [vuejs/vue-cli#2771]
### Version
3.0.5

### Reproduction link
[https://github.com/liron-navon/vue-nightwatch-bug-example](https://github.com/liron-navon/vue-nightwatch-bug-example)

### Node and OS info
macos el capitan, node 10.11.0, npm 6.4.1

### Steps to reproduce
1. start a new cli project.
2. add a file to the tests directory (config.js) and export something.
3. add an import statement in any file in tests/e2e directory

### What is expected?
The import should work as usual

### What is actually happening?
The terminal throws an error "unexpected import"

---
import config from '../../config';
       ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by LinusBorg** [comment]
Nightwatch test files are run in node, not in a browser, and not though Babel. 

And node doesn't support es6 modules.
