### ISSUE TITLE
npm run build is broken with "Cannot read property 'stat' of undefined"

### ISSUE THREAD

**Issue by amir20** [vuejs/vue-cli#2847]
### Version
3.0.5

### Reproduction link
[https://gist.github.com/amir20/741117cd85858949c866e01dcf578a7f](https://gist.github.com/amir20/741117cd85858949c866e01dcf578a7f)

### Node and OS info
node v10.7.0, npm 6.1.0

### Steps to reproduce
npm install -g @vue/cli
vue create -d hello-world
cd hello-world
npm run build

### What is expected?
Successfully be able to build for production 

### What is actually happening?
⠙  Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                                                             3:47:08 PM

 error  in ./src/App.vue?vue&type=script&lang=js&

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 1)
Cannot read property 'stat' of undefined

    at toDepDetails (/hello-world/node_modules/cache-loader/dist/index.js:65:14)
    at arrayIterator (/hello-world/node_modules/neo-async/async.js:3780:9)
    at timesSync (/hello-world/node_modules/neo-async/async.js:2292:7)
    at Object.mapLimit (/hello-world/node_modules/neo-async/async.js:3775:5)
    at Array.<anonymous> (/hello-world/node_modules/cache-loader/dist/index.js:88:18)
    at arrayEachFunc (/hello-world/node_modules/neo-async/async.js:2512:19)
    at Object.parallel (/hello-world/node_modules/neo-async/async.js:6867:9)
    at Object.loader (/hello-world/node_modules/cache-loader/dist/index.js:87:9)

 @ ./src/App.vue?vue&type=script&lang=js& 1:0-302 1:318-321 1:323-622 1:323-622
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

**Comment by pixelizedPeanut** [comment]
same here

**Comment by dezechristophe** [comment]
same with npm@6.4.1 node v11.0.0

**Comment by pixelizedPeanut** [comment]
I added a postinstall script for now in my package.json:
```
"scripts": {
    "postinstall": "npm i cache-loader@1.2.2",
```
it's horribly ugly but it sticked :D

**Comment by pixelizedPeanut** [comment]
https://github.com/webpack-contrib/cache-loader/commit/d8c630b6b9437d2e37ee461ebd95afb7ee675e3f also this might help for tracking

**Comment by itmayziii** [comment]
same problem

**Comment by itmayziii** [comment]
For now instead of doing a post install I would just say update your dev dependencies to use the last working version of the cache-loader which was 1.2.2

```
"devDependencies": {
  "cache-loader": "1.2.2"
}
```

**Comment by harishdurga** [comment]
> 
> 
> I added a postinstall script for now in my package.json:
> 
> ```
> "scripts": {
>     "postinstall": "npm i cache-loader@1.2.2",
> ```
> 
> it's horribly ugly but it sticked :D

I don't know what's this for, but it really solved the build error. big thanks.

**Comment by limistah** [comment]
> > I added a postinstall script for now in my package.json:
> > ```
> > "scripts": {
> >     "postinstall": "npm i cache-loader@1.2.2",
> > ```
> > it's horribly ugly but it sticked :D
> 
> I don't know what's this for, but it really solved the build error. big thanks.

Read https://docs.npmjs.com/misc/scripts
