### ISSUE TITLE
vue-cli-service now throws npm uninstall during "serve" command from vue ui 

### ISSUE THREAD

**Issue by CraigHead** [vuejs/vue-cli#2848]
### Version
@vue/cli 3.0.5

### Node and OS info
Node: v10.13.0 / NPM 6.4.1 / Windows 10 v1803

### Steps to reproduce
Install the latest @vue/cli. Create an application using vue create or the UI. Update the Project Plugins to use @vue/cli-service 3.10. Attempt to "serve" the application. 

### What is expected?
The application starts as normal. 

### What is actually happening?
$ vue-cli-service serve --open --mode development --dashboard
 INFO  Starting development server...

 ERROR  Error: Cannot find module 'acorn/dist/walk'

Error: Cannot find module 'acorn/dist/walk'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\code\Sandbox\todo-vue\node_modules\@vue\cli-service\lib\webpack\analyzeBundle.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\code\Sandbox\todo-vue\node_modules\@vue\cli-service\lib\webpack\DashboardPlugin.js:11:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)

Total task duration: 3.03s

**Comment by CraigHead** [comment]
Thank you for the quick fix!
