### ISSUE TITLE
No files matching 'tests' were found.

### ISSUE THREAD

**Issue by donbot-inc** [vuejs/vue-cli#2854]
### Version
3.0.5

### Reproduction link
[https://github.com/vuejs/vue-cli/issues](https://github.com/vuejs/vue-cli/issues)

### Node and OS info
Node: v10.11.0 (MacOS, NVM)

### Steps to reproduce
Init project with vue-cli 3.0.5 version and node 10.11.0 version with this configuration:

Vue CLI v3.0.5
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, Vuex, CSS Pre-processors, Linter
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Stylus
? Pick a linter / formatter config: Prettier
? Pick additional lint features: Lint on save
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No

### What is expected?
Initialization of the project 

### What is actually happening?
Initialization of the project is interrupted with an error

---
Vue CLI v3.0.5
✨  Creating project in /Users/User/Projects/Project.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

> fsevents@1.2.4 install /Users/User/Projects/Project/node_modules/fsevents
> node install

[fsevents] Success: "/Users/User/Projects/Project/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> yorkie@2.0.0 install /Users/User/Projects/Project/node_modules/yorkie
> node bin/install.js

setting up Git hooks
done

added 1186 packages from 754 contributors and audited 13857 packages in 51.946s
found 0 vulnerabilities

🚀  Invoking generators...
📦  Installing additional dependencies...

added 43 packages from 78 contributors, updated 2 packages, moved 1 package and audited 14213 packages in 24.772s
found 0 vulnerabilities

 ERROR  Error: No files matching 'tests' were found.
Error: No files matching 'tests' were found.
    at resolvedPathsByGlobPattern.reduce (/Users/User/Projects/Project/node_modules/eslint/lib/util/glob-utils.js:244:19)
    at Array.reduce (<anonymous>)
    at Object.listFilesToProcess (/Users/User/Projects/Project/node_modules/eslint/lib/util/glob-utils.js:242:59)
    at CLIEngine.executeOnFiles (/Users/User/Projects/Project/node_modules/eslint/lib/cli-engine.js:513:36)
    at lint (/Users/User/Projects/Project/node_modules/@vue/cli-plugin-eslint/lint.js:47:25)
    at api.onCreateComplete (/Users/User/Projects/Project/node_modules/@vue/cli-plugin-eslint/generator/index.js:106:25)
    at Creator.create (/Users/User/.nvm/versions/node/v10.11.0/lib/node_modules/@vue/cli/lib/Creator.js:176:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by zilan830** [comment]
我也遇到这个问题了。但是我在卸载@vue/cli之后重新下载再创建项目后，还是报了同样的错误。
translate：I met the same error. It also happened after I uninstalled @vue/cli then installed again.

**Comment by Mada75** [comment]
Same error as the original post here

**Comment by LeeStaySmall** [comment]
![image](https://user-images.githubusercontent.com/19145355/47781344-71aefa80-dd38-11e8-8a0e-145c17d8af42.png)
![image](https://user-images.githubusercontent.com/19145355/47781385-868b8e00-dd38-11e8-9c6b-3161a2dc3c40.png)

**Comment by LeeStaySmall** [comment]
Can successfully create a project, but can't run "npm run link", maybe related to the new version, there is a problem with the eslint referenced in the version.

**Comment by sodatea** [comment]
FYI: It's caused by this issue in ESLint v5: https://github.com/eslint/eslint/issues/10587

**Comment by ideacco** [comment]
I also have the same problem：
 vue-cli-service lint
 ERROR  Error: No files matching 'tests' were found.

**Comment by dasDaniel** [comment]
had the same issue. Confirming that removing `"eslint": "^5.8.0",` fixed it

**Comment by zetaraku** [comment]
This problem still exists when `vue-cli-service lint` is executed without having files in any default lint path.
Manually specifying the lint path should solve this problem: `vue-cli-service lint ./src/`

**Comment by cmauf** [comment]
Thanks so much @zetaraku, this issue boggled me so much in a LTS project and now I fixed it!
