### ISSUE TITLE
Error on compiling after including a .vue File

### ISSUE THREAD

**Issue by kayyyy** [vuejs/vue-cli#288]
After including my `Articles.vue` i am getting an error on Compiling the Files. In the Shell it`s only waiting and waiting `WAIT  Compiling...`. After cancel it and run `npm run dev` again i am getting an Error and i have to restart the whole Macbook.
#### Articles.vue
```
<template>
<v-card class="green">
    <v-card-text>
        <p>bla</p>
    </v-card-text>
</v-card> 
</template>
<script>
export default {
    name: 'Articles'
}
</script
```

If i want to run `npm run dev` again i am getting the following Error

```
npm run dev

> sell@1.0.0 dev /Users/chris/Desktop/code/sell
> node build/dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventEmitter.listen (/Users/chris/Desktop/code/sell/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/chris/Desktop/code/sell/build/dev-server.js:67:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sell@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sell@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sell
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sell
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chris/Desktop/code/sell/npm-debug.log
```

**Comment by kayyyy** [comment]
Orgh .. After rebooting 10 Times and reinstalling Node and NPM i saw now that i forgot to close the `<script>` Tag .. Gosh ..
