### ISSUE TITLE
Vue create fails: Cannot find module './clone.js'

### ISSUE THREAD

**Issue by Trymunx** [vuejs/vue-cli#2880]
### Version
3.1.1

### Node and OS info
Node 10.1.0 / npm 6.4.0 / GalliumOS 2.1 (Ubuntu 16.04)

### Steps to reproduce
Install latest vue-cli version using npm i -g @vue/cli
Run `vue create project`

### What is expected?
An interactive prompt opens for creating a new project

### What is actually happening?
An error occurs saying the following:
```
[21:35] >> vue create 02-time
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v10.1.0/lib/node_modules/@vue/cli/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

**Comment by Trymunx** [comment]
I didn't realise I had a previous version of vue-cli installed on this computer. After double checking this, I just uninstalled (`npm uninstall -g vue-cli`) as stated in the docs, and then reinstalled @vue/cli, fixing the issue.
