### ISSUE TITLE
I'm having a problem trying to install the Vue Cli : permission denied node-sass

### ISSUE THREAD

**Issue by moisesads** [vuejs/vue-cli#2929]
I'm having a problem trying to install the Vue Cli :

```setting up Git hooks
can't find .git directory, skipping Git hooks installation
added 1058 packages from 712 contributors and audited 13336 packages in 97.698s
found 0 vulnerabilities

🚀  Invoking generators...
📦  Installing additional dependencies...


> node-sass@4.10.0 install /opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass
> node scripts/install.js

Unable to save binary /opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass/vendor/linux-x64-67 : { Error: EACCES: permission denied, mkdir '/opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:768:3)
    at sync (/opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass/vendor' }

> node-sass@4.10.0 postinstall /opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@11.0.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 11.0.0
gyp verb command install [ '11.0.0' ]
gyp verb install input version string "11.0.0"
gyp verb install installing version: 11.0.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/11.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '11.0.0' ]
gyp verb install input version string "11.0.0"
gyp verb install installing version: 11.0.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 11.0.0
gyp verb ensuring nodedir is created /opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass/.node-gyp/11.0.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '11.0.0' ]
gyp verb remove using node-gyp dir: /opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 11.0.0
gyp verb remove removing development files for version: 11.0.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '11.0.0' ]
gyp verb remove using node-gyp dir: /opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 11.0.0
gyp verb remove removing development files for version: 11.0.0
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.15.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /opt/lampp/htdocs/crud-ajax-simples-b3/exemplo/node_modules/node-sass
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-09T20_04_25_702Z-debug.log
 ERROR  command failed: npm install --loglevel error
```
permission denied???

I Tried:
chmod -R 777 ...

**Comment by moisesads** [comment]
> Hello, your issue has been closed because it does not conform to our issue requirements. In order to ensure every issue provides the necessary information for us to investigate, we require the use of the [Issue Helper](https://new-issue.vuejs.org/?repo=vuejs/vue-cli) when creating new issues. Thank you!
https://new-issue.vuejs.org/?repo=vuejs/vue-cli

after filling out: 
414 Request-URI Too Large
nginx
