### ISSUE TITLE
events.js throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by workwsl** [vuejs/vue-cli#297]
查看了[#22](https://github.com/vuejs/vue-cli/issues/22)和[#64](https://github.com/vuejs/vue-cli/issues/64),并没得到解决。

```
OS: win10
node: v7.3.0
npm: v3.10.9
```

指定dev prot 为：9090，npm run dev 仍然会提示8080被占用。
利用 ```netstat -ano``` 查看了下端口占用情况，8080 并没有被占用。
虽然提示8080被占用，但是不影响项目的启动，http://localhost:9090  可以正常访问。

```
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       892
  TCP    0.0.0.0:443            0.0.0.0:0              LISTENING       3708
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:902            0.0.0.0:0              LISTENING       2836
  TCP    0.0.0.0:912            0.0.0.0:0              LISTENING       2836
  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING       1212
  TCP    0.0.0.0:9090           0.0.0.0:0              LISTENING       14228
  TCP    0.0.0.0:9930           0.0.0.0:0              LISTENING       2632
```
```
 node build/dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Function.listen (E:\flowspace\vue-todolist\node_modules\express\lib\application.js:617:24)
    at Object.<anonymous> (E:\flowspace\vue-todolist\build\dev-server.js:67:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\WSL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v7.3.0
 DONE  Compiled successfully in 3780ms

 Listening at http://localhost:9090
```

**Comment by egoist** [comment]
Please report this in relevant template repo.
