### ISSUE TITLE
Error: EACCES: permission denied, open '/var/www/domain.com/.git/hooks/applypatch-msg'

### ISSUE THREAD

**Issue by jiapei100** [vuejs/vue-cli#2972]
```
Vue CLI v3.1.3
✨  Creating project in /var/www/domain.com.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...


> yorkie@2.0.0 install /var/www/domain.com/node_modules/yorkie
> node bin/install.js

setting up Git hooks
{ Error: EACCES: permission denied, open '/var/www/domain.com/.git/hooks/applypatch-msg'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1187:35)
    at write (/var/www/domain.com/node_modules/yorkie/src/install.js:18:6)
    at createHook (/var/www/domain.com/node_modules/yorkie/src/install.js:45:5)
    at /var/www/domain.com/node_modules/yorkie/src/install.js:86:21
    at Array.map (<anonymous>)
    at installFrom (/var/www/domain.com/node_modules/yorkie/src/install.js:83:10)
    at Object.<anonymous> (/var/www/domain.com/node_modules/yorkie/bin/install.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/var/www/domain.com/.git/hooks/applypatch-msg' }
added 1113 packages from 737 contributors and audited 14787 packages in 21.735s
found 0 vulnerabilities
```

**Comment by LeszekSz** [comment]
I have the same issue when creating a new Vuejs project on my local machine:

~/projects/vue$ sudo vue create project1
...
> yorkie@2.0.0 install /home/kevin/projects/vue/project1/node_modules/yorkie
> node bin/install.js
setting up Git hooks
{ Error: EACCES: permission denied, open '/home/kevin/projects/vue/project1/.git/hooks/applypatch-msg'
...


my environment:
linux Ubuntu 16.04
npm --version 
6.5.0
node --version
v11.7.0
vue --version
3.3.0

any help greatly appreciated

**Comment by Liumkattan** [comment]
Check out Issue #1809
