### ISSUE TITLE
多页面保存热更新时 大概率出现 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by GodStream** [vuejs/vue-cli#2991]
### Version
3.1.1

### Reproduction link
[https://github.com/GodStream/multi-vue-cli3.0-bug](https://github.com/GodStream/multi-vue-cli3.0-bug)

### Node and OS info
Node 10.13.0 / npm 6.4.1 / yarn  1.9.2 / Mac 10.14.1

### Steps to reproduce
1、动态获取目录结构，生成多页面pages，historyApiFallback rewrites 配置
2、热更新时会堆栈溢出，利用 fix-memory-limit 增加了node 内存配置
3、实际上还是会出现问题
```
68% building 1/1 modules 0 active/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/tapable/lib/HookCodeFactory.js:32
                                fn = new Function(
                                     ^

RangeError: Maximum call stack size exceeded
    at new Function (<anonymous>)
    at AsyncSeriesHookCodeFactory.create (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/tapable/lib/HookCodeFactory.js:32:10)
    at AsyncSeriesHook.compile (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/tapable/lib/AsyncSeriesHook.js:24:18)
    at AsyncSeriesHook._createCall (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/tapable/lib/Hook.js:24:15)
    at AsyncSeriesHook.lazyCompileHook [as callAsync] (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/tapable/lib/Hook.js:153:21)
    at source.tapAsync (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/enhanced-resolve/lib/ResultPlugin.js:16:26)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at resolver.getHook.tapAsync (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/enhanced-resolve/lib/NextPlugin.js:16:13)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at Array.fs.stat (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/enhanced-resolve/lib/FileExistsPlugin.js:29:14)
    at Storage.finished (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/zpq/SJ-Project/zhuhong/yp-webapp-next/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
error Command failed with exit code 1.
```

### What is expected?
热更新正常

### What is actually happening?
出现了 Maximum call stack size exceeded

**Comment by sodatea** [comment]
麻烦提供可以复现的代码仓库

**Comment by GodStream** [comment]
@sodatea  https://github.com/GodStream/multi-vue-cli3.0-bug 当页面较多时，多次保存后就出现堆栈溢出的情况。暂时未复现出
```
68% building 1/1 modules 0 active /node_modules/tapable/lib/HookCodeFactory.js:32
                                fn = new Function(
                                     ^

RangeError: Maximum call stack size exceeded
```
可能是目前的项目仅仅为了复现，结构比真实项目要简单

**Comment by julytian** [comment]
@GodStream ,试下这样 
```js
"startdev": "cross-env SERVER_TYPE=develop node --max_old_space_size=4096 node_modules/@vue/cli-service/bin/vue-cli-service.js serve",
```

**Comment by GodStream** [comment]
max_old_space_size试过的，但感觉治标不治本，最终还是会溢出的，总不能无限往上加

**Comment by hezhongfeng** [comment]
我这是`build`的时候会有出现这个，然后一通检查，后来发现只要砍掉一些路由就可以~坑死我了

**Comment by DarkoPeng** [comment]
我在多页面热更新的时候也碰到这个问题，必现！不过我是 JavaScript heap out of memory，现在的页面数量是在 50 个左右。
```
 WAIT  Compiling...                                                                                                                                                            11:27:02 AM

 95% emitting CopyPlugin
<--- Last few GCs --->

[14248:0x104002400]    92477 ms: Mark-sweep 1369.8 (1412.6) -> 1369.8 (1412.6) MB, 176.5 / 0.0 ms  allocation failure GC in old space requested
[14248:0x104002400]    92655 ms: Mark-sweep 1369.8 (1412.6) -> 1369.8 (1411.6) MB, 177.9 / 0.0 ms  last resort GC in old space requested
[14248:0x104002400]    92831 ms: Mark-sweep 1369.8 (1411.6) -> 1369.8 (1411.6) MB, 176.1 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3cca75fa55e9 <JSObject>
    1: fromString(aka fromString) [buffer.js:336] [bytecode=0x3cca592b4259 offset=161](this=0x3cca5da822d1 <undefined>,string=0x3cca1f8cd8a1 <Very long string[3983957]>,encoding=0x3cca75fb6aa1 <String[4]: utf8>)
    2: from [buffer.js:189] [bytecode=0x3cca592b3d39 offset=14](this=0x3cca2f1c5d69 <JSFunction Buffer (sfi = 0x3cca6cc9cd59)>,value=0x3cca1f8cd8a1 <Very long string[3983957]>,encodingOr...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
10: node::Buffer::(anonymous namespace)::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
12: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
13: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x23337ef842fd
15: 0x23337f03d196
[1]    14247 abort      npm run serve
```

**Comment by frxing** [comment]
v-cli 2.x

`
"local": "SELF_ENV=local node --max-old-space-size=4096 ./node_modules/.bin/webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
"start": "npm run local",
`

**Comment by shaonialife** [comment]
目前我通过配置白名单对pages进行过滤, 打生产包时不进行过滤, 可以大大减少在dev时的页面数量, 白名单不会被提交到git, 优点是每个开发人员可以根据自己的情况配置不同的白名单, 缺点是在新增开发页面的时候需要重新run一下(这个缺点可以忽略掉)

**Comment by Anniezandr** [comment]
> max_old_space_size试过的，但感觉治标不治本，最终还是会溢出的，总不能无限往上加

这个内存溢出的问题解决了吗
