### ISSUE TITLE
the boilerplate fails 

### ISSUE THREAD

**Issue by z** [vuejs/vue-cli#31]
This is my first time installing vue-cli, I received the following error when I ran `npm run dev`:

```
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./src/App.vue
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/mint/dev/node/my-project/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/mint/dev/node/my-project/node_modules/vue-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (/home/mint/dev/node/my-project/node_modules/vue-loader/lib/style-rewriter.js:88:6)
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./src/App.vue 4:14-199 13:2-17:4 14:20-205
```

This caused the demo application to fail.

**Workaround**
downground css-loader in package.json

```
"css-loader": "^0.18.0",
```

**Comment by yyx990803** [comment]
Upgrade your Node version. Your Node is too old and has no native Promise support. Use at least 4.0+, preferrably 5.x.
