### ISSUE TITLE
vue ui - TypeError: Expected `cwd` to be of type `string` but received type `undefined`

### ISSUE THREAD

**Issue by cindoum** [vuejs/vue-cli#3303]
### Version
3.3.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 10.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.3.0
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.3.0
    @vue/cli-plugin-babel: ^3.3.0 => 3.3.0
    @vue/cli-plugin-pwa: ^3.3.0 => 3.3.0
    @vue/cli-plugin-typescript: ^3.3.0 => 3.3.0
    @vue/cli-service: ^3.3.0 => 3.3.0
    @vue/cli-shared-utils:  3.3.0
    @vue/component-compiler-utils:  2.5.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    vue: ^2.5.21 => 2.5.22
    vue-class-component: ^6.0.0 => 6.3.2
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.5.1
    vue-property-decorator: ^7.0.0 => 7.3.0
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.5.22
    vue-template-es2015-compiler:  1.8.1
    vuex: ^3.0.1 => 3.0.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue create my-app
vue ui

### What is expected?
Vue ui to show without error

### What is actually happening?
TypeError: Expected `cwd` to be of type `string` but received type `undefined`

**Comment by cindoum** [comment]
forgot the stack trace:
```
TypeError: Expected `cwd` to be of type `string` but received type `undefined`
...\AppData\Local\Yarn\Data\global\node_modules\dir-glob\index.js:1
TypeError: Expected `cwd` to be of type `string` but received type `undefined`
    at module.exports.sync (...\AppData\Local\Yarn\Data\global\node_modules\dir-glob\index.js:56:9)
    at globDirs (...\AppData\Local\Yarn\Data\global\node_modules\globby\index.js:58:9)
    at getPattern (...\AppData\Local\Yarn\Data\global\node_modules\globby\index.js:61:64)
    at globTasks.reduce (...\AppData\Local\Yarn\Data\global\node_modules\globby\index.js:107:19)
    at Array.reduce (<anonymous>)
    at Function.module.exports.sync (...\AppData\Local\Yarn\Data\global\node_modules\globby\index.js:106:26)
    at Object.<anonymous> (...\AppData\Local\Yarn\Data\global\node_modules\@vue\cli-ui\apollo-server\type-defs.js:88:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
