### ISSUE TITLE
Failed generator invoking

### ISSUE THREAD

**Issue by kazupon** [vuejs/vue-cli#3309]
### Version
3.3.0

### Reproduction link
[https://no.link](https://no.link)

### Environment info
```

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7Y54 CPU @ 1.20GHz
  Binaries:
    Node: 11.6.0 - ~/bin/.nvm/versions/node/v11.6.0/bin/node
    Yarn: 1.13.0 - ~/bin/.nvm/versions/node/v11.6.0/bin/yarn
    npm: 6.5.0-next.0 - ~/bin/.nvm/versions/node/v11.6.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 61.0.2
    Safari: 12.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2 
    @vue/babel-preset-app:  3.3.0 
    @vue/babel-preset-jsx:  1.0.0-beta.2 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2 
    @vue/babel-sugar-inject-h:  1.0.0-beta.2 
    @vue/babel-sugar-v-model:  1.0.0-beta.2 
    @vue/babel-sugar-v-on:  1.0.0-beta.2 
    @vue/cli-overlay:  3.3.0 
    @vue/cli-plugin-babel: ^3.3.0 => 3.3.0 
    @vue/cli-plugin-eslint: ^3.3.0 => 3.3.0 
    @vue/cli-service: ^3.3.0 => 3.3.0 
    @vue/cli-shared-utils:  3.3.0 
    @vue/component-compiler-utils:  2.5.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    babel-plugin-transform-vue-jsx:  4.0.1 
    eslint-plugin-vue: ^5.0.0 => 5.1.0 
    vue: ^2.5.21 => 2.5.22 
    vue-eslint-parser:  4.0.3 
    vue-hot-reload-api:  2.3.1 
    vue-loader:  15.5.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.5.22 
    vue-template-es2015-compiler:  1.8.1 
  npmGlobalPackages:
    @vue/cli: 3.3.0
```

### Steps to reproduce
1. `vue create repro1` with `default (babel, eslint)`
2. `cd repro1`
3. edit `src/main.js`
```diff
  import Vue from 'vue'
  import App from './App.vue'

  Vue.config.productionTip = false

+ function loader (path) {
+   return () => import(path)
+ }

  new Vue({
    render: h => h(App),
  }).$mount('#app')
```
4. `vue add vuex`

### What is expected?
vuex should be possible install.

### What is actually happening?
esprima error occurred as following.

```
🚀  Invoking generator for core:vuex...
(node:31993) UnhandledPromiseRejectionWarning: Error: Line 7: Unexpected reserved word
    at ErrorHandler.constructError (/Users/kazupon/.enviroments/bin/.nvm/versions/node/v11.6.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/Users/kazupon/.enviroments/bin/.nvm/versions/node/v11.6.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/Users/kazupon/.enviroments/bin/.nvm/versions/node/v11.6.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/Users/kazupon/.enviroments/bin/.nvm/versions/node/v11.6.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parsePrimaryExpression (/Users/kazupon/.enviroments/bin/.nvm/versions/node/v11.6.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2390:38)
    at Parser.inheritCoverGrammar (/Users/kazupon/.enviroments/bin/.nvm/versions/node/v11.6.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseLeftHandSideExpressionAllowCall (/Users/kazupon/.enviroments/bin/.nvm/versions/node/v11.6.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2899:26)
    at Parser.inheritCoverGrammar (/Users/kazupon/.enviroments/bin/.nvm/versions/node/v11.6.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseUpdateExpression (/Users/kazupon/.enviroments/bin/.nvm/versions/node/v11.6.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:3004:26)
    at Parser.parseUnaryExpression (/Users/kazupon/.enviroments/bin/.nvm/versions/node/v11.6.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:3048:26)
(node:31993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31993) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

---
The same issue occurs with `vue add router` as well.

Related issues
https://github.com/kazupon/vue-cli-plugin-i18n/issues/32

We should be added notice to  documentation, due to I think `main.(js|ts)` should not be edited by user.

**Comment by LinusBorg** [comment]
That's probably because Esprima only supports ES6, and dynamic imports are still a stage 3 proposal.

**Comment by lbogdan** [comment]
(Maybe) related: #3335 .

**Comment by gwvt** [comment]
I encountered this error adding the vue-i18n plugin to an existing project in which `src/main.js` had been edited. I reverted the file to the vue-cli boilerplate, but the error persisted. Creating a new, clean project and adding the plugin worked correctly.
