### ISSUE TITLE
update vue-cli lastest version, when i run vue inpsect --mode production > output.js, there is an error

### ISSUE THREAD

**Issue by proshuai** [vuejs/vue-cli#3318]
in the file of output.js
================== Error ==================
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.get (/Users/work/aa/build/server.js:30:19)
    at Object.getServer (/Users/work/aa/build/server.js:57:30)
    at configureWebpack (/Users/work/aa/vue.config.js:32:31)
    at webpackRawConfigFns.forEach.fn (/Users/work/aa/node_modules/@vue/cli-service/lib/Service.js:240:21)
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (/Users/work/aa/node_modules/@vue/cli-service/lib/Service.js:237:30)
    at PluginAPI.resolveWebpackConfig (/Users/work/aa/node_modules/@vue/cli-service/lib/PluginAPI.js:115:25)
    at api.registerCommand.args (/Users/work/aa/node_modules/@vue/cli-service/lib/commands/inspect.js:16:24)
    at Service.run (/Users/work/aa/node_modules/@vue/cli-service/lib/Service.js:219:12)
    at Object.<anonymous> (/Users/work/aa/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
===========================================

**Comment by sodatea** [comment]
According to the first few lines in the output, it is very likely that there's a bug in your `configureWebpack` function.

> ```
> SyntaxError: Unexpected token u in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at Object.get (/Users/work/aa/build/server.js:30:19)
>     at Object.getServer (/Users/work/aa/build/server.js:57:30)
>     at configureWebpack (/Users/work/aa/vue.config.js:32:31)
> ```

**Comment by proshuai** [comment]
@sodatea config:
![image](https://user-images.githubusercontent.com/13295895/51307427-a0f12000-1a7a-11e9-85aa-2f852a49c9a8.png)
