### ISSUE TITLE
cypress tests cannot be exeuted in cypress/base:10 docker image

### ISSUE THREAD

**Issue by thilko** [vuejs/vue-cli#3322]
### Version
3.3.0

### Reproduction link
[https://gitlab.com/thilko.richter/cypress_test/tree/master](https://gitlab.com/thilko.richter/cypress_test/tree/master)

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.9 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: (2) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.3.0
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.3.0
    @vue/cli-plugin-babel: ^3.3.0 => 3.3.0
    @vue/cli-plugin-e2e-cypress: ^3.3.0 => 3.3.0
    @vue/cli-plugin-eslint: ^3.3.0 => 3.3.0
    @vue/cli-service: ^3.3.0 => 3.3.0
    @vue/cli-shared-utils:  3.3.0
    @vue/component-compiler-utils:  2.5.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: ^5.0.0 => 5.1.0
    vue: ^2.5.21 => 2.5.22
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.5.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.5.22
    vue-template-es2015-compiler:  1.8.1
  npmGlobalPackages:
    @vue/cli: 3.3.0

```

### Steps to reproduce
docker build .

### What is expected?
Cypress tests are executed

### What is actually happening?
```
> cypress_test@0.1.0 test:e2e /
> vue-cli-service test:e2e --headless

 INFO  Starting e2e tests...
 INFO  Starting development server...
 DONE  Compiled successfully in 5228ms8:08:03 PM

  App running at:
  - Local:   http://localhost:8080/

  It seems you are running Vue CLI inside a container.
  Access the dev server via http://localhost:<your container's external mapped port>/

  App is served in production mode.
  Note this is for preview or E2E testing only.

No version of Cypress is installed in: /root/.cache/Cypress/3.1.4/Cypress

Please reinstall Cypress by running: cypress install

Cypress executable not found at: /root/.cache/Cypress/3.1.4/Cypress/Cypress

Platform: linux (Debian - 8.11)
Cypress Version: 3.1.4
 ERROR  Error: Command failed: /node_modules/cypress/bin/cypress run --config baseUrl=http://localhost:8080/
Error: Command failed: /node_modules/cypress/bin/cypress run --config baseUrl=http://localhost:8080/
    at makeError (/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress_test@0.1.0 test:e2e: `vue-cli-service test:e2e --headless`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress_test@0.1.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

---
I was wondering if vue-cli-service looks for a different path? I can execute the tests locally but not in the docker image.

Originally I was trying to execute the tests with gitlab where this error occurs. The error message there is slightly different:

```
The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /builds/cypress-io/cypress-example-docker-gitlab/cache/Cypress/3.1.4/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /root/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /root/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error
----------

Platform: linux (Debian - 8.11)
Cypress Version: 3.1.4
 ERROR  Error: Command failed: /builds/thekla-tech/heating-grid-ui/node_modules/cypress/bin/cypress run --config baseUrl=http://localhost:8080/
Error: Command failed: /builds/thekla-tech/heating-grid-ui/node_modules/cypress/bin/cypress run --config baseUrl=http://localhost:8080/
    at makeError (/builds/thekla-tech/heating-grid-ui/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/builds/thekla-tech/heating-grid-ui/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fernwarme-mobile-vue@0.1.0 test:e2e: `vue-cli-service test:e2e --headless`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fernwarme-mobile-vue@0.1.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /builds/cypress-io/cypress-example-docker-gitlab/.npm/_logs/2019-01-17T05_39_06_560Z-debug.log
```

**Comment by thilko** [comment]
Found the issue, I missed `npm ci` task

**Comment by CrashyBang** [comment]
Hey @thilko could you please elaborate on what you mean by `npm ci` task?

**Comment by seyfer** [comment]
@chopfitzroy `npm ci` does the same as `npm install` but with a frozen package.lock (no changes). 
OP forgot to install dependencies.
