### ISSUE TITLE
config.plugins.delete is not a function

### ISSUE THREAD

**Issue by weituotian** [vuejs/vue-cli#3339]
### Version
3.3.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Binaries:
    Node: 10.13.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.3.0
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.3.0
    @vue/cli-plugin-babel: ^3.0.1 => 3.3.0
    @vue/cli-plugin-eslint: ^3.0.1 => 3.3.0
    @vue/cli-service: ^3.0.1 => 3.3.0
    @vue/cli-shared-utils:  3.3.0
    @vue/component-compiler-utils:  2.5.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue:  4.7.1
    sweet-modal-vue: ^2.0.0 => 2.0.0
    vue: ^2.5.17 => 2.5.17
    vue-cropper: ^0.4.0 => 0.4.0
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.1
    vue-lazyload: ^1.2.6 => 1.2.6
    vue-loader:  15.5.1
    vue-loaders: ^2.0.0 => 2.0.0
    vue-quill-editor: ^3.0.6 => 3.0.6
    vue-router: ^3.0.1 => 3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.17 => 2.5.17
    vue-template-es2015-compiler:  1.8.1
    vue-tippy: ^2.0.19 => 2.0.19
    vue-upload-component: ^2.8.14 => 2.8.14
    vue2-editor: ^2.6.6 => 2.6.6
    vue2-transitions: ^0.2.3 => 0.2.3
    vuex: ^3.0.1 => 3.0.1
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
```
module.exports = {
    publicPath: './',
    configureWebpack: config => {

        // 移除 prefetch 插件
        config.plugins.delete('prefetch');

        if (process.env.NODE_ENV === 'production') {
            // 为生产环境修改配置...
        } else {
            // 为开发环境修改配置...
            // config.devtool = '#source-map'
        }
    }

};
```

### What is expected?
fix this error

### What is actually happening?
 ERROR  TypeError: config.plugins.delete is not a function
```
TypeError: config.plugins.delete is not a function
    at configureWebpack (D:\hui\projects\H5Book\vue.config.js:6:30)
    at webpackRawConfigFns.forEach.fn (D:\hui\projects\H5Book\node_modules\@vue\cli-service\lib\Service.js:240:21)
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (D:\hui\projects\H5Book\node_modules\@vue\cli-service\lib\Service.js:237:30)
    at PluginAPI.resolveWebpackConfig (D:\hui\projects\H5Book\node_modules\@vue\cli-service\lib\PluginAPI.js:115:25)
    at module.exports (D:\hui\projects\H5Book\node_modules\@vue\cli-service\lib\commands\build\resolveAppConfig.js:36:25)
    at build (D:\hui\projects\H5Book\node_modules\@vue\cli-service\lib\commands\build\index.js:129:50)
    at api.registerCommand (D:\hui\projects\H5Book\node_modules\@vue\cli-service\lib\commands\build\index.js:76:13)
    at Service.run (D:\hui\projects\H5Book\node_modules\@vue\cli-service\lib\Service.js:219:12)
    at Object.<anonymous> (D:\hui\projects\H5Book\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)

```

**Comment by weituotian** [comment]
![image](https://user-images.githubusercontent.com/7270968/51464620-f2fab400-1da0-11e9-9be0-a648a375358a.png)

**Comment by LinusBorg** [comment]
Its `chainWebpack`, not `configureWebpack`

**Comment by samfrexz** [comment]
this didn't solve the error!
