### ISSUE TITLE
vue ui not working

### ISSUE THREAD

**Issue by seijikohara** [vuejs/vue-cli#3406]
### Version
3.4.0

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 11.9.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 12.0.2
  npmPackages:
    @vue/cli:  3.4.0
  npmGlobalPackages:
    @vue/cli: 3.4.0
```

### Steps to reproduce
`vue ui` command does not start with an error.

```
$ vue ui
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/apollo-env/lib/polyfills/array.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
```

### What is expected?
`vue ui` will start without errors.

### What is actually happening?
Necessary modules are missing.

**Comment by larsmars** [comment]
I have the same, just updated vue cli.

vue --version = 3.4.0
macOS Mojave 10.14.2
node v10.14.1
yarn 1.5.1
npm 6.7.0

**Comment by mnewt00** [comment]
Yeah I have the same error as well, trying to find a fix

**Comment by Kerbores** [comment]
me too

**Comment by Kerbores** [comment]
~ vue -V
3.4.0
➜  ~ npm -v
6.4.1
➜  ~ node -v
v10.15.1
➜  ~ vue ui
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/apollo-env/lib/polyfills/array.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by iAn-Pinto** [comment]
me too, same error:

 vue --version is 3.4.0
macOS Mojave 10.14.1 (18B75)
node --version is v11.9.0
npm --version  is 6.5.0

 vue ui

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/apollo-env/lib/polyfills/array.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by riiccardo** [comment]
+1

reinstall every thing like `vue-cli` `node` `core-js`  but still have problem

**Comment by sodatea** [comment]
It’s a bug in apollo-env

**Comment by sodatea** [comment]
The

**Comment by riiccardo** [comment]
Let us know when the bug was fixed , thanks 👍

**Comment by wangwenyin** [comment]
怎么修复呢？安装3.0低版本的cli？

**Comment by wangwenyin** [comment]
you gays can try：npm install -g core-js@3.0.0-beta.11 ，it's work for me!

**Comment by mnewt00** [comment]
Wow, thank you so much @wangwenyin it works now

**Comment by bellsenawat** [comment]
I try `yarn global add core-js@3.0.0-beta.3` and it's work !!!

**Comment by dousybox** [comment]
Seems apollo-env has fixed this problem.
https://github.com/apollographql/apollo-tooling/issues/962#issuecomment-460015427

**Comment by seijikohara** [comment]
This issue has been resolved. Thanks!

```shell
$ npm install -g @vue/cli && vue ui
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/usr/local/bin/vue -> /usr/local/lib/node_modules/@vue/cli/bin/vue.js
+ @vue/cli@3.4.0
updated 1 package in 4.664s
🚀  Starting GUI...
🌠  Ready on http://localhost:8000
```

**Comment by MCYouks** [comment]
After trying all the different solutions proposed above, it seems that removing the `node_modules` and then running `npm build` worked for me!
