### ISSUE TITLE
vue-upgrade does not work if npm is not installed

### ISSUE THREAD

**Issue by urkle** [vuejs/vue-cli#3439]
### Version
3.4.0

### Environment info
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
  Binaries:
    Node: 8.15.0 - /opt/local/bin/node
    Yarn: 1.12.3 - /opt/local/bin/yarn
    npm: Not Found
  Browsers:
    Chrome: 72.0.3626.96
    Firefox: 65.0
    Safari: 12.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.4.0
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.4.0
    @vue/cli-plugin-babel: ^3.3.0 => 3.4.0
    @vue/cli-plugin-eslint: ^3.3.0 => 3.4.0
    @vue/cli-plugin-unit-jest: ^3.3.0 => 3.4.0
    @vue/cli-service: ^3.3.0 => 3.4.0
    @vue/cli-shared-utils:  3.4.0
    @vue/component-compiler-utils:  2.5.2
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: ^1.0.0-beta.20 => 1.0.0-beta.28
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.1.0
    jest-serializer-vue:  2.0.2
    vue: ^2.5.21 => 2.5.22
    vue-eslint-parser:  4.0.3
    vue-hot-reload-api:  2.3.1
    vue-jest:  3.0.3
    vue-loader:  15.6.2
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.5.22
    vue-template-es2015-compiler:  1.8.2
    vuex: ^3.0.1 => 3.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
run `vue upgrade` in a vue-cli based project w/o having npm installed (only yarn)

### What is expected?
It to work

### What is actually happening?
error output (unhandled promise rejection) and the process gets stuck in a loop.
```
⠋  Gathering update information...(node:55613) UnhandledPromiseRejectionWarning: Error: Command failed: /bin/sh -c npm view @vue/cli-plugin-babel@^3.3.0 version --json
/bin/sh: npm: command not found


    at makeError (/Users/urkle/.config/yarn/global/node_modules/execa/index.js:174:9)
    at module.exports.sync (/Users/urkle/.config/yarn/global/node_modules/execa/index.js:338:15)
    at handleShell (/Users/urkle/.config/yarn/global/node_modules/execa/index.js:117:9)
    at Function.module.exports.shellSync (/Users/urkle/.config/yarn/global/node_modules/execa/index.js:361:43)
    at getMaxSatisfying (/Users/urkle/.config/yarn/global/node_modules/@vue/cli-upgrade/get-upgradable-version.js:5:11)
    at getUpgradableVersion (/Users/urkle/.config/yarn/global/node_modules/@vue/cli-upgrade/get-upgradable-version.js:27:28)
    at vueCliUpgrade (/Users/urkle/.config/yarn/global/node_modules/@vue/cli-upgrade/index.js:72:26)
    at Command.program.command.description.action (/Users/urkle/.config/yarn/global/node_modules/@vue/cli/bin/vue.js:167:47)
    at Command.listener (/Users/urkle/.config/yarn/global/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
(node:55613) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:55613) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠧  Gathering update information...^C
```

**Comment by LinusBorg** [comment]
The `upgrade` command/package isn't officially release yet, it's till experimental. 

It will work with both when it's done.

**Comment by sodatea** [comment]
Should have been fixed in 4.x
