### ISSUE TITLE
Allow silent/minimal/standard output when building

### ISSUE THREAD

**Issue by kjleitz** [vuejs/vue-cli#3603]
### What problem does this feature solve?

First: thank you guys so much for your time and effort on this project. It's **seriously** a life-saver.

So, I'm not sure if this is a feature request or _actually_ kind of a bug report... maybe a little of both. But I think whatever bug I'm experiencing would be made moot were this feature to exist.

I'm looking for an option for "minimal output" from `vue-cli-service build [--watch]` which does not have a progress status line which is neither animated nor changed in-place.

When running `vue-cli-service build --watch`, it does something funky with the standard output. First you see "building for development", then a progress status line which changes in place:

```
 34% building 204/220 modules 16 active ...e_modules/core-js/modules/_string-at.js`
```

...before finally logging the build output, something like:

```
 DONE  Compiled successfully in 10200ms1:42:48 PM

  File            Size                          Gzipped

  dist/blah.js    13645.43 KiB                  2565.83 KiB
  dist/app.js     980.16 KiB                    235.21 KiB

  Images and other types of assets omitted.

  DONE  Build complete. Watching for changes...
```

A similar thing happens when doing a plain, unwatched, `vue-cli-service build`.

If I try to redirect the output to a file and tail that file (e.g., `yarn run vue-cli-service build > foo.log`, `tail -f foo.log`), I _still see_ the dynamically-replaced progress line appear in the terminal where I ran the build command, and in `foo.log` I see a logged line from the TypeScript type-checking service starting up, and then I see the build output appear appended to the file. When I make a change to a watched file (if I use `build --watch`), I see the progress line in the previous terminal appear and I see another build "DONE" output in the log file.

See the following gif for an example:

![vue_cli_build_output](https://user-images.githubusercontent.com/18669659/54076420-756c0400-4279-11e9-9e71-d3279c301850.gif)

Also, if I use a process-management program (e.g., `node-foreman`) to start the `vue-cli-service build --watch`, it logs a line for _every single time_ the progress line changes, which easily fills my terminal buffer in just a few seconds—thousands of lines of output... 10-11 lines to one "XX% building ..." line. Even if the feature provided a way for each "1% building ...", "2% building ...", etc. line to be simply appended to standard output, that would be fine (for me). I can always filter the lines by piping to `grep`/`sed`/`awk`/whatever if I'm logging to a file or running the process with foreman. But currently there's no way to do that.

See the following gif for an example:

![vue_cli_build_nf_start](https://user-images.githubusercontent.com/18669659/54076435-946a9600-4279-11e9-91d7-4b6009e6f94c.gif)

So, if there were a way to simply log output "traditionally", line-by-line to STDOUT, without the observed hijacking (not sure what's going on), it would make it a heck of a lot easier to use `vue-cli-service` with other common development tools and basic utilities. I'm having a hard time setting up a simple local dev setup with vue-cli that reflects the workflow/practices of my team, so this feature would make our lives a lot smoother.

### What does the proposed API look like?

I'm picturing something like:

```bash
vue-cli-service build --verbosity silent  # no output
vue-cli-service build --verbosity minimal # no progress, appends every line instead of modifying in-place
vue-cli-service build --verbosity log     # includes progress but appends every line instead of modifying in-place
vue-cli-service build --verbosity default # business as usual
```

But I'm sure there's a better idea than that. Not quite sure how it should look.

**Comment by ashrafhadden** [comment]
## Please allow this for `vue-cli-service serve` as well!
I've sunk countless hours into trying to customize/minimize/suppress/silence/disable the output, but all to no avail. 

According to https://cli.vuejs.org/config/#devserver
> All options for webpack-dev-server are supported.

But trying to set some options like `devServer.info` give error:
```bash
 ERROR  ValidationError: webpack Dev Server Invalid Options
               
options should NOT have additional properties
               
ValidationError: webpack Dev Server Invalid Options

options should NOT have additional properties

    at validateOptions (/Users/ashrafhadden/code/bt-vue/node_modules/webpack-dev-server/node_modules/schema-utils/src/validateOptions.js:32:11)
    at new Server (/Users/ashrafhadden/code/bt-vue/node_modules/webpack-dev-server/lib/Server.js:87:5)
    at serve (/Users/ashrafhadden/code/bt-vue/node_modules/@vue/cli-service/lib/commands/serve.js:138:20)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
```
Many of the options on https://webpack.js.org/configuration/dev-server cause the same error.

This also makes using webpack output plugins like [webpackbar](https://www.npmjs.com/package/webpackbar) a complete mess since you can't silence the oirginal output, it all gets intermingled.
```bash
.bel/runtime-corejs2/core-js/date/now.j 40% building 142/149 modules 7 active ...bel/runtime-corejs2/core-js/date/now.j● Webpack █████████████████████████ building (40%) 144/150 modules 6 active  ...39m src/components/grids/AgGridBa● Webpack █████████████████████████ building (40%) 145/151 modules 6 active  ● Webpack █████████████████████████ building (40%) 147/151 modules 4 active
  ...loader/lib/runtime/installComponents.js 40% building 147/152 modules 5 active ...vue-style-loader/lib/addStylesClient.j
```

**Comment by ashrafhadden** [comment]
# Temp Solution

I found the [offending code](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/config/dev.js#L18-L22)! This hacky fix will at least completely disable any output until `--silent` and `--verbose` options can be properly implemented.
## The Hack
###### Remove offending code
```bash
sed -i.bak '17,22d' node_modules/@vue/cli-service/lib/config/dev.js
```
###### Restore offending code
```bash
cat node_modules/@vue/cli-service/lib/config/dev.js.bak > node_modules/@vue/cli-service/lib/config/dev.js
```

**Comment by kjleitz** [comment]
@ashrafhadden :+1: :+1: :+1: I'll definitely check out the plugin!

**Comment by vacri** [comment]
The 'build' action definitely needs a 'no progress bar' action - for a lot of CI systems, they just append all output text to log, and a progress bar is a _lot_ of output text as it is rewritten constantly. An append-only long doesn't care about the 'clear line' character used in dynamic status bars.

I've got some builds at the moment that have 1.2MB worth of buildlog... about 1.1MB of which is progress bar spam.

Just piping up with another use case...

**Comment by kjleitz** [comment]
bump! :)

**Comment by MKorostoff** [comment]
I was able to accomplish basically what this thread is asking for simply by passing the `--silent` flag at the command line, e.g.

```
vue-cli-service build --watch --silent
```

This has the advantage of still printing errors, but doesn't give me an ultra long list of all the file chunks that have been built.

**Comment by georgyfarniev** [comment]
Is there any updates about it?

**Comment by kjleitz** [comment]
@MKorostoff that change anything for me on v3.11.0 (still has the animated/changed-in-place progress line). Regardless, though, a `--silent` option doesn't satisfy the issue—I still _do need_ success/informational output, just output that's not... broken.

**Comment by vpiskunov** [comment]
The verbose line logging now started happening for me in Vue-UI (of CLI) - didn't happen before - any way to fix?

**Comment by geekytime** [comment]
It took me some digging to figure it out, but there does seem to be a way to get this working with `serve`. I tried to explain the situation here: https://github.com/vuejs/vue-cli/issues/4557#issuecomment-545965828

**Comment by UnicornDeluxe** [comment]
# Please allow this for vue-cli-service test:unit as well!

According to https://cli.vuejs.org/config/#devserver

    All options for webpack-dev-server are supported.

But trying to set any output options like devServer.stats and devServer.noInfo via vue.config.js have no effect.

A simple --silent and --verbose option for serve, build and test:unit would be awesome!

**Comment by denyo** [comment]
Adding this reduces the majority of logs.
```
// vue.config.js
module.exports = {
  devServer: {
    progress: false
  }
}
```

Also `vue-cli-service build --silent` works with `"@vue/cli-service": "^4.4.1"`.

**Comment by garcianavalon** [comment]
My use-case is  using `vue-cli-service serve` in a monorepo setup with several other commands run with `lerna --parallel`.

I settled with this conf:
- suppressing the default output 
- adding [simple-progress-webpack-plugin ](https://github.com/dominique-mueller/simple-progress-webpack-plugin) to still have visibility on the progress (single line output)

```js
// vue.config.js
const SimpleProgressWebpackPlugin = require('simple-progress-webpack-plugin')

module.exports = {
  configureWebpack: {
    plugins: [
      new SimpleProgressWebpackPlugin({
        format: 'minimal'
      })
    ]
  },
  devServer: {
    progress: false
  }
}
```

**Comment by jswinarton** [comment]
Just wanted to emphasize this aspect of the initial issue:

> So, if there were a way to simply log output "traditionally", line-by-line to STDOUT, without the observed hijacking (not sure what's going on), it would make it a heck of a lot easier to use vue-cli-service with other common development tools and basic utilities. I'm having a hard time setting up a simple local dev setup with vue-cli that reflects the workflow/practices of my team, so this feature would make our lives a lot smoother.

So far I have been able to figure out how to silence the majority of the unnecessary logs, but this doesn't fully fix the issue. There appears to be no way to prevent the builder from clearing the terminal window after the build is complete. This is a pretty serious issue because it doesn't play nice with other dev tools. For example, we are running Vue in a Docker container within docker-compose, which aggregates logs from multiple services to a single terminal window in development. As it stands this clobbers the output from all the other services, which is not ideal.

**Comment by jasonkarns** [comment]
Double 👍 to @jswinarton 's comment about clearing the console... We are booting our dev processes with overmind, and vue is nuking the output from the other processes. "not ideal" is a huge understatement

**Comment by vegerot** [comment]
When trying to run `vue-cli-service serve` in docker-compose, it is very annoying having to see a few thousands lines of 

```log
app_1    | <s> [webpack.Progress] 88% hashing
app_1    | <s> [webpack.Progress] 88% after hashing
app_1    | <s> [webpack.Progress] 88% after hashing
app_1    | <s> [webpack.Progress] 88% after hashing HotModuleReplacementPlugin
app_1    | <s> [webpack.Progress] 88% after hashing HotModuleReplacementPlugin
app_1    | <s> [webpack.Progress] 89% record hash
app_1    | <s> [webpack.Progress] 89% record hash
app_1    | <s> [webpack.Progress] 89% module assets processing
app_1    | <s> [webpack.Progress] 89% module assets processing
app_1    | <s> [webpack.Progress] 90% chunk assets processing
app_1    | <s> [webpack.Progress] 90% chunk assets processing
app_1    | <s> [webpack.Progress] 90% additional chunk assets processing
app_1    | <s> [webpack.Progress] 90% additional chunk assets processing
app_1    | <s> [webpack.Progress] 90% additional chunk assets processing HotModuleReplacementPlugin
app_1    | <s> [webpack.Progress] 90% additional chunk assets processing HotModuleReplacementPlugin
app_1    | <s> [webpack.Progress] 91% recording
app_1    | <s> [webpack.Progress] 91% recording
app_1    | <s> [webpack.Progress] 91% recording HotModuleReplacementPlugin
app_1    | <s> [webpack.Progress] 91% recording HotModuleReplacementPlugin
app_1    | <s> [webpack.Progress] 92% additional asset processing
app_1    | <s> [webpack.Progress] 92% additional asset processing
app_1    | <s> [webpack.Progress] 92% chunk asset optimization
app_1    | <s> [webpack.Progress] 92% chunk asset optimization
```

Every time I start the frontend.  


Please advise.  I am wondering if it is possible to get the fancy auto-updating single-line output I get when running this outside of docker.  That way I wouldn't need to turn off progress, but have the same experience I get when running it outside of docker

**Comment by ensc** [comment]
My hack  (for building within emacs which sets `TERM=dumb`) is

```js
if (process.env.TERM === 'dumb') {
    const t = require('@vue/cli-shared-utils');

    process.env.CI = 't';

    t.logWithSpinner = () => {};
    t.stopSpinner = () => {};
    t.pauseSpinner = () => {};
    t.resumeSpinner = () => {};
}

module.exports = {
     // ...
```

in top of `vue.config.js`.

**Comment by rmp135** [comment]
I've found a solution to the console nuking during serve. 

It's down to the "friendly-errors" plugin, so you can tap the config and remove the console clearing. In `vue.config.js` add the following.

```js
chainWebpack: config => {
  // Prevent HMR nuking the console.
  config
    .plugin('friendly-errors')
    .tap(args => {
      return [{
        ...args,
        clearConsole: false
      }]
    })
}
```
You still get the "App running at ..."  every time it compiles but there's no way around that.
