### ISSUE TITLE
执行vue ui报错

### ISSUE THREAD

**Issue by Frank-Mei** [vuejs/vue-cli#3630]
### Version
3.5.1

### Environment info
```

  System:
    OS: macOS High Sierra 10.13.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 10.4.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
    Safari: 11.1.1
  npmGlobalPackages:
    @vue/cli: 3.5.1
```

### Steps to reproduce
vue ui

### What is expected?
正常启动GUI

### What is actually happening?
Starting GUI...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
Emitted 'error' event at:
    at Server.emit (events.js:182:13)
    at Server.EventEmitter.emit (domain.js:442:20)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1498:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:17)

**Comment by web525** [comment]
sudo vi /etc/hosts加：127.0.0.1 localhost
