### ISSUE TITLE
Unable to build using vue-cli-service

### ISSUE THREAD

**Issue by arunrreddy** [vuejs/vue-cli#3667]
### Version
3.5.1

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
  Binaries:
    Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
    Yarn: Not Found
    npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
  Browsers:
    Chrome: 73.0.3683.75
    Firefox: 65.0.1
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.5 => 0.1.5 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2 
    @vue/babel-preset-app:  3.5.1 
    @vue/babel-preset-jsx:  1.0.0-beta.2 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2 
    @vue/babel-sugar-inject-h:  1.0.0-beta.2 
    @vue/babel-sugar-v-model:  1.0.0-beta.2 
    @vue/babel-sugar-v-on:  1.0.0-beta.2 
    @vue/cli-overlay:  3.5.1 
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.1 
    @vue/cli-plugin-eslint: ^3.5.0 => 3.5.1 
    @vue/cli-plugin-pwa: ^3.5.0 => 3.5.1 
    @vue/cli-service: ^3.5.0 => 3.5.1 
    @vue/cli-shared-utils:  3.5.1 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    bootstrap-vue: ^2.0.0-rc.11 => 2.0.0-rc.11 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 
    vue: ^2.6.6 => 2.6.9 
    vue-carousel: ^0.14.0 => 0.14.0 
    vue-cli-webpack:  1.0.0 
    vue-eslint-parser:  2.0.3 
    vue-functional-data-merge:  2.0.7 
    vue-google-signin-button: ^1.0.2 => 1.0.2 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-play:  3.2.1 
    vue-router: ^3.0.1 => 3.0.1 
    vue-slim-modal:  0.3.0 
    vue-star-rating: ^1.6.1 => 1.6.1 
    vue-style-loader:  4.1.2 
    vue-swal: ^0.1.0 => 0.1.0 
    vue-template-compiler: ^2.5.21 => 2.6.9 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.0.1 
    vuex-router-sync:  4.3.2 
  npmGlobalPackages:
    @vue/cli: 3.5.1
```

### Steps to reproduce
Getting the flowing error while building
Error: [BABEL] $HOME/src/main.js: Cannot find module '@babel/core' (While processing: "$HOME/@vue/babel-preset
-app/index.js")
at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at _core ($HOME/node_modules/@babel/plugin-proposal-async-generator-functions/lib/for-await.js:9:16)
    at Object.<anonymous> ($HOME/node_modules/@babel/plugin-proposal-async-generator-functions/lib/for-await.js:18:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ($HOME/node_modules/@babel/plugin-proposal-async-generator-functions/lib/index.js:48:40)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)

### What is expected?
Build should be successful

### What is actually happening?
Build fails on above error

**Comment by LinusBorg** [comment]
1. remove node_modules & package-lock.json / yarn.lock
2. install dependencies again

If that doesn'T work, provide a git repository as a reproduction.

**Comment by sodatea** [comment]
Closing due to inactivity. Please open a new issue with a reference to this one if you can follow up with more information.
