### ISSUE TITLE
vue-cli create a new app,and this app can't run with 'npm run serve'

### ISSUE THREAD

**Issue by fengcms** [vuejs/vue-cli#3727]
### Version
3.5.3

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.15 Deepin 15 15.9.2
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.5.3 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.5.1 
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.3 
    @vue/cli-plugin-eslint: ^3.5.0 => 3.5.1 
    @vue/cli-service: ^3.5.0 => 3.5.3 
    @vue/cli-shared-utils:  3.5.1 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 
    vue: ^2.6.6 => 2.6.10 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-router: ^3.0.1 => 3.0.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.0 
  npmGlobalPackages:
    @vue/cli: 3.5.3

```

### Steps to reproduce
```
vue create xxx
cd xxx
vue run serve
```
### What is expected?
it's run

### What is actually happening?
```
npm run serve                                                                                       1 ↵
> draggable-test@0.1.0 serve /home/fungleo/Sites/TMS/draggable-test
> vue-cli-service serve

 INFO  Starting development server...
 10% building 1/1 modules 0 activeevents.js:174                              
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/fungleo/Sites/TMS/draggable-test/public'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1253:11)
    at createFsWatchInstance (/home/fungleo/Sites/TMS/draggable-test/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/fungleo/Sites/TMS/draggable-test/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/fungleo/Sites/TMS/draggable-test/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/fungleo/Sites/TMS/draggable-test/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/home/fungleo/Sites/TMS/draggable-test/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/home/fungleo/Sites/TMS/draggable-test/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqWrap.oncomplete (fs.js:154:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/fungleo/Sites/TMS/draggable-test/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/fungleo/Sites/TMS/draggable-test/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home/fungleo/Sites/TMS/draggable-test/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:154:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! draggable-test@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the draggable-test@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fungleo/.npm/_logs/2019-03-29T10_24_44_708Z-debug.log
```

---
I'm chinese, and my english is poor, so...
I'm try reinstall 'chokidar@2.1.2', but the problem alway there...

**Comment by sodatea** [comment]
See https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by twenty-one-savage** [comment]
just change your port from :8080 to :xxxx
