### ISSUE TITLE
Cannot find module when installing bundled library

### ISSUE THREAD

**Issue by shayneo** [vuejs/vue-cli#3737]
### Version
3.5.4

### Reproduction link
[https://github.com/shayneo/vue-fuse/tree/fix-install-method](https://github.com/shayneo/vue-fuse/tree/fix-install-method)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.10.1 - ~/.nvm/versions/node/v8.10.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.2
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.5.4 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.5.1 
    @vue/cli-plugin-babel: ^3.5.4 => 3.5.4 
    @vue/cli-plugin-eslint: ^3.5.1 => 3.5.1 
    @vue/cli-plugin-unit-jest: ^3.5.3 => 3.5.3 
    @vue/cli-service: ^3.5.3 => 3.5.3 
    @vue/cli-shared-utils:  3.5.1 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/test-utils: ^1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0-0 => 5.2.2 
    jest-serializer-vue:  2.0.2 
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.3 
    vue-jest:  3.0.4 
    vue-loader:  15.7.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.5.4
```

### Steps to reproduce
1. clone project from here
2. create a test project `vue create tester`
3. install local version of plugin `npm i vue-fuse ../vue-fuse`
4. Add vue fuse to main.js
5. `npm run serve` 

### What is expected?
The project builds

### What is actually happening?
```
 ERROR  Failed to compile with 1 errors                                                                                                                               19:10:16

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module '@vue/eslint-config-standard'
Referenced from: /Users/shayneosullivan/projects/vue-fuse/.eslintrc.js
    at ModuleResolver.resolve (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/config/config-file.js:507:28)
    at load (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/config/config-file.js:579:26)
    at configExtends.reduceRight (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/config/config-file.js:453:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/config/config-file.js:431:26)
    at loadFromDisk (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/config/config-file.js:551:22)
    at Object.load (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/config/config-file.js:587:20)
    at Config.getLocalConfigHierarchy (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/config.js:342:29)
    at processText (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/cli-engine.js:181:33)
    at CLIEngine.executeOnText (/Users/shayneosullivan/projects/tester/node_modules/eslint/lib/cli-engine.js:690:40)
    at lint (/Users/shayneosullivan/projects/tester/node_modules/eslint-loader/index.js:263:17)
    at transform (/Users/shayneosullivan/projects/tester/node_modules/eslint-loader/index.js:237:18)
```

**Comment by sodatea** [comment]
https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root
