### ISSUE TITLE
Module build failed (from ./node_modules/eslint-loader/index.js):

### ISSUE THREAD

**Issue by michealjroberts** [vuejs/vue-cli#3776]
### Version
3.4.0

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: Not Found
    Safari: 12.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.5.5 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.5.1 
    @vue/cli-plugin-babel: ^3.0.3 => 3.5.5 
    @vue/cli-plugin-eslint: ^3.0.3 => 3.5.1 
    @vue/cli-service: ^3.0.3 => 3.5.3 
    @vue/cli-shared-utils:  3.5.1 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    shards-vue: ^1.0.7 => 1.0.7 
    vue: ^2.5.17 => 2.6.10 
    vue-clickaway:  2.2.2 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-router: ^3.0.1 => 3.0.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.17 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuejs-datepicker:  1.5.4 
  npmGlobalPackages:
    @vue/cli: 3.4.0
```

### Steps to reproduce
?

### What is expected?
Smooth running of npm run serve

### What is actually happening?
Error: Cannot find module '@vue/eslint-config-airbnb'

---
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin                                                    

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                  4:55:59 PM

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module '@vue/eslint-config-airbnb'
Referenced from: /Users/michaelroberts/Developer/repos/hug-front-end/.eslintrc.js
    at ModuleResolver.resolve (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/config/config-file.js:479:28)
    at load (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/config/config-file.js:551:26)
    at configExtends.reduceRight (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/config/config-file.js:425:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/config/config-file.js:403:26)
    at loadFromDisk (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/config/config-file.js:523:22)
    at Object.load (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/config/config-file.js:559:20)
    at Config.getLocalConfigHierarchy (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/config.js:227:44)
    at Config.getConfigHierarchy (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/config.js:286:21)
    at Config.getConfig (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/config.js:329:29)
    at processText (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/cli-engine.js:163:33)
    at CLIEngine.executeOnText (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/@vue/cli-plugin-eslint/node_modules/eslint/lib/cli-engine.js:620:17)
    at lint (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/eslint-loader/index.js:263:17)
    at transform (/Users/michaelroberts/Developer/repos/hug-front-end/node_modules/eslint-loader/index.js:237:18)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

**Comment by LinusBorg** [comment]
Hi  

Thanks for filing this issue! Could you please provide a small reporduction on jsfiddle.net so we can debug this without trying to replicate this ourselves?`

That would be very helpful, thanks!

**Comment by LinusBorg** [comment]
It sounds as if this package is defined as a dependency but not actually installed. 

Have you tried to install it?

**Comment by sodatea** [comment]
Closing due to inactivity. Please open a new issue with a reference to this one if you can follow up with more information.

**Comment by lucas-hugdahl** [comment]
This is an issue for me as well

**Comment by LinusBorg** [comment]
Well we can reopen it if you can provide a reproduction as is required.

**Comment by jonathanCNITA** [comment]
Hello, same here.
I use vue cli version 3.6: 
+ `vue create myproject`
+ choose default settings
+ `cd myproject`
+ `npm run serve`
And get this error 
````
 INFO  Starting development server...
 98% after emitting CopyPlugin                                                 

 ERROR  Failed to compile with 1 errors

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module '/Users/toto/Documents/programming/VueProjects/myproject/node_modules/eslint/lib/api.js/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.module.exports (/Users/mcz/Documents/programming/VueProjects/myproject/node_modules/eslint-loader/index.js:170:23)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
````
I use this yesterday and everythings worked fine.
tested on 3.6.3 & 3.7.0
Any idea

**Comment by LinusBorg** [comment]
See #4231
