### ISSUE TITLE
pages parameter causes `vue serve` to stack trace

### ISSUE THREAD

**Issue by cacosmi** [vuejs/vue-cli#3798]
### Version
3.5.3

### Reproduction link
[https://github.com/CamusEnergy/ritta/tree/6c9d58a854b780ce699b3ce2bcc4abffea40711b](https://github.com/CamusEnergy/ritta/tree/6c9d58a854b780ce699b3ce2bcc4abffea40711b)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 25.0.1
    Safari: 12.1
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.6 => 0.1.6 
    @vue/cli-overlay:  3.5.1 
    @vue/cli-service: ^3.5.3 => 3.5.3 
    @vue/cli-shared-utils:  3.5.1 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    vue: ^2.6.10 => 2.6.10 
    vue-cli-webpack:  1.0.0 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-spinner: ^1.0.3 => 1.0.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.5.5
```

### Steps to reproduce
Uncomment the 'pages' parameter in vue.config.js and  run `vue serve`.

### What is expected?
Not a stack trace.

### What is actually happening?
A stack trace.

---
Stack trace is:

(node:48537) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'template' of undefined

It looks like this accesses the plugin via the name 'html', and gets back undefined:

https://github.com/vuejs/vue-cli/blob/bd57f15a15303d7ae32eb4961d9418b76593189c/packages/%40vue/cli-service-global/lib/globalConfigPlugin.js#L125

That happens because, in multi-page mode, the plugin is assigned the name 'html-${name}':

https://github.com/vuejs/vue-cli/blob/f1807fd304cc07c1b3707c2491e584f9ee079ab8/packages/%40vue/cli-service/lib/config/app.js#L229

See full stack trace below.

Thanks,
Cody

$ vue serve
 INFO  Starting development server...
(node:48537) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'template' of undefined
    at config.plugin.tap.args (/usr/local/lib/node_modules/@vue/cli-service-global/lib/globalConfigPlugin.js:127:34)
    at Object.tap (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/webpack-chain/src/Plugin.js:24:24)
    at api.chainWebpack.config (/usr/local/lib/node_modules/@vue/cli-service-global/lib/globalConfigPlugin.js:126:16)
    at webpackChainFns.forEach.fn (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:227:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:227:26)
    at Service.resolveWebpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:231:48)
    at PluginAPI.resolveWebpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/PluginAPI.js:115:25)
    at serve (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/commands/serve.js:47:31)
    at Service.run (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:221:12)
    at Object.exports.serve (/usr/local/lib/node_modules/@vue/cli-service-global/index.js:88:33)
    at Command.program.command.description.option.option.action (/usr/local/lib/node_modules/@vue/cli/bin/vue.js:116:53)
    at Command.listener (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:193:13)
    at Command.parseArgs (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:474:21)
(node:48537) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:48537) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sodatea** [comment]
`vue serve` is for instant prototyping with zero config only.

In this case you are expected to use `npx vue-cli-service serve` to run it.
