### ISSUE TITLE
Path error when adding plugins via 'vue add' or vue ui

### ISSUE THREAD

**Issue by Diizzayy** [vuejs/vue-cli#3808]
### Version
3.6.1

### Reproduction link
[https://github.com/Diizzayy/vue-test](https://github.com/Diizzayy/vue-test)

### Environment info
```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 11.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: Not Found
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.6.0 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli: ^3.6.1 => 3.6.1 
    @vue/cli-overlay:  3.6.0 
    @vue/cli-plugin-babel: ^3.6.0 => 3.6.0 
    @vue/cli-plugin-eslint: ^3.6.0 => 3.6.0 
    @vue/cli-plugin-pwa: ^3.6.0 => 3.6.0 
    @vue/cli-service: ^3.6.0 => 3.6.0 
    @vue/cli-shared-utils:  3.6.0 
    @vue/cli-ui:  3.6.1 
    @vue/cli-ui-addon-webpack:  3.6.0 
    @vue/cli-ui-addon-widgets:  3.6.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 
    vue: ^2.6.10 => 2.6.10 
    vue-cli-plugin-apollo:  0.19.2 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-observe-visibility:  0.4.3 
    vue-resize:  0.4.5 
    vue-router: ^3.0.3 => 3.0.4 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vue-virtual-scroller:  1.0.0-rc.2 
    vuex: ^3.0.1 => 3.1.0 
  npmGlobalPackages:
    @vue/cli: 3.6.1
```

### Steps to reproduce
Installed latest version of @vue/cli using 'npm i -g @vue/cli@latest'
created new project and added the plugins (pwa, babel, vuex, vue-router and eslint)
attempt to install ANY vue plugin using 'vue add '

### What is expected?
Should be able to add plugins either using the Vue UI or via cli using ('vue add example)

### What is actually happening?
The project is running and build perfectly, however though I am unable to add any plugins, neither by cli ('vue add vuetify') for example nor by the Vue UI. When attempting to add any plugins using either method I am met with this error:

 ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type strin
g. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Recei
ved type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1036:7)
    at exports.hasProjectPnpm (/usr/local/lib/node_modules/@vue/cli/node_modules/@v
ue/cli-shared-utils/lib/env.js:113:25)
    at add (/usr/local/lib/node_modules/@vue/cli/lib/add.js:30:94)
    at module.exports.args (/usr/local/lib/node_modules/@vue/cli/lib/add.js:66:10)
    at Command.program.command.description.option.allowUnknownOption.action (/usr/local/lib/node_modules/@vue/cli/bin/vue.js:86:26)
    at Command.listener (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:193:13)
    at Command.parseArgs (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:474:21)

**Comment by Diizzayy** [comment]
It is a confirmed bug

https://github.com/vuejs/vue-cli/issues/3804#issuecomment-482942950
