### ISSUE TITLE
创建新项目 环境选择npm包管理保存 (版本没有3.6.3)

### ISSUE THREAD

**Issue by helloweb314** [vuejs/vue-cli#3823]
### Version
3.6.2

### Reproduction link
[http://meiyou.com](http://meiyou.com)

### Environment info
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: Not Found
    Safari: 11.1.2
  npmGlobalPackages:
    @vue/cli: 3.6.3
```

### Steps to reproduce
1. npm install -g @vue/cli        //3.6.3
2. vue ui
3.包管理选择npm , 手动配置项目,
4 router  vuex  css pro-processors linter  使用配置文件
5 ESLint   Standard config    ESLint   Standard config 关闭  Lint on save
6. 保存预设 base

🚀  Starting GUI...
🌠  Ready on http://localhost:8000
/bin/sh: pnpm: command not found
Invalid project name: "domain"
Warning: domain is a core module name
 ERROR  Error: Process exited with code 1
Error: Process exited with code 1
    at exports.exit (/usr/local/lib/node_modules/@vue/cli/node_modules/@vue/cli-shared-utils/lib/exit.js:7:11)
    at create (/usr/local/lib/node_modules/@vue/cli/lib/create.js:30:5)
    at module.exports.args (/usr/local/lib/node_modules/@vue/cli/lib/create.js:77:10)
    at Command.program.command.description.option.option.option.option.option.option.option.option.option.option.option.option.action (/usr/local/lib/node_modules/@vue/cli/bin/vue.js:77:29)
    at Command.listener (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:193:13)
    at Command.parseArgs (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli/bin/vue.js:227:9)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
{ Error: Command failed: vue create domain --skipGetStarted --inlinePreset {"useConfigFiles":true,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"standard","lintOn":[]}},"router":true,"routerHistoryMode":false,"vuex":true,"cssPreprocessor":"less"}

    at makeError (/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:278:16)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  code: 1,
  stdout: '',
  stderr: null,
  failed: true,
  signal: null,
  cmd:
   'vue create domain --skipGetStarted --inlinePreset {"useConfigFiles":true,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-eslint":{"config":"standard","lintOn":[]}},"router":true,"routerHistoryMode":false,"vuex":true,"cssPreprocessor":"less"}',
  timedOut: false,
  killed: false }

我未选择pnpm  选择的是npm  多次尝试
    

### What is expected?
创建完项目

### What is actually happening?
失败

---
学习第一步..

**Comment by helloweb314** [comment]
包管理哪里不管选啥都爆这个错

**Comment by sodatea** [comment]
这个错误提示很清楚啊……
项目名不能叫 domain，因为和 Node.js 的核心包名冲突了

**Comment by helloweb314** [comment]
谢谢, 确实是这样的,  换个名字就没问题, 就是不明白为啥 为报 pnpm不存在, 可能是包的问题,
包括  vue create -m npm my-app 也会闪一下 pnpm no found
非常感谢您的帮助

**Comment by sodatea** [comment]
如果用户没指定包管理工具的话，我们会按 yarn -> pnpm -> npm 的顺序检测并使用。可能是检测 pnpm 的代码不小心把报错信息暴露出来了。
