### ISSUE TITLE
CLI document explains developers how to debugger each command within nodejs

### ISSUE THREAD

**Issue by vuchan** [vuejs/vue-cli#3855]
### What problem does this feature solve?
i could debugger `Service` with vue-cli-service, but i don't know how to debugger `Generator` and how to write the VSCode configuration `launch.json` for it?

it was very unfriendly for developers who very need a CLI3 plugin but not familiar with nodejs debugger.
although i can write a configuration for vue-cli-serive, but `generator` be called in global command `vue` the following VSCode configuration was not work for that:
```json
{
      "type": "node",
      "request": "launch",
      "name": "Launch Test with vue-cli generator",
      "program": "/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/bin/vue",
      "args": [
        "invoke",
        "vue-cli-plugin-portal",
      ]
    },
```

So, if the CLI document in [plugin-development-guide](https://cli.vuejs.org/dev-guide/plugin-dev.html#plugin-development-guide) chapter indicates how to debugger `generator`, `Service` very be very useful for plugin developers. and it could make Vue-Cli ecosystem more bigger as well.

### What does the proposed API look like?
as above mentioned.

**Comment by vuchan** [comment]
The question from this situation, when i Invoking generator for vue-cli-plugin-portal i got a very confusing error and cannot get any useful information for debug, even i added those env variables `VUE_CLI_TEST=true` & `VUE_CLI_DEBUG=true` in`.env` file` of current project.

Is there anyone know how to debug with following messages?
What i got is:
1. here has a syntax error the `esprima` cannot understand `...` just like Object spread operator
2. i tried remove all ES6 `...` spread operator in plugin, but error still exists.

What can i do? anyone can help? Thanks!

```bash
❯ sh run-plugin-generation.sh
? Use master-runtime or not? Yes
? Which one? iBuild
? Input master-runtime version ^1.0.4

🚀  Invoking generator for vue-cli-plugin-portal...
 ERROR  Error: Line 40: Unexpected token ...
Error: Line 40: Unexpected token ...
    at ErrorHandler.constructError (/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parseObjectPropertyKey (/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2499:33)
    at Parser.parseObjectProperty (/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2534:25)
    at Parser.parseObjectInitializer (/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2602:35)
    at Parser.inheritCoverGrammar (/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parsePrimaryExpression (/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2354:38)
    at Parser.inheritCoverGrammar (/Users/vuchan.c.wu/.nvm/versions/node/v10.13.0/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2285:37)
```
