### ISSUE TITLE
vue-cli crashes with node.js v12

### ISSUE THREAD

**Issue by zaharsk** [vuejs/vue-cli#3883]
### Version
3.6.3

### Environment info
```
  System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 12.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    @vue/cli-overlay:  3.6.0
    @vue/cli-plugin-eslint: ^3.6.0 => 3.6.0
    @vue/cli-service: ^3.6.0 => 3.6.0
    @vue/cli-shared-utils:  3.6.0
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router: ^3.0.3 => 3.0.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Create new project with `vue create hello-world` AND Try to serve with `cd hello-world` and `pnpm run serve` OR Try to build with `cd hello-world` and `pnpm run build`

### What is expected?
Normal serving/building

### What is actually happening?
For serving:
```
 INFO  Starting development server...
 98% after emitting CopyPlugin



#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 000000A35415D7A0npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! hello-world@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the hello-world@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Roaming\npm-cache\_logs\2019-04-24T16_07_36_996Z-debug.log
```
For building:
```
|  Building for production...



#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 000000394D6FD4C0npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! hello-world@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the hello-world@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Roaming\npm-cache\_logs\2019-04-24T16_09_57_883Z-debug.log
```

---
Perhaps this is caused by this bug in the latest version of Node:
https://github.com/nodejs/node/issues/27379

Detailed log from `C:\Users\<username>\AppData\Roaming\npm-cache\_logs\2019-04-24T16_09_57_883Z-debug.log`
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle hello-world@0.1.0~prebuild: hello-world@0.1.0
6 info lifecycle hello-world@0.1.0~build: hello-world@0.1.0
7 verbose lifecycle hello-world@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle hello-world@0.1.0~build: PATH: C:\Users\<username>\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\dev\hello-world\node_modules\.bin;D:\dev\hello-world\node_modules\.bin;C:\Program Files\nodejs;C:\Python27\;C:\Python27\Scripts;C:\Python37\Scripts\;C:\Python37\;C:\ProgramData\Boxstarter;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\libnvvp;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Dart\dart-sdk\bin;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\TortoiseSVN\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Go\bin;C:\Program Files\nodejs\;C:\Users\<username>\AppData\Local\Microsoft\WindowsApps;C:\tools\dart-sdk\bin;C:\Users\<username>\AppData\Roaming\Pub\Cache\bin;C:\Users\<username>\AppData\Local\Microsoft\WindowsApps;C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\<username>\go\bin;C:\Users\<username>\.dotnet\tools;C:\Users\<username>\go\bin;C:\Users\<username>\AppData\Roaming\npm
9 verbose lifecycle hello-world@0.1.0~build: CWD: D:\dev\hello-world
10 silly lifecycle hello-world@0.1.0~build: Args: [ '/d /s /c', 'vue-cli-service build' ]
11 silly lifecycle hello-world@0.1.0~build: Returned: code: 3221225477  signal: null
12 info lifecycle hello-world@0.1.0~build: Failed to exec build script
13 verbose stack Error: hello-world@0.1.0 build: `vue-cli-service build`
13 verbose stack Exit status 3221225477
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\<username>\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\<username>\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1000:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
14 verbose pkgid hello-world@0.1.0
15 verbose cwd D:\dev\hello-world
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.0.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 3221225477
22 error hello-world@0.1.0 build: `vue-cli-service build`
22 error Exit status 3221225477
23 error Failed at the hello-world@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225477, true ]
```

**Comment by Akryum** [comment]
Looks like an upstream issue in node.

**Comment by zaharsk** [comment]
@Akryum yes. I pointed to the Node issue in the description.

**Comment by AkonXI** [comment]
+1 same issue

**Comment by SimonSP** [comment]
same problem

**Comment by DRoet** [comment]
This should be fixed now that node.js `12.1.0` is out

**Comment by phavor** [comment]
Am getting similar error with `npm v7.10.0` and `node v12.22.1`
