### ISSUE TITLE
test:unit not accepting Jest options

### ISSUE THREAD

**Issue by aniforprez** [vuejs/vue-cli#3936]
### Version
3.7.0

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.3
    Safari: 12.1
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.6 => 0.1.6
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0-beta.3
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3
    @vue/babel-sugar-inject-h:  1.0.0-beta.3
    @vue/babel-sugar-v-model:  1.0.0-beta.3
    @vue/babel-sugar-v-on:  1.0.0-beta.3
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0
    @vue/cli-plugin-eslint: ^3.7.0 => 3.7.0
    @vue/cli-plugin-pwa: ^3.7.0 => 3.7.0
    @vue/cli-plugin-unit-jest: ^3.7.0 => 3.7.0
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    eslint-plugin-vue: ^5.2.2 => 5.2.2
    jest-serializer-vue:  2.0.2
    typescript:  2.9.2
    vue: ^2.6.10 => 2.6.10
    vue-cli-webpack:  1.0.0
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.3
    vue-jest:  3.0.4
    vue-loader:  15.7.0
    vue-resource: ^1.5.1 => 1.5.1
    vue-router: ^3.0.6 => 3.0.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    @vue/cli: 3.5.1
```

### Steps to reproduce
Run `npm run test:unit --watch`  or `npm run test:unit -- --watch`  on a Jest initialized repo or replace the "test:unit" script in packages.json with `vue-cli-service test:unit --watch`

### What is expected?
It should pass the options onto jest and allow interactive test running and watch the folder for changes

### What is actually happening?
The command fails with the following error

```
➜  npm run test:unit -- --watch

> reddit-saved@0.1.0 test:unit /Users/anirudhs/Documents/personal-projects/reddit-saved
> vue-cli-service test:unit "--watch"

Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/anirudhs/Documents/personal-projects/reddit-saved/node_modules/sane/src/fsevents_watcher.js:41:11)
    at createWatcher (/Users/anirudhs/Documents/personal-projects/reddit-saved/node_modules/jest-haste-map/build/index.js:780:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/anirudhs/Documents/personal-projects/reddit-saved/node_modules/jest-haste-map/build/index.js:936:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/anirudhs/Documents/personal-projects/reddit-saved/node_modules/jest-haste-map/build/index.js:355:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reddit-saved@0.1.0 test:unit: `vue-cli-service test:unit "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reddit-saved@0.1.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anirudhs/.npm/_logs/2019-05-04T06_44_48_159Z-debug.log
```

**Comment by LinusBorg** [comment]
That problem is related to jest's watcher implementation. It seems that for some reason, it thinks you are not on OSX? 

Have you tried deleting the lock file, deleting node-modules/ and reinstalling all packages?

**Comment by aniforprez** [comment]
I don't understand which file is the "lock file" but deleting node_modules/ and reinstalling all the dependencies once again worked

**Comment by LinusBorg** [comment]
I don't understand which file is the "lock file" 
Either `/package-lock.json` or `yarn.lock`in your project root - depending which package manager you are using (npm or yarn)

**Comment by aniforprez** [comment]
Ah all right I forgot abut the package-lock.json. In any case, jest is now properly accepting options so I think I don't need to do any further steps. Once again, thanks a lot for taking the time to help
