### ISSUE TITLE
vue init with templete cause an error

### ISSUE THREAD

**Issue by joshidhruv** [vuejs/vue-cli#402]
`MacBook-Pro-2: Dreamer$ vue -V`
2.8.1
`MacBook-Pro-2:Dreamer$ vue init browserify test`

/usr/local/lib/node_modules/vue-cli/bin/vue-init:65
  console.log(`> Use cached template at ${chalk.yellow(tildify(tmp))}`)
              ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

I was trying run a sample app with the template and cause this issue. I am new to VueJs.

**Comment by yyx990803** [comment]
You are probably using an outdated version of Node.js that does not support ES2015 template strings. Please upgrade to a newer version (6+).

**Comment by joshidhruv** [comment]
Thank you for your help. Thats exactly was the issue. +1
