### ISSUE TITLE
npm run build   就是官网案例直接打包报错

### ISSUE THREAD

**Issue by 768722060** [vuejs/vue-cli#4028]
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at PoolWorker.writeJson (C:\Users\Administrator\vue11\node_modules\thread-loader\dist\WorkerPool.js:118:20)
    at PoolWorker.run (C:\Users\Administrator\vue11\node_modules\thread-loader\dist\WorkerPool.js:100:10)
    at WorkerPool.distributeJob (C:\Users\Administrator\vue11\node_modules\thread-loader\dist\WorkerPool.js:332:15)
    at runQueue (C:\Users\Administrator\vue11\node_modules\neo-async\async.js:8097:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:425:12)
    at onwrite (_stream_writable.js:456:5)
    at doWrite (_stream_writable.js:406:11)
    at writeOrBuffer (_stream_writable.js:394:5)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue11@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue11@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-05-20T06_00_39_175Z-debug.log

**Comment by 768722060** [comment]
node  v10.15.3                        vue 3.7.0

**Comment by Fanpero** [comment]
Hello, I'd like to ask. Has it been solved? How to solve this problem
