### ISSUE TITLE
Proxy and cypress - cli-plugin-e2e-cypress

### ISSUE THREAD

**Issue by dcrystalj** [vuejs/vue-cli#4167]
### Version
3.8.0

### Environment info
```
osx, node 12.4.0
```

### Steps to reproduce
setup vue.config.js:
```
const defaultProxySettings = {
  target: 'http://localhost:8000/,
 };

module.exports = {
  devServer: {
    public: '127.0.0.1:8080',
    disableHostCheck: true,
    proxy: {
      '/ajax': defaultProxySettings,
      '/api': defaultProxySettings,
    },
  },
```
yields
```
yarn run v1.13.0
$ vue-cli-service test:e2e --mode develop
 INFO  Starting e2e tests...
 INFO  Starting development server...
 10% building 4/4 modules 0 active ERROR  TypeError: Cannot read property 'upgrade' of undefined
TypeError: Cannot read property 'upgrade' of undefined
    at Server.<anonymous> (/.../node_modules/webpack-dev-server/lib/Server.js:148:47)
    at Array.forEach (<anonymous>)
    at new Server (/.../node_modules/webpack-dev-server/lib/Server.js:147:27)
    at serve (/.../node_modules/@vue/cli-service/lib/commands/serve.js:138:20)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async /.../node_modules/@vue/cli-plugin-e2e-cypress/index.js:26:9
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### What is expected?
run server

### What is actually happening?
error lunching cypress

---
running `./node_modules/cypress/bin/cypress open` works fine.
Disabling proxy in config also does not fail cli-plugin-e2e-cypress

**Comment by sodatea** [comment]
Please provide a runnable reproduction.

**Comment by dcrystalj** [comment]
I realised cypress is running in production mode, where I was missing some environment variables for development server which were used in vue.config.js.

in package.json i have now --mode included
`"test:e2e1": "vue-cli-service test:e2e --mode development",`
