### ISSUE TITLE
console.log(`> Use cached template at ${chalk.yellow(tildify(tmp))}`)

### ISSUE THREAD

**Issue by Profeten** [vuejs/vue-cli#446]
C:\ > vue.cmd 
initconsole.log(`> Use cached template at ${chalk.yellow(tildify(tmp))}`)
                       ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Seems to be a problem under Windows with the CLI?

**Comment by Profeten** [comment]
node -v
v0.12.2

Nvm

**Comment by posva** [comment]
yeah, node 4 min

**Comment by brutalaty** [comment]
Thank you, I'm a newborn when it comes to Node.js. If you hadn't of posted this and it's solution, I'd have given up.

I installed VS Code and it seems as though it installed 0.12.2. 
**Uninstalling node,js and installing a later version solved all my problems.**
Thank you again.
