### ISSUE TITLE
Cannot build project with @vue/prettier

### ISSUE THREAD

**Issue by numfin** [vuejs/vue-cli#4465]
### Version
3.10.0

### Reproduction link
[https://github.com/numfin/vue-prettier-problem](https://github.com/numfin/vue-prettier-problem)

### Environment info
```
docker image node:alpine-current (in node:lts same situatuion)
```

### Steps to reproduce
when running npm run build locally - everything works.
when building docker container - it crashes.
- add @vue/prettier in .eslintrc
- npm run build

### What is expected?
build succesfully

### What is actually happening?
error:
```
> vue-cli-service build --modern


-  Building legacy bundle for production...
Starting type checking service...
Using 1 worker with 2048MB memory limit
 ERROR  Failed to compile with 1 errors12:48:37 AM

 error  in /src/main.ts

Module build failed (from /node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
ENOENT: no such file or directory, scandir '/rc'
Occurred while linting /rc/main.ts:1
    at PoolWorker.fromErrorObj (/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at Object.readdirSync (fs.js:795:3)
    at traverseFolder (/node_modules/prettier/index.js:40340:18)
    at findRoot (/node_modules/prettier/index.js:40356:10)
    at maybeParse (/node_modules/prettier/index.js:40368:16)
    at editorconfigSyncNoCache (/node_modules/prettier/index.js:40381:35)
    at editorconfigSyncNoCache (/node_modules/prettier/index.js:36212:20)
    at /node_modules/prettier/index.js:42627:14
    at Array.map (<anonymous>)
    at _resolveConfig (/node_modules/prettier/index.js:42626:40)
    at Function.resolveConfig.sync (/node_modules/prettier/index.js:42662:12)

 @ multi ../src/main.ts

 ERROR  Build failed with errors.
```

---
Also im working in visual studio docker environment and it building ok there. When im trying to build in my native system with `docker build -t s .` - it shows error.

**Comment by sodatea** [comment]
See https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
It seems to be a permission issue. I didn't find the exact code that caused this problem but the error disappears after I modified the docker file to use a non-root user.

The `Dockerfile` after modification:
```Dockerfile
FROM node:latest as build
USER node

COPY --chown=node:node . /home/node/app
WORKDIR /home/node/app
RUN npm ci
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build dist /usr/share/nginx/html
```

**Comment by numfin** [comment]
thanks
