### ISSUE TITLE
Anyone knows this error when type running and building project?

### ISSUE THREAD

**Issue by lifuyao** [vuejs/vue-cli#4579]
Using Vue cli3 , when type running or building  project  command, it will raise error like this, it dose not block the running and building, but the output is in a mess, anyone has even seen this? very thanks for your help

`> vue-cli-service serve

 ERROR  TypeError: Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
    at interpolate (\node_modules\dotenv-expand\lib\main.js:8:28)
    at dotenvExpand (D:\\node_modules\dotenv-expand\lib\main.js:36:32)
    at load (D:\Vue\node_modules\@vue\cli-service\lib\Service.js:103:9)
    at Service.loadEnv (D:\Vue\node_modules\@vue\cli-service\lib\Service.js:114:5)
    at Service.init (D:\Vue\node_modules\@vue\cli-service\lib\Service.js:69:12)
    at Service.run (D:\Vue\node_modules\@vue\cli-service\lib\Service.js:221:10)
    at Object.<anonymous> (D:\Vue\node_modules\@vue\cli-service\bin\vue-cli-service.js:37:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
 INFO  Starting development server...`

**Comment by lifuyao** [comment]
This error was seen on the start of building and running command
