### ISSUE TITLE
'Cannot read property 'match' of undefined' error  when building and running project

### ISSUE THREAD

**Issue by lifuyao** [vuejs/vue-cli#4580]
### Version
3.11.0

### Environment info
```
Windows 10家庭中文版
```

### Steps to reproduce
1. npm run serve | npm run build

### What is expected?
The output console won't raise any error then building and running project

### What is actually happening?
> vue-cli-service serve

ERROR TypeError: Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
at interpolate (\node_modules\dotenv-expand\lib\main.js:8:28)
at dotenvExpand (D:\node_modules\dotenv-expand\lib\main.js:36:32)
at load (D:\Vue\node_modules@vue\cli-service\lib\Service.js:103:9)
at Service.loadEnv (D:\Vue\node_modules@vue\cli-service\lib\Service.js:114:5)
at Service.init (D:\Vue\node_modules@vue\cli-service\lib\Service.js:69:12)
at Service.run (D:\Vue\node_modules@vue\cli-service\lib\Service.js:221:10)
at Object. (D:\Vue\node_modules@vue\cli-service\bin\vue-cli-service.js:37:9)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
INFO Starting development server...`

---
> vue-cli-service serve

ERROR TypeError: Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
at interpolate (\node_modules\dotenv-expand\lib\main.js:8:28)
at dotenvExpand (D:\node_modules\dotenv-expand\lib\main.js:36:32)
at load (D:\Vue\node_modules@vue\cli-service\lib\Service.js:103:9)
at Service.loadEnv (D:\Vue\node_modules@vue\cli-service\lib\Service.js:114:5)
at Service.init (D:\Vue\node_modules@vue\cli-service\lib\Service.js:69:12)
at Service.run (D:\Vue\node_modules@vue\cli-service\lib\Service.js:221:10)
at Object. (D:\Vue\node_modules@vue\cli-service\bin\vue-cli-service.js:37:9)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
INFO Starting development server...`

**Comment by lifuyao** [comment]
Anyone know how to resolve this issue , very thanks for your help

**Comment by sodatea** [comment]
Please provide a reproduction for bug reports.
Looks like some syntax issues in your `.env` file.

**Comment by lifuyao** [comment]
@sodatea Thanks for your help, based on your instructions, I resolved this issue, I defined a variable valued empty string(eg: BASE_API = '') in .env file, so it would raise error mentioned in this issue, I closed this issue, many thanks.

**Comment by lifuyao** [comment]
> Please provide a reproduction for bug reports.
> Looks like some syntax issues in your `.env` file.

Nice, But I wonder how did you this issue related with the .env file, very good insight。

**Comment by sodatea** [comment]
From this line of error message:
`at interpolate (\node_modules\dotenv-expand\lib\main.js:8:28)`

And [dotenv-expand](https://github.com/motdotla/dotenv-expand) is used for variable expansion in `.env` files.
