### ISSUE TITLE
 ubuntu 16.4 电脑上装了crossover之后运行vue --help报以下错误

### ISSUE THREAD

**Issue by henjue** [vuejs/vue-cli#461]
```bash
Wine cannot find the ncurses library (libncurses.so.5).
module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (Z:\usr\local\bin\vue:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
估计内部把电脑识别成windows了，这个怎么解决

**Comment by henjue** [comment]
我的问题，path里首先找到了crossover里的node了

**Comment by zjhr** [comment]
@henjue 请问一下怎么解决？我也是这样，玩不了。。

**Comment by henjue** [comment]
@zjhr path里优先找到了crossover里的node。把path里的顺序修改下就可以了
