### ISSUE TITLE
@vue/cli-shared-utils issue in dependancy @hapi/joi

### ISSUE THREAD

**Issue by hitesh399** [vuejs/vue-cli#4645]
Hi Team,
I am using @vue/cli-shared-utils@3.11.0 and getting some problem in dependancy @hapi/joi

Error: Cannot find module './types/any'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/var/www/vuetify-material-dashboard/node_modules/@hapi/joi/lib/index.js:5:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
**OS:** Mac

**Comment by hitesh399** [comment]
I am still facing this issue. If You already resolved the issue. Please guide me how can I fix It?
