### ISSUE TITLE
Create new project - TypeError: api.assertCliVersion is not a function

### ISSUE THREAD

**Issue by InspireTheLostBoys** [vuejs/vue-cli#4688]
### Version
3.3.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
open terminal
vue create <project-name>
* manually select features
  * Babel
  * PWA
  * Router
  * Vuex
  * Linter/Formatter
<enter>
"Use history mode for router..." : No
<enter>
* ESLint with error prevention only
<enter>
* Lint on save
<enter>
In package.json
"Save this as a preset..." : No

### What is expected?
A new project should be created, usually works every time, but today i cannot create a new project

### What is actually happening?
Vue CLI v3.3.0
....
�🚀  Invoking generators...
 ERROR  TypeError: api.assertCliVersion is not a function
TypeError: api.assertCliVersion is not a function
    at module.exports (c:\Work\DevInspire\GIT\Shout\NEW\shout-admin-portal\node_modules\@vue\cli-plugin-eslint\generator\index.js:5:7)
    at Generator.plugins.forEach (C:\Users\Jason Werber\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:103:7)
    at Array.forEach (<anonymous>)
    at new Generator (C:\Users\Jason Werber\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:101:13)
    at Creator.create (C:\Users\Jason Werber\AppData\Roaming\npm\node_modules\@vue\cli\lib\Creator.js:161:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by sodatea** [comment]
Fixed in v4.0.1. But I do recommend you upgrade your `@vue/cli` to v4 for the best experience.
