### ISSUE TITLE
_schema.then is not a function after upgrading

### ISSUE THREAD

**Issue by alex88** [vuejs/vue-cli#4721]
### Version
4.0.4

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0
    Safari: 13.0.2
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Run `vue ui`

### What is expected?
Starts the UI

### What is actually happening?
Output is
```
🚀  Starting GUI...
 ERROR  TypeError: _schema.then is not a function
TypeError: _schema.then is not a function
    at new ApolloServerBase (/Users/alex/.config/yarn/global/node_modules/apollo-server-core/dist/ApolloServer.js:209:46)
    at new ApolloServer (/Users/alex/.config/yarn/global/node_modules/apollo-server-express/dist/ApolloServer.js:59:9)
    at module.exports (/Users/alex/.config/yarn/global/node_modules/vue-cli-plugin-apollo/graphql-server/index.js:141:18)
    at ui (/Users/alex/.config/yarn/global/node_modules/@vue/cli/lib/ui.js:52:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

---
I've tried to remove `.vue-cli-ui` and `.vuerc` but the error still persists

**Comment by tpodom** [comment]
I ran into this as well in a project that was configured to use Apollo Server.  I was able to install a matching version of graphql package (14.5.8) and then remove the nested node_modules/vue-cli-plugin-apollo/node_modules/graphql package.

**Comment by shazha** [comment]
I fixed it by upgrading yarn to v1.22

**Comment by robsonsobral** [comment]
To update yarn isn't enough for me.

**Comment by robsonsobral** [comment]
I manually delete yarn folder, restart the computer, and `npm install --global --production windows-build-tools`

**Comment by Tim152** [comment]
the same problem, waiting for answer

**Comment by silvio-e** [comment]
I completely uninstalled vue-cli from my machine and installed it again. The error disappeared but then I got a version mismatch with the vue-template-compiler.

For solving this I deleted the `node_modules` folder in `/Users/myuser/.config/yarn/global/` and the `yarn.lock` and then did a `yarn global add @vue/cli` again.

So the last step alone could already do the trick I guess :D

```
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 73.0
    Safari: 13.0.5
```

**Comment by sodatea** [comment]
I'm not exactly sure what causes this issue. But it seems to be caused by `graphql` version mismatch according to https://github.com/apollographql/apollo-server/issues/3381.
Because of dependency hoisting by various other packages, such issues happens more often when the package is installed globally.

So it's worth trying to delete the global `node_modules` folder and reinstall.
