### ISSUE TITLE
Upgrade results in conflict with vue and vue-template-compiler from vue-jscodeshift-adapter

### ISSUE THREAD

**Issue by dolbex** [vuejs/vue-cli#4722]
### Version
4.0.4

### Environment info
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 67.0
    Safari: 13.0.2
  npmGlobalPackages:
    @vue/cli: 3.5.5

```

### Steps to reproduce
Tried upgrading from 3.x (sorry, unsure where I was previously) to 4.0.4
Also removed and reinstalled globally

Ran vue ui

### What is expected?
Vue UI initializes

### What is actually happening?
I'm getting the following output

```
Vue packages version mismatch:

- vue@2.5.17 (/Users/dolbex/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/dolbex/.config/yarn/global/node_modules/vue-jscodeshift-adapter/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

/Users/dolbex/.config/yarn/global/node_modules/vue-jscodeshift-adapter/node_modules/vue-template-compiler/index.js:1
Error:

Vue packages version mismatch:

- vue@2.5.17 (/Users/dolbex/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/dolbex/.config/yarn/global/node_modules/vue-jscodeshift-adapter/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/dolbex/.config/yarn/global/node_modules/vue-jscodeshift-adapter/node_modules/vue-template-compiler/index.js:10:9)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
```

---
Yarn lock has the following:

```

vue-jscodeshift-adapter@^2.0.2:
  version "2.0.2"
  resolved "https://registry.yarnpkg.com/vue-jscodeshift-adapter/-/vue-jscodeshift-adapter-2.0.2.tgz#67824b360ad84d06f5200f5269ad419a947e7e97"
  integrity sha512-EnRKDgQXGHnNbHpHdTEqBfDMxRPFSUc/hlDNLd9ucgdfpJ3S6o/V6og CfNYgGPO2GKD6AQOsd lltRuoM/SVA==
  dependencies:
    cheerio "^1.0.0-rc.2"
    detect-indent "^6.0.0"
    indent-string "^4.0.0"
    vue-sfc-descriptor-to-string "^1.0.0"
    vue-template-compiler "^2.5.13"


vue-loader@^15.4.2:
  version "15.4.2"
  resolved "https://registry.yarnpkg.com/vue-loader/-/vue-loader-15.4.2.tgz#812bb26e447dd3b84c485eb634190d914ce125e2"
  dependencies:
    "@vue/component-compiler-utils" "^2.0.0"
    hash-sum "^1.0.2"
    loader-utils "^1.1.0"
    vue-hot-reload-api "^2.3.0"
    vue-style-loader "^4.1.0"

vue-template-compiler@^2.5.13:
  version "2.6.10"
  resolved "https://registry.yarnpkg.com/vue-template-compiler/-/vue-template-compiler-2.6.10.tgz#323b4f3495f04faa3503337a82f5d6507799c9cc"
  integrity sha512-jVZkw4/I/HT5ZMvRnhv78okGusqe0 qH2A0Em0Cp8aq78 NK9TII263CDVz2QXZsIT yyV/gZc/j/vlwa Epyg==
  dependencies:
    de-indent "^1.0.2"
    he "^1.1.0"

vue-template-compiler@^2.5.17:
  version "2.5.17"
  resolved "https://registry.yarnpkg.com/vue-template-compiler/-/vue-template-compiler-2.5.17.tgz#52a4a078c327deb937482a509ae85c06f346c3cb"
  dependencies:
    de-indent "^1.0.2"
    he "^1.1.0"

vue-template-es2015-compiler@^1.6.0:
  version "1.6.0"
  resolved "https://registry.yarnpkg.com/vue-template-es2015-compiler/-/vue-template-es2015-compiler-1.6.0.tgz#dc42697133302ce3017524356a6c61b7b69b4a18"

vue@^2.5.17:
  version "2.5.17"
  resolved "https://registry.yarnpkg.com/vue/-/vue-2.5.17.tgz#0f8789ad718be68ca1872629832ed533589c6ada"
```

**Comment by sodatea** [comment]
Not likely caused by the fresh install.

`vue-template-compiler@^2.5.13` & `vue-template-compiler@^2.5.17`, if they are installed at the same time, package managers are very likely to dedupe them and resolve to the latest `2.6.10`.

It is possible that you have accidentally globally installed `vue` & `vue-template-compiler` in the past. Could you try `yarn global remove vue vue-template-compiler` and then try again?

**Comment by dolbex** [comment]
@sodatea - appreciate the response. I did figure that might be the case but looked in the global yarn.lock with nothing in there. Went ahead and ran the command for giggles:

```
yarn global remove vue-template-compiler     
yarn global v1.19.1
[1/2] 🗑  Removing module vue-template-compiler...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

yarn global remove vue                                                                                                                                                       
yarn global v1.19.1
[1/2] 🗑  Removing module vue...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by dolbex** [comment]
Ok, I also double checked and made sure it wasn't installed with NPM - it was. I uninstalled that sucker and also from yarn global to try fresh. Installed in yarn.... no go. installed through npm -g and it worked.... whatever... I'm sure it's just something gross on my end.

**Comment by langlangbody** [comment]
I also have this problem. I try to run `npm install vue -g`it  work
