### ISSUE TITLE
Babel v3 to v4 Migration Fails

### ISSUE THREAD

**Issue by jforlenza-bnydc** [vuejs/vue-cli#4753]
### Version
4.0.5

### Reproduction link
[https://github.com/gtalarico/django-vue-template](https://github.com/gtalarico/django-vue-template)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Binaries:
    Node: 12.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.7 => 0.1.7
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.12.1
    @vue/cli-plugin-babel: ~3.12.1 => 3.12.1
    @vue/cli-plugin-eslint: ~3.12.1 => 3.12.1
    @vue/cli-service: ~3.12.1 => 3.12.1
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    bootstrap-vue: ^2.0.1 => 2.0.1
    eslint-plugin-vue:  4.7.1
    portal-vue:  2.1.6
    vue: ^2.5.17 => 2.6.10
    vue-cli-webpack:  1.0.0
    vue-clipboard2: ^0.3.1 => 0.3.1
    vue-eslint-parser:  2.0.3
    vue-functional-data-merge:  3.1.0
    vue-headful: ^2.0.1 => 2.0.1
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-router: ^3.0.1 => 3.1.3
    vue-select: ^3.2.0 => 3.2.0
    vue-style-loader:  4.1.2
    vue-svg-inline-loader: ^1.3.3 => 1.3.3
    vue-template-compiler: ^2.5.17 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vue-the-mask: ^0.11.1 => 0.11.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
Run vue upgrade

### What is expected?
Vue to upgrade to v4

### What is actually happening?
Getting error for babel migration,   

```
�  Running migrator of @vue/cli-plugin-babel
 ERROR  TypeError: Received an unexpected value [object Undefined]
TypeError: Received an unexpected value [object Undefined]
    at fromAST (C:\Users\jforlenza\AppData\Local\Yarn\Data\global\node_modules\jscodeshift\src\core.js:72:9)
    at core (C:\Users\jforlenza\AppData\Local\Yarn\Data\global\node_modules\jscodeshift\src\core.js:47:5)
    at module.exports (C:\Users\jforlenza\WebstormProjects\django-vue-template\node_modules\@vue\cli-plugin-babel\codemods\usePluginPreset.js:3:16)
    at newTransform (C:\Users\jforlenza\AppData\Local\Yarn\Data\global\node_modules\vue-jscodeshift-adapter\src\jscodeshift-mode.js:9:14)
    at runCodemod (C:\Users\jforlenza\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\util\runCodemod.js:5:26)
    at C:\Users\jforlenza\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\GeneratorAPI.js:338:21
    at Migrator.resolveFiles (C:\Users\jforlenza\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\Generator.js:261:13)
    at Migrator.generate (C:\Users\jforlenza\AppData\Local\Yarn\Data\global\node_modules\@vue\cli\lib\Generator.js:168:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by sodatea** [comment]
Move the `babel` config in `package.json` to a separate `babel.config.js`.

I thought all projects generated by Vue CLI with the babel plugin should have the `babel.config.js` file (see the code below) so I assume its presence when writing the migrator.

https://github.com/vuejs/vue-cli/blob/17925c6ae643608853d43bb413ceccc4b8a1bd6b/packages/%40vue/cli/lib/Generator.js#L211-L214

**Comment by jforlenza-bnydc** [comment]
Thank you, that worked 👍

**Comment by AlexWayfer** [comment]
It's failing for me with `.babelrc`.

**Comment by AlexWayfer** [comment]
And with `babel.config.json`. I don't see `babel.config.js` in https://babeljs.io/docs/en/configuration

**Comment by AlexWayfer** [comment]
I found syntax with `module.exports`, but it's so ugly… OK, but migrator is not good enough and issue somewhy closed.

**Comment by industral** [comment]
not sure why issue was closed, it hasn't been fixed yet. If somebody has the same issue - just move your `.babelrc` to `babel.config.js`.

It should contain something like:

```
module.exports = {
  "presets": [
    "@vue/app"
  ]
};
```
