### ISSUE TITLE
使用vue ui来创建远程preset的时候不会在图形界面上出现prompts选项

### ISSUE THREAD

**Issue by F-happy** [vuejs/vue-cli#4813]
### Version
4.0.5

### Environment info
```
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.87
    Firefox: 69.0.3
    Safari: 13.0.3
  npmGlobalPackages:
    @vue/cli: 4.0.5
```

### Steps to reproduce
1、使用vue ui来创建项目。
2、选择远程preset

### What is expected?
使用vue ui来创建远程preset的时候会在图形界面上出现prompts选项

### What is actually happening?
并没有任何显示，需要我在命令行里手动回车才会继续

**Comment by birender** [comment]
Hi
Vue command not recongized in command prompt after successfully install vue
OS : Window 10 Home Edition 64 Bit
Error on Command Prompt

is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Users\Birender \node_modules\@vue\cli\bin\vue.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

Thanks
