### ISSUE TITLE
Css Manification Failed

### ISSUE THREAD

**Issue by CalmAndCoDe** [vuejs/vue-cli#4823]
### Version
3.12.1

### Environment info
```
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
  Binaries:
    Node: 10.16.2 - /usr/bin/node
    Yarn: Not Found
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  4.0.5 
    @vue/babel-preset-jsx:  1.1.1 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.1.1 
    @vue/babel-sugar-v-on:  1.1.0 
    @vue/cli-overlay:  4.0.5 
    @vue/cli-plugin-babel: ^4.0.0 => 4.0.5 
    @vue/cli-plugin-eslint: ^4.0.0 => 4.0.5 
    @vue/cli-plugin-pwa: ^4.0.0 => 4.0.5 
    @vue/cli-plugin-router:  4.0.5 
    @vue/cli-plugin-unit-mocha: ^4.0.0 => 4.0.5 
    @vue/cli-plugin-vuex:  4.0.5 
    @vue/cli-service: ^4.0.0 => 4.0.5 
    @vue/cli-shared-utils:  4.0.5 
    @vue/component-compiler-utils:  3.0.0 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.7.1 
    vue-meta: ^2.3.1 => 2.3.1 
    vue-router: ^3.1.3 => 3.1.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.1 
  npmGlobalPackages:
    @vue/cli: 3.3.0
```

### Steps to reproduce

Error: CSS minification error: Cannot read property 'type' of undefined. File: css/app.a2e8f177.css
Error: CSS minification error: Cannot read property 'type' of undefined. File: css/app.a2e8f177.css
    at /home/username/Documents/pubg-afg/node_modules/@intervolga/optimize-cssnano-plugin/index.js:106:21

### What is expected?
hello, i recently tried to build my vue app but i get this error, it only shows in production build.

### What is actually happening?

Error: CSS minification error: Cannot read property 'type' of undefined. File: css/app.a2e8f177.css
Error: CSS minification error: Cannot read property 'type' of undefined. File: css/app.a2e8f177.css
    at /home/username/Documents/pubg-afg/node_modules/@intervolga/optimize-cssnano-plugin/index.js:106:21

**Comment by CalmAndCoDe** [comment]
deplicate #3415
