### ISSUE TITLE
the problem of using yarn to install the vue

### ISSUE THREAD

**Issue by moshuying** [vuejs/vue-cli#4864]
### Version
4.0.5

### Environment info
```

Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue create newApp

### What is expected?
Initialize a project

### What is actually happening?
command failed: yarn --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist

---
Npm installed,
yarn  installed,
all use default,
then `command failed: yarn --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist`

**Comment by sodatea** [comment]
Are there any more specific error logs?
Also, I don't think we support project names with uppercase letters.

**Comment by moshuying** [comment]
Sorry, character capitalization is my mistake. I'm more used to using hump variable names.
I tried to solve the problem,open `.vuerc` ,change `"packageManager": "yarn"`to`"packageManager": "npm"`,No more tips on this question.
I'm going to step back and step back. Now, the new error log is as follows
```
(base) PS E:\> vue create test


Vue CLI v3.12.0
┌───────────────────────────┐
│  Update available: 4.0.5  │
└───────────────────────────┘
? Please pick a preset: Now (vue-router, vuex, node-sass, babel, pwa, eslint, unit-mocha, e2e-cypress)


Vue CLI v3.12.0
✨  Creating project in E:\test.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

yarn install v1.13.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success Saved lockfile.
Done in 29.52s.
🚀  Invoking generators...
📦  Installing additional dependencies...
[-/7] ⠁ waiting...
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error E:\test\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: E:\test\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe E:\test\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\test\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.10.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\test\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\test\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\test\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\test\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\test\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\test\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:169:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\test\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\test\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\test\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\test\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\test\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\test\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:169:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (E:\\test\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (E:\\test\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (E:\\test\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at E:\\test\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at E:\\test\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at E:\\test\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:169:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python D:\ProgramData\Anaconda3\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: D:\ProgramData\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\test\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\test\node_modules\node-sass
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 ERROR  command failed: yarn --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist
(base) PS E:\>
```

**Comment by sodatea** [comment]
1. You were using an old version of @vue/cli; it's recommended to upgrade to the latest;
2. It's because you were installing node-sass and the url that hosts the binary package is blocked in China, so it fell back to compile locally, which, requires node-gyp & python2, which is not installed on your computer, thus the error;

---

So the solution is simple:
Either choose the Dart Sass option, which does not require a binary package to be downloaded, or use @vue/cli v4.1.0, which automatically switches to the mirror website in China when installing binary packages for users.

**Comment by abdallah-abozaid** [comment]
As per the error it's trying to find yarn's config file in node_modules. You does not have yarn packageManager installed in your system I believe

Try this: vue config -s packageManager npm

and re-run: vue create
