### ISSUE TITLE
TypeError when installing new plugin using vue ui

### ISSUE THREAD

**Issue by aligoren** [vuejs/vue-cli#4907]
### Version
3.4.0

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.19 Manjaro Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz
  Binaries:
    Node: 11.9.0 - ~/.nvm/versions/node/v11.9.0/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v11.9.0/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v11.9.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 69.0.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.1.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.1.1 
    @vue/cli-plugin-babel: ^4.1.0 => 4.1.1 
    @vue/cli-plugin-eslint: ^4.1.0 => 4.1.1 
    @vue/cli-plugin-router:  4.1.1 
    @vue/cli-plugin-vuex:  4.1.1 
    @vue/cli-service: ^4.1.0 => 4.1.1 
    @vue/cli-shared-utils:  4.1.1 
    @vue/component-compiler-utils:  3.0.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.7.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.4.0


```

### Steps to reproduce
1-) I visited plugins page [http://localhost:8000/plugins](http://localhost:8000/plugins)

2-) I saw the vue-router and vuex plugins as installable plugins.

3-) I clicked the **Add vue-router** button.

4-) I saw error messages like below;

```error
TypeError: Cannot read property 'routerHistoryMode' of undefined
    at module.exports (/home/opcode/Projects/vue-projeleri/admin-panel/node_modules/@vue/cli-service/generator/router.js:3:26)
    at Generator.plugins.forEach (/home/opcode/.nvm/versions/node/v11.9.0/lib/node_modules/@vue/cli/lib/Generator.js:103:7)
    at Array.forEach (<anonymous>)
    at new Generator (/home/opcode/.nvm/versions/node/v11.9.0/lib/node_modules/@vue/cli/lib/Generator.js:101:13)
    at Function.runGenerator (/home/opcode/.nvm/versions/node/v11.9.0/lib/node_modules/@vue/cli/lib/invoke.js:116:21)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

### What is expected?
It should install vue-router without any problem.

### What is actually happening?
I couldn't install vue-router using UI. It thrown an error.

**Comment by aligoren** [comment]
Considering #4906 I'll close this issue. Because my problem was solved.
