### ISSUE TITLE
Jest not working on Windows 10 on new project

### ISSUE THREAD

**Issue by alexanderVu** [vuejs/vue-cli#4939]
### Version
4.1.1

### Reproduction link
[https://github.com/alexanderVu/windumbo](https://github.com/alexanderVu/windumbo)

### Environment info
```
Windows 10 1809
```

### Steps to reproduce
Install vue cli on windows 10. Use pwa, vuex, router, unit tests (jest). Run npm run test:unit after installation.

### What is expected?
The test shoud run.

### What is actually happening?
 vue-cli-service test:unit
● Validation Error:

  Preset @vue/cli-plugin-unit-jest is invalid:

  The "id" argument must be of type string. Received type object
  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at validateString (internal/validators.js:107:11)
    at Module.require (internal/modules/cjs/loader.js:659:3)
    at require (internal/modules/cjs/helpers.js:16:16)
    at setupPreset (Z:\Projects\windumbo\node_modules\jest-config\build\normalize.js:230:14)
    at normalize (Z:\Projects\windumbo\node_modules\jest-config\build\normalize.js:554:15)
    at readConfig (Z:\Projects\windumbo\node_modules\jest-config\build\index.js:163:46)
    at readConfigs (Z:\Projects\windumbo\node_modules\jest-config\build\index.js:373:26)
    at Z:\Projects\windumbo\node_modules\@jest\core\build\cli\index.js:155:58
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (Z:\Projects\windumbo\node_modules\@jest\core\build\cli\index.js:108:24)

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

error Command failed with exit code 1.

**Comment by sodatea** [comment]
Seems an upstream issue https://github.com/facebook/jest/issues/8763
