### ISSUE TITLE
利用 api.render delete src/ 后渲染新的 src/ 报错

### ISSUE THREAD

**Issue by zoux** [vuejs/vue-cli#4970]
### Version
4.1.1

### Reproduction link
[https://github.com/zoux/vue-preset/tree/feature/vue-cli-4.x](https://github.com/zoux/vue-preset/tree/feature/vue-cli-4.x)

### Environment info
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Binaries:
    Node: 10.15.3 - /usr/local/opt/node@10/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
  Browsers:
    Chrome: 79.0.3945.79
    Firefox: Not Found
    Safari: 12.1.1
  npmGlobalPackages:
    @vue/cli: 4.1.1
```

### Steps to reproduce
在根目录执行 vue create --preset ./ app 来利用本地 perset.json 创建项目，generator 流程中报错。

### What is expected?
能正确渲染：
api.render(files => {
    Object.keys(files)
      .filter(path => ['src/', 'tsconfig.json', 'tslint.json'].some(keyword => path.includes(keyword)))
      .forEach(path => delete files[path])
  })

api.render('./template/default')

### What is actually happening?
generator 流程中报错：
SyntaxError: Identifier 'router' has already been declared (9:7)
    at Object.raise (/usr/local/lib/node_modules/@vue/cli/node_modules/_@babel_parser@7.7.5@@babel/parser/lib/index.js:6983:17)
    at ScopeHandler.checkRedeclarationInScope (/usr/local/lib/node_modules/@vue/cli/node_modules/_@babel_parser@7.7.5@@babel/parser/lib/index.js:4259:12)
    at ScopeHandler.declareName (/usr/local/lib/node_modules/@vue/cli/node_modules/_@babel_parser@7.7.5@@babel/parser/lib/index.js:4225:12)
    at Object.checkLVal (/usr/local/lib/node_modules/@vue/cli/node_modules/_@babel_parser@7.7.5@@babel/parser/lib/index.js:8811:22)
    at Object.checkLVal (/usr/local/lib/node_modules/@vue/cli/node_modules/_@babel_parser@7.7.5@@babel/parser/lib/index.js:376:15)
    at Object.parseImportSpecifierLocal (/usr/local/lib/node_modules/@vue/cli/node_modules/_@babel_parser@7.7.5@@babel/parser/lib/index.js:12023:10)
    at Object.maybeParseDefaultImportSpecifier (/usr/local/lib/node_modules/@vue/cli/node_modules/_@babel_parser@7.7.5@@babel/parser/lib/index.js:12029:12)
    at Object.parseImport (/usr/local/lib/node_modules/@vue/cli/node_modules/_@babel_parser@7.7.5@@babel/parser/lib/index.js:12000:31)
    at Object.parseStatementContent (/usr/local/lib/node_modules/@vue/cli/node_modules/_@babel_parser@7.7.5@@babel/parser/lib/index.js:10764:27)
    at Object.parseStatement (/usr/local/lib/node_modules/@vue/cli/node_modules/_@babel_parser@7.7.5@@babel/parser/lib/index.js:10666:17)

**Comment by zoux** [comment]
在 vue cli 3.x 时，曾提过一次 [iisue](https://github.com/vuejs/vue-cli/issues/2470) 并实现了这种功能。

但更新为 vue cli 4.x 后，就报错了。

**Comment by sodatea** [comment]
直接原因是 delete 了文件之后对应的 render 回调仍然会存在，所以执行到这里时报错了……
https://github.com/vuejs/vue-cli/blob/00acca5f14be9f69b763ba4b755c6290368cae2c/packages/%40vue/cli-plugin-router/generator/index.js#L2-L3

我得想想怎么处理这种场景……

**Comment by fangbinwei** [comment]
只要不使用官方的router和vuex的插件就行了吧? @zoux  因为你有自己的模板, 这两个插件对你的作用只是往`package.json`中添加`vue-router`和`vuex`依赖?
