### ISSUE TITLE
使用cli工具创建electron-vue App，运行时报错

### ISSUE THREAD

**Issue by xxxxxccc** [vuejs/vue-cli#503]
$ npm run app

> toeflpc@0.1.0 app F:\project\newToefl\toeflpc
> cross-env NODE_ENV=development electron app/

Reading F:\project\newToefl\toefl\node_modules\devtron\manifest.json failed.
Error: ENOENT: no such file or directory, open 'F:\project\newToefl\toefl\node_m                                                                                                                                                                                               odules\devtron\manifest.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20                                                                                                                                                                                               )
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at getManifestFromPath (F:\project\newToefl\toeflpc\node_modules\_electron@1                                                                                                                                                                                               .6.11@electron\dist\resources\electron.asar\browser\chrome-extension.js:34:26)
    at App.<anonymous> (F:\project\newToefl\toeflpc\node_modules\_electron@1.6.1                                                                                                                                                                                               1@electron\dist\resources\electron.asar\browser\chrome-extension.js:363:26)
    at Object.onceWrapper (events.js:290:19)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

**Comment by egoist** [comment]
Please reopen this issue in the actual template repo you use.
