### ISSUE TITLE
absolute path to loader in webpack config

### ISSUE THREAD

**Issue by jbuhacoff** [vuejs/vue-cli#5049]
### Version
4.1.2

### Environment info
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
  Binaries:
    Node: 12.10.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.7 => 0.1.7
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.1.2
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.2
    @vue/cli-plugin-babel: ^4.0.5 => 4.1.2
    @vue/cli-plugin-e2e-nightwatch: ^4.0.5 => 4.1.2
    @vue/cli-plugin-eslint: ^4.0.5 => 4.1.2
    @vue/cli-plugin-pwa: ^4.0.5 => 4.1.2
    @vue/cli-plugin-router:  4.1.2
    @vue/cli-plugin-unit-mocha: ^4.0.5 => 4.1.2
    @vue/cli-plugin-vuex:  4.1.2
    @vue/cli-service: ^4.0.5 => 4.1.2
    @vue/cli-shared-utils:  4.1.2
    @vue/component-compiler-utils:  3.1.1
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.1
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.2.3 => 5.2.3
    eslint-plugin-vuetify: ^1.0.0-beta.5 => 1.0.0-beta.5
    vue: ^2.6.10 => 2.6.10
    vue-cli-plugin-vuetify: ^1.1.1 => 1.1.2
    vue-cli-webpack:  1.0.0
    vue-eslint-parser:  undefined (5.0.0)
    vue-gravatar: ^1.3.1 => 1.3.1
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.8.3
    vue-router: ^3.1.3 => 3.1.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuetify: ^2.1.6 => 2.2.1
    vuetify-loader: ^1.3.0 => 1.3.0
    vuex: ^3.1.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: 4.1.2

```

### Steps to reproduce
export NODE_ENV=production && vue-cli-service build

### What is expected?
Build success.

Also, output of "vue inspect" shows this configuration block for vue-loader:

```
          /* config.module.rule('vue').use('vue-loader') */
          {
            loader: 'vue-loader',
            options: { ... }
          }
```

### What is actually happening?
Build fails with the following error message:

```
[VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (/tmp/test-app/node_modules/vuetify-loader/lib/plugin.js:18:13)
    at webpack (/tmp/test-app/node_modules/webpack/lib/webpack.js:51:13)
    at /tmp/test-app/node_modules/@vue/cli-service/lib/commands/build/index.js:192:5
    at new Promise (<anonymous>)
    at build (/tmp/test-app/node_modules/@vue/cli-service/lib/commands/build/index.js:191:10)
    at async /tmp/test-app/node_modules/@vue/cli-service/lib/commands/build/index.js:88:7
npm ERR! code ELIFECYCLE
```

Also, output of "vue inspect" shows this configuration block for vue-loader:

```
          /* config.module.rule('vue').use('vue-loader') */
          {
            loader: '/tmp/test-app/node_modules/vue-loader/lib/index.js',
            options: { ... }
          }
```

---
This error happens when using @vue/cli-service version 4.1.2.  It did not happen with an earlier version 4.0.5.  Downgrading from 4.1.2 to 4.0.5 resolved the issue. I noticed that the "vue-loader" rule generated by version 4.1.2 uses the full path to the vue-loader module instead of the module name "vue-loader".  That seems to be directly related to the error message "No matching rule for vue-loader found".

I tried reproducing the issue with a new project like this:

```
vue create test-app
cd test-app/
vue add vuetify
npm run build
vue inspect
```

But it is working with version 4.1.2 and the full path to the vue-loader instead of just "vue-loader" in the webpack config.

**Comment by sodatea** [comment]
It's a bug in old versions of `vuetify-loader`. Please upgrade it to the latest.

**Comment by jbuhacoff** [comment]
Upgrading to vuetify-loader 1.4.3 fixed this for me. Thanks!
