### ISSUE TITLE
After using the 'vue init webpack' to initialize the project, 'npm install' is reporting

### ISSUE THREAD

**Issue by tudoubang** [vuejs/vue-cli#506]
### After using the 'vue init webpack' to initialize the project, 'npm install' is reporting

```
$ npm i                                                         
npm ERR! Unexpected end of input at 1:45424
npm ERR! rg/autoprefixer/-/autoprefixer-6.0.0.tgz"},"_hasShrinkwrap":false},"6
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lethe/.npm/_logs/2017-06-22T03_24_45_936Z-debug.log
```
### node

```
$node -v
v8.1.2
```
### npm

```
$ npm -v
5.0.3
```

### log

```
2153 silly resolveWithNewModule webpack-merge@4.1.0 checking installable status
2154 verbose stack SyntaxError: Unexpected end of input at 1:45424
2154 verbose stack rg/autoprefixer/-/autoprefixer-6.0.0.tgz"},"_hasShrinkwrap":false},"6
2154 verbose stack                                                                      ^
2154 verbose stack     at Object.parseJSON (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
2154 verbose stack     at parse (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
2154 verbose stack     at consumeBody.call.then.buffer (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
2154 verbose stack     at <anonymous>
2154 verbose stack     at process._tickCallback (internal/process/next_tick.js:169:7)
2155 verbose cwd /home/lethe/work/admin-template
2156 verbose Linux 4.10.0-22-generic
2157 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
2158 verbose node v8.1.2
2159 verbose npm  v5.0.3
2160 error Unexpected end of input at 1:45424
2160 error rg/autoprefixer/-/autoprefixer-6.0.0.tgz"},"_hasShrinkwrap":false},"6
2160 error                                                                      ^
2161 verbose exit [ 1, true ]
"~/.npm/_logs/2017-06-22T03_24_45_936Z-debug.log" 2185L, 168133C                                                                                                                                 2151,1       
```
@yyx990803 
@egoist

**Comment by posva** [comment]
Looks to be fixed with a later release of autoprefixer
