### ISSUE TITLE
vue-cli-service test:e2e won't work

### ISSUE THREAD

**Issue by mg98** [vuejs/vue-cli#5169]
### Version
4.2.2

### Reproduction link
[https://github.com/mg98/Minimal-Reproduction-for-Issue](https://github.com/mg98/Minimal-Reproduction-for-Issue)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
    Safari: 13.0.4
  npmPackages:
    @chenfengyuan/vue-countdown: ^1.1.4 => 1.1.4 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.1.2 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.1.2 
    @vue/cli-plugin-babel: ^4.1.2 => 4.1.2 
    @vue/cli-plugin-e2e-cypress: ^4.2.2 => 4.2.2 
    @vue/cli-plugin-eslint: ^4.1.2 => 4.1.2 
    @vue/cli-plugin-router:  4.1.2 
    @vue/cli-plugin-unit-mocha: ^4.1.2 => 4.1.2 
    @vue/cli-plugin-vuex:  4.1.2 
    @vue/cli-service: ^4.1.2 => 4.1.2 
    @vue/cli-shared-utils:  4.1.2 (4.2.2)
    @vue/component-compiler-utils:  3.1.1 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    eslint-plugin-vue: ^6.1.2 => 6.1.2 
    typescript:  3.7.2 
    vue: ^2.6.11 => 2.6.11 (2.3.3)
    vue-acl: 4.1.7 => 4.1.7 
    vue-apexcharts: ^1.5.1 => 1.5.1 
    vue-apollo: ^3.0.2 => 3.0.2 
    vue-awesome-swiper: ^3.1.3 => 3.1.3 
    vue-backtotop: ^1.6.1 => 1.6.1 
    vue-class-component:  7.1.0 
    vue-cli-plugin-apollo: ^0.21.3 => 0.21.3 
    vue-clickaway:  2.2.2 
    vue-clipboard2: ^0.3.1 => 0.3.1 
    vue-context: ^5.0.0 => 5.0.0 
    vue-echarts: ^4.1.0 => 4.1.0 
    vue-eslint-parser:  2.0.3 (7.0.0)
    vue-feather-icons: ^5.0.0 => 5.0.0 
    vue-flatpickr-component: ^8.1.5 => 8.1.5 
    vue-form-wizard: ^0.8.4 => 0.8.4 
    vue-fullcalendar: ^1.0.9 => 1.0.9 
    vue-hot-reload-api:  2.3.4 
    vue-i18n: ^8.15.3 => 8.15.3 
    vue-instantsearch: ^2.6.0 => 2.6.0 
    vue-loader:  15.8.3 
    vue-perfect-scrollbar: ^0.2.1 => 0.2.1 
    vue-prism-component: ^1.1.1 => 1.1.1 
    vue-property-decorator: ^8.3.0 => 8.3.0 
    vue-quill-editor: ^3.0.6 => 3.0.6 
    vue-router: ^3.1.3 => 3.1.3 
    vue-select: ^3.4.0 => 3.4.0 
    vue-simple-calendar: ^4.3.2 => 4.3.2 
    vue-simple-suggest: ^1.10.1 => 1.10.1 
    vue-star-rating: ^1.6.1 => 1.6.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vue-tour: ^1.2.0 => 1.2.0 
    vue-tree-halower: ^1.8.3 => 1.8.3 
    vue-video-player: ^5.0.2 => 5.0.2 
    vue2-google-maps: ^0.10.7 => 0.10.7 
    vue2-hammer: ^2.1.2 => 2.1.2 
    vuecode.js: 0.0.27 => 0.0.27 
    vuedraggable: ^2.23.2 => 2.23.2 
    vuejs-datepicker: ^1.6.2 => 1.6.2 
    vuelidate: ^0.7.4 => 0.7.4 
    vuesax: ^3.11.5 => 3.11.5 
    vuex: ^3.1.2 => 3.1.2 
  npmGlobalPackages:
    @vue/cli: 4.1.1

```

### Steps to reproduce
Run `vue-cli-service test:e2e`.

### What is expected?
Cypress e2e tests should run in headless mode.

### What is actually happening?
I am getting this error message:
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '@vue/cli-plugin-e2e-cypress'
Require stack:
- /usr/local/lib/node_modules/@vue/cli-service/lib/Service.js
- /usr/local/lib/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at idToPlugin (/usr/local/lib/node_modules/@vue/cli-service/lib/Service.js:150:14)
    at /usr/local/lib/node_modules/@vue/cli-service/lib/Service.js:189:20
    at Array.map (<anonymous>)
    at Service.resolvePlugins (/usr/local/lib/node_modules/@vue/cli-service/lib/Service.js:175:10)
    at new Service (/usr/local/lib/node_modules/@vue/cli-service/lib/Service.js:34:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli-service/bin/vue-cli-service.js:16:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@vue/cli-service/lib/Service.js',
    '/usr/local/lib/node_modules/@vue/cli-service/bin/vue-cli-service.js'
  ]
}
```

---
It is actually working with command `cypress run` and I would have expected the vue cli command to do the same.

**Comment by jdvegmond** [comment]
Have you tried "npm run test:e2e"? In my project that works fine.

Actually, "vue-cli-service test:e2e" as is in your package.json will (should) run the Cypress Runner. If you want to run in headless mode, you should use "vue-cli-service test:e2e --headless".

**Comment by sodatea** [comment]
It's `npm run test:e2e`.

Seems you mistakenly installed the `@vue/cli-service` package globally and ran the wrong command.

**Comment by mg98** [comment]
My `package.json` is configured to run `vue-cli-service test:e2e` on `npm run test:e2e`, just like `npm run test:unit` executes `vue-cli-service test:unit --recursive ....` (which _does_ work for me!) and I think it's like that for you too! Or isn't it? I see Vue example projects that also use the `vue-cli-service` command to build and serve too. And isn't a cli library supposed to be installed globally to be able to be run on the command line?

To clarify: `npm run test:e2e` gives me the very same output and error.

Thanks so far.

**Comment by sodatea** [comment]
Please provide the error log of `npm run test:e2e`.

The error log in the original post doesn't look right unless your project locates under `/usr/local/lib`, which, typically, is the place where npm installs its global packages.

Plus, the reproduction repo isn't even runnable.
