### ISSUE TITLE
npm install -g vue-cli returns EINTEGRITY error

### ISSUE THREAD

**Issue by coderpradp** [vuejs/vue-cli#521]
I'm using Windows 10 pro x64.
Command: npm install -g vue-cli
Error:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: postcss@6.0.6 (node_modules\vue-cli\node_modules\postcss-modules-local-by-default\node_modules\postcss):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Invoker\AppData\Roaming\npm\node_modules\.staging\postcss-65fe55b6\lib\lazy-result.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: seek-bzip@1.0.5 (node_modules\vue-cli\node_modules\seek-bzip):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Invoker\AppData\Roaming\npm\node_modules\.staging\seek-bzip-5b219872\lib\crc32.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: postcss@6.0.6 (node_modules\vue-cli\node_modules\postcss-modules-values\node_modules\postcss):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Invoker\AppData\Roaming\npm\node_modules\.staging\postcss-da86ffc9\lib\lazy-result.js'

npm ERR! code EINTEGRITY
npm ERR! sha1-gv+wKynmYq5TvcIK8VlHcGc5xTY= integrity checksum failed when using sha1: wanted sha1-gv+wKynmYq5TvcIK8VlHcGc5xTY= but got sha1-r97SxQOIiJ+Tuz4zzKkoJmK7gvk=. (496683 bytes)
```

Here is the log:
```
........................
12734 silly pacote trying relateurl@https://registry.npmjs.org/relateurl/-/relateurl-0.2.7.tgz by hash: sha1-VNvzd+UUQKypCkzSdGANP/LYiKk=
12735 silly pacote data for sha1-VNvzd+UUQKypCkzSdGANP/LYiKk= not present. Using manifest.
12736 http fetch GET 200 https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz 34752ms
12737 silly pacote tunnel-agent@https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz extracted in 34752ms
12738 verbose unlock done using C:\Users\Invoker\AppData\Roaming\npm-cache\_locks\staging-16c90dc88c762147.lock for C:\Users\Invoker\AppData\Roaming\npm\node_modules\.staging
12739 warn optional SKIPPING OPTIONAL DEPENDENCY: postcss@6.0.6 (node_modules\vue-cli\node_modules\postcss-modules-local-by-default\node_modules\postcss):
12740 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Invoker\AppData\Roaming\npm\node_modules\.staging\postcss-65fe55b6\lib\lazy-result.js'
12741 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
12741 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
12742 warn optional SKIPPING OPTIONAL DEPENDENCY: seek-bzip@1.0.5 (node_modules\vue-cli\node_modules\seek-bzip):
12743 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Invoker\AppData\Roaming\npm\node_modules\.staging\seek-bzip-5b219872\lib\crc32.js'
12744 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
12744 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
12745 warn optional SKIPPING OPTIONAL DEPENDENCY: postcss@6.0.6 (node_modules\vue-cli\node_modules\postcss-modules-values\node_modules\postcss):
12746 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\Invoker\AppData\Roaming\npm\node_modules\.staging\postcss-da86ffc9\lib\lazy-result.js'
12747 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
12747 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
12748 verbose stack Error: sha1-gv+wKynmYq5TvcIK8VlHcGc5xTY= integrity checksum failed when using sha1: wanted sha1-gv+wKynmYq5TvcIK8VlHcGc5xTY= but got sha1-r97SxQOIiJ+Tuz4zzKkoJmK7gvk=. (496683 bytes)
12748 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:278:19)
12748 verbose stack     at emitNone (events.js:110:20)
12748 verbose stack     at Transform.emit (events.js:207:7)
12748 verbose stack     at endReadableNT (_stream_readable.js:1047:12)
12748 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
12748 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
12749 verbose cwd E:\Project\Vue.js
12750 verbose Windows_NT 10.0.14393
12751 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "vue-cli"
12752 verbose node v8.1.3
12753 verbose npm  v5.0.3
12754 error code EINTEGRITY
12755 error sha1-gv+wKynmYq5TvcIK8VlHcGc5xTY= integrity checksum failed when using sha1: wanted sha1-gv+wKynmYq5TvcIK8VlHcGc5xTY= but got sha1-r97SxQOIiJ+Tuz4zzKkoJmK7gvk=. (496683 bytes)
12756 verbose exit [ 1, true ]

```

**Comment by coderpradp** [comment]
never mind it was the issue related with npm i guess
Anyway solved it by using following command
**`npm cache verify`** and running installation again

**Comment by andrearecuyo** [comment]
> never mind it was the issue related with npm i guess
> Anyway solved it by using following command
> **`npm cache verify`** and running installation again

thanks this worked!
