### ISSUE TITLE
Error on installation - Cannot find module vue/build/install-hooks.js

### ISSUE THREAD

**Issue by DannyFeliz** [vuejs/vue-cli#523]
OS: Ubuntu 16.04.2 LTS
Node: v6.10.2
NPM: 3.10.10

Hi, I'm having this error when I try to install the `vue-cli` globally, this is the error that I'm getting.

*The Error*
```bash
➜ vagrant: ~/Code sudo npm install -g vue-cli
/usr/bin/vue -> /usr/lib/node_modules/vue-cli/bin/vue
/usr/bin/vue-init -> /usr/lib/node_modules/vue-cli/bin/vue-init
/usr/bin/vue-list -> /usr/lib/node_modules/vue-cli/bin/vue-list
/usr/bin/vue-build -> /usr/lib/node_modules/vue-cli/bin/vue-build

> vue@2.4.0 postinstall /usr/lib/node_modules/vue-cli/node_modules/vue
> node build/install-hooks.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/vue-cli/node_modules/vue/build/install-hooks.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
/usr/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/vue-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "vue-cli"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! vue@2.4.0 postinstall: `node build/install-hooks.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue@2.4.0 postinstall script 'node build/install-hooks.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/install-hooks.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/npm-debug.log
npm ERR! code 1
```

**Comment by yhhwpp** [comment]
我也遇到同样的问题了

**Comment by PGorshkov** [comment]
+1

**Comment by franklingu** [comment]
this is the vue 2.4.0 bug. issue [here](https://github.com/vuejs/vue/issues/6086)

**Comment by posva** [comment]
Fixed with latest vue release
