### ISSUE TITLE
Error on vue ui

### ISSUE THREAD

**Issue by shermax** [vuejs/vue-cli#5251]
### Version
4.2.3

### Reproduction link
[https://github.com/shermax/vue-ui-issue](https://github.com/shermax/vue-ui-issue)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz      
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Users\Max\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.2 - C:\Users\Max\AppData\Roaming\npm\npm.CMD  
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.2.3 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.2.3 
    @vue/cli-plugin-babel: ^4.2.3 => 4.2.3 
    @vue/cli-plugin-eslint: ^4.2.3 => 4.2.3 
    @vue/cli-plugin-pwa: ^4.2.3 => 4.2.3 
    @vue/cli-plugin-router: ^4.2.3 => 4.2.3 
    @vue/cli-plugin-vuex: ^4.2.3 => 4.2.3 
    @vue/cli-service: ^4.2.3 => 4.2.3 
    @vue/cli-shared-utils:  4.2.3 
    @vue/component-compiler-utils:  3.1.1 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.1 => 6.2.1 
    vue: ^2.6.11 => 2.6.11
    vue-eslint-parser:  7.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.0
    vue-router: ^3.1.6 => 3.1.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.2 => 3.1.2
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Created sample project with vue create and then started ui with command vue ui

### What is expected?
vue ui should start normally

### What is actually happening?
vue ui started with error.

ui error title: 
Kill Port

ui error content: 
Component load timeout
The custom component takes too much time to load, there might be an error

Error on log:

�🚀  Starting GUI...
�🌠  Ready on http://localhost:8000
Error: Cannot find module '@vue/cli-ui-addon-widgets/dist'
Require stack:
- C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\apollo-server\connectors\client-addons.js
- C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\apollo-server\connectors\plugins.js
- C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\apollo-server\connectors\configurations.js
- C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\apollo-server\schema\configuration.js
- C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\apollo-server\type-defs.js
- C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\graphql-server.js
- C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\server.js
- C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli\lib\ui.js
- C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli\bin\vue.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at serve (C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\apollo-server\connectors\client-addons.js:56:34)
    at Layer.handle [as handle_request] (C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\node_modules\express\lib\router\index.js:284:7
    at param (C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\node_modules\express\lib\router\index.js:365:14)
    at param (C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\Max\AppData\Roaming\npm\node_modules\@vue\cli-ui\node_modules\express\lib\router\index.js:410:3)

**Comment by gtsiolis** [comment]
Hey @shermax! The command `vue ui` is used as an alternative way to create a project [using a graphical user interface](https://cli.vuejs.org/guide/creating-a-project.html#using-the-gui) instead of using `vue create`. Are you still having trouble with this? 🖖

**Comment by shermax** [comment]
Hi @gtsiolis !

Project dashboard is not working normally after importing project... Log is saying some errors related to apollo-server and add ons...

Please look into the screenshots below:
https://drive.google.com/file/d/1eyEULXtsBzQADNf0vOQLHpScOpAGpIOu/view?usp=sharing
https://drive.google.com/file/d/1hqwIpcdtotUycKVEOF2LNEMwu0O9ak3B/view?usp=sharing

**Comment by gtsiolis** [comment]
@shermax importing the project you mentioned in the issue description works fine here.

Can you try this with `4.3.1`?

Maybe this is OS related. /cc @Akryum
