### ISSUE TITLE
Build failing in modern mode

### ISSUE THREAD

**Issue by chasegiunta** [vuejs/vue-cli#5367]
### Version
4.3.1

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.92
    Firefox: 75.0
    Safari: 13.0.5
  npmPackages:
    @vue/cli-overlay:  4.3.1 
    @vue/cli-plugin-eslint: ^4.0.5 => 4.3.1 
    @vue/cli-plugin-router:  4.3.1 
    @vue/cli-plugin-vuex:  4.3.1 
    @vue/cli-service: ^4.0.5 => 4.3.1 
    @vue/cli-shared-utils:  4.3.1 
    @vue/component-compiler-utils:  3.1.2 
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.0.1 => 6.2.2 
    portal-vue: ^2.1.7 => 2.1.7 
    vue: ^2.6.0 => 2.6.11 
    vue-agile: ^1.0.11 => 1.0.11 
    vue-eslint-parser:  7.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.1 
    vue-scrollto: ^2.17.1 => 2.17.1 
    vue-smooth-reflow: ^0.1.12 => 0.1.12 
    vue-style-loader:  4.1.2 
    vue-svgicon: ^3.2.6 => 3.2.6 
    vue-template-compiler: ^2.6.0 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
run `vue-cli-service build --modern`

### What is expected?
Build with modern mode enabled

### What is actually happening?
Build fails with stack trace:

```
TypeError: Cannot read property 'tapAsync' of undefined
    at compiler.hooks.compilation.tap.compilation (/Users/chasegiunta/Sites/hchb/node_modules/@vue/cli-service/lib/webpack/ModernModePlugin.js:26:57)
    at SyncHook.eval [as call] (eval at create (/Users/chasegiunta/Sites/hchb/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:15:1)
    at SyncHook.lazyCompileHook (/Users/chasegiunta/Sites/hchb/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/chasegiunta/Sites/hchb/node_modules/webpack/lib/Compiler.js:631:26)
    at hooks.beforeCompile.callAsync.err (/Users/chasegiunta/Sites/hchb/node_modules/webpack/lib/Compiler.js:667:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chasegiunta/Sites/hchb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/chasegiunta/Sites/hchb/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/chasegiunta/Sites/hchb/node_modules/webpack/lib/Compiler.js:662:28)
    at readRecords.err (/Users/chasegiunta/Sites/hchb/node_modules/webpack/lib/Compiler.js:321:11)
    at Compiler.readRecords (/Users/chasegiunta/Sites/hchb/node_modules/webpack/lib/Compiler.js:529:11)
    at hooks.run.callAsync.err (/Users/chasegiunta/Sites/hchb/node_modules/webpack/lib/Compiler.js:318:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chasegiunta/Sites/hchb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/chasegiunta/Sites/hchb/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/Users/chasegiunta/Sites/hchb/node_modules/webpack/lib/Compiler.js:315:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chasegiunta/Sites/hchb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/chasegiunta/Sites/hchb/node_modules/tapable/lib/Hook.js:154:20)
```

---
Not sure why `vue info` is reporting `@vue/cli: Not Found`, but it most certainly is. It's installed via yarn.
```
➜ vue --version 
@vue/cli 4.3.1
```

**Comment by chasegiunta** [comment]
*facepalm* Sorry, this is due to trying to tap into html-webpack-plugin during build via
```
  chainWebpack: config => {
    config.plugins.delete('html')
    config.plugins.delete('preload')
    config.plugins.delete('prefetch')
  }
```
Removing this gets around the error. It's somewhat documented at the bottom here:
https://cli.vuejs.org/guide/browser-compatibility.html#modern-mode
