### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: 

### ISSUE THREAD

**Issue by VladStepanov** [vuejs/vue-cli#5421]
### Version
4.3.1

### Environment info
```
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: Not Found
    Safari: 13.1
  npmGlobalPackages:
    @vue/cli: 4.3.1

```

### Steps to reproduce
I just installed package via npm globally, then tried to create a project. The error throws immediately

```
npm i -g @vue/cli
vue create client
```

### What is expected?
Scaffold a project

### What is actually happening?
Error
```
[mac@MacBook-Pro-Mac client ]$ vue create client
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/lib/node_modules/@vue/cli/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /usr/local/lib/node_modules/@vue/cli/node_modules/is-promise/index.js from /usr/local/lib/node_modules/@vue/cli/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /usr/local/lib/node_modules/@vue/cli/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/local/lib/node_modules/@vue/cli/node_modules/is-promise/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/run-async/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'ERR_REQUIRE_ESM'
}

```

**Comment by VladStepanov** [comment]
Downgrading node to 12.11.1 fixed issue

**Comment by sodatea** [comment]
See https://github.com/then/is-promise/issues/20
