### ISSUE TITLE
New Beta of Vue 3 - 

### ISSUE THREAD

**Issue by sinner** [vuejs/vue-cli#5483]
### Version
4.3.1

### Reproduction link
[https://github.com/sinner/vue3-new-features/tree/error/vue-3-plugin](https://github.com/sinner/vue3-new-features/tree/error/vue-3-plugin)

### Environment info
```
- MacOS
- Node v13.7.0
- @vue/cli: 4.3.1
- vuetify: 2.2.28
- vuetify-loader: 1.4.3
```

### Steps to reproduce
Add the vue-next plugin in an existing Vue CLI project already using VuetifyJS and execute `npm run serve`

### What is expected?
After adding the vue-next plugin executing `npm run serve` it should serve the application with the Vue 3 new features without errors

### What is actually happening?
After executing `npm run serve` it throws an error

---
I've reviewed previously this ticket https://github.com/vuetifyjs/vuetify-loader/pull/97 and I've seen in the vuetify-loader the lines with the fixes even with some improvements, but the error is still there:

This is the error details:
```sh
> npm run serve
> vue3-features-backp@0.1.0 serve /Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (/Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp/node_modules/vuetify-loader/lib/plugin.js:29:13)
    at webpack (/Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp/node_modules/webpack/lib/webpack.js:51:13)
    at serve (/Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp/node_modules/@vue/cli-service/lib/commands/serve.js:162:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue3-features-backp@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue3-features-backp@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jsinner/.npm/_logs/2020-05-14T15_12_21_989Z-debug.log

<!-- generated by vue-issues. DO NOT REMOVE -->
```

**Comment by sinner** [comment]
If you need more information about the log file content, here you are:

```sh
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/jsinner/.nvm/versions/node/v13.7.0/bin/node',
1 verbose cli   '/Users/jsinner/.nvm/versions/node/v13.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.14.2
3 info using node@v13.7.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle vue3-features-backp@0.1.0~preserve: vue3-features-backp@0.1.0
6 info lifecycle vue3-features-backp@0.1.0~serve: vue3-features-backp@0.1.0
7 verbose lifecycle vue3-features-backp@0.1.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle vue3-features-backp@0.1.0~serve: PATH: /Users/jsinner/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp/node_modules/.bin:/usr/local/opt/zip/bin:/usr/local/opt/python@3.8/bin:/Users/jsinner/.nvm/versions/node/v13.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/usr/local/opt/zip/bin:/usr/local/opt/python@3.8/bin:/Users/jsinner/.nvm/versions/node/v13.7.0/bin
9 verbose lifecycle vue3-features-backp@0.1.0~serve: CWD: /Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp
10 silly lifecycle vue3-features-backp@0.1.0~serve: Args: [ '-c', 'vue-cli-service serve' ]
11 silly lifecycle vue3-features-backp@0.1.0~serve: Returned: code: 1  signal: null
12 info lifecycle vue3-features-backp@0.1.0~serve: Failed to exec serve script
13 verbose stack Error: vue3-features-backp@0.1.0 serve: `vue-cli-service serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/jsinner/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/jsinner/.nvm/versions/node/v13.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid vue3-features-backp@0.1.0
15 verbose cwd /Users/jsinner/workspace/study/vuejs-tests/vue3-features-backp
16 verbose Darwin 18.7.0
17 verbose argv "/Users/jsinner/.nvm/versions/node/v13.7.0/bin/node" "/Users/jsinner/.nvm/versions/node/v13.7.0/bin/npm" "run" "serve"
18 verbose node v13.7.0
19 verbose npm  v6.14.2
20 error code ELIFECYCLE
21 error errno 1
22 error vue3-features-backp@0.1.0 serve: `vue-cli-service serve`
22 error Exit status 1
23 error Failed at the vue3-features-backp@0.1.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
