### ISSUE TITLE
`vue init` doesn't work

### ISSUE THREAD

**Issue by rashuo** [vuejs/vue-cli#552]
**system**: MAC OS
**Node.js**: v8.1.2
**npm**: v5.3.0
**my command**: `vue init webpack vpro`
**error info**: `Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vue-cli/node_modules/rc/lib/utils.js:3:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)`

**Comment by jaytanweb** [comment]
pls try 'vue init webpack vpro' again. 
"**Error: Cannot find module 'ini'** "shows that you probably typed  '**vue ini** ' instead of '**vue init**'.

**Comment by rashuo** [comment]
I've tried lots of times, I'm pretty sure that I did typed `vue init webpack vpro'

**Comment by rashuo** [comment]
In the 'error info', It did mean the error was not caused by 'input params'

**Comment by jaytanweb** [comment]
Node.js: v8.1.2
npm: v5.3.0
`vue init webpack vpro` worked good in my MAC, you may need to reinstall the vue-cli or even the node.

**Comment by rashuo** [comment]
I've tried run `npm i -g ini`,
and then I run `npm init webpack vpro` again, 
the error info was updated to: `Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vue-cli/node_modules/readable-stream/lib/_stream_readable.js:67:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)`

**Comment by rashuo** [comment]
I've already reinstall vue-cli three times

**Comment by rashuo** [comment]
It's work! may be it's caused by my network, I reinstall vue-cli again, then all trouble were gone!
