### ISSUE TITLE
Error installing with npm

### ISSUE THREAD

**Issue by Ethilios** [vuejs/vue-cli#5529]
### Version
4.4.1

### Environment info
```
Vue is not installed
```

### Steps to reproduce
npm install -g @vue/cli

### What is expected?
Vue cli should install globally to the latest version

### What is actually happening?
It errors:
```
114 verbose stack SyntaxError: Unexpected end of JSON input while parsing near "...oi":"^14.3.0","launch'
114 verbose stack     at JSON.parse (<anonymous>)
114 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
114 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
114 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by sodatea** [comment]
Likely a network/cache issue.
Please run `npm cache verify` and then try again. If that doesn't work, run `npm cache clean -f` and try again.
