### ISSUE TITLE
macOS 10.15.2 使用vue ui命令报错

### ISSUE THREAD

**Issue by leapp** [vuejs/vue-cli#5532]
### Version
4.4.1

### Environment info
```
System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 13.1.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Edge: Not Found
    Firefox: Not Found
    Safari: 13.0.4
  npmPackages:
    @vue/cli:  4.4.1
    @vue/cli-shared-utils:  4.4.1
    @vue/cli-ui:  4.4.1
    @vue/cli-ui-addon-webpack:  4.4.1
    @vue/cli-ui-addon-widgets:  4.4.1
    typescript:  3.9.3
    vue:  2.6.11
    vue-cli-plugin-apollo:  0.21.3
    vue-jscodeshift-adapter:  2.1.0
    vue-sfc-descriptor-to-string:  1.0.0
    vue-template-compiler:  2.6.11
  npmGlobalPackages:
    @vue/cli: 4.4.1
```

### Steps to reproduce
vue ui

### What is expected?
open vue ui window.

### What is actually happening?
internal/modules/cjs/loader.js:548
  throw e;
  ^

Error: Package exports for '/usr/local/lib/node_modules/@vue/cli/node_modules/apollo-engine-reporting/node_modules/uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/apollo-engine-reporting/dist/agent.js:26:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND'
}

**Comment by sodatea** [comment]
https://github.com/nodejs/modules/issues/446
Please upgrade your Node.js version.

**Comment by leapp** [comment]
> https://github.com/nodejs/modules/issues/446
> 
> Please upgrade your Node.js version.

The problem is solved ，thanks 😃
