### ISSUE TITLE
Run yarn build and yarn serve failed

### ISSUE THREAD

**Issue by thretho** [vuejs/vue-cli#5551]
### Version
4.4.1

### Environment info
```
  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz
  Binaries:
    Node: 12.16.2 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - D:\Program Files\nodejs\npm.CMD
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.4.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.4.1
    @vue/cli-plugin-babel: ~4.4.0 => 4.4.1
    @vue/cli-plugin-eslint: ~4.4.0 => 4.4.1
    @vue/cli-plugin-router:  4.4.1
    @vue/cli-plugin-vuex:  4.4.1
    @vue/cli-service: ~4.4.0 => 4.4.1
    @vue/cli-shared-utils:  4.4.1
    @vue/component-compiler-utils:  3.1.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.11
    vue-eslint-parser:  7.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. run `vue create -n -m yarn vue-test-2`
2. run `yarn build`

### What is expected?
Build application

### What is actually happening?
```
\  Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                    1:50:31

 error  in ./src/main.js

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
[BABEL] D:\Projects\vue-test-2\src\main.js: Cannot find module './available-plugins'
Require stack:
- D:\Projects\vue-test-2\node_modules\@babel\preset-env\lib\plugins-compat-data.js
- D:\Projects\vue-test-2\node_modules\@babel\preset-env\lib\normalize-options.js
- D:\Projects\vue-test-2\node_modules\@babel\preset-env\lib\index.js
- D:\Projects\vue-test-2\node_modules\@vue\babel-preset-app\index.js
- D:\Projects\vue-test-2\node_modules\@vue\cli-plugin-babel\preset.js
- D:\Projects\vue-test-2\node_modules\@babel\core\lib\config\files\plugins.js
- D:\Projects\vue-test-2\node_modules\@babel\core\lib\config\files\index.js
- D:\Projects\vue-test-2\node_modules\@babel\core\lib\index.js
- D:\Projects\vue-test-2\node_modules\babel-loader\lib\index.js
- D:\Projects\vue-test-2\node_modules\loader-runner\lib\loadLoader.js
- D:\Projects\vue-test-2\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Projects\vue-test-2\node_modules\thread-loader\dist\worker.js (While processing: "D:\\Projects\\vue-test-2\\node_modules\\@vue\\cli-plugin-babel\\preset.js")
    at PoolWorker.fromErrorObj (D:\Projects\vue-test-2\node_modules\thread-loader\dist\WorkerPool.js:262:12)
    at D:\Projects\vue-test-2\node_modules\thread-loader\dist\WorkerPool.js:204:29
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Projects\vue-test-2\node_modules\@babel\preset-env\lib\plugins-compat-data.js:12:48)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)

 @ multi ./src/main.js

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sodatea** [comment]
Could you share the project that has this problem with us? I can't find a clue to the underlying bug by looking at the error stack.

**Comment by thretho** [comment]
> Could you share the project that has this problem with us? I can't find a clue to the underlying bug by looking at the error stack.

Sure 
[https://github.com/thretho/vue-cli-issue-5551](https://github.com/thretho/vue-cli-issue-5551)

**Comment by sodatea** [comment]
I'm sorry but I can't reproduce the issue with the given project.

**Comment by thretho** [comment]
I tried clearing cache and reinstalling dependencies, it works. Maybe some package is broken in global cache.

**Comment by wuxiaobin1995** [comment]
Version
4.4.1

Environment info
System:
OS: Windows 10
Binaries:
Node: 12.18.0 - D:\Program Files\nodejs\node.EXE
npm: 6.14.4 - D:\Program Files\nodejs\npm.CMD
npmPackages:
{
"name": "test-7",
"version": "0.1.0",
"private": true,
"scripts": {
"serve": "vue-cli-service serve",
"build": "vue-cli-service build",
"lint": "vue-cli-service lint"
},
"dependencies": {
"core-js": "^3.6.5",
"vue": "^2.6.11",
"vue-router": "^3.2.0",
"vuex": "^3.4.0"
},
"devDependencies": {
"@vue/cli-plugin-babel": "~4.4.0",
"@vue/cli-plugin-eslint": "~4.4.0",
"@vue/cli-plugin-router": "~4.4.0",
"@vue/cli-plugin-vuex": "~4.4.0",
"@vue/cli-service": "~4.4.0",
"@vue/eslint-config-standard": "^5.1.2",
"babel-eslint": "^10.1.0",
"eslint": "^6.7.2",
"eslint-plugin-import": "^2.20.2",
"eslint-plugin-node": "^11.1.0",
"eslint-plugin-promise": "^4.2.1",
"eslint-plugin-standard": "^4.0.0",
"eslint-plugin-vue": "^6.2.2",
"node-sass": "^4.12.0",
"sass-loader": "^8.0.2",
"vue-template-compiler": "^2.6.11"
}
}

What is actually happening?

`Starting development server...
98% after emitting CopyPlugin

ERROR Failed to compile with 1 errors 11:01:29 ├F10: AM┤

error in ./src/main.js

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Failed to load plugin 'import' declared in '.eslintrc.js » @vue/eslint-config-standard » C:\Users\wxb\Desktop\test-7\node_modules\eslint-config-standard\index.js': Cannot find module 'typescript'
Require stack:

C:\Users\wxb\Desktop\test-7\node_modules\eslint-plugin-import\lib\ExportMap.js
C:\Users\wxb\Desktop\test-7\node_modules\eslint-plugin-import\lib\rules\named.js
C:\Users\wxb\Desktop\test-7\node_modules\eslint-plugin-import\lib\index.js
C:\Users\wxb\Desktop\test-7\node_modules\eslint\lib\cli-engine\config-array-factory.js
C:\Users\wxb\Desktop\test-7\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
C:\Users\wxb\Desktop\test-7\node_modules\eslint\lib\cli-engine\cli-engine.js
C:\Users\wxb\Desktop\test-7\node_modules\eslint\lib\cli-engine\index.js
C:\Users\wxb\Desktop\test-7\node_modules\eslint\lib\api.js
C:\Users\wxb\Desktop\test-7\node_modules\eslint-loader\index.js
C:\Users\wxb\Desktop\test-7\node_modules\loader-runner\lib\loadLoader.js
C:\Users\wxb\Desktop\test-7\node_modules\loader-runner\lib\LoaderRunner.js
C:\Users\wxb\Desktop\test-7\node_modules\webpack\lib\NormalModule.js
C:\Users\wxb\Desktop\test-7\node_modules\webpack\lib\NormalModuleFactory.js
C:\Users\wxb\Desktop\test-7\node_modules\webpack\lib\Compiler.js
C:\Users\wxb\Desktop\test-7\node_modules\webpack\lib\webpack.js
C:\Users\wxb\Desktop\test-7\node_modules@vue\cli-service\lib\commands\serve.js
C:\Users\wxb\Desktop\test-7\node_modules@vue\cli-service\lib\Service.js
C:\Users\wxb\Desktop\test-7\node_modules@vue\cli-service\bin\vue-cli-service.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
at Function.Module._load (internal/modules/cjs/loader.js:842:27)
at Module.require (internal/modules/cjs/loader.js:1026:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object. (C:\Users\wxb\Desktop\test-7\node_modules\eslint-plugin-import\lib\ExportMap.js:46:19)
at Module._compile (internal/modules/cjs/loader.js:1138:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
at Module.load (internal/modules/cjs/loader.js:986:32)
at Function.Module._load (internal/modules/cjs/loader.js:879:14)
at Module.require (internal/modules/cjs/loader.js:1026:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object. (C:\Users\wxb\Desktop\test-7\node_modules\eslint-plugin-import\lib\rules\named.js:7:18)
at Module._compile (internal/modules/cjs/loader.js:1138:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
at Module.load (internal/modules/cjs/loader.js:986:32)
at Function.Module._load (internal/modules/cjs/loader.js:879:14)
@ multi (webpack)-dev-server/client?http://192.168.1.158:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js`

**Comment by sodatea** [comment]
@wuxiaobin1995 
See https://github.com/benmosher/eslint-plugin-import/blob/master/CHANGELOG.md#2211---2020-06-07
Bug in eslint-plugin-import v2.21.0, fixed in v2.21.1
