### ISSUE TITLE
Error: Cannot find module '@vue/cli-shared-utils'

### ISSUE THREAD

**Issue by crli** [vuejs/vue-cli#5632]
### Version
4.4.6

### Environment info
node v10.21.0
Windows 10
npm 6.14.4
```
$ vue info
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@vue/cli-shared-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\node\lib\node_modules\@vue\cli\bin\vue.js:6:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

```

### Steps to reproduce
```powershell
npm uninstall vue-cli -g
```

```powershell
npm install -g @vue/cli
```

```powershell
$ vue -v
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@vue/cli-shared-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\node\lib\node_modules\@vue\cli\bin\vue.js:6:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

```powershell
$ vue info
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@vue/cli-shared-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\node\lib\node_modules\@vue\cli\bin\vue.js:6:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### What is expected?
The vue command is used normally

### What is actually happening?
Error: Cannot find module '@vue/cli-shared-utils'

**Comment by crli** [comment]
卸载node重装已解决
