### ISSUE TITLE
@vue/cli 启动 vue ui 报错

### ISSUE THREAD

**Issue by web-mr-dl** [vuejs/vue-cli#5654]
### Version
4.4.6

### Environment info
```
  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Edge: Not Found
    Firefox: Not Found
    Safari: 13.1.1
  npmGlobalPackages:
    @vue/cli: 4.4.6
```

### Steps to reproduce
npm install -g @vue/cli

vue ui

### What is expected?
Normal access to start the project manager

### What is actually happening?
root@DoubleL ~ # vue ui                       
/usr/local/lib/node_modules/@vue/cli/node_modules/apollo-engine-reporting/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1043:16)
    at Module._compile (internal/modules/cjs/loader.js:1091:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/apollo-engine-reporting/dist/agent.js:26:16)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)

**Comment by sodatea** [comment]
Please upgrade your Node.js version. If I remember correctly, it's a bug in Node.js v13.2.

**Comment by web-mr-dl** [comment]
Thk fixed it...  => update nodejs version is
