### ISSUE TITLE
Unable to start Vue UI - lodash

### ISSUE THREAD

**Issue by slntopp** [vuejs/vue-cli#5662]
### Version
4.4.6

### Environment info
```
Clean macOS Catalina
```

### Steps to reproduce
npm install -g @vue/cli
vue ui

### What is expected?
Get running Vue UI

### What is actually happening?
```
🚀  Starting GUI...
TypeError: lodash.runInContext is not a function
    at new module.exports (/usr/local/lib/node_modules/@vue/cli/node_modules/lowdb/lib/main.js:12:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/@vue/cli-ui/apollo-server/util/db.js:6:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/@vue/cli-ui/apollo-server/context.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
```

**Comment by sodatea** [comment]
> ```
> Clean macOS Catalina
> ```

It's not useful environment info. Please provide the full output of `vue info`.

**Comment by slntopp** [comment]
```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Edge: Not Found
    Firefox: Not Found
    Safari: 13.1.1
  npmGlobalPackages:
    @vue/cli: 4.4.6
```

**Comment by sodatea** [comment]
https://github.com/lodash/lodash/issues/4845

**Comment by sodatea** [comment]
```
npm cache clean -f
npm i -g @vue/cli
```

**Comment by slntopp** [comment]
Yep, this has worked out, thanks!
