### ISSUE TITLE
使用@vue/cli 4.4.6 创建项目报错

### ISSUE THREAD

**Issue by 15070262009** [vuejs/vue-cli#5666]
### Version
4.4.6

### Environment info
```
Windows 10  node 13.1.0  npm 6.12.1
```

### Steps to reproduce
我创建完项目，run serve 的时候直接报错
Error: Package exports for 'C:\Users\juwa03\Desktop\project\project\node_modules\colorette' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\juwa03\Desktop\project\project\node_modules\autoprefixer\lib\autoprefixer.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\juwa03\scoop\persist\nodejs\cache\_logs\2020-07-09T10_57_19_153Z-debug.log

### What is expected?
run ok

### What is actually happening?
run no ok

**Comment by sodatea** [comment]
Node.js 13.1 的 bug，请升级。
