### ISSUE TITLE
Cannot find module '@vue/cli/lib/util/rcPath error when using volta as node version manager

### ISSUE THREAD

**Issue by 3nigm4** [vuejs/vue-cli#5724]
### Version
4.4.6

### Environment info
```
Windows Subsystem For Linux (WSL) 2, but the error also happens in WSL 1.

System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz
  Binaries:
    Node: 12.18.3 - ~/.volta/tools/image/node/12.18.3/bin/node
    Yarn: 1.22.4 - ~/.volta/tools/image/yarn/1.22.4/bin/yarn
    npm: 6.14.6 - ~/.volta/tools/image/node/12.18.3/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.4.6
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.4.6
    @vue/cli-plugin-babel: ~4.4.0 => 4.4.6
    @vue/cli-plugin-eslint: ~4.4.0 => 4.4.6
    @vue/cli-plugin-router: ~4.4.0 => 4.4.6
    @vue/cli-plugin-unit-jest: ~4.4.0 => 4.4.6
    @vue/cli-plugin-vuex: ~4.4.0 => 4.4.6
    @vue/cli-service: ~4.4.0 => 4.4.6
    @vue/cli-shared-utils:  4.4.6
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/test-utils: ^1.0.3 => 1.0.3
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    jest-serializer-vue:  2.0.2
    vue: ^2.6.11 => 2.6.11
    vue-eslint-parser:  7.1.0
    vue-hot-reload-api:  2.3.4
    vue-jest:  3.0.6
    vue-loader:  15.9.3
    vue-router: ^3.2.0 => 3.3.4
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.4.0 => 3.5.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
make sure you use wsl2
`wsl -l -v`

install Volta `curl https://get.volta.sh | bash`

install Node `volta install node`

start using Node `node`

install vue-cli exectubale (volta does not allow npm install -g) `volta install @vue/cli`

### What is expected?
start vue ui

### What is actually happening?
🚀  Starting GUI...
 ERROR  Error: Cannot find module '@vue/cli/lib/util/rcPath'
Require stack:
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/rcFolder.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/db.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/context.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/plugins.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/configurations.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/schema/configuration.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/type-defs.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/graphql-server.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/server.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/lib/ui.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/bin/vue.js
Error: Cannot find module '@vue/cli/lib/util/rcPath'
Require stack:
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/rcFolder.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/db.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/context.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/plugins.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/configurations.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/schema/configuration.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/type-defs.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/graphql-server.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/server.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/lib/ui.js
- /home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/bin/vue.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/rcFolder.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)

**Comment by 3nigm4** [comment]
Note that `vue create` works fine, but `vue ui` does not.

**Comment by sodatea** [comment]
That's because of the circular dependencies in the `@vue/cli-ui` package that references `@vue/cli`. 
It's not good practice but it works with most common package managers. We don't have much time to fix it, but any help would be appreciated.
