### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by KyotoCode** [vuejs/vue-cli#5743]
### Version
4.4.6

### Environment info
```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 79.0
  npmGlobalPackages:
    @vue/cli: 4.4.6

```

### Steps to reproduce
npm create test1
Please pick a preset: default (babel, eslint)

### What is expected?
create successfull

### What is actually happening?
Vue CLI v4.4.6
Failed to check for updates
✨  Creating project in /home/mihajlo/Desktop/test1.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

 ERROR  Error: Command failed: npm config get npmRegistryServer
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'semver'
Require stack:
- /usr/share/npm/lib/utils/unsupported.js
- /usr/share/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/npm/lib/utils/unsupported.js',
    '/usr/share/npm/bin/npm-cli.js'
  ]
}

Error: Command failed: npm config get npmRegistryServer
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'semver'
Require stack:
- /usr/share/npm/lib/utils/unsupported.js
- /usr/share/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/npm/lib/utils/unsupported.js',
    '/usr/share/npm/bin/npm-cli.js'
  ]
}

    at makeError (/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

---
I didn't use vue for long time, i was experimenting with node and after long time when i tried to make vue app with vue create i ran on this problem. I tried to fix this problem with reinstalling vue cli but same thing happens.

**Comment by sodatea** [comment]
Looks like something's wrong with your npm installation.

**Comment by sodatea** [comment]
>    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
/usr/share/npm/bin/npm-cli.js

These directories don't match. There must be several instances of npm installations and one takes too high a priority (presumably the `/usr/share` one). Please check your `PATH` environment variable and make sure `/usr/local/bin` comes before the other one.

**Comment by KyotoCode** [comment]
> > Node: 10.19.0 - /usr/bin/node
> > npm: 6.14.7 - /usr/local/bin/npm
> > /usr/share/npm/bin/npm-cli.js
> 
> These directories don't match. There must be several instances of npm installations and one takes too high a priority (presumably the `/usr/share` one). Please check your `PATH` environment variable and make sure `/usr/local/bin` comes before the other one.

I'm sorry but can you describe what should i do exactly. Are you saying that i have more than one npm installations and i should delete one of them?

**Comment by sodatea** [comment]
Yeah

**Comment by KyotoCode** [comment]
> Yeah

Dude thank you, after 4 days of fixing this problem i finally fixed it with your help... Thank you so much.

**Comment by NyllRE** [comment]
excuse me how did you find the other npm installation and delete it?
I entered usr/local/bin and usr/bin and I found one in each of them should I delete one of them and if so which one?
