### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by Luigidefra** [vuejs/vue-cli#5757]
### Version
4.4.6
I can't add vuecli

yarn add @vue/vue-cli

Error in yarn-error.log

Arguments:
  /usr/bin/node /usr/share/yarn/bin/yarn.js add @vue/cli

PATH:
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Yarn version:
  1.19.1

Node version:
  10.16.3

Platform:
  linux x64

Trace:
  Error: https://registry.yarnpkg.com/@vue%2fcli: Not found
      at Request.params.callback [as _callback] (/usr/share/yarn/lib/cli.js:66926:18)
      at Request.self.callback (/usr/share/yarn/lib/cli.js:140564:22)
      at Request.emit (events.js:198:13)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:141536:10)
      at Request.emit (events.js:198:13)
      at IncomingMessage.<anonymous> (/usr/share/yarn/lib/cli.js:141458:12)
      at Object.onceWrapper (events.js:286:20)
      at IncomingMessage.emit (events.js:203:15)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

npm manifest:
  {
    "dependencies": {
      "vue": "^2.6.11"
    }
  }

yarn manifest:
  No manifest

Lockfile:
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1

  vue@^2.6.11:
    version "2.6.11"
    resolved "https://registry.yarnpkg.com/vue/-/vue-2.6.11.tgz#76594d877d4b12234406e84e35275c6d514125c5"
    integrity sha512-VfPwgcGABbGAue9 sfrD4PuwFar7gPb1yl1UK1MwXoQPAw0BKSqWfoYCT/ThFrdEVWoI51dBuyCoiNU9bZDZxQ==

### What is actually happening?
I can't add vuecli

**Comment by sodatea** [comment]
https://status.npmjs.org/
The NPM registry is down.
