### ISSUE TITLE
TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by niexias** [vuejs/vue-cli#5773]
### Version
4.5.2

### Environment info
```
node v11.11.0
@vue/cli 4.5.2
```

### Steps to reproduce
1. install
```
npm install -g @vue/cli
npm install -g @vue/cli-service-global
```
2. create a demo project
```
|—App.vue
```
3. run the cli
```
vue serve
```

### What is expected?
start server

### What is actually happening?
```
vue serve
 INFO  Starting development server...
(node:69570) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'version' of undefined
    at api.chainWebpack.webpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/config/base.js:74:26)
    at webpackChainFns.forEach.fn (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:236:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:236:26)
    at Service.resolveWebpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:240:48)
    at PluginAPI.resolveWebpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/commands/serve.js:75:31)
    at Service.run (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at Object.exports.serve (/usr/local/lib/node_modules/@vue/cli-service-global/index.js:85:24)
    at Command.program.command.description.option.option.option.action (/usr/local/lib/node_modules/@vue/cli/bin/vue.js:119:53)
(node:69570) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:69570) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Shinobi247** [comment]
Can you try `npm install --save-dev eslint@4`?
