### ISSUE TITLE
2017年9月4日适用vue-cli构建项目（空项目）出错。

### ISSUE THREAD

**Issue by hasbug** [vuejs/vue-cli#582]
9月4使用vue-cli进行构建，无论是翻墙还是不翻墙来进行vue init webpack 然后 npm install ,之后运行npm run dev就直接报错了。。

下面是npm的出错日志，看不懂，求助:

```javascript
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle calendar-sign-in@1.0.0~predev: calendar-sign-in@1.0.0
6 silly lifecycle calendar-sign-in@1.0.0~predev: no script for predev, continuing
7 info lifecycle calendar-sign-in@1.0.0~dev: calendar-sign-in@1.0.0
8 verbose lifecycle calendar-sign-in@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle calendar-sign-in@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;G:\calendar-sign-in\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Java\jdk1.7.0_79;C:\Program Files\SlikSvn\bin;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;E:\服务器工具\PuTTY\;%MAVEN_HOME%;C:\Program Files\Java\jdk1.7.0_79;C:\Ruby24-x64\bin;C:\Users\hasbu\AppData\Roaming\npm;C:\Users\hasbu\AppData\Local\Microsoft\WindowsApps;;C:\Users\hasbu\AppData\Local\Programs\Fiddler
10 verbose lifecycle calendar-sign-in@1.0.0~dev: CWD: G:\calendar-sign-in
11 silly lifecycle calendar-sign-in@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle calendar-sign-in@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle calendar-sign-in@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: calendar-sign-in@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid calendar-sign-in@1.0.0
16 verbose cwd G:\calendar-sign-in
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error calendar-sign-in@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the calendar-sign-in@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the calendar-sign-in package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs calendar-sign-in
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls calendar-sign-in
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]


````

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

The error seems to be happening in a package called calendar-sign-in which doesn't even exist in npm so I imagine it's a private package. I cannot help you, sorry
