### ISSUE TITLE
Vue CLI fail to compile when updated to 4.5.6

### ISSUE THREAD

**Issue by ccsv** [vuejs/vue-cli#5931]
### Version
4.5.6

### Environment info
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @ckeditor/ckeditor5-vue: ^1.0.3 => 1.0.3
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.3
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app: ^4.5.6 => 4.5.6
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.5.6
    @vue/cli-plugin-babel: ^4.5.6 => 4.5.6
    @vue/cli-plugin-eslint: ^4.5.6 => 4.5.6
    @vue/cli-plugin-router: ^4.5.6 => 4.5.6
    @vue/cli-plugin-unit-jest: ^4.5.6 => 4.5.6
    @vue/cli-plugin-vuex: ^4.5.6 => 4.5.6
    @vue/cli-service: ^4.5.6 => 4.5.6
    @vue/cli-shared-utils:  4.5.6
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/test-utils: ^1.1.0 => 1.1.0
    @vue/web-component-wrapper:  1.2.0
    bootstrap-vue: ^2.17.3 => 2.17.3
    eslint-plugin-vue: ^7.0.1 => 7.0.1
    jest-serializer-vue:  2.0.2
    portal-vue: ^2.1.6 => 2.1.7
    typescript: ^4.0.3 => 4.0.3
    vue: ^2.6.12 => 2.6.12
    vue-apollo: ^3.0.4 => 3.0.4
    vue-cli-plugin-apollo: ^0.22.2 => 0.22.2
    vue-cli-plugin-bootstrap-vue: ^0.7.0 => 0.7.0
```

### Steps to reproduce
Ran `npm update` on console

got this in the vue ui build:

``` 
error  in ./src/main.js

Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
Error: Error while loading rule 'graphql/template-strings': ENOENT: no such file or directory, open 'node_modules/.temp/graphql/schema.json'
Occurred while linting C:\Users\0\Desktop\test\test\front\src\main.js
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at initSchemaFromFile (C:\Users\0\Desktop\test\test\front\node_modules\eslint-plugin-graphql\lib\index.js:352:44)
    at parseOptions (C:\Users\0\Desktop\test\test\front\node_modules\eslint-plugin-graphql\lib\index.js:242:14)
    at C:\Users\0\Desktop\test\test\front\node_modules\eslint-plugin-graphql\lib\index.js:123:76
    at createRule (C:\Users\0\Desktop\test\test\front\node_modules\eslint-plugin-graphql\lib\createRule.js:175:9)
    at Object.create (C:\Users\0\Desktop\test\test\front\node_modules\eslint-plugin-graphql\lib\index.js:123:51)
    at createRuleListeners (C:\Users\0\Desktop\test\test\front\node_modules\eslint\lib\linter\linter.js:746:21)
    at C:\Users\0\Desktop\test\test\front\node_modules\eslint\lib\linter\linter.js:916:31
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\0\Desktop\test\test\front\node_modules\eslint\lib\linter\linter.js:861:34)
    at Linter._verifyWithoutProcessors (C:\Users\0\Desktop\test\test\front\node_modules\eslint\lib\linter\linter.js:1157:31)
    at Linter._verifyWithConfigArray (C:\Users\0\Desktop\test\test\front\node_modules\eslint\lib\linter\linter.js:1255:21)
    at Linter.verify (C:\Users\0\Desktop\test\test\front\node_modules\eslint\lib\linter\linter.js:1210:25)
    at Linter.verifyAndFix (C:\Users\0\Desktop\test\test\front\node_modules\eslint\lib\linter\linter.js:1400:29)
    at verifyText (C:\Users\0\Desktop\test\test\front\node_modules\eslint\lib\cli-engine\cli-engine.js:230:48)

 @ multi (webpack)-dev-server/client?http://192.168.42.69:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

Tried the following:
* deleting node modules & package-lock.json then running`npm i` and then `npm audit fix`
* tried `npm install -f`

Output from NPM audit:
```
npm WARN relay-compiler@10.0.1 requires a peer of graphql@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-loader@2.1.2 requires a peer of eslint@>=1.6.0 <6.0.0 but none is installed. You must install peer dependencies yourself.
```

### What is expected?
build compiles

### What is actually happening?
Either 
* Versions of eslint is incompatible eslint-loader
* Mismatch with graphql versions

---
Any suggestion on what package to back out or dev package to upgrade to?

**Comment by sodatea** [comment]
1. None of the core plugins depends on `graphql` so I think it's an issue in your project's own dependencies, rather than Vue CLI packages;
2. `@vue/cli-plugin-eslint` depends on `eslint-loader` >= 2.2.1 (https://github.com/vuejs/vue-cli/blob/v4.5.6/packages/%40vue/cli-plugin-eslint/package.json#L27), so the `eslint-loader` 2.1.2 is either introduced by other dependencies in your project, or the plugin wasn't actually updated to the latest version.

**Comment by ccsv** [comment]
>     2. `@vue/cli-plugin-eslint` depends on `eslint-loader` >= 2.2.1 (https://github.com/vuejs/vue-cli/blob/v4.5.6/packages/%40vue/cli-plugin-eslint/package.json#L27), so the `eslint-loader` 2.1.2 is either introduced by other dependencies in your project, or the plugin wasn't actually updated to the latest version.

@sodatea  But if I upgrade to "eslint-loader": "^4.0.2". I get an issue with the loading the graphql:

```
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Error while loading rule 'graphql/template-strings': ENOENT: no such file or directory, open 'node_modules/.temp/graphql/schema.json'
Occurred while linting C:\Users\0\Desktop\test\test\front\src\main.js
```

**Comment by sodatea** [comment]
1. Don't install eslint-loader separately, it's bundled inside `@vue/cli-plugin-eslint` already.
2. https://github.com/Akryum/vue-cli-plugin-apollo/issues/21
