### ISSUE TITLE
Error: Cannot find module '@vue/cli-shared-utils'

### ISSUE THREAD

**Issue by Libidine** [vuejs/vue-cli#5966]
### Version
4.5.7

### Environment info
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Xeon(R) CPU           X3440  @ 2.53GHz
  Binaries:
    Node: 14.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.423.0), Chromium (84.0.522.69)
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.10 => 0.1.10
    @intlify/vue-i18n-loader: ^1.0.0 => 1.0.0
    @vue/cli-overlay:  4.5.7
    @vue/cli-plugin-router:  4.5.7
    @vue/cli-plugin-vuex:  4.5.7
    @vue/cli-service: ^4.5.7 => 4.5.7
    @vue/cli-shared-utils:  undefined (4.5.7)
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    vue: ^2.6.12 => 2.6.12
    vue-cli-plugin-i18n: ^1.0.1 => 1.0.1
    vue-cli-plugin-vuetify: ^2.0.7 => 2.0.7
    vue-cli-webpack:  1.0.0
    vue-draggable-resizable: ^2.2.0 => 2.2.0
    vue-hot-reload-api:  2.3.4
    vue-i18n: ^8.22.0 => 8.22.0
    vue-i18n-extract:  1.0.2
    vue-loader:  15.9.3 (16.0.0-beta.8)
    vue-plyr: ^6.0.4 => 6.0.4
    vue-router: ^3.4.6 => 3.4.6
    vue-scroll-behavior: ^0.3.0 => 0.3.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.12 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
    vue-virtual-scroll-list: ^2.3.1 => 2.3.1
    vuetify: ^2.3.14 => 2.3.14
    vuetify-loader: ^1.6.0 => 1.6.0
    vuex: ^3.5.1 => 3.5.1
    vuex-persistedstate: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
None

### What is expected?
That the build process will start normally.

### What is actually happening?
```
 ERROR  Error: Cannot find module '@vue/cli-shared-utils'
Require stack:
- D:\Dev\lab\node_modules\vue-cli-plugin-i18n\report.js
- D:\Dev\lab\node_modules\vue-cli-plugin-i18n\index.js
- D:\Dev\lab\node_modules\@vue\cli-service\lib\Service.js
- D:\Dev\lab\node_modules\@vue\cli-service\bin\vue-cli-service.js
Error: Cannot find module '@vue/cli-shared-utils'
Require stack:
- D:\Dev\lab\node_modules\vue-cli-plugin-i18n\report.js
- D:\Dev\lab\node_modules\vue-cli-plugin-i18n\index.js
- D:\Dev\lab\node_modules\@vue\cli-service\lib\Service.js
- D:\Dev\lab\node_modules\@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.<anonymous> (D:\Dev\lab\node_modules\vue-cli-plugin-i18n\report.js:1:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at module.exports (D:\Dev\lab\node_modules\vue-cli-plugin-i18n\index.js:22:18)
    at D:\Dev\lab\node_modules\@vue\cli-service\lib\Service.js:78:7
    at Array.forEach (<anonymous>)
    at Service.init (D:\Dev\lab\node_modules\@vue\cli-service\lib\Service.js:76:18)
    at Service.run (D:\Dev\lab\node_modules\@vue\cli-service\lib\Service.js:215:10)
    at Object.<anonymous> (D:\Dev\lab\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

---
Deleted @vue/cli-plugin-babel and then this strange error appeared.

Also, for some reason, vue --info displays:
```
npmGlobalPackages:
@vue/cli: Not Found
```
Although it is installed, I even installed it again: npm install-g @vue/cli

**Comment by sodatea** [comment]
1. Please report to `vue-cli-plugin-i18n` that they need to list `@vue/cli-shared-utils` as an explicit direct dependency.
2. It's because requiring the implicit dependency only works when the npm package hoisting mechanism places the `@vue/cli-shared-utils` package as a top-level dependency. Deleting a dependency shuffles the directory structure of `node_modules`, and the result is indeterministic, so somehow the `@vue/cli-shared-utils` package is no longer at top-level.

**Comment by sodatea** [comment]
The error can be fixed by:
```
rm -rf node_modules package-lock.json
npm i
```
