### ISSUE TITLE
Error with vue create

### ISSUE THREAD

**Issue by ndri** [vuejs/vue-cli#5977]
### Version
4.5.7

### Environment info
```

  System:
    OS: Linux 5.8 Debian GNU/Linux bullseye/sid
    CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  Binaries:
    Node: 12.19.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 81.0
  npmGlobalPackages:
    @vue/cli: 4.5.7


```

### Steps to reproduce
`vue create project` with any configuration

### What is expected?
Project is created

### What is actually happening?
```
Vue CLI v4.5.7
Failed to check for updates
✨  Creating project in /home/andri/Dev/Vue/moz-todo-vue.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

 ERROR  Error: Command failed: npm config get npmRegistryServer
TypeError: invalid options argument
    at optsArg (/usr/share/nodejs/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/usr/share/nodejs/mkdirp/index.js:11:10)
    at module.exports (/usr/share/npm/node_modules/gentle-fs/lib/mkdir.js:10:12)
    at Conf.setUser (/usr/share/npm/lib/config/set-user.js:22:3)
    at Conf.loadExtras (/usr/share/npm/lib/config/core.js:225:8)
    at Conf.<anonymous> (/usr/share/npm/lib/config/core.js:166:12)
    at Object.onceWrapper (events.js:421:26)
    at Conf.emit (events.js:314:20)
    at ConfigChain._resolve (/usr/share/nodejs/config-chain/index.js:281:34)
    at ConfigChain.add (/usr/share/nodejs/config-chain/index.js:259:10)
/usr/share/npm/lib/npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/share/npm/lib/npm.js:59:13)
    at process.errorHandler (/usr/share/npm/lib/utils/error-handler.js:208:32)
    at process.emit (events.js:314:20)
    at process._fatalException (internal/process/execution.js:165:25)


Error: Command failed: npm config get npmRegistryServer
TypeError: invalid options argument
    at optsArg (/usr/share/nodejs/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/usr/share/nodejs/mkdirp/index.js:11:10)
    at module.exports (/usr/share/npm/node_modules/gentle-fs/lib/mkdir.js:10:12)
    at Conf.setUser (/usr/share/npm/lib/config/set-user.js:22:3)
    at Conf.loadExtras (/usr/share/npm/lib/config/core.js:225:8)
    at Conf.<anonymous> (/usr/share/npm/lib/config/core.js:166:12)
    at Object.onceWrapper (events.js:421:26)
    at Conf.emit (events.js:314:20)
    at ConfigChain._resolve (/usr/share/nodejs/config-chain/index.js:281:34)
    at ConfigChain.add (/usr/share/nodejs/config-chain/index.js:259:10)
/usr/share/npm/lib/npm.js:59
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/share/npm/lib/npm.js:59:13)
    at process.errorHandler (/usr/share/npm/lib/utils/error-handler.js:208:32)
    at process.emit (events.js:314:20)
    at process._fatalException (internal/process/execution.js:165:25)


    at makeError (/usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:174:9)
    at /usr/local/lib/node_modules/@vue/cli/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PackageManager.getRegistry (/usr/local/lib/node_modules/@vue/cli/lib/util/ProjectPackageManager.js:190:21)
    at async PackageManager.setRegistryEnvs (/usr/local/lib/node_modules/@vue/cli/lib/util/ProjectPackageManager.js:231:22)
    at async PackageManager.runCommand (/usr/local/lib/node_modules/@vue/cli/lib/util/ProjectPackageManager.js:332:5)
    at async PackageManager.install (/usr/local/lib/node_modules/@vue/cli/lib/util/ProjectPackageManager.js:377:12)
    at async Creator.create (/usr/local/lib/node_modules/@vue/cli/lib/Creator.js:216:7)
    at async create (/usr/local/lib/node_modules/@vue/cli/lib/create.js:72:3)
```

---
Want to learn vue, but I can't make a project. Tried to reinstall and clear cache without any success:
```
$ sudo npm uninstall -g vue
$ sudo npm uninstall -g vue-cli
$ sudo npm uninstall -g @vue/cli
$ sudo npm cache clean --force
$ sudo npm install -g vue
$ sudo npm install -g @vue/cli
```

**Comment by ndri** [comment]
Upgrading node.js to version 14.14.0 worked!
