### ISSUE TITLE
Error: Cannot find module 'ini'

### ISSUE THREAD

**Issue by rlam3** [vuejs/vue-cli#602]
Cannot init

```bash
XXX~$ node -v
v8.6.0
XXX~$ npm -v
5.3.0
XXX~$ vue -V
2.9.1


XXX~$ vue init 
module.js:529
    throw err;
    ^

Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vue-cli/node_modules/config-chain/index.js:4:11)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by posva** [comment]
Except for npm, which I have 5.4.2, I have the same versions and it doesn't show the error. Can you try removing it and reinstalling it again? What OS are you using?

**Comment by posva** [comment]
Closing due to inactivity. Please open a new issue with a reference to this one if you can follow up with more information.

**Comment by vitorbertulucci** [comment]
I'm have the same problem here but with a different module.

```
module.js:557
    throw err;
    ^

Error: Cannot find module 'slash'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/bin/vue:5:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```
Any solution or idea for what is happening?

npm version: 5.6.0
