### ISSUE TITLE
Error: Cannot find module 'babel-code-frame'

### ISSUE THREAD

**Issue by MrMic** [vuejs/vue-cli#6024]
### Version
4.5.8

### Environment info
```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) CPU           W3540  @ 2.93GHz
  Binaries:
    Node: 10.19.0 - /bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 82.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2 
    @vue/babel-plugin-jsx:  1.0.0-rc.3 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.8 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.8 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.8 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.8 
    @vue/cli-plugin-router:  4.5.8 
    @vue/cli-plugin-vuex:  4.5.8 
    @vue/cli-service: ~4.5.0 => 4.5.8 
    @vue/cli-shared-utils:  4.5.8 
    @vue/component-compiler-utils:  3.2.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.12 
    vue-eslint-parser:  7.1.1 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.4 (16.0.0-beta.9)
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.5.8
```

### Steps to reproduce
- Create a project with:
vue create my-project

- cd my-project
- and run:

npm run serve

> mon-project@0.1.0 serve /home/mic/DEVS/UDEMY/VueJS_A_Z/Section03/mon-project
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: Cannot find module 'babel-code-frame'
Error: Cannot find module 'babel-code-frame'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/share/nodejs/eslint/lib/formatters/codeframe.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at exports.loadModule (/home/mic/DEVS/UDEMY/VueJS_A_Z/Section03/mon-project/node_modules/@vue/cli-shared-utils/lib/module.js:79:14)
    at api.chainWebpack.webpackConfig (/home/mic/DEVS/UDEMY/VueJS_A_Z/Section03/mon-project/node_modules/@vue/cli-plugin-eslint/index.js:59:26)
    at webpackChainFns.forEach.fn (/home/mic/DEVS/UDEMY/VueJS_A_Z/Section03/mon-project/node_modules/@vue/cli-service/lib/Service.js:236:40)
    at Array.forEach (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mon-project@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mon-project@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### What is expected?
run the dev server

### What is actually happening?
Error - !crash

**Comment by fangbinwei** [comment]
It's weird error come from your global path `/usr/share/nodejs/eslint/lib/formatters/codeframe`. Could you provide a reproducible repo ?

**Comment by MrMic** [comment]
Thanks ! You give me thze clue to solve this issue.
I had installed eslint with my package manager (apt).
I remove and purge it and now all seems working.

Thank you! :+1:

**Comment by alexlopesbr** [comment]
Thank You so much MrMic, it's works for me

**Comment by LaurentReese** [comment]
I confirm what MrMic said : same problem (eslint), same solution.
