### ISSUE TITLE
vue ui 无法正常启动

### ISSUE THREAD

**Issue by longshibagithub** [vuejs/vue-cli#6154]
### Version
4.5.9

### Environment info
```
window10，node1016.0，@vue/cli 4.5.9
```

### Steps to reproduce
安装vuecli，然后运行vueui命令
试过cmd powershell git命令行
都跑不起来

### What is expected?
正常启动vueui

### What is actually happening?
报错
$ vue ui
�  Starting GUI...

CScript ����: �޷��ҵ��ű���C:\Users\xx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@akryum\winattr\lib\sh

ell\hostscript.js���Ľű����桰jscript����
^

SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at getParseResult (C:\Users\xx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@akryum\winattr\lib\shell\index.js:3
1:17)
    at C:\Users\xx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@akryum\winattr\lib\shell\index.js:102:14
    at ChildProcess.<anonymous> (C:\Users\xx\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@akryum\winattr\lib\shell\
index.js:84:5)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

---
想知道这种情况发生的原因以及如何能跑起来

**Comment by springxing** [comment]
只能降版本了，

**Comment by MaidSG** [comment]
我的解决办法就是先降到3.0.0，然后导入一个项目或者打开一个项目看看能不能正常显示，如果可以，再重新执行npm uninstall -g @vue/cli，安装了5.0.8的就可以了，cli4我试了4.4.6的，还是不行，可能与node.js的版本有关，因为之前我用cli4是可以的，但是不知道怎么node.js现在变成16.16就寄了
