### ISSUE TITLE
git init fails when trying to make a new 'vue create' app.

### ISSUE THREAD

**Issue by danjmillier** [vuejs/vue-cli#6184]
### Version
4.5.9

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.66)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue create quotes

### What is expected?
Should initalize a git repo based on name of project.

### What is actually happening?
Vue CLI v4.5.9
✨  Creating project in C:\Users\danjm\dev\quotes.
�  Initializing git repository...
 ERROR  Error: Command failed: git init
fatal: invalid branch name: init.defaultBranch =

Error: Command failed: git init
fatal: invalid branch name: init.defaultBranch =

    at makeError (C:\Users\danjm\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\execa\index.js:174:9)
    at C:\Users\danjm\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Creator.create (C:\Users\danjm\AppData\Roaming\npm\node_modules\@vue\cli\lib\Creator.js:204:7)
    at async create (C:\Users\danjm\AppData\Roaming\npm\node_modules\@vue\cli\lib\create.js:72:3)

**Comment by sodatea** [comment]
This seems to be caused by the git configuration on your machine. Please try to run this command: `git config --global init.defaultBranch main` before creating the project.

**Comment by danjmillier** [comment]
> This seems to be caused by the git configuration on your machine. Please try to run this command: `git config --global init.defaultBranch main` before creating the project.

@sodatea, that did it! :) Weird though, I could of sworn I did that command awhile ago. Appreciate the help!
