### ISSUE TITLE
Vue UI 应该在用户尝试创建含有大写字母的项目时提出警告

### ISSUE THREAD

**Issue by cesaryuan** [vuejs/vue-cli#6248]
### Version
4.5.11

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 14.15.1 - E:\mysoftware\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - E:\mysoftware\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.53)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
使用 Vue UI 随便创建一个名字含有大写字母（比如Upper）的项目，项目不需要任何内容，只要名字含有大写字母就可以。
创建成功后 build，就会报错（错误信息放在了补充说明）。

### What is expected?
网页中直接禁止含有大写字母的项目名称，而不是擅自将大写字母转成小写（因为这并不能得到一个正常的项目）

### What is actually happening?
网页并没有禁止大写字母（尽管我注意到会自动将项目名称转为全小写），并且当我创建一个含有大写字母的项目是，创建过程是没有报错的，但是创建完成后，Build 的过程确会出错。
当我去掉名称中的大写字母后，创建和 Build 的过程就完全正常了。

---
-  Building for production...

 ERROR  Error: No module factory available for dependency type: CssDependency
Error: No module factory available for dependency type: CssDependency
    at addDependency (E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compilation.js:800:12)
    at iterationOfArrayCallback (E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compilation.js:208:3)
    at addDependenciesBlock (E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compilation.js:816:5)
    at Compilation.processModuleDependencies (E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compilation.js:827:4)
    at afterBuild (E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compilation.js:954:15)
    at E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compilation.js:998:11
    at callback (E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compilation.js:734:5)
    at E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compilation.js:782:12
    at handleParseResult (E:\Desktop\vuetest\abac\node_modules\webpack\lib\NormalModule.js:478:12)
    at E:\Desktop\vuetest\abac\node_modules\webpack\lib\NormalModule.js:500:6
    at E:\Desktop\vuetest\abac\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\Desktop\vuetest\abac\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\Desktop\vuetest\abac\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at E:\Desktop\vuetest\abac\node_modules\loader-runner\lib\LoaderRunner.js:186:6
    at context.callback (E:\Desktop\vuetest\abac\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at E:\Desktop\vuetest\AbAc\node_modules\mini-css-extract-plugin\dist\loader.js:199:12
    at E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compiler.js:343:11
    at E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\Desktop\vuetest\abac\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (E:\Desktop\vuetest\abac\node_modules\tapable\lib\Hook.js:154:20)
    at E:\Desktop\vuetest\abac\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (E:\Desktop\vuetest\abac\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)

E:\Desktop\vuetest\abac\node_modules\neo-async\async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (E:\Desktop\vuetest\abac\node_modules\neo-async\async.js:16:11)
    at E:\Desktop\vuetest\abac\node_modules\neo-async\async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

Total task duration: 4.98s

**Comment by fredgan** [comment]
我使用4.5.11版本的cli尝试复现该问题，尝试创建了2个项目，然而，创建完之后的项目都是可以正常构建的，并没有发现你所说的这个错误。

我又再看了一下你的这个错误，看起来像是创建项目过程中下载依赖失败导致。
建议再多试一下，看看该问题必现的。

**Comment by cesaryuan** [comment]
谢谢您的回复，为了证明该问题在我这是稳定复现的，我录制了一个不到1分钟的视频。该视频控制了所有变量，包括网络环境等等都是相同的，唯一不同的就是项目名的大小写，希望您可以看一下。

https://user-images.githubusercontent.com/35998162/106740825-e24ecb00-6655-11eb-80a4-36a8db134f20.mp4
