### ISSUE TITLE
SyntaxError: Unexpected token  

### ISSUE THREAD

**Issue by blinglee** [vuejs/vue-cli#633]
First of all, I'm a rookie，I've been studying a tutorial on VUE.JS in Imooc， It was a mistake at first。
my OS is Window 7-64,node version is V4.5.5,
I've gone through an order   $ npm install -g vue-cli  ，It worked，
but I execute another order vue list 

C:\Users\Administrator\AppData\Roaming\npm\node_modules\vue-cli\lib\logger.js:17

exports.log = function (...args) {
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\vue-cli\bin\vue-list:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by posva** [comment]
Hey, you'll get faster replies on the [forum](http://forum.vuejs.org/) and the [Discord server](https://vue-land.js.org/) 😉 .

---

Try upgrading node to version 8

**Comment by blinglee** [comment]
thank you , I upgraded node to the latest version，it works
