### ISSUE TITLE
some errors happen when i vue init webpack projectname

### ISSUE THREAD

**Issue by tangshengzhi** [vuejs/vue-cli#636]
let template = program.args[0]
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

**Comment by RokkerRuslan** [comment]
Your npm and Node.js versions? (Prerequisites: Node.js (>=4.x, 6.x preferred), npm version 3+)

**Comment by tangshengzhi** [comment]
Node.js  v5.0.0  npm3.3.6

**Comment by HaitianLiu** [comment]
@tangshengzhi You need update your node. This only works on node >=6.0.0
