### ISSUE TITLE
The local run build package is normal, but the code is submitted to our company to Gerrit, and Jenkins can not verify it

### ISSUE THREAD

**Issue by W-ChenAMG** [vuejs/vue-cli#6364]
### Version
4.5.12

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/new/choose](https://github.com/vuejs/vue-cli/issues/new/choose)

### Environment info
```
Local node version 10.24, Gerrit node version 11.15.0. I can't upgrade the local node just like Gerrit. Gerrit reports an error
```

### Steps to reproduce
up to date in 8.153s
  /usr/local/bin/npm run build

> project-one@0.1.0 build /home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription
> vue-cli-service build

 ERROR  Error loading /home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription/vue.config.js:
(node:3965) ExperimentalWarning: queueMicrotask() is experimental.
 ERROR  ReferenceError: globalThis is not defined
ReferenceError: globalThis is not defined
    at Object.<anonymous> (/home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription/node_modules/queue-microtask/index.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription/node_modules/run-parallel/index.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-one@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project-one@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2021-03-19T03_04_54_376Z-debug.log
  echo npm build failed

### What is expected?
up to date in 8.153s
  /usr/local/bin/npm run build

> project-one@0.1.0 build /home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription
> vue-cli-service build

 ERROR  Error loading /home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription/vue.config.js:
(node:3965) ExperimentalWarning: queueMicrotask() is experimental.
 ERROR  ReferenceError: globalThis is not defined
ReferenceError: globalThis is not defined
    at Object.<anonymous> (/home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription/node_modules/queue-microtask/index.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription/node_modules/run-parallel/index.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-one@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project-one@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2021-03-19T03_04_54_376Z-debug.log
  echo npm build failed

### What is actually happening?
up to date in 8.153s
  /usr/local/bin/npm run build

> project-one@0.1.0 build /home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription
> vue-cli-service build

 ERROR  Error loading /home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription/vue.config.js:
(node:3965) ExperimentalWarning: queueMicrotask() is experimental.
 ERROR  ReferenceError: globalThis is not defined
ReferenceError: globalThis is not defined
    at Object.<anonymous> (/home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription/node_modules/queue-microtask/index.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/jenkins/workspace/upload_html5_industry_wash_all/HTML5/industry/wash_functiondescription/node_modules/run-parallel/index.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-one@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project-one@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jenkins/.npm/_logs/2021-03-19T03_04_54_376Z-debug.log
  echo npm build failed

**Comment by fangbinwei** [comment]
Close via https://github.com/feross/queue-microtask/issues/17
