### ISSUE TITLE
Vue cli broken after updating to latest stable with npm

### ISSUE THREAD

**Issue by Nilpo** [vuejs/vue-cli#6395]
### Version
4.5.12

### Environment info
```
/home/user/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/node_modules/node-ipc/dao/client.js:13
class Client extends Events{
                     ^

TypeError: Class extends value #<Object> is not a constructor or null
    at Object.<anonymous> (/home/user/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/node_modules/node-ipc/dao/client.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/node_modules/node-ipc/services/IPC.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

### Steps to reproduce
npm install -g @vue/cli
v 4.5.12 install completes with no errors
Run the vue command in any context

### What is expected?
Vue should execute with no errors

### What is actually happening?
/home/user/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/node_modules/node-ipc/dao/client.js:13
class Client extends Events{
                     ^

TypeError: Class extends value #<Object> is not a constructor or null
    at Object.<anonymous> (/home/user/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/node_modules/node-ipc/dao/client.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v14.16.0/lib/node_modules/@vue/cli/node_modules/node-ipc/services/IPC.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

---
This install has been working flawlessly before now. Unfortunately, I don't know what the working version of the cli was.

**Comment by Nilpo** [comment]
Purging @vue/cli and starting over worked.

    npm uninstall @vue/cli -g
    npm install -g @vue/cli
