### ISSUE TITLE
Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'

### ISSUE THREAD

**Issue by rmlzy** [vuejs/vue-cli#6468]
### Version
4.5.13

### Reproduction link
[https://github.com/rmlzy/vue3-npm6.4.1](https://github.com/rmlzy/vue3-npm6.4.1)

### Environment info
```
node v10.15.1
npm 6.4.1
```

### Steps to reproduce
1. Create repo with @vue/cli@^4.5.13, (ts enabled).
2. Use node@10.15.1 and npm@6.4.1
3. Exec `npm run serve`

### What is expected?
Lift the dev server without errors

### What is actually happening?
I got an error:

Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'

**Comment by rmlzy** [comment]
In fact, when I first executed `npm run serve`, I got the error:

```
$ npm run serve
> vue3-npm6.4.1@0.1.0 serve /Users/rmlzy/Documents/mygithub/vue3-npm6.4.1
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: Cannot find module 'vue-loader-v16/package.json'
Error: Cannot find module 'vue-loader-v16/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at api.chainWebpack.webpackConfig (/Users/rmlzy/Documents/mygithub/vue3-npm6.4.1/node_modules/@vue/cli-service/lib/config/base.js:114:23)
    at webpackChainFns.forEach.fn (/Users/rmlzy/Documents/mygithub/vue3-npm6.4.1/node_modules/@vue/cli-service/lib/Service.js:236:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/rmlzy/Documents/mygithub/vue3-npm6.4.1/node_modules/@vue/cli-service/lib/Service.js:236:26)
    at Service.resolveWebpackConfig (/Users/rmlzy/Documents/mygithub/vue3-npm6.4.1/node_modules/@vue/cli-service/lib/Service.js:240:48)
    at PluginAPI.resolveWebpackConfig (/Users/rmlzy/Documents/mygithub/vue3-npm6.4.1/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue3-npm6.4.1@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue3-npm6.4.1@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rmlzy/.npm/_logs/2021-05-11T07_21_37_584Z-debug.log
```

I tried to run `npm i --save-dev vue-loader-v16` and the error disappeared, but i got another error:
```
$ npm run serve
Error: Cannot find module 'fork-ts-checker-webpack-plugin-v5'
```

**Comment by sodatea** [comment]
Vue 3 support in Vue CLI uses the package alias feature of NPM.
NPM only supports this feature in >= v6.9.
