### ISSUE TITLE
Vue 2 error after serving 

### ISSUE THREAD

**Issue by saeedshabani** [vuejs/vue-cli#6572]
### Version
2.6.11

### Reproduction link
[https://github.com/saeedshabani/newapp](https://github.com/saeedshabani/newapp)

### Steps to reproduce
After install vue v2, and run `npm run serve` I got this error

### What is expected?
How can i solve this issue?

### What is actually happening?

```
    > newapp@0.1.0 serve
    > vue-cli-service serve

    npm ERR! code ENOENT
    npm ERR! syscall spawn bash
    npm ERR! path D:\FrontEnd\newapp
    npm ERR! errno -4058
    npm ERR! enoent spawn bash ENOENT
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\DigiMax\AppData\Local\npm-cache\_logs\2021-07-05T06_24_11_998Z-debug.log

```

**Comment by standbyoneself** [comment]
Works fine
<img width="1440" alt="Screenshot 2021-07-06 at 17 56 17" src="https://user-images.githubusercontent.com/57719759/124622233-9a8dd300-de83-11eb-94f9-86c7113dc3af.png">

`rm -rf node_modules`

`npm cache clean -f`

**Comment by saeedshabani** [comment]
But in my system, it's not work fine. it's full log :

```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\DigiMax\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'serve'
0 verbose cli ]
1 info using npm@7.19.1
2 info using node@v14.17.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\DigiMax\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:D:\FrontEnd\newapp\.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\DigiMax\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\DigiMax\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 12ms
26 timing config:load:flatten Completed in 2ms
27 timing command:run-script Completed in 16ms
28 verbose stack Error: spawn bash ENOENT
28 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
28 verbose stack     at onErrorNT (internal/child_process.js:467:16)
28 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
29 verbose pkgid newapp@0.1.0
30 verbose cwd D:\FrontEnd\newapp
31 verbose Windows_NT 10.0.18363
32 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\DigiMax\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
33 verbose node v14.17.2
34 verbose npm  v7.19.1
35 error code ENOENT
36 error syscall spawn bash
37 error path D:\FrontEnd\newapp
38 error errno -4058
39 error enoent spawn bash ENOENT
40 error enoent This is related to npm not being able to find a file.
41 verbose exit -4058

```

**Comment by standbyoneself** [comment]
Give the full log of `C:\Users\DigiMax\AppData\Local\npm-cache\_logs\2021-07-05T06_24_11_998Z-debug.log`

Which version of the `node` you are using?

**Comment by saeedshabani** [comment]
@standbyoneself Here you are

npm@7.19.1
node@v14.17.2

**Comment by standbyoneself** [comment]
@saeedshabani,

Sorry for my carelessness. Do you have succeeded-start projects powered by vue2? Is this project an exception?

**Comment by saeedshabani** [comment]
@standbyoneself 

In past week all things works fine, But at this time i have this problem with vue2 , I also have the same problem with vue 3 and react app.

**Comment by standbyoneself** [comment]
@saeedshabani,

Would you try to reinstall the node.js? Let's find the problem step by step

**Comment by saeedshabani** [comment]
Yes i try to reinstall node js and npm, clear npm cache but nothing changes

**Comment by saeedshabani** [comment]
Thanks @standbyoneself

This problem solve by "running VSCode as administrator"
