### ISSUE TITLE
transpileDependencies option is ignored in build --modern

### ISSUE THREAD

**Issue by slaweet** [vuejs/vue-cli#6619]
### Version
4.5.13

### Reproduction link
[https://github.com/slaweet/vue-cli-numeric-separator-issue/commits/main](https://github.com/slaweet/vue-cli-numeric-separator-issue/commits/main)

### Environment info
```
$ vue info

Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 90.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.6 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router:  4.5.13 
    @vue/cli-plugin-vuex:  4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/component-compiler-utils:  3.2.2 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.14 
    vue-eslint-parser:  7.10.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.8 (16.4.1)
    vue-style-loader:  4.1.3 
    vue-template-compiler: ^2.6.11 => 2.6.14 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
In the minimal reproduction repo, run:
```
yarn install;
yarn build --modern
```

### What is expected?
When the `transpileDependencies` config is specified, then `yarn build --modern` succeeds in the same way as ` yarn build` (without the --modern flag) does.

### What is actually happening?
```
 ERROR  Failed to compile with 1 error                                                                                                             9:28:13 AM

 error  in ./node_modules/color/index.js

Module parse failed: Identifier directly after number (64:18)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/thread-loader/dist/cjs.js
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   } else if (typeof object === 'number') {
|     // This is always RGB - can be converted later on.
>     object &= 0xFF_FF_FF;
|     this.model = 'rgb';
|     this.color = [object >> 16 & 0xFF, object >> 8 & 0xFF, object & 0xFF];

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js& 9:0-26 10:12-17
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.
 ERROR  Error: Command failed: node /home/slaweet/git/vue-cli-numeric-separator-issue/node_modules/@vue/cli-service/bin/vue-cli-service.js build --modern
Error: Command failed: node /home/slaweet/git/vue-cli-numeric-separator-issue/node_modules/@vue/cli-service/bin/vue-cli-service.js build --modern
    at makeError (/home/slaweet/git/vue-cli-numeric-separator-issue/node_modules/execa/index.js:174:9)
    at /home/slaweet/git/vue-cli-numeric-separator-issue/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/slaweet/git/vue-cli-numeric-separator-issue/node_modules/@vue/cli-service/lib/commands/build/index.js:66:9
error Command failed with exit code 1.
```

---
There is no mention in the docs https://cli.vuejs.org/config/#transpiledependencies that it should not work with --modern

Some more context:
I have found out  this because I was trying to work around https://github.com/Qix-/color/issues/206 which the maintainer refuses to resolve.

**Comment by david-l-riley** [comment]
I am running into this issue as well. It's not insurmountable for us, since the separators are (AFAICT) only in an internal package, but it did take a while to figure out what was breaking, and that doesn't guarantee an external dependency won't add it later.

I know underscore separators are a relatively recent feature, but allowing `transpileDependencies` does seem like a reasonable thing if this is to target a specific (slightly older) ES standard for `--modern`, as more packages are beginning to add these.

**Comment by david-l-riley** [comment]
Spoke too soon, this is a problem for us because the separators are added in generated code from `ts-proto`, which uses them by default. For the moment we've just patched the generated code, but that's not going to be a scalable option as more upstream packages use these features.
