### ISSUE TITLE
"Minimizer function doesn't return result" error with 5.0.0-beta.4

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/vue-cli#6723]
### Version
5.0.0-beta.4

### Reproduction link
[github.com/cexbrayat/css-mini](https://github.com/cexbrayat/css-mini)

### Environment info
```
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 14.17.6 - ~/.volta/tools/image/node/14.17.6/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.14 - ~/.volta/tools/image/npm/6.14.14/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Edge: Not Found
    Firefox: 92.0.1
    Safari: 15.0
  npmPackages:
    @vue/cli-overlay:  5.0.0-beta.4
    @vue/cli-plugin-router:  5.0.0-beta.4
    @vue/cli-plugin-typescript: ~5.0.0-beta.4 => 5.0.0-beta.4
    @vue/cli-plugin-vuex:  5.0.0-beta.4
    @vue/cli-service: ~5.0.0-beta.4 => 5.0.0-beta.4
    @vue/cli-shared-utils:  5.0.0-beta.4
    @vue/compiler-core:  3.2.19
    @vue/compiler-dom:  3.2.19
    @vue/compiler-sfc: ^3.2.6 => 3.2.19
    @vue/compiler-ssr:  3.2.19
    @vue/component-compiler-utils:  3.2.2
    @vue/reactivity:  3.2.19
    @vue/ref-transform:  3.2.19
    @vue/runtime-core:  3.2.19
    @vue/runtime-dom:  3.2.19
    @vue/server-renderer:  3.2.19
    @vue/shared:  3.2.19
    @vue/web-component-wrapper:  1.3.0
    typescript: ~4.1.5 => 4.1.6
    vue: ^3.2.6 => 3.2.19
    vue-hot-reload-api:  2.3.4
    vue-loader:  16.8.1 (15.9.8)
    vue-style-loader:  4.1.3
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Create a new app with CLI v5.0.0-beta.4:
```
npx -p @vue/cli@next vue create css-mini --inlinePreset '{"useConfigFiles": true,"plugins": {"@vue/cli-plugin-typescript": {"classComponent": false}},"vueVersion": "3"}'
```

Add bootstrap
```
cd css-mini
npm install --save-exact bootstrap
```

Use bootstrap in `App.vue`
```vue
<template>
  <h1>Hello</h1>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "App",
});
</script>

<style>
@import "~bootstrap/dist/css/bootstrap.min.css";
</style>
```

Run:
```
yarn build
```

Or just run `yarn build` in the repro repository https://github.com/cexbrayat/css-mini

### What is expected?
Should build without errors

### What is actually happening?
Throws:
```
⠋  Building for production...

 ERROR  Failed to compile with 1 error                                                                                               10:18:52

 error  in css/app.8a97e00d.css

css/app.8a97e00d.css from Css Minimizer Plugin
Error: Minimizer function doesn't return result
    at minify (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/css-minimizer-webpack-plugin/dist/minify.js:29:13)
    at async Object.transform (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/css-minimizer-webpack-plugin/dist/minify.js:62:18)

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/lib/webpack.js:141:8
    at /Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/lib/Cache.js:150:23)
    at /Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/lib/Compiler.js:1156:15
    at Hook.eval [as callAsync] (eval at create (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/lib/Compiler.js:1149:23)
error Command failed with exit code 1.
```

---
https://github.com/webpack-contrib/css-minimizer-webpack-plugin/releases/tag/v3.1.0 was released yesterday and the CLI allows `css-minimizer-webpack-plugin: ^3.0.2` to be installed

Maybe this is an upstream issue, but in the meantime forcing a resolution to `css-minimizer-webpack-plugin@3.0.2` fixes the build and should unblock creating new applications with the CLI v5.

**Comment by cexbrayat** [comment]
I reported the issue upstream https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/126

In the meantime, I opened a PR to set the version to v3.0.2 in the CLI to fix the regression. See #6724
