### ISSUE TITLE
Fail when running devServer

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vue-cli#6738]
### Version
5.0.0-beta.5

### Reproduction link

just-a-fresh-template-with-clean-install

### Environment info
```
vue: The term 'vue' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

# I am not sure, but which package is providing a vue command?
```

### Steps to reproduce
Just open the devServer

### What is expected?
No error

### What is actually happening?
Because `webpack-dev-server` is validating config, so the project won't work.

```
 vue-cli-service serve
 INFO  Starting development server...
[1%] setup (initialize)
 ERROR  ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
         - options has an unknown property 'overlay'. These properties are valid:
           object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, setupExitSignals?, static?, watchFiles?, webSocketServer? }
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'overlay'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, setupExitSignals?, static?, watchFiles?, webSocketServer? }
    at validate (F:\template\vue\node_modules\schema-utils\dist\validate.js:105:11)
    at new Server (F:\template\vue\node_modules\webpack-dev-server\lib\Server.js:31:5)
    at serve (F:\template\vue\node_modules\@vue\cli-service\lib\commands\serve.js:183:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.
```

**Comment by Mister-Hope** [comment]
https://github.com/Mister-Hope/vue-template

**Comment by LinusBorg** [comment]
https://github.com/Mister-Hope/vue-template/blob/295e33c03d272753f3425060e69628c1e7f14197/vue.config.js#L78-L81

These are not valid webpack-dev-server options ([see docs](https://webpack.js.org/configuration/dev-server/)). And that's what the error message is telling you.

Why do you have them in the config? What do you think they do?
