### ISSUE TITLE
ERROR  ValidationError: Progress Plugin Invalid Options

### ISSUE THREAD

**Issue by Icacls** [vuejs/vue-cli#6840]
### Version
5.0.0-rc.1

### Environment info
```
node: v12.22.0
@vue/cli 5.0.0-rc.1
npm:7.20.3
```

### Steps to reproduce
Migrate from v4

### What is expected?
project working good

### What is actually happening?
not ok

---
 INFO  Starting development server...
 ERROR  ValidationError: Progress Plugin Invalid Options

        options should NOT have additional properties
        options should NOT have additional properties
        options should NOT have additional properties
        options should pass "instanceof" keyword validation
        options should match exactly one schema in oneOf

ValidationError: Progress Plugin Invalid Options

options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

    at validateOptions (/Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/webpack/node_modules/schema-utils/src/validateOptions.js:32:11)
    at new ProgressPlugin (/Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/webpack/lib/ProgressPlugin.js:62:3)
    at new Progress (/Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/progress-webpack-plugin/index.js:25:21)
    at new progressPlugin (/Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/progress-webpack-plugin/index.js:127:10)
    at /Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/webpack-chain/src/Plugin.js:14:18
    at Object.toConfig (/Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/webpack-chain/src/Plugin.js:78:22)
    at /Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/webpack-chain/src/Config.js:129:63
    at Array.map (<anonymous>)
    at module.exports.toConfig (/Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/webpack-chain/src/Config.js:129:40)
    at Service.resolveWebpackConfig (/Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/@vue/cli-service/lib/Service.js:261:34)
    at PluginAPI.resolveWebpackConfig (/Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/@vue/cli-service/lib/commands/serve.js:73:31)
    at Service.run (/Users/Documents/WORKSPACE/JTeam/test/packages/jms-web-main/node_modules/@vue/cli-service/lib/Service.js:246:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.

**Comment by 695648896** [comment]
您好！请问是如何解决它的，我也碰到了一样的错误

**Comment by 695648896** [comment]
> 您好！请问是如何解决它的，我也碰到了一样的错误
您好，我已正常运行
删除package-lock.json和nodemodules
执行npm cache clean --force
重新执行 npm i
npm run serve 即可正常运行

**Comment by Icacls** [comment]
检查下有没有package peerDependencies 包含webpack4.x

**Comment by Icacls** [comment]
> 您好！请问是如何解决它的，我也碰到了一样的错误

检查下有没有package peerDependencies 包含webpack4.x

**Comment by rehack** [comment]
我也遇到同样的报错，不知道咋解决，上面的方法也不管用

**Comment by leopold537** [comment]
I have the same issue. I was trying to disable progress with:
```js
devServer: {
  progress: false,
},
```
in vue.config.js but it ends with "ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema." because the progress option has been moved to the "client" property in Webpack 5.

For now, I commented out lines 63-68 in node_modules\@vue\cli-service\lib\commands\serve.js
```js
// if (!process.env.VUE_CLI_TEST && options.devServer.progress !== false) {
//   // the default progress plugin won't show progress due to infrastructreLogging.level
//   webpackConfig
//     .plugin('progress')
//     .use(require('progress-webpack-plugin'))
// }
```

**Comment by websharik** [comment]
`process.env.VUE_CLI_TEST = false` to up `vue.config.js` fix that.

**Comment by regazzoj** [comment]
I just did what websharik, and it was working but I still had a warning which was =>
`(node:9149) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
(Use `node --trace-deprecation ...` to show where the warning was created)`

I found this [SO post](https://stackoverflow.com/questions/69931346/vue-3-and-vuetify-3-alpha-validationerror-progress-plugin-invalid-options) which said to run `npm update` and re-create the project.
I only did the former and it worked like a charm in case anyone got the same problem.

**Comment by ChendayUP** [comment]
看看webpack中使用的plugin是否有不兼容的, 我这边是compression-webpack-plugin 升级到7.1.2, script-ext-html-webpack-plugin不支持webpack5, 去掉, 然后就好了

**Comment by king-open** [comment]
👆 的 方法 不管用

**Comment by W01fh4cker** [comment]
> > 您好！请问是如何解决它的，我也碰到了一样的错误
> > 您好，我已正常运行
> > 删除package-lock.json和nodemodules
> > 执行npm cache clean --force
> > 重新执行 npm i
> > npm run serve 即可正常运行

按照您这个方法解决成功了，感谢！
