### ISSUE TITLE
"serve" breaks itself using an another name instead of index.html (build works good)

### ISSUE THREAD

**Issue by Vector-Green** [vuejs/vue-cli#6847]
### Version
5.0.0-rc.1

### Reproduction link
[github.com](https://github.com/Vector-Green/vue3Glitch.git)

### Environment info
```
project presset
  "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-typescript": {
          "classComponent": true,
          "useTsWithBabel": true
        },
        "@vue/cli-plugin-router": {
          "historyMode": true
        },
        "@vue/cli-plugin-vuex": {},
        "@vue/cli-plugin-eslint": {
          "config": "prettier",
          "lintOn": [
            "save"
          ]
        },
        "@vue/cli-plugin-unit-jest": {},
        "@vue/cli-plugin-e2e-cypress": {}
      },
      "vueVersion": "3",
      "cssPreprocessor": "dart-sass"

webpack@5.64.2
vue@3.2.22

Environment Info:
  System:
    OS: Windows 10 10.0.17763
    CPU: (2) x64 Intel(R) Celeron(R) CPU G3930 @ 2.90GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Not Found
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce way №1
//copy this in an empty vue.config.js
```
const { defineConfig } = require("@vue/cli-service");
module.exports = defineConfig({
  transpileDependencies: true,

  chainWebpack: (config) => {
    config.plugin("html").tap((args) => {
      Object.assign(args[0], {
        filename: "[contenthash].html",
      });
      return args;
    });
  },

});
```
also instead of way №1 you can cause an error using another way
### Steps to reproduce way №2
//copy this in an empty vue.config.js
```
const { defineConfig } = require("@vue/cli-service");
module.exports = defineConfig({
  transpileDependencies: true,

  pages: {
    index: {
      entry: "src/main.ts",
      filename: "[contenthash].html",
    },
  },
  
});

````
### Steps to reproduce way №3
//copy this in an empty vue.config.js
```
const HtmlWebpackPlugin = require("html-webpack-plugin");

const { defineConfig } = require("@vue/cli-service");

module.exports = defineConfig({
  transpileDependencies: true,

  chainWebpack: (config) => {
    config.plugins.delete("html");
  },
  configureWebpack: {
    plugins: [
      new HtmlWebpackPlugin({
        title: "test",
        filename: "[contenthash].html",
        template: "public/index.html",
        publicPath: "/",
      }),
    ],
  },

});

```
### Logs
```
No issues found.
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.options.publicPath%20%%3Efavicon.svg'
    at decodeURIComponent (<anonymous>)
    at decode_param (D:\Projects\FrontEnd\node_modules\express\lib\router\layer.js:172:12)
    at Layer.match (D:\Projects\FrontEnd\node_modules\express\lib\router\layer.js:123:27)
    at matchLayer (D:\Projects\FrontEnd\node_modules\express\lib\router\index.js:574:18)
    at next (D:\Projects\FrontEnd\node_modules\express\lib\router\index.js:220:15)
    at expressInit (D:\Projects\FrontEnd\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\Projects\FrontEnd\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Projects\FrontEnd\node_modules\express\lib\router\index.js:317:13)
    at D:\Projects\FrontEnd\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Projects\FrontEnd\node_modules\express\lib\router\index.js:335:12)
```

### What is expected?
yarn serve should generate [contenthash].html (in default)
```
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    <title>test</title>
    <script defer="defer" src="/js/chunk-vendors.bc77563e.js"></script>
    <script defer="defer" src="/js/app.339977b8.js"></script>
    <link href="/css/app.b1d1061b.css" rel="stylesheet" />
  </head>
  <body>
    <noscript
      ><strong
        >We're sorry but test doesn't work properly without JavaScript enabled.
        Please enable it to continue.</strong
      ></noscript
    >
    <div id="app"></div>
  </body>
</html>
```

### What is actually happening?
yarn serve is generating [contenthash].html (in default)
```
<html lang="" data-lt-installed="true"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    <title>&lt;%= htmlWebpackPlugin.options.title %&gt;</title>
</head>
  <body>
    <noscript>
      <strong>We're sorry but <%= htmlWebpackPlugin.options.title %> doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  

</body></html>
```

With **yarn build --mode development** or **yarn build** everything works correctly
but **yarn serve --mode production** or just **yarn serve** makes a glitch
any another name instead of *index.html* for example *1.html* or *[contenthash].html* will also make this issue

```
<link rel="icon" href="<%= BASE_URL %>favicon.ico">
<title>&lt;%= htmlWebpackPlugin.options.title %&gt;</title>
```
instead of 
```
<link rel="icon" href="/favicon.ico" />
<title>test</title>

```

**Comment by Vector-Green** [comment]
So far I've found such a solution for myself
vue.config.js
```
 filename:
        process.env.VUE_APP_PROCEDURE === "build"
          ? "[contenthash].html"
          : "index.html",
```
```
//package.json
"scripts": {
    "serve": "set VUE_APP_PROCEDURE=serve& vue-cli-service serve",
    "build": "set VUE_APP_PROCEDURE=build& vue-cli-service build",
}
```
