### ISSUE TITLE
VueUI crashed after creating Vue Project

### ISSUE THREAD

**Issue by dextercai** [vuejs/vue-cli#6857]
### Version
4.5.15

### Environment info
```
Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
npm@8.1.4
node@17.2.0
```

### Steps to reproduce
after create Vue Project

### What is expected?
Vue UI not crashed

### What is actually happening?
```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/Users/dextercai/project/xxxxxx/node_modules/@vue/cli-service/locales'
    at Object.readdirSync (node:fs:1390:3)
    at exports.readdir (/opt/homebrew/lib/node_modules/@vue/cli/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/opt/homebrew/lib/node_modules/@vue/cli/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/opt/homebrew/lib/node_modules/@vue/cli/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at Readable.DirectoryReader.stream._read (/opt/homebrew/lib/node_modules/@vue/cli/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:496:27)
    at readdirSync (/opt/homebrew/lib/node_modules/@vue/cli/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/opt/homebrew/lib/node_modules/@vue/cli/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/opt/homebrew/lib/node_modules/@vue/cli/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/opt/homebrew/lib/node_modules/@vue/cli/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/dextercai/project/xxxxxx/node_modules/@vue/cli-service/locales'
}
```

**Comment by thejaylee** [comment]
I had the same problem. I rolled node back to 16.13.1 (LTS) and that seemed to solve it 🤷‍♂️

**Comment by bodograumann** [comment]
Thank @thejaylee that helped me as well.
Given that vue-cli is only in maintenance mode now, is there an alternative like `vue ui` for vite?
