### ISSUE TITLE
Vue UI throws error message 'cannot read properties of undefined (reading 'indexOf')'

### ISSUE THREAD

**Issue by ziadomalik** [vuejs/vue-cli#6880]
### Version
5.0.0-rc.1

### Environment info
```

  System:
    OS: Linux 5.4 Zorin OS 15.3
    CPU: (4) x64 Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.15 - /snap/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 80.0.1
  npmGlobalPackages:
    @vue/cli: 4.5.15

```

### Steps to reproduce
1. Open VSCode.
2. Type `vue ui` into the integrated terminal.
3. Choose a name and npm in the first setup page.
4. Choose default Vue 3 with Babel Preset in the next page.
5. Proceed with your choices.

### What is expected?
Vue UI creates a project.

### What is actually happening?

**Vue UI shows a red screen with the error message:**
![Screenshot_2021-12-18_01-25-34](https://user-images.githubusercontent.com/95140266/146622568-f883ce52-ecd5-4737-a7ef-ed1ec4c81e35.png)

'cannot read properties of undefined (reading 'indexOf')'

**This is what you see in the terminal:**
![Screenshot_2021-12-18_01-26-11](https://user-images.githubusercontent.com/95140266/146622581-b0fe2003-203c-4825-85b5-94b327f81251.png)

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at /home/zmalik/.nvm/versions/node/v16.13.1/lib/node_modules/@vue/cli/node_modules/@vue/cli-ui/apollo-server/connectors/projects.js:283:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.wrap (/home/zmalik/.nvm/versions/node/v16.13.1/lib/node_modules/@vue/cli/node_modules/@vue/cli-ui/apollo-server/connectors/progress.js:39:14)

**Comment by KKKZOZ** [comment]
I have the same problem,too
If I toggle on the choice "CSS Pre-processors", the problem would happen
![image](https://user-images.githubusercontent.com/70520782/150683921-75ad4098-09b7-490e-9a38-9365a5542b74.png)
But if I toggle it off, everything goes well

**Comment by vivian1223** [comment]
I have same issue too!!
I've remove node modules and @vue/cli, and then install then again, still cannot solve this problem.
I've also tried clean npm cache, but nothing happened :( 
For most important, i need sass-loader to use sass, but from the comment above, toggle off the CSS pre-processor is not a good idea for me.

node version: v16.13.2
@vue/cli  version: v4.5.15
<img width="503" alt="截圖 2022-02-03 下午9 17 59" src="https://user-images.githubusercontent.com/65521038/152351530-8c8fa3cf-0f15-43d6-995e-c9d5c98b84bd.png">

**Comment by KKKZOZ** [comment]
> I have same issue too!! I've remove node modules and @vue/cli, and then install then again, still cannot solve this problem. I've also tried clean npm cache, but nothing happened :( For most important, i need sass-loader to use sass, but from the comment above, toggle off the CSS pre-processor is not a good idea for me.
> 
> node version: v16.13.2 @vue/cli version: v4.5.15 <img alt="截圖 2022-02-03 下午9 17 59" width="503" src="https://user-images.githubusercontent.com/65521038/152351530-8c8fa3cf-0f15-43d6-995e-c9d5c98b84bd.png">

I have solved this problem but can not remeber clearly how....
Probably your project name is like "xxx_xxx"(include "_")?
 Try to change anther project name?("xxx-xxx")

**Comment by vivian1223** [comment]
> I have solved this problem but can not remeber clearly how.... Probably your project name is like "xxx_xxx"(include "_")? Try to change anther project name?("xxx-xxx")

I've tried these two way of naming project, they both worked well before.
I've finally found my issue!!! Sometimes Vue ui will auto set the package manager into yarn while i didn't set install yarn before.

So i use the command : 
```shell=
$ npm install -g yarn
```
then solve the problem!
