### ISSUE TITLE
Building for production...Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by amcardle** [vuejs/vue-cli#6885]
Unable to build using vue-cli on Windows 10

### Node Version
<pre>
C:\Users\andre\code\vue-template>node --version
v17.3.0
</pre>

### Attempt to run build command
<pre>

C:\Users\andre\code\vue-template>npm run build

> vue-template@0.1.0 build
> vue-cli-service build

|  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\andre\code\vue-template\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\andre\code\vue-template\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\andre\code\vue-template\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\andre\code\vue-template\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\andre\code\vue-template\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\andre\code\vue-template\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\andre\code\vue-template\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
-  Building for production...C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\andre\code\vue-template\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\andre\code\vue-template\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\andre\code\vue-template\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\andre\code\vue-template\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\andre\code\vue-template\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (C:\Users\andre\code\vue-template\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\andre\code\vue-template\node_modules\cache-loader\dist\index.js:147:7
    at C:\Users\andre\code\vue-template\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.3.0

C:\Users\andre\code\vue-template>
</pre>

### package.json
<pre>
{
  "name": "vue-template",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "register-service-worker": "^1.7.1",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@types/jest": "^24.0.19",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-pwa": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vue/test-utils": "^2.0.0-0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.0.0",
    "prettier": "^2.2.1",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "typescript": "~4.1.5",
    "vue-jest": "^5.0.0-0"
  }
}
</pre>

**Comment by delcioPHP** [comment]
Greetings;
This error only happens in NodeJS version 17. I recommend that you use NodeJs Version 16.13.1 LTS and your problem will be solved!

**Comment by ccnmxns** [comment]
Hello,

this problem is not related to Node version. It's more of a SSL issue.

In Fedora 36 this will ALWAYS break, as you couldn't downgrade OpenSSL (that said, it's the worst solution). I use Node LTS (v16.14.0) if wondering.

My two cents on this would be to upgrade all SSL-related things, and NOT to stuck in OpenSSL < 3.0 as eventually would be a big problem. Today is Fedora 36, but tomorrow it may be macOS 13.x
