### ISSUE TITLE
vue-cli新建webpack项目出现问题，无法build

### ISSUE THREAD

**Issue by PandaTsui** [vuejs/vue-cli#693]
**问题描述：** 上午时vue-cli还很好使，下午就不行了，用vue init webpack mypeoject 创建一个新项目，创建成功后run build就报下面的错
**报错：**
TypeError: requestShortener.shorten is not a function
    at Function.buildError (D:\coding\agotoz_web\node_modules\uglifyjs-webpack-plugin\dist\index.js:272:87)
    at D:\coding\agotoz_web\node_modules\uglifyjs-webpack-plugin\dist\index.js:206:56
    at Array.forEach (<anonymous>)
    at D:\coding\agotoz_web\node_modules\uglifyjs-webpack-plugin\dist\index.js:189:21
    at step (D:\coding\agotoz_web\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:90:11)
    at done (D:\coding\agotoz_web\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:99:22)
    at D:\coding\agotoz_web\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:105:15
    at D:\coding\agotoz_web\node_modules\worker-farm\lib\farm.js:191:19
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by ForeveHG** [comment]
遇见了同样的问题，装回2.8.2可以正常打包，先用着....

**Comment by An0nymous0** [comment]
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/197

**Comment by SuperGod** [comment]
同样的问题

**Comment by mengqing723** [comment]
降级 uglifyjs-webpack-plugin 至 v0.4.6 就可以了，@An0nymous0 已经说明了

**Comment by LinusBorg** [comment]
Wrong respository. https://github.com/vuejs-templates/webpack/issues/1200

**Comment by terenceyhj** [comment]
用“vue init webpack mypeoject” 创建项目时，不能运行，提示如下警告：
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
node:8
npm:5.6.0
