### ISSUE TITLE
npm run e2e - Webpack error

### ISSUE THREAD

**Issue by celilunver** [vuejs/vue-cli#694]
```
Running:  app should work
C:\Users\celil\OneDrive\VueJs\10-vue-testing\node_modules\uglifyjs-webpack-plugin\dist\index.js:272
          return new Error(`${file} from UglifyJs\n${err.message} [${requestShortener.shorten(original.source)}:${original.line},${original.column}][${file}:${err.line},${err.col}]`);
                                                                                      ^

TypeError: requestShortener.shorten is not a function
    at Function.buildError (C:\Users\celil\OneDrive\VueJs\10-vue-testing\node_modules\uglifyjs-webpack-plugin\dist\index.js:272:87)
    at C:\Users\celil\OneDrive\VueJs\10-vue-testing\node_modules\uglifyjs-webpack-plugin\dist\index.js:206:56
    at Array.forEach (<anonymous>)
    at C:\Users\celil\OneDrive\VueJs\10-vue-testing\node_modules\uglifyjs-webpack-plugin\dist\index.js:189:21
    at step (C:\Users\celil\OneDrive\VueJs\10-vue-testing\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:90:11)
    at done (C:\Users\celil\OneDrive\VueJs\10-vue-testing\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:99:22)
    at C:\Users\celil\OneDrive\VueJs\10-vue-testing\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:105:15
    at C:\Users\celil\OneDrive\VueJs\10-vue-testing\node_modules\worker-farm\lib\farm.js:191:19
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 10-vue-testing@1.0.0 e2e: `node test/e2e/runner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 10-vue-testing@1.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\celil\AppData\Roaming\npm-cache\_logs\2017-12-25T14_24_18_627Z-debug.log

C:\Users\celil\OneDrive\VueJs\10-vue-testing> × Timed out while waiting for element <#app> to be present for 5000 milliseconds.  - expected "visible" but got: "not found"
    at Object.appShouldWork [as app should work] (C:/Users/celil/OneDrive/VueJs/10-vue-testing/test/e2e/specs/test.js:13:8)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)


FAILED:  1 assertions failed (10.901s)

 _________________________________________________

 TEST FAILURE:  1 assertions failed, 0 passed. (11.139s)

 × test

   - app should work (10.901s)
   Timed out while waiting for element <#app> to be present for 5000 milliseconds.  - expected "visible" but got: "not found"
       at Object.appShouldWork [as app should work] (C:/Users/celil/OneDrive/VueJs/10-vue-testing/test/e2e/specs/test.js:13:8)
       at _combinedTickCallback (internal/process/next_tick.js:131:7)


```

**Comment by posva** [comment]
Hello!
Please, open the issue on the relevant template repo and provide some steps to reproduce the problem.
Thanks!
