### ISSUE TITLE
Creating new project with standard options (Vue 3 Typescript) fails on windows 

### ISSUE THREAD

**Issue by iklemm** [vuejs/vue-cli#6977]
### Version
4.5.15

### Environment info
```

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
  npmGlobalPackages:
    @vue/cli: Not Found


Additional Info: node is installed and used via NVM (windows)

```

### Steps to reproduce
start vue ui
create new project with standard options

### What is expected?
new vue project should be created

### What is actually happening?
project not created, execution of vue/cli stopps.

---
Additional info:
It's likely that this does not have to do with vue/cli. Nevertheless it would be good to know how to solve the issue. 
It seems to me, that the problem is related to sass. Creating a project with costum options and without css preprocesseor works.

Error log:

 Invoking generators...
📦  Installing additional dependencies...

    at makeError (C:\-----------------\AppData\Local\Yarn\Data\global\node_modules\execa\index.js:174:9)
    at C:\Users\-----------------\AppData\Local\Yarn\Data\global\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\iklemm\AppData\Local\Yarn\Data\global\node_modules\@vue\cli-ui\apollo-server\connectors\projects.js:354:5
    at async Object.wrap (C:\Users\--------\AppData\Local\Yarn\Data\global\node_modules\@vue\cli-ui\apollo-server\connectors\progress.js:39:14) {
  code: 1,
  stdout: '✨  Creating project in C:\\Users\\\-----------------\\\coding\\github\\other\\test.\n' +
    '🗃  Initializing git repository...\n'  +
    '⚙️  Installing CLI plugins. This might take a while...\n' +
    '\n' +
    '🚀  Invoking generators...\n' +
    '📦  Installing additional dependencies...\n' +
    '\n',
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'vue create test --skipGetStarted --inlinePreset {"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-typescript":{"classComponent":false,"useTsWithBabel":true},"@vue/cli-plugin-eslint":{"config":"base","lintOn":["save"]}},"vueVersion":"3","cssPreprocessor":"node-sass"}',
  timedOut: false,
  killed: false

**Comment by iklemm** [comment]
In the end it turns out, that Python was missing on the mashine. Python seems to be some "build dependency" for some node libs. After installing Python problem disappeared.
