### ISSUE TITLE
Cannot add PWA

### ISSUE THREAD

**Issue by spixy** [vuejs/vue-cli#6997]
### Version
5.0.1

### Environment info
```
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found  (note: idk why not found, I have v98.0.4758.102)
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.50)    
  npmPackages:
    @vitejs/plugin-vue: ^1.10.0 => 1.10.1 
    @volar/vue-code-gen:  0.29.8 
    @vue/compiler-core:  3.2.26 
    @vue/compiler-dom:  3.2.26 
    @vue/compiler-sfc:  3.2.26 
    @vue/compiler-ssr:  3.2.26 
    @vue/reactivity:  3.2.26 
    @vue/reactivity-transform:  3.2.26 
    @vue/runtime-core:  3.2.26 
    @vue/runtime-dom:  3.2.26 
    @vue/server-renderer:  3.2.26 
    @vue/shared:  3.2.26
    eslint-plugin-prettier-vue: ^3.1.0 => 3.1.0
    eslint-plugin-vue: ^8.1.1 => 8.1.1
    typescript: ~4.4.4 => 4.4.4
    vscode-vue-languageservice:  0.29.8
    vue: ^3.2.22 => 3.2.23
    vue-eslint-parser:  8.0.1
    vue-tsc: ^0.29.6 => 0.29.6
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
> vue add pwa

### What is expected?
PWA is added

### What is actually happening?
```
📦  Installing @vue/cli-plugin-pwa...

ERROR  Error: command failed: pnpm install --reporter silent --shamefully-hoist @vue/cli-plugin-pwa@~5.0.0 -D
Error: command failed: pnpm install --reporter silent --shamefully-hoist @vue/cli-plugin-pwa@~5.0.0 -D
    at ChildProcess.<anonymous> (C:\...\npm\node_modules\@vue\cli\lib\util\executeCommand.js:138:16)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\...\npm\node_modules\@vue\cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

---
> cat C:\\...\\.vuerc
{
  "useTaobaoRegistry": false
}

**Comment by darrinmn9** [comment]
possibly related to https://github.com/vuejs/vue-cli/issues/6951 ?

**Comment by ayu-exorcist** [comment]
1. `cd your_project_path`
2. `rm -rf .npmrc && rm -rf node_modules`
3. `pnpm install`
4. `pnpm add @vue/cli-plugin-pwa@~5.0.0 -D`
5. `pnpm add -D yorkie webpack @babel/core @types/node @types/webpack-env`

More: 
- https://github.com/vuejs/vue-cli/blob/b154dbd7aca4b4538e6c483b1d4b817499d7b8eb/packages/%40vue/cli/lib/Creator.js#L168-L176
- https://github.com/vuejs/vue-cli/blob/b154dbd7aca4b4538e6c483b1d4b817499d7b8eb/packages/%40vue/cli/lib/util/ProjectPackageManager.js#L48-L59
