### ISSUE TITLE
ERROR  TypeError: Cannot read property 'tapPromise' of undefined

### ISSUE THREAD

**Issue by nervusdm** [vuejs/vue-cli#7019]
### Version
5.0.1

### Environment info
```
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Edge: 96.0.1054.62
    Firefox: Not Found
    Safari: 15.1
  npmPackages:
    @element-plus/icons-vue:  0.2.7 
    @fortawesome/vue-fontawesome: ^3.0.0-3 => 3.0.0-5 
    @meforma/vue-toaster: ^1.3.0 => 1.3.0 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.1.1 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.15 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.15 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.15 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.15 
    @vue/cli-plugin-pwa: ~5.0.0 => 5.0.1 
    @vue/cli-plugin-router:  4.5.15 
    @vue/cli-plugin-vuex:  4.5.15 
    @vue/cli-service: ~4.5.0 => 4.5.15 
    @vue/cli-shared-utils:  4.5.15 (5.0.1)
    @vue/compiler-core:  3.2.31 
    @vue/compiler-dom:  3.2.31 
    @vue/compiler-sfc: ^3.0.0 => 3.2.31 
    @vue/compiler-ssr:  3.2.31 
    @vue/component-compiler-utils:  3.3.0 
    @vue/devtools-api:  6.0.12 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/reactivity:  3.2.31 
    @vue/reactivity-transform:  3.2.31 
    @vue/runtime-core:  3.2.31 
    @vue/runtime-dom:  3.2.31 
    @vue/server-renderer:  3.2.31 
    @vue/shared:  3.2.31 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^7.0.0 => 7.20.0 
    vue: ^3.0.0 => 3.2.31 
    vue-awesome-example:  2.0.0 
    vue-demi:  0.12.1 
    vue-eslint-parser:  7.11.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.8 (16.8.3)
    vue-router: ^4.0.6 => 4.0.13 
    vue-style-loader:  4.1.3 
    vue-template-es2015-compiler:  1.9.1 
    vue3-icon:  2.0.0 
    vue3-qrcode-reader: 0.0.1 => 0.0.1 
    vue3-snackbar: ^1.1.2 => 1.1.2 
    vuex: ^4.0.0 => 4.0.2 
  npmGlobalPackages:
    @vue/cli: 5.0.1
```

### Steps to reproduce
yarn build

### What is expected?
Buidling success.

### What is actually happening?
Just installed vue cli, and pwa plugin.
Now, I can't do yarn build.

**Comment by nervusdm** [comment]
same with vue build

**Comment by CosminBd** [comment]
Environment info
```
Environment Info:

  System:
    OS: Windows 10 x64
    CPU: Intel(R) Core(TM) i7-4720HQ
  Binaries:
    Node: v14.16.1 - /usr/local/bin/node
    npm: 6.14.12 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.51 (Official Build) (64-bit)
  npmPackages:
    "@tailwindcss/postcss7-compat": "^2.2.17",
    "@vee-validate/rules": "^4.5.7",
	"@intlify/vue-i18n-loader": "^3.0.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-e2e-cypress": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-airbnb": "^5.0.2",
	"@vue/cli-plugin-pwa": "5.0.1" 
    "@vue/test-utils": "^2.0.0-0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^7.0.0",
    "typescript": "~3.9.3",
    "vue-cli-plugin-i18n": "~2.3.1",
    "vue-cli-plugin-tailwind": "~2.2.18",
    "vue-jest": "^5.0.0-0"
    "autoprefixer": "^9",
    "core-js": "^3.6.5",
    "css-minimizer-webpack-plugin": "^1.3.0",
    "firebase": "8",
    "howler": "^2.2.3",
    "postcss": "^7",
    "register-service-worker": "^1.7.2",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.17",
    "vee-validate": "^4.5.8",
    "vue": "^3.0.0",
    "vue-i18n": "^9.1.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.2"
```

I have the same issue with 5.0.1
I've attached the output below

```
$ vue-cli-service build --mode production --target app --dashboard


-  Building for production...

 ERROR  TypeError: Cannot read property 'tapPromise' of undefined

TypeError: Cannot read property 'tapPromise' of undefined
    at \node_modules\@vue\cli-plugin-pwa\node_modules\workbox-webpack-plugin\build\generate-sw.js:107:49
    at SyncHook.eval [as call] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (\node_modules\webpack\lib\Compiler.js:630:30)
    at \node_modules\webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (\node_modules\webpack\lib\Compiler.js:662:28)
    at \node_modules\webpack\lib\Compiler.js:321:11
    at Compiler.readRecords (\node_modules\webpack\lib\Compiler.js:529:11)
    at \node_modules\webpack\lib\Compiler.js:318:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (\node_modules\tapable\lib\Hook.js:154:20)
    at \node_modules\webpack\lib\Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (\node_modules\tapable\lib\Hook.js:154:20)

```

**Comment by bjorne84** [comment]
I have the same problem

**Comment by fabus961** [comment]
Yep, same issue here. 

**package.json:**
"dependencies": {
    "blockly": "^8.0.2",
    "chokidar": "^3.5.3",
    "core-js": "^3.6.5",
    "pinia": "^2.0.14",
    "register-service-worker": "^1.7.2",
    "sweetalert2": "^8.19.0",
    "three": "^0.140.2",
    "vue": "^3.0.0",
    "vue-i18n": "^9.1.10",
    "vue-router": "^4.0.15"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.15",
    "@vue/cli-plugin-eslint": "~4.5.15",
    "@vue/cli-plugin-pwa": "~5.0.0",
    "@vue/cli-plugin-typescript": "~4.5.15",
    "@vue/cli-service": "~4.5.15",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "autoprefixer": "^9.8.8",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "typescript": "~4.1.5"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended",
      "@vue/typescript"
    ],

**Comment by ezpzlmnsqz1337** [comment]
I had the same issue, downgrading to `@vue/cli-plugin-pwa": "4.5.17"` solved it.

**Comment by matheusodilon** [comment]
> I had the same issue, downgrading to `@vue/cli-plugin-pwa": "4.5.17"` solved it.

It worked!

**Comment by etiennedibi** [comment]
Very usefull. thanks for this tips. 
It works for me too !

But i think that it's time to migrate on vuejs3 :)
