### ISSUE TITLE
vue-cli-service serve fails when there are multiple `static` entries specified

### ISSUE THREAD

**Issue by halostatue** [vuejs/vue-cli#7080]
### Version

5.0.4

### Reproduction link

[github.com](https://github.com/halostatue/vue-cli-devserver-error)

### Environment info

```
  System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.14.0 - ~/.local/share/nvm/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.local/share/nvm/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.local/share/nvm/v16.14.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Edge: 99.0.1150.52
    Firefox: 98.0.1
    Safari: 15.4
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.1.1 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  5.0.4 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  5.0.4 
    @vue/cli-plugin-babel: ~5.0.0 => 5.0.4 
    @vue/cli-plugin-router:  5.0.4 
    @vue/cli-plugin-vuex:  5.0.4 
    @vue/cli-service: ~5.0.0 => 5.0.4 
    @vue/cli-shared-utils:  5.0.4 
    @vue/component-compiler-utils:  3.3.0 
    @vue/web-component-wrapper:  1.3.0 
    vue: ^2.6.14 => 2.6.14 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  17.0.0 (15.9.8)
    vue-style-loader:  4.1.3 
    vue-template-compiler: ^2.6.14 => 2.6.14 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 5.0.4
```

### Steps to reproduce

In the repro repo, type `yarn serve`.

### What is expected?

The vue application serves.

### What is actually happening?

```
✖ yarn serve
yarn run v1.22.17
$ vue-cli-service serve
 INFO  Starting development server...
 ERROR  ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
         - options.static should be one of these:
           [non-empty string | object { directory?, staticOptions?, publicPath?, serveIndex?, watch? }, ...] | boolean | non-empty string | object { directory?, staticOptions?, publicPath?, serveIndex?, watch? }
           -> Allows to configure options for serving static files from directory (by default 'public' directory).
           -> Read more at https://webpack.js.org/configuration/dev-server/#devserverstatic
           Details:
            * options.static has an unknown property '0'. These properties are valid:
              object { directory?, staticOptions?, publicPath?, serveIndex?, watch? }
            * options.static has an unknown property '1'. These properties are valid:
              object { directory?, staticOptions?, publicPath?, serveIndex?, watch? }
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.static should be one of these:
   [non-empty string | object { directory?, staticOptions?, publicPath?, serveIndex?, watch? }, ...] | boolean | non-empty string | object { directory?, staticOptions?, publicPath?, serveIndex?, watch? }
   -> Allows to configure options for serving static files from directory (by default 'public' directory).
   -> Read more at https://webpack.js.org/configuration/dev-server/#devserverstatic
   Details:
    * options.static has an unknown property '0'. These properties are valid:
      object { directory?, staticOptions?, publicPath?, serveIndex?, watch? }
    * options.static has an unknown property '1'. These properties are valid:
      object { directory?, staticOptions?, publicPath?, serveIndex?, watch? }
    at validate (/Users/austin/mess/2022/12/vue-cli-devserver-error/node_modules/webpack-dev-server/node_modules/schema-utils/dist/validate.js:115:11)
    at new Server (/Users/austin/mess/2022/12/vue-cli-devserver-error/node_modules/webpack-dev-server/lib/Server.js:232:5)
    at serve (/Users/austin/mess/2022/12/vue-cli-devserver-error/node_modules/@vue/cli-service/lib/commands/serve.js:185:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

---

The error is in the initialization of the WebpackDevServer, specifically on how the defaults for `static` are overridden at [lib/commands/serve.js:201…207](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/serve.js#L201-L207).

Specifically, `...projectDevServerOptions.static` when applied to an array puts the values as `'0': { … }`.

```
     static: {
        directory: api.resolve('public'),
        publicPath: options.publicPath,
        watch: !isProduction,

        ...projectDevServerOptions.static
      },
```

This would be better specified some other way. Something like (I’m short handing this):

```js
let staticOptions

if (isArray(projectDevServerOptions.static)) {
  staticOptions = projectDevServerOptions.static.map((entry) => {
    if (isString(entry)) {
      return {
        directory: api.resolve(entry),
        publicPath: options.publicPath,
        watch: !isProduction,
      }
    }

    return {
      directory: api.resolve('public'),
      publicPath: options.publicPath,
      watch: !isProduction,
      ...entry,
    }
  })
} else {
  staticOptions = {
    directory: api.resolve('public'),
    publicPath: options.publicPath,
    watch: !isProduction,
    ...projectDevServerOptions.static
  }
}
```

That would provide _most_ compatibility with `webpack-dev-server`.

**Comment by halostatue** [comment]
As a side note, I found the issue creation process both user-hostile and broken. Not only are the text boxes used _less_ capable than the entry boxes provided by Github (which matters when you’re typing a lot), but the first pass _failed_ to submit because the entire issue is passed as part of a query URL and the result was too long to process. I understand that a lot of issues received in the past have been low quality, but the custom form used is disastrous, and the fact that I needed to create a repro repo for something that is _trivially_ demonstrably wrong _in the server code_ is unnecessarily user-hostile and makes me less interested in contributing to Vue in any way.

**Comment by shenchaoran** [comment]
face the same problem

**Comment by halostatue** [comment]
Not happy about the crickets here, especially for something that is _obviously_ wrong and has a relatively easy fix described in a complete ticket. I guess it’s because `vue-cli` is basically a dead end, as is vue2. Leaning very strongly toward svelte for my next project.

**Comment by ottopaulsen** [comment]
I am having the same problem. Is there any workaround? I have to serve two different static directories to two different paths.

**Comment by halostatue** [comment]
The only fix for this is for the vue-cli team to fix the bug I found and suggested a fix for. vue-cli is explicitly breaking what webpack’s dev server is doing correctly.

**Comment by harentius** [comment]
same here

**Comment by halostatue** [comment]
This is obviously something that the vue-cli team does not care about. I don’t particularly want to receive any more notifications on a bug that won’t be seeing any action on a project that is essentially dead in the water, so I’m closing this and unsubscribing. We’re already switching to Vite and Svelte for the next version of the project we originally built with vue-cli and vue2.
