### ISSUE TITLE
Fresh install with pnpm isn't working

### ISSUE THREAD

**Issue by CyntaxDotDev** [vuejs/vue-cli#7106]
### Version
5.0.4

### Reproduction link
[cli.vuejs.org](https://cli.vuejs.org/guide/cli-service.html)

### Environment info
```
  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
  Binaries:
    Node: 16.14.2 - /usr/bin/node
    Yarn: 1.22.15 - /usr/bin/yarn
    npm: 8.6.0 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: 5.0.4


PNPM version is 7.0.0-rc.3 (I also tested rc.2)
```

### Steps to reproduce
Regular `vue create project-name`. Manual or default 3.x install doesn't matter.
In the end, choose PNPM as your package manager (or launch with --packageManager=pnpm)

### What is expected?
A cleanly installed project

### What is actually happening?
No install except the basic generation of the required package.json and other related files (no node_modules)

```ERROR  Error: command failed: pnpm install --reporter silent --shamefully-hoist
Error: command failed: pnpm install --reporter silent --shamefully-hoist
    at ChildProcess.<anonymous> (/usr/lib/node_modules/@vue/cli/lib/util/executeCommand.js:138:16)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)```

---
I added a link to the Vue CLI docs as I didn't know where to start up this code. StackBlitz and Codepen both basically generate the project for you, but that step before is actually what's going wrong.

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by rumbis** [comment]
i got the same issue did you find a solution ?

**Comment by CyntaxDotDev** [comment]
I did not. I chose NPM as my installer and it works fine for now. I loved the way PNPM works but together they just don't work yet. (edited as I mistakenly thought this ticket was about Nuxt3)

**Comment by Hergeirs** [comment]
Any update on this?
I get the same error when adding a vue plugin to my existing project
```  
$ vue add tauri                                                                   

📦  Installing vue-cli-plugin-tauri...

 ERROR  Error: command failed: pnpm install --reporter silent --shamefully-hoist vue-cli-plugin-tauri -D
Error: command failed: pnpm install --reporter silent --shamefully-hoist vue-cli-plugin-tauri -D
    at ChildProcess.<anonymous> (/usr/lib/node_modules/@vue/cli/lib/util/executeCommand.js:138:16)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

```

Running the command ``` pnpm install --reporter silent --shamefully-hoist vue-cli-plugin-tauri -D ``` works without issue by itself.

**Comment by Hergeirs** [comment]
Figured my issue. It might be yours. 

Found out that ```pnpm install --reporter silent --shamefully-hoist vue-cli-plugin-tauri -D``` actually returned an error code 1. So I ran the command without ```--reporter silent``` and got this error:
```
 ERR_PNPM_PUBLIC_HOIST_PATTERN_DIFF   This module was created using a different public-hoist-pattern value. run "pnpm install" to recreate the modules directory.
```
Somehow, something had created a node_modules folder in the project. I removed it and ran ```pnpm install``` as instructed. 
Now I'm getting a different error . But that might belong on a different issue

**Comment by bartlian** [comment]
I have met this issue today. I have found the packageManager field value is 'pnpm' in .vuerc file. Then change to 'npm' and it can fix this issue temporarily.

**Comment by Jackllllll** [comment]
@bartlian That's useful for me. Thank u so much! Maybe it's PNPM7.1  of  i use

**Comment by gastrodia** [comment]
> I have met this issue today. I have found the packageManager field value is 'pnpm' in .vuerc file. Then change to 'npm' and it can fix this issue temporarily.
thanks

**Comment by ToddEmonster** [comment]
Thanks to @Hergeirs', I found this solution : 

1) Delete your `node_modules` folder
2) Run `vue add tauri` 

And it worked for me, `node_modules` is recreated in the process

**Comment by Yash-Singh1** [comment]
I am having this problem too, I can't create a new Vue.js App with the `pnpm` package manager. Strangely, the logs stack trace has a reference to `yarn`, idk if it's related:

```
 ERROR  Error: command failed: pnpm install --reporter silent --shamefully-hoist
Error: command failed: pnpm install --reporter silent --shamefully-hoist
    at ChildProcess.<anonymous> (/home/saiansh/.config/yarn/global/node_modules/@vue/cli/lib/util/executeCommand.js:138:16)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by jay-p-b-7span** [comment]
I am also facing this Issue.

**Comment by ayu-exorcist** [comment]
1. `cd your_project_path`
2. `rm -rf .npmrc && rm -rf node_modules`
3. `pnpm install`
4. `pnpm add -D yorkie webpack @babel/core @types/node @types/webpack-env`

More: 
- https://github.com/vuejs/vue-cli/blob/b154dbd7aca4b4538e6c483b1d4b817499d7b8eb/packages/%40vue/cli/lib/Creator.js#L168-L176
- https://github.com/vuejs/vue-cli/blob/b154dbd7aca4b4538e6c483b1d4b817499d7b8eb/packages/%40vue/cli/lib/util/ProjectPackageManager.js#L48-L59

**Comment by marty-mcgee** [comment]
Two alternative quick-fixes (workarounds) not yet mentioned:
1. use the @vue/cli command OPTION "-m, --packageManager <command>  Use specified npm client when installing dependencies"
-- for example: `vue create my-app -m npm` or `vue create my-app --packageManager yarn`
-- helpful source link: [https://v3.cli.vuejs.org/guide/creating-a-project.html#vue-create](https://v3.cli.vuejs.org/guide/creating-a-project.html#vue-create)
2. run this @vue/cli command to automagically open your .vuerc file: `vue config --edit` and you can edit entries as necessary.
-- helpful source link: [https://cli.vuejs.org/config/#global-cli-config](https://cli.vuejs.org/config/#global-cli-config)

**Comment by jay-p-b-7span** [comment]
Tried your approach. Still not able to create vue 2 scaffolded project with pnpm. Issue still persists. @ReSpawN  @ayu14214

**Comment by marty-mcgee** [comment]
> Tried your approach. Still not able to create vue 2 scaffolded project with pnpm. Issue still persists. @ReSpawN @ayu14214

Hmmm.. Let me try it in Vue 2. I will hopefully get back to you soon.

**Comment by QuentinHsu** [comment]
I am also facing this Issue.

**Comment by aleksanderwalczuk** [comment]
+1 faced on both node v14 and 16. Setting npm as dependency manage save the issue.

**Comment by IceApriler** [comment]
How to solve this problem?

**Comment by aleksanderwalczuk** [comment]
> How to solve this problem?

Post more messages and wait for next release 😁

**Comment by lclrobert2020** [comment]
Using pnpm v6 solved the issue for me

**Comment by lvqq** [comment]
pnpm v7 makes breaking change to set `strict-peer-dependencies=true` by default. It may interrupt the installing while there exist peer dependencies install errors.

**Comment by linghengqian** [comment]
This issue was fixed in #7265 and should be closed.
