### ISSUE TITLE
为什么我安装完的vue-cli不能创建项目

### ISSUE THREAD

**Issue by shuaidaipeng** [vuejs/vue-cli#7140]
### Version
4.5.13

### Reproduction link
[github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
win11
```

### Steps to reproduce
npm install @vue/cli@4  ，执行 vue ui  也报这个错误

### What is expected?
能够得到解决

### What is actually happening?
 ERROR  SyntaxError: Unexpected token '.'
E:\nodejs\node_global\node_modules\@vue\cli\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:3316
                            s.prepend(`import { ${input.slice(specifier.local.start, specifier.local.end)} } from '${node.source?.value}'\n`);
                                                                                                                                 ^

SyntaxError: Unexpected token '.'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\nodejs\node_global\node_modules\@vue\cli\node_modules\vue-codemod\dist\src\run-transformation.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

**Comment by haoqunjiang** [comment]
https://github.com/vuejs/vue-cli/issues/7141#issuecomment-1133575732
