### ISSUE TITLE
5版本和4版本，全局安装之后，无法创建项目，如下报错

### ISSUE THREAD

**Issue by yinwubikong** [vuejs/vue-cli#7141]
### Version
5.0.4

### Reproduction link
[github.com](https://github.com/vuejs/vue-cli/issues)

### Environment info
```
node 12.18.2
```

### Steps to reproduce
C:\Users\27946\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:3261
            if (grandparent?.source) {
                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\27946\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\compiler-core\index.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

### What is expected?
https://github.com/vuejs/vue-cli/issues

### What is actually happening?
https://github.com/vuejs/vue-cli/issues

---
https://github.com/vuejs/vue-cli/issues

**Comment by shuaidaipeng** [comment]
我也碰到过这个问题，我测试过了 大概率是在win11系统中会出现这种错误，我在win10系统中却能够正常的创建项目

**Comment by haoqunjiang** [comment]
Vue 3.2.34 的 bug https://github.com/vuejs/core/issues/5957 现在应该好了

不过还是建议升级一下 Node 版本，Node 12 已经 EOL 了，不能保证以后依赖里不会再出现类似问题……
