### ISSUE TITLE
Error: Plugin/Preset files are not allowed to export objects, only functions. In node_modules\babel-preset-stage-2\lib\index.js

### ISSUE THREAD

**Issue by DreamPWJ** [vuejs/vue-cli#7147]
### Version
4.5.17

### Environment info
```
Node v14.19.1

```

### Steps to reproduce
vue-cli-service build

### What is expected?
sucesss

### What is actually happening?
 ERROR  Error: Plugin/Preset files are not allowed to export objects, only functions. In E:\hub\rzhtc\node_modules\babel-preset-stage-2\lib\index.js
Error: Plugin/Preset files are not allowed to export objects, only functions. In E:\hub\rzhtc\node_modules\babel-preset-stage-2\lib\index.js
    at createDescriptor (E:\hub\rzhtc\node_modules\@babel\core\lib\config\config-descriptors.js:211:11)
    at createDescriptor.next (<anonymous>)
    at evaluateSync (E:\hub\rzhtc\node_modules\gensync\index.js:251:28)
    at E:\hub\rzhtc\node_modules\gensync\index.js:31:34
    at Array.map (<anonymous>)
    at Function.sync (E:\hub\rzhtc\node_modules\gensync\index.js:31:22)
    at Function.all (E:\hub\rzhtc\node_modules\gensync\index.js:210:24)
    at Generator.next (<anonymous>)
    at createDescriptors (E:\hub\rzhtc\node_modules\@babel\core\lib\config\config-descriptors.js:142:41)
    at createDescriptors.next (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! epark-h5@1.0.0 build:juxina: `vue-cli-service build  --mode juxian`
npm ERR! Exit status 1
npm ERR!

**Comment by DreamPWJ** [comment]
add @vue/cli-plugin-babel  not workiing

**Comment by Youky1** [comment]
How did you solve this?
