### ISSUE TITLE
vue ui is not work , lack of pubsub

### ISSUE THREAD

**Issue by EricCheng0508** [vuejs/vue-cli#7175]
### Version
5.0.4

### Environment info
```
  System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 16.15.0 - D:\Work\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.11.0 - D:\Work\nodejs\node_global\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
install @vue/cli
vue ui 
TypeError: Cannot read properties of undefined (reading 'pubsub')
    at Object.exports.add (D:\Work\nodejs\node_global\node_modules\@vue\cli\node_modules\_@vue_cli-ui@5.0.4@@vue\cli-ui\apollo-server\connectors\logs.js:36:11)
    at runPluginApi (D:\Work\nodejs\node_global\node_modules\@vue\cli\node_modules\_@vue_cli-ui@5.0.4@@vue\cli-ui\apollo-server\connectors\plugins.js:241:12)
    at D:\Work\nodejs\node_global\node_modules\@vue\cli\node_modules\_@vue_cli-ui@5.0.4@@vue\cli-ui\apollo-server\connectors\plugins.js:172:33
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (D:\Work\nodejs\node_global\node_modules\@vue\cli\node_modules\_@vue_cli-ui@5.0.4@@vue\cli-ui\apollo-server\connectors\plugins.js:172:15)

### What is expected?
vue ui 
String...

### What is actually happening?
vue ui
TypeError: Cannot read properties of undefined (reading 'pubsub')
    at Object.exports.add (D:\Work\nodejs\node_global\node_modules\@vue\cli\node_modules\_@vue_cli-ui@5.0.4@@vue\cli-ui\apollo-server\connectors\logs.js:36:11)
    at runPluginApi (D:\Work\nodejs\node_global\node_modules\@vue\cli\node_modules\_@vue_cli-ui@5.0.4@@vue\cli-ui\apollo-server\connectors\plugins.js:241:12)
    at D:\Work\nodejs\node_global\node_modules\@vue\cli\node_modules\_@vue_cli-ui@5.0.4@@vue\cli-ui\apollo-server\connectors\plugins.js:172:33
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (D:\Work\nodejs\node_global\node_modules\@vue\cli\node_modules\_@vue_cli-ui@5.0.4@@vue\cli-ui\apollo-server\connectors\plugins.js:172:15)...

---
lack of pubsub  and i dont know how to fix it
i already reinstall 3times  i dont know why

**Comment by EricCheng0508** [comment]
windows11 down to the windows 10  question fixed
