### ISSUE TITLE
vue-cli-service build crash

### ISSUE THREAD

**Issue by Archie2035** [vuejs/vue-cli#7180]
### Version
4.4.4

### Environment info
```
ubuntu18.04
```

### Steps to reproduce
vue-cli-service build

### What is expected?
build prod dist

### What is actually happening?
 ERROR  TypeError: ErrorStackParser.parse is not a function
TypeError: ErrorStackParser.parse is not a function
    at getOriginalErrorStack (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:31:29)
    at extractError (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/@soda/friendly-errors-webpack-plugin/src/core/extractWebpackError.js:22:20)
    at Array.map (<anonymous>)
    at processErrors (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/@soda/friendly-errors-webpack-plugin/src/core/transformErrors.js:31:17)
    at FriendlyErrorsWebpackPlugin.displayErrors (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:97:29)
    at doneFn (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/@soda/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:57:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at AsyncSeriesHook.lazyCompileHook (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/tapable/lib/Hook.js:154:20)
    at /media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/webpack/lib/Compiler.js:499:39)
    at /media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/webpack/lib/Compiler.js:298:10
    at /media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/webpack/lib/Compiler.js:485:14
    at _next0 (eval at create (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at eval (eval at create (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at /media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/copy-webpack-plugin/dist/index.js:115:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/media/fanglei/mpca_wq_2T/workspace/recorder/DFDI-Console/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dfdi-console@1.0.0 build:stage: `vue-cli-service build --mode staging`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dfdi-console@1.0.0 build:stage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by CharlotteMorrison** [comment]
I am having the same issue as above.

**Comment by nik736** [comment]
Experiencing the same issue for a few hours now.

**Comment by vitaliimak** [comment]
I also had the same issue. I temporarily fixed it by taking the `package-lock.json` file from the old project (a few days old) and replacing the file in the new project.

**Comment by lewiswill** [comment]
I'm also experiencing this exact issue.

**Comment by fitzhavey** [comment]
Count me in, I picked a bad time to try and prune our peer dependencies 😆 - was sure it was something I'd done.


| &nbsp; |&nbsp; |
|-------|-|
| Node | 16.13.1 |
| npm | 8.1.2 |
| @vue/cli-service | ^5.0.4 |

**Comment by EminCimen** [comment]
im having this issue also, following

**Comment by Jeff-Levy** [comment]
Ah, yup, me too. Experienced first during a CI/CD run on w/Github -> Azure. All builds are failing across the board.

**Comment by ckosidow** [comment]
Also seeing this problem on code that hasn't changed

**Comment by MarioGuiloff** [comment]
also having the same issue!  CI/CD run on w/Github -> Azure

**Comment by PsionicTemplar** [comment]
This fixed it for me - It's a temporary workaround. https://github.com/stacktracejs/error-stack-parser/issues/80

**Comment by tassiovale** [comment]
Adding ```"error-stack-parser": "2.0.6"``` to ```devDependencies``` in ```package.json``` worked for me.

**Comment by oleynikd** [comment]
If you are using yarn also add:
```json
"resolutions": {
  "error-stack-parser": "2.0.6"
}
```
to your package.json

**Comment by duyanren** [comment]
I am having the same issue as above.

**Comment by neitheraaa** [comment]
LIKE THIS,it is valid
`  "devDependencies": {
    "@vue/cli-plugin-babel": "4.4.6",
    "@vue/cli-plugin-eslint": "4.4.6",
    "@vue/cli-service": "4.4.6",
    "babel-eslint": "10.1.0",
    "chalk": "4.1.0",
    "connect": "3.6.6",
    "eslint": "7.15.0",
    "eslint-plugin-vue": "7.2.0",
    "lint-staged": "10.5.3",
    "runjs": "4.4.2",
    "sass": "1.39.0",
    "sass-loader": "10.1.1",
    "script-ext-html-webpack-plugin": "2.1.5",
    "svg-sprite-loader": "5.1.1",
    "vue-template-compiler": "2.6.12",
    "error-stack-parser": "2.0.6",
    "stackframe": "1.2.1"
  },
  "resolutions": {
    "error-stack-parser": "2.0.6",
    "stackframe": "1.2.1"
  },`

**Comment by Z3rio** [comment]
For me I was using the CLI which auto install VueX and Vue Router, simply removing them fixed this for me
So if you have vuex / vue router installed **BUT NOT USING IT** then I recommend removing it.
npm remove @vue/cli-plugin-vuex
npm remove @vue/cli-plugin-router

**Comment by GabrielFRails** [comment]
Hi, I was stuck in the same problem as yours, I added "error-stack-parser": "2.1.4" to devDependencies in package.json of my vuejs project and that worked for me.
source: https://forum.vuejs.org/t/all-vue-js-apps-with-error-on-build/130184/2?u=gabrielfrails
