### ISSUE TITLE
Unable to install with node 16.x.x

### ISSUE THREAD

**Issue by JMZach** [vuejs/vue-cli#7192]
### Version
5.0.4

### Reproduction link
Issue is with CLI

### Environment info
```
Windows 10 - node 16.x.x NVM 7.x.x & 8.x.x
```

### Steps to reproduce
```
Broken between these two LTS builds
Node.js 16.15.1	Gallium	2022-06-01	9.4.146.24	8.11.0	93
Node.js 16.14.0	Gallium	2022-02-08	9.4.146.24	8.3.1	93

Works with:
Node.js 16.13.2	Gallium	2022-01-10	9.4.146.24	8.1.2	93
Node.js 16.13.0	Gallium	2021-10-26	9.4.146.19	8.1.0	93
Node.js 16.12.0		2021-10-20	9.4.146.19	8.1.0	93
Node.js 16.11.0		2021-10-08	9.4.146.19	8.0.0	93
Node.js 16.10.0		2021-09-22	9.3.345.19	7.24.0	93
Node.js 16.9.0		2021-09-07	9.3.345.16	7.21.1	93
Node.js 16.8.0		2021-08-25	9.2.230.21	7.21.0	93
Node.js 16.7.0		2021-08-18	9.2.230.21	7.20.3	93
Node.js 16.6.0		2021-07-29	9.2.230.21	7.19.1	93
Node.js 16.5.0		2021-07-14	9.1.269.38	7.19.1	93



# Install a Gallium revision of node with nvm 
nvm install 16.14.0 
nvm use 16.14.0 

# Try to install the CLI 
npm install -g @vue/cli

# Install hangs
npm ERR! Unexpected token '.'

npm ERR! A complete log of this run can be found in:
C:\Users\<User>\AppData\Local\npm-cache\_logs\2022-06-14T07_35_27_011Z-debug-0.log   
```

### What is expected?
The CLI installs 

### What is actually happening?
```
Failure to install
npm ERR! Unexpected token '.'

npm ERR! A complete log of this run can be found in:
C:\Users\<User>\AppData\Local\npm-cache\_logs\2022-06-14T07_35_27_011Z-debug-0.log   
```

---

```
C:\Users\<User>\AppData\Local\npm-cache\_logs\2022-06-14T07_35_27_011Z-debug-0.log  

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   '@vue/cli'
0 verbose cli ]
1 info using npm@8.3.1
2 info using node@v16.14.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\<User>\AppData\Roaming\nvm\v16.14.0\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\zach\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 9ms
18 timing npm:load:configload Completed in 9ms
19 timing npm:load:setTitle Completed in 0ms
20 timing config:load:flatten Completed in 2ms
21 timing npm:load:display Completed in 4ms
22 verbose logfile C:\Users\<User>\AppData\Local\npm-cache\_logs\2022-06-14T07_35_27_011Z-debug-0.log
23 timing npm:load:logFile Completed in 14ms
24 timing npm:load:timers Completed in 0ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load Completed in 29ms
27 verbose stack C:\Users\<User>\AppData\Roaming\nvm\v16.14.0\node_modules\npm\node_modules\libnpmfund:1
27 verbose stack ../workspaces/libnpmfund
27 verbose stack ^
27 verbose stack
27 verbose stack SyntaxError: Unexpected token '.'
27 verbose stack     at Object.compileFunction (node:vm:352:18)
27 verbose stack     at wrapSafe (node:internal/modules/cjs/loader:1032:15)
27 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1067:27)
27 verbose stack     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
27 verbose stack     at Module.load (node:internal/modules/cjs/loader:981:32)
27 verbose stack     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
27 verbose stack     at Module.require (node:internal/modules/cjs/loader:1005:19)
27 verbose stack     at require (node:internal/modules/cjs/helpers:102:18)
27 verbose stack     at Object.<anonymous> (C:\Users\<User>\AppData\Roaming\nvm\v16.14.0\node_modules\npm\lib\utils\reify-output.js:16:38)
27 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1103:14)
27 verbose stack     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
27 verbose stack     at Module.load (node:internal/modules/cjs/loader:981:32)
27 verbose stack     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
27 verbose stack     at Module.require (node:internal/modules/cjs/loader:1005:19)
27 verbose stack     at require (node:internal/modules/cjs/helpers:102:18)
27 verbose stack     at Object.<anonymous> (C:\Users\<User>\AppData\Roaming\nvm\v16.14.0\node_modules\npm\lib\utils\reify-finish.js:1:21)
28 verbose cwd C:\Users\zach\Desktop\alnf
29 verbose Windows_NT 10.0.19044
30 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@vue/cli"
31 verbose node v16.14.0
32 verbose npm  v8.3.1
33 error Unexpected token '.'
34 verbose exit 1
35 timing npm Completed in 272ms
36 verbose code 1
37 error A complete log of this run can be found in:
37 error     C:\Users\<User>\AppData\Local\npm-cache\_logs\2022-06-14T07_35_27_011Z-debug-0.log
```

**Comment by haoqunjiang** [comment]
Not a bug of `@vue/cli`. See https://github.com/npm/cli/issues/4234#issuecomment-1040528646
