### ISSUE TITLE
Typescript with 2.7.0-beta.5 throws error

### ISSUE THREAD

**Issue by smilosevic** [vuejs/vue-cli#7213]
### Version
4.5.18

### Reproduction link
[github.com](https://github.com/smilosevic/vue-2.7.0-beta.5-typescript-error)

### Environment info
```
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 16.15.1 - ~\AppData\Local\Volta\tools\image\node\16.15.1\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
    npm: 8.13.1 - ~\AppData\Local\Volta\tools\image\npm\8.13.1\bin\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1.0), Chromium (102.0.1245.44)
  npmPackages:
    @vue/cli-overlay:  4.5.18
    @vue/cli-plugin-router:  4.5.18
    @vue/cli-plugin-typescript: ~4.5.18 => 4.5.18
    @vue/cli-plugin-vuex:  4.5.18
    @vue/cli-service: ~4.5.18 => 4.5.18
    @vue/cli-shared-utils:  4.5.18
    @vue/compiler-sfc:  2.7.0-beta.5
    @vue/component-compiler-utils:  3.3.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.3.0
    typescript: ~4.1.5 => 4.1.6
    vue: ^2.7.0-beta.5 => 2.7.0-beta.5
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.8 (16.8.3)
    vue-style-loader:  4.1.3
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
-initialize fresh app with @vue/cli@4

-choose typescript

-change vue version to 2.7.0-beta.5, remove vue-template-compiler, add override for vue-laoder

-serve project

### What is expected?
typescript to work normally

### What is actually happening?
Type checking in progress...

INTERNAL ERROR(undefined,undefined) parser.parseComponent is not a function
stack trace:
TypeError: parser.parseComponent is not a function
    
at Function.resolveScriptBlock (C:\Users\stmil\Downloads\vue-2.7.0-beta.5-typescript-error-main\node_modules\fork-ts-checker-webpack-plugin\lib\VueProgram.js:196:35)
    
at Object.host.getSourceFile (C:\Users\stmil\Downloads\vue-2.7.0-beta.5-typescript-error-main\node_modules\fork-ts-checker-webpack-plugin\lib\VueProgram.js:106:45)
    
at findSourceFileWorker (C:\Users\stmil\Downloads\vue-2.7.0-beta.5-typescript-error-main\node_modules\typescript\lib\typescript.js:106878:29)
    
at findSourceFile (C:\Users\stmil\Downloads\vue-2.7.0-beta.5-typescript-error-main\node_modules\typescript\lib\typescript.js:106788:26)
    
at processImportedModules (C:\Users\stmil\Downloads\vue-2.7.0-beta.5-typescript-error-main\node_modules\typescript\lib\typescript.js:107190:25)
    
at findSourceFileWorker (C:\Users\stmil\Downloads\vue-2.7.0-beta.5-typescript-error-main\node_modules\typescript\lib\typescript.js:106926:17)
    
at findSourceFile (C:\Users\stmil\Downloads\vue-2.7.0-beta.5-typescript-error-main\node_modules\typescript\lib\typescript.js:106788:26)
    
at C:\Users\stmil\Downloads\vue-2.7.0-beta.5-typescript-error-main\node_modules\typescript\lib\typescript.js:106745:85
    
at getSourceFileFromReferenceWorker (C:\Users\stmil\Downloads\vue-2.7.0-beta.5-typescript-error-main\node_modules\typescript\lib\typescript.js:106712:34)
    
at processSourceFile (C:\Users\stmil\Downloads\vue-2.7.0-beta.5-typescript-error-main\node_modules\typescript\lib\typescript.js:106745:13)

Version: typescript 4.1.6

**Comment by haoqunjiang** [comment]
Fixed in 4.5.19
