### ISSUE TITLE
Please Help Error: Cannot find module './src'

### ISSUE THREAD

**Issue by Bot07** [vuejs/vue-cli#722]
I get this error please help, how can ı solve it?
Error: Cannot find module './src'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\username\Desktop\Bot\node_modules\snekfetch\index.js:1:80)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

**Comment by yyx990803** [comment]
Please provide more information - if this is not from a fresh webpack template install we can't really help with just an error message.
