### ISSUE TITLE
HookWebpackError when use @vue/cli-plugin-pwa and compress-webpack-plugin

### ISSUE THREAD

**Issue by kukuyuhai** [vuejs/vue-cli#7267]
### Version
5.0.8

### Environment info
```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1023.0), Chromium (104.0.1293.47)
```

### Steps to reproduce
```sh
vue add compression
yarn build
```

### What is expected?
no error

### What is actually happening?
```
 ERROR  HookWebpackError: this._obj.updateHash is not a function
HookWebpackError: this._obj.updateHash is not a function
    at D:\demo\compress-error-demo\node_modules\webpack\lib\HookWebpackError.js:65:13
    at eval (eval at create (D:\demo\compress-error-demo\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:38:1)       
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by 0xdevalias** [comment]
Potentially related:

- https://github.com/webpack/webpack/issues/16057#issuecomment-1186290838
- https://github.com/webpack-contrib/compression-webpack-plugin/issues/346
