### ISSUE TITLE
EMFILE error - too many open files

### ISSUE THREAD

**Issue by xiazhaoqiang** [vuejs/vue-cli#7295]
### Version
5.0.8

### Environment info
```
Node.js v18.8.0
Ubuntu 20.04
```

### Steps to reproduce
1. Use the default configuration of Vue
2. run the Tasks/serve

### What is expected?
localhost:8080 can be accessed

### What is actually happening?
The log shows "serve ended with error code 1"

---
$ vue-cli-service serve --mode development --dashboard
 INFO  Starting development server...

[3%] setup (watch run)
[9%] setup (compilation ExportsInfoApiPlugin)

node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error: EMFILE: too many open files, watch '/home/user/Programming/Vue-Tutorial/vue_test'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at createFsWatchInstance (/home/user/Programming/Vue-Tutorial/vue_test/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/user/Programming/Vue-Tutorial/vue_test/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/user/Programming/Vue-Tutorial/vue_test/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/home/user/Programming/Vue-Tutorial/vue_test/node_modules/chokidar/lib/nodefs-handler.js:567:19)
    at NodeFsHandler._addToNodeFs (/home/user/Programming/Vue-Tutorial/vue_test/node_modules/chokidar/lib/nodefs-handler.js:617:27)
    at async /home/user/Programming/Vue-Tutorial/vue_test/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/user/Programming/Vue-Tutorial/vue_test/node_modules/chokidar/index.js:647:10)
    at NodeFsHandler._addToNodeFs (/home/user/Programming/Vue-Tutorial/vue_test/node_modules/chokidar/lib/nodefs-handler.js:645:18)
    at async /home/user/Programming/Vue-Tutorial/vue_test/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/home/user/Programming/Vue-Tutorial/vue_test',
  filename: '/home/user/Programming/Vue-Tutorial/vue_test'
}

Node.js v18.8.0
[10%] building (0/0 modules)

Total task duration: 1.66s

**Comment by durban89** [comment]
no idea?

**Comment by myc00** [comment]
> no idea?

hello, Is there any solution?

**Comment by byk04712** [comment]
same error here
