### ISSUE TITLE
Clean installation of vue-cli results in white screen and "Uncaught TypeError" in console

### ISSUE THREAD

**Issue by temofart** [vuejs/vue-cli#7388]
### Version
5.0.8

### Environment info
```
MacBook Pro M1
Different version of nodejs
I tried 14, 16, 18, 20. With only NVM or only brew
Last try was with:
➜  app git:(main) node -v   
v16.20.0
➜  app git:(main) npm -v
8.19.4
➜  app git:(main) vue -V
@vue/cli 5.0.8
```

### Steps to reproduce
1. clean node js installation via nvm or brew
2. npm install @vue/cli -g
3. npm install yarn -g
4. vue create app
5. cd app
6. npm or yarn serve

### What is expected?
The application should load without errors, displaying the default Vue template.

### What is actually happening?
After creating a new Vue project using vue create app, running the application results in a white screen and the following error message in the browser console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'e')
    at eval (stripAnsi.js:18:1)
    at ./node_modules/webpack-dev-server/client/utils/stripAnsi.js (chunk-vendors.js:325:1)
    at __webpack_require__ (app.js:255:33)
    at fn (app.js:488:21)
    at eval (index.js?protocol=ws&hostname=192.168.0.226&port=8080&pathname=%2Fws&logging=none&progress=true&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true:7:77)
    at ./node_modules/webpack-dev-server/client/index.js?protocol=ws&hostname=192.168.0.226&port=8080&pathname=%2Fws&logging=none&progress=true&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true (chunk-vendors.js:172:1)
    at __webpack_require__ (app.js:255:33)
    at app.js:1374:83
    at __webpack_require__.O (app.js:301:23)
    at app.js:1377:53
```

P.S. I didn't provide a link to repo because it's completely clean vue create installation without any changes.

---
btw I tried vite creating way, it worked but I need vue-cli way to use electron. and even more, I have another one production project based on vue 3.2 and vue-cli 5 and everything there works fine. I didn't find any solution in google about "Uncaught TypeError: Cannot read properties of undefined (reading 'e')
    at eval (stripAnsi.js:18:1)"

**Comment by temofart** [comment]
My friend just got the same using PC on Windows. Seems like the process has been broken.

**Comment by gregstephensen** [comment]
This is happening for my entire team
