### ISSUE TITLE
Project List Screen won't load.

### ISSUE THREAD

**Issue by JohnathanValentine** [vuejs/vue-cli#7396]
### Version
5.0.8

### Environment info
```
Running on MacBook Pro Ventura 13.4. running  vue ui from terminal window.
```

### Steps to reproduce
Click on Vue Project Manager from Drop down menu.

### What is expected?
Vue Project Manager loads with list of projects.

### What is actually happening?
Vue Project Manager loads with no projects shown. Errors in the console window:

An error occurred
vue-apollo.js:60 GraphQL error: Cannot return null for non-nullable field Project.name. | Cannot return null for non-nullable field Project.name. | Cannot return null for non-nullable field Project.name. | Cannot return null for non-nullable field Project.name.
vue-apollo.js:62 Array(4)
vue.runtime.esm.js:1897 TypeError: Cannot read properties of null (reading 'favorite')
    at filter (ProjectSelectList.vue:5:410)
    at Array.filter (<anonymous>)
    at render (ListFilter.vue:6:1)
    at tn (vue.runtime.esm.js:3077:30)
    at sn (vue.runtime.esm.js:3250:12)
    at pn (vue.runtime.esm.js:3443:15)
    at vn (vue.runtime.esm.js:3374:10)
    at e._c (vue.runtime.esm.js:3512:42)
    at ProjectSelectList.vue:5:291
    at o.Wt [as _l] (vue.runtime.esm.js:2646:16)

**Comment by anto80** [comment]
same problem, did you solve it somehow?

**Comment by JohnathanValentine** [comment]
Yes. I uninstalled and reinstalled everything for Vue and it started working again.
