### ISSUE TITLE
Vue-cli ,Creating a New Project, give an error, Unexpected token

### ISSUE THREAD

**Issue by mrafea-sa** [vuejs/vue-cli#744]
npm install -g @vue/cli
{
~\AppData\Roaming\npm\node_modules\@vue\cli\bin\vue
+ @vue/cli@3.0.0-alpha.4
}

vue create spa-03tut
{
 ~\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-shared-utils\linkBin.js:14
exports.linkBin = async (src, dest) => {
                        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ( ~\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-shared-utils\index.js:4:24)
}

**Comment by mrafea-sa** [comment]
please update  document
the working steps from (https://scotch.io/courses/build-an-online-shop-with-vue/vue-cli):

npm install -g vue-cli
# Run the following anywhere
# on your machine that you want
# your project to be located
vue init webpack scotch-store
