### ISSUE TITLE
'TypeError: promisify is not a function'

### ISSUE THREAD

**Issue by Cacivy** [vuejs/vue-cli#745]
### Version
3.0.0-alpha.5

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
OS: windows10
nodejs: v7.6.0
 
npm install -g @vue/cli
vue create hello-world

### What is expected?
create a project by vue/cli

### What is actually happening?
λ vue create hello-world ​​​​
C:\Users\q6094\AppData\Roaming\nvm\v7.6.0\node_modules\@vue\cli\node_modules\@vue\cli-shared-utils\lib\linkBin.js:9
const chmod = promisify(fs.chmod)
              ^

TypeError: promisify is not a function
    at Object.<anonymous> (C:\Users\q6094\AppData\Roaming\nvm\v7.6.0\node_modules\@vue\cli\node_modules\@vue\cli-shared-utils\lib\linkBin.js:9:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at __dirname.forEach.m (C:\Users\q6094\AppData\Roaming\nvm\v7.6.0\node_modules\@vue\cli\node_modules\@vue\cli-shared-utils\index.js:9:26)
    at Array.forEach (native)

**Comment by dcdrawk** [comment]
I ran into a similar error yesterday with 3.0.0-alpha.4. Updating nodejs fixed the issues I was having with linkBin.js

**Comment by Cacivy** [comment]
thinks, it's ok
