### ISSUE TITLE
vue-cli 3.0 not working on node v6.11.4

### ISSUE THREAD

**Issue by lasthrun** [vuejs/vue-cli#751]
### Version
3.0.0-alpha.5

### Reproduction link
[http://www.noreproduction.com](http://www.noreproduction.com)

### Steps to reproduce
npm install -g @vue/cli
vue create vueCli3

### What is expected?
is should work

### What is actually happening?
C:\Users\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-shared-utils\lib\linkBin.js:14
exports.linkBin = async (src, dest) => {
                        ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at __dirname.forEach.m (C:\Users\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-shared-utils\index.js:9:26)

**Comment by LinusBorg** [comment]
vue-cli 3 will require Node >=8

**Comment by lasthrun** [comment]
oh, got it. is there should mark it on the readme?
