### ISSUE TITLE
Webpack plugin issue

### ISSUE THREAD

**Issue by dcdrawk** [vuejs/vue-cli#764]
### Version
3.0.0-alpha.5

### Reproduction link
[https://github.com/dcdrawk/vue-cli-test](https://github.com/dcdrawk/vue-cli-test)

### Steps to reproduce
- Create a new vue-cli project
- add the following to `vue.config.js`
```javascript
configureWebpack: {
    plugins: [
      new webpack.EnvironmentPlugin({
        FOO: 'BAR'
      })
    ]
}
```
- `npm run serve`

### What is expected?
Webpack to use/merge the plugin successfully.

### What is actually happening?
I receive the following error:
```
TypeError: arguments[i].apply is not a function
    at Compiler.apply (path\to\my-project\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (path\to\my-project\node_modules\webpack\lib\webpack.js:33:19)
    at Promise (path\to\my-project\node_modules\@vue\cli-service\lib\commands\serve.js:78:24)
    at new Promise (<anonymous>)
    at portPromise.then.port (path\to\my-project\node_modules\@vue\cli-service\lib\commands\serve.js:51:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

---
After some trial and error, I was able to get the env plugin working using `chainWebpack` and creating an `.env.development.local` file.

In my `vue.config.js`:
```javascript
chainWebpack: chainableConfig => {
  chainableConfig
    .plugin('env')
    .use(webpack.EnvironmentPlugin, ['FOO'])
}
```

However, if I try using chainWebpack and object syntax to define default values for env variables, I also receive an error.
```
TypeError: undefined is not a function
    at init (path\to\my-project\node_modules\webpack-chain\src\Plugin.js:9:38)
    at Object.toConfig (path\to\my-project\node_modules\webpack-chain\src\Plugin.js:38:12)
    at clean.Object.assign.plugins.plugins.values.map.plugin (path\to\my-project\node_modules\webpack-chain\src\Config.js:69:59)
    at Array.map (<anonymous>)
    at module.exports.toConfig (path\to\my-project\node_modules\webpack-chain\src\Config.js:69:38)
    at Service.resolveWebpackConfig (path\to\my-project\node_modules\@vue\cli-service\lib\Service.js:138:37)
    at PluginAPI.resolveWebpackConfig (path\to\my-project\node_modules\@vue\cli-service\lib\PluginAPI.js:51:25)
    at Promise (path\to\my-project\node_modules\@vue\cli-service\lib\commands\serve.js:52:33)
    at new Promise (<anonymous>)
    at portPromise.then.port (path\to\my-project\node_modules\@vue\cli-service\lib\commands\serve.js:51:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by yyx990803** [comment]
fixed in 7d590d8
