### ISSUE TITLE
plugins is not defined -ReferenceError: ejs:11

### ISSUE THREAD

**Issue by NachoCodeX** [vuejs/vue-cli#799]
Hello, I've a problem with Vue-cli when I use  -> vue create "project-name", the next error display in my console after:🚀  Invoking generators...

 ERROR  ReferenceError: ejs:11
    9|     <h3>Installed CLI Plugins</h3>
    10|     <ul>
 >> 11| <%_ for (plugin of plugins) { _%>
    12|       <li><a href="<%- plugin.link %>" target="_blank"><%- plugin.name %></a></li>
    13| <%_ } _%>
    14|     </ul>
               
plugins is not defined
ReferenceError: ejs:11
    9|     <h3>Installed CLI Plugins</h3>
    10|     <ul>
 >> 11| <%_ for (plugin of plugins) { _%>
    12|       <li><a href="<%- plugin.link %>" target="_blank"><%- plugin.name %></a></li>
    13| <%_ } _%>
    14|     </ul>

plugins is not defined
    at eval (eval at compile (/usr/lib/node_modules/@vue/cli/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:23)
    at returnedFn (/usr/lib/node_modules/@vue/cli/node_modules/ejs/lib/ejs.js:580:17)
    at Object.exports.render (/usr/lib/node_modules/@vue/cli/node_modules/ejs/lib/ejs.js:384:37)
    at renderFile (/usr/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:125:14)
    at injectFileMiddleware (/usr/lib/node_modules/@vue/cli/lib/GeneratorAPI.js:69:27)
    at <anonymous>

-Sorry my English is so bad ! Jajaja , I hope that you all understand me.

**Comment by yyx990803** [comment]
Make sure to upgrade your global `@vue/cli`.
