### ISSUE TITLE
Support creating project in current directory

### ISSUE THREAD

**Issue by cecilphillip** [vuejs/vue-cli#896]
### What problem does this feature solve?
Makes a step towards more easily using the 3.x CLI with other non-javascript backend projects such as asp.net or flask.

Currently, invoking `vue create .` in an empty directory throws the following error

```
🚀  Invoking generators...
 ERROR  Error: Cannot find module '@vue/cli-service/generator' from '/Users/cecilphillip/Desktop/toss'
Error: Cannot find module '@vue/cli-service/generator' from '/Users/cecilphillip/Desktop/toss'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/@vue/cli/node_modules/resolve/lib/sync.js:40:15)
    at Object.keys.map.id (/usr/local/lib/node_modules/@vue/cli/lib/Creator.js:246:30)
    at Array.map (<anonymous>)
    at Creator.resolvePlugins (/usr/local/lib/node_modules/@vue/cli/lib/Creator.js:245:36)
    at Creator.create (/usr/local/lib/node_modules/@vue/cli/lib/Creator.js:134:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

### What does the proposed API look like?
`vue create .`   ||   `vue create --here`

**Comment by willl** [comment]
Just tried doing this but couldn't get it to work.

![image](https://user-images.githubusercontent.com/926823/38158065-4a4eed0e-34d9-11e8-925f-3b0f8a652219.png)

It says "The batch file cannot be found" and then fails. 

Currently running vue-cli `3.0.0-beta6`. 
![image](https://user-images.githubusercontent.com/926823/38158078-80426c9c-34d9-11e8-90ad-2d32a2cfd085.png)

Happy to create a new issue (if needed) and/or provide more info.

**Comment by willl** [comment]
Replying to my own comment, it looks like it works correctly when I tried again and told vue cli to manually select features.
