### ISSUE TITLE
Got error after updated

### ISSUE THREAD

**Issue by anhnhoktvn** [vuejs/vue-cli#90]
$ vue help list

  Available official templates:

/home/xxx/.nvm/versions/node/v5.11.0/lib/node_modules/vue-cli/bin/vue-list:29
  JSON.parse(body).forEach(function (repo) {
                   ^

TypeError: JSON.parse(...).forEach is not a function
    at Request._callback (/home/xxx/.nvm/versions/node/v5.11.0/lib/node_modules/vue-cli/bin/vue-list:29:20)
    at Request.self.callback (/home/xxx/.nvm/versions/node/v5.11.0/lib/node_modules/vue-cli/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/home/xxx/.nvm/versions/node/v5.11.0/lib/node_modules/vue-cli/node_modules/request/request.js:1067:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/home/xxx/.nvm/versions/node/v5.11.0/lib/node_modules/vue-cli/node_modules/request/request.js:988:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)

**Comment by anhnhoktvn** [comment]
It seems that I got github API rate limit exceeded. How can I add a github token for vue-cli?

**Comment by zigomir** [comment]
Why would you need to run `list` command so many times?

**Comment by anhnhoktvn** [comment]
I use octotree chrome extension, which uses github API many times. I think i should get rid of octotree.

**Comment by ip2k** [comment]
See https://github.com/vuejs/vue-cli/issues/368#issuecomment-281638835 . Basically, you need to do something like add `export GITHUB_PERSONAL_ACCESS_TOKEN=foo` to your `.bashrc` or `.zshrc` and reload it (e.g. `source ~/.bashrc`) or open a new terminal session. You can generate a new Github Personal Access Token at https://github.com/settings/tokens .
